#include "THISDUST.H"
#include "PAD.H"


// autogenerated function stub: 
// void /*$ra*/ padinit()
void padinit()
{ // line 66, offset 0x800e40e8
	/* begin block 1 */
		// Start line: 132
	/* end block 1 */
	// End Line: 133

	/* begin block 2 */
		// Start line: 132
	/* end block 2 */
	// End Line: 133

}


// autogenerated function stub: 
// void /*$ra*/ PAD_restore()
void PAD_restore()
{ // line 83, offset 0x800e4158
	/* begin block 1 */
		// Start line: 167
	/* end block 1 */
	// End Line: 168

	/* begin block 2 */
		// Start line: 167
	/* end block 2 */
	// End Line: 168

}


// autogenerated function stub: 
// unsigned short /*$ra*/ PAD_state(int padID /*$a0*/)
unsigned short PAD_state(int padID)
{ // line 172, offset 0x800e41ac
	/* begin block 1 */
		// Start line: 301
	/* end block 1 */
	// End Line: 302

	/* begin block 2 */
		// Start line: 306
	/* end block 2 */
	// End Line: 307

	/* begin block 3 */
		// Start line: 306
	/* end block 3 */
	// End Line: 307

	return 0;
}


// autogenerated function stub: 
// unsigned short /*$ra*/ PAD_convert(struct PAD_COMMON *pad /*$a0*/)
unsigned short PAD_convert(struct PAD_COMMON *pad)
{ // line 299, offset 0x800e41fc
	/* begin block 1 */
		// Start line: 576
	/* end block 1 */
	// End Line: 577

	/* begin block 2 */
		// Start line: 452
	/* end block 2 */
	// End Line: 453

	/* begin block 3 */
		// Start line: 453
	/* end block 3 */
	// End Line: 454

	/* begin block 4 */
		// Start line: 453
	/* end block 4 */
	// End Line: 454

	return 0;
}


// autogenerated function stub: 
// void /*$ra*/ PAD_update()
void PAD_update()
{ // line 342, offset 0x800e4210
	/* begin block 1 */
		// Start line: 343
		// Start offset: 0x800E4210
		// Variables:
			int i; // $t0
	/* end block 1 */
	// End offset: 0x800E42FC
	// End Line: 376

	/* begin block 2 */
		// Start line: 496
	/* end block 2 */
	// End Line: 497

	/* begin block 3 */
		// Start line: 538
	/* end block 3 */
	// End Line: 539

	/* begin block 4 */
		// Start line: 538
	/* end block 4 */
	// End Line: 539

}




