#include "NFS4.H"
#include "MMEFFECT.H"

// decompiled code
// original method signature: 
// void /*$ra*/ FeDraw_SetABRMode__Fi(int abr /*$a1*/)
 // line 233, offset 0x8004d6d8
	/* begin block 1 */
		// Start line: 234
		// Start offset: 0x8004D6D8
		// Variables:
	// 		struct DR_MODE *dr_mode; // $s0
	/* end block 1 */
	// End offset: 0x8004D6D8
	// End Line: 234

void FeDraw_SetABRMode__Fi(int abr)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}





