#include "THISDUST.H"
#include "AIH_PLAY.H"


// decompiled code
// original method signature: 
// int /*$ra*/ CheckIfABlockadeCanBeSetup__13AIHigh_Player(struct AIHigh_Player *this /*$s2*/)
 // line 55, offset 0x80061400
	/* begin block 1 */
		// Start line: 56
		// Start offset: 0x80061400
		// Variables:
	// 		int copLoop; // $a3
	// 		struct copLevel_t *pLevel; // $s0
	// 		int nCopsNeeded[2]; // stack offset -40
	// 		int ready[2]; // stack offset -32
	// 		int assigned[2]; // stack offset -24
	// 		int split; // $a2

		/* begin block 1.1 */
			// Start line: 56
			// Start offset: 0x80061400
			// Variables:
		// 		struct AICop_PerpChaseInfo *this; // $s1

			/* begin block 1.1.1 */
				// Start line: 56
				// Start offset: 0x80061400
			/* end block 1.1.1 */
			// End offset: 0x80061400
			// End Line: 56
		/* end block 1.1 */
		// End offset: 0x80061400
		// End Line: 56

		/* begin block 1.2 */
			// Start line: 56
			// Start offset: 0x80061400

			/* begin block 1.2.1 */
				// Start line: 72
				// Start offset: 0x80061464

				/* begin block 1.2.1.1 */
					// Start line: 72
					// Start offset: 0x80061464
				/* end block 1.2.1.1 */
				// End offset: 0x80061464
				// End Line: 72
			/* end block 1.2.1 */
			// End offset: 0x80061464
			// End Line: 72

			/* begin block 1.2.2 */
				// Start line: 72
				// Start offset: 0x80061474

				/* begin block 1.2.2.1 */
					// Start line: 72
					// Start offset: 0x80061474
				/* end block 1.2.2.1 */
				// End offset: 0x80061474
				// End Line: 72
			/* end block 1.2.2 */
			// End offset: 0x80061474
			// End Line: 72

			/* begin block 1.2.3 */
				// Start line: 72
				// Start offset: 0x80061494

				/* begin block 1.2.3.1 */
					// Start line: 72
					// Start offset: 0x80061494
				/* end block 1.2.3.1 */
				// End offset: 0x80061494
				// End Line: 72
			/* end block 1.2.3 */
			// End offset: 0x80061494
			// End Line: 72
		/* end block 1.2 */
		// End offset: 0x800614C0
		// End Line: 73

		/* begin block 1.3 */
			// Start line: 76
			// Start offset: 0x800614C0

			/* begin block 1.3.1 */
				// Start line: 80
				// Start offset: 0x800614F0
				// Variables:
			// 		struct AIHigh_Cop *thisCop; // $a2

				/* begin block 1.3.1.1 */
					// Start line: 82
					// Start offset: 0x800614FC

					/* begin block 1.3.1.1.1 */
						// Start line: 84
						// Start offset: 0x80061524

						/* begin block 1.3.1.1.1.1 */
							// Start line: 84
							// Start offset: 0x80061524
							// Variables:
						// 		struct AIHigh_BasicCop *this; // $a2

							/* begin block 1.3.1.1.1.1.1 */
								// Start line: 84
								// Start offset: 0x80061524
							/* end block 1.3.1.1.1.1.1 */
							// End offset: 0x80061524
							// End Line: 84
						/* end block 1.3.1.1.1.1 */
						// End offset: 0x80061524
						// End Line: 84

						/* begin block 1.3.1.1.1.2 */
							// Start line: 84
							// Start offset: 0x80061524

							/* begin block 1.3.1.1.1.2.1 */
								// Start line: 87
								// Start offset: 0x80061554

								/* begin block 1.3.1.1.1.2.1.1 */
									// Start line: 92
									// Start offset: 0x80061554
									// Variables:
								// 		struct AIHigh_BasicCop *this; // $a2

									/* begin block 1.3.1.1.1.2.1.1.1 */
										// Start line: 92
										// Start offset: 0x80061554
									/* end block 1.3.1.1.1.2.1.1.1 */
									// End offset: 0x80061554
									// End Line: 92
								/* end block 1.3.1.1.1.2.1.1 */
								// End offset: 0x80061554
								// End Line: 92
							/* end block 1.3.1.1.1.2.1 */
							// End offset: 0x80061584
							// End Line: 96
						/* end block 1.3.1.1.1.2 */
						// End offset: 0x80061584
						// End Line: 96
					/* end block 1.3.1.1.1 */
					// End offset: 0x80061584
					// End Line: 96
				/* end block 1.3.1.1 */
				// End offset: 0x80061584
				// End Line: 96
			/* end block 1.3.1 */
			// End offset: 0x80061584
			// End Line: 96
		/* end block 1.3 */
		// End offset: 0x80061590
		// End Line: 100

		/* begin block 1.4 */
			// Start line: 103
			// Start offset: 0x80061590

			/* begin block 1.4.1 */
				// Start line: 104
				// Start offset: 0x800615C0

				/* begin block 1.4.1.1 */
					// Start line: 105
					// Start offset: 0x800615C0

					/* begin block 1.4.1.1.1 */
						// Start line: 105
						// Start offset: 0x800615E0
						// Variables:
					// 		struct AIHigh_Cop *thisCop; // $a2

						/* begin block 1.4.1.1.1.1 */
							// Start line: 107
							// Start offset: 0x800615EC

							/* begin block 1.4.1.1.1.1.1 */
								// Start line: 108
								// Start offset: 0x80061614
								// Variables:
							// 		struct AIHigh_BasicCop *this; // $a2

								/* begin block 1.4.1.1.1.1.1.1 */
									// Start line: 108
									// Start offset: 0x80061614
								/* end block 1.4.1.1.1.1.1.1 */
								// End offset: 0x80061614
								// End Line: 108
							/* end block 1.4.1.1.1.1.1 */
							// End offset: 0x80061614
							// End Line: 108

							/* begin block 1.4.1.1.1.1.2 */
								// Start line: 109
								// Start offset: 0x80061624

								/* begin block 1.4.1.1.1.1.2.1 */
									// Start line: 109
									// Start offset: 0x80061624
									// Variables:
								// 		struct AIHigh_BasicCop *this; // $a2

									/* begin block 1.4.1.1.1.1.2.1.1 */
										// Start line: 109
										// Start offset: 0x80061624
									/* end block 1.4.1.1.1.1.2.1.1 */
									// End offset: 0x80061624
									// End Line: 109
								/* end block 1.4.1.1.1.1.2.1 */
								// End offset: 0x80061624
								// End Line: 109

								/* begin block 1.4.1.1.1.1.2.2 */
									// Start line: 109
									// Start offset: 0x80061624

									/* begin block 1.4.1.1.1.1.2.2.1 */
										// Start line: 112
										// Start offset: 0x80061650

										/* begin block 1.4.1.1.1.1.2.2.1.1 */
											// Start line: 118
											// Start offset: 0x80061650
											// Variables:
										// 		struct AIHigh_BasicCop *this; // $a2

											/* begin block 1.4.1.1.1.1.2.2.1.1.1 */
												// Start line: 118
												// Start offset: 0x80061650
											/* end block 1.4.1.1.1.1.2.2.1.1.1 */
											// End offset: 0x80061650
											// End Line: 118
										/* end block 1.4.1.1.1.1.2.2.1.1 */
										// End offset: 0x80061650
										// End Line: 118
									/* end block 1.4.1.1.1.1.2.2.1 */
									// End offset: 0x80061660
									// End Line: 121
								/* end block 1.4.1.1.1.1.2.2 */
								// End offset: 0x80061660
								// End Line: 121
							/* end block 1.4.1.1.1.1.2 */
							// End offset: 0x80061660
							// End Line: 121
						/* end block 1.4.1.1.1.1 */
						// End offset: 0x80061660
						// End Line: 121
					/* end block 1.4.1.1.1 */
					// End offset: 0x80061660
					// End Line: 121
				/* end block 1.4.1.1 */
				// End offset: 0x8006166C
				// End Line: 125
			/* end block 1.4.1 */
			// End offset: 0x8006166C
			// End Line: 125
		/* end block 1.4 */
		// End offset: 0x8006166C
		// End Line: 125

		/* begin block 1.5 */
			// Start line: 129
			// Start offset: 0x8006166C

			/* begin block 1.5.1 */
				// Start line: 130
				// Start offset: 0x80061698

				/* begin block 1.5.1.1 */
					// Start line: 131
					// Start offset: 0x80061698

					/* begin block 1.5.1.1.1 */
						// Start line: 131
						// Start offset: 0x800616BC
						// Variables:
					// 		struct AIHigh_Cop *thisCop; // $v1

						/* begin block 1.5.1.1.1.1 */
							// Start line: 133
							// Start offset: 0x800616C8

							/* begin block 1.5.1.1.1.1.1 */
								// Start line: 135
								// Start offset: 0x800616F0

								/* begin block 1.5.1.1.1.1.1.1 */
									// Start line: 135
									// Start offset: 0x800616F0
									// Variables:
								// 		struct AIHigh_BasicCop *this; // $v1

									/* begin block 1.5.1.1.1.1.1.1.1 */
										// Start line: 135
										// Start offset: 0x800616F0
									/* end block 1.5.1.1.1.1.1.1.1 */
									// End offset: 0x800616F0
									// End Line: 135
								/* end block 1.5.1.1.1.1.1.1 */
								// End offset: 0x800616F0
								// End Line: 135

								/* begin block 1.5.1.1.1.1.1.2 */
									// Start line: 135
									// Start offset: 0x800616F0

									/* begin block 1.5.1.1.1.1.1.2.1 */
										// Start line: 139
										// Start offset: 0x80061720

										/* begin block 1.5.1.1.1.1.1.2.1.1 */
											// Start line: 146
											// Start offset: 0x80061720
											// Variables:
										// 		struct AIHigh_BasicCop *this; // $v1

											/* begin block 1.5.1.1.1.1.1.2.1.1.1 */
												// Start line: 146
												// Start offset: 0x80061720
											/* end block 1.5.1.1.1.1.1.2.1.1.1 */
											// End offset: 0x80061720
											// End Line: 146
										/* end block 1.5.1.1.1.1.1.2.1.1 */
										// End offset: 0x80061720
										// End Line: 146
									/* end block 1.5.1.1.1.1.1.2.1 */
									// End offset: 0x8006172C
									// End Line: 149
								/* end block 1.5.1.1.1.1.1.2 */
								// End offset: 0x8006172C
								// End Line: 149
							/* end block 1.5.1.1.1.1.1 */
							// End offset: 0x8006172C
							// End Line: 149
						/* end block 1.5.1.1.1.1 */
						// End offset: 0x8006172C
						// End Line: 149
					/* end block 1.5.1.1.1 */
					// End offset: 0x8006172C
					// End Line: 149
				/* end block 1.5.1.1 */
				// End offset: 0x80061738
				// End Line: 153
			/* end block 1.5.1 */
			// End offset: 0x80061738
			// End Line: 153
		/* end block 1.5 */
		// End offset: 0x80061738
		// End Line: 153
	/* end block 1 */
	// End offset: 0x8006176C
	// End Line: 171

	/* begin block 2 */
		// Start line: 110
	/* end block 2 */
	// End Line: 111

	/* begin block 3 */
		// Start line: 110
	/* end block 3 */
	// End Line: 111

int CheckIfABlockadeCanBeSetup__13AIHigh_Player(AIHigh_Player *this)

{
  bool bVar1;
  int iVar2;
  int iVar3;
  int iVar4;
  Car_tObj *pCVar5;
  int iVar6;
  int *piVar7;
  Car_tObj **ppCVar8;
  AIHigh_Base *pAVar9;
  int iVar10;
  copLevel_t *pcVar11;
  int local_28 [4];
  int local_18;
  int local_14;
  
  pcVar11 = (this->perpChaseInfo_).chaseLevel_;
  memset(local_28 + 2,0,8);
  memset(local_28 + 4,0,8);
  iVar10 = Cars_gNumCopCars;
  bVar1 = false;
  if ((((pcVar11->numBlockaders == 0) || ((this->perpChaseInfo_).blockadeDone_ != 0)) ||
      (((this->AIHigh_BasicPerp).basicPerpInfo_.copsAssigned_[0] < pcVar11->copChasers[0] &&
       (Cars_gNumHumanRaceCars != 2)))) ||
     (((this->AIHigh_BasicPerp).basicPerpInfo_.copsAssigned_[1] < pcVar11->copChasers[1] &&
      (Cars_gNumHumanRaceCars != 2)))) {
    bVar1 = true;
  }
  iVar3 = 0;
  if (!bVar1) {
    iVar3 = 0;
    iVar4 = pcVar11->copBlockaders[0];
    iVar6 = pcVar11->copBlockaders[1];
    ppCVar8 = &Cars_gCopCarList9;
    while (iVar2 = Cars_gNumCopCars, iVar3 < iVar10) {
      pAVar9 = (&highLevelAIObjs9)[(*ppCVar8)->carIndex];
      if ((((*ppCVar8)->speechInfo).speechSource & 0xc) == 0xc) {
        pCVar5 = pAVar9[1].carObj_;
        piVar7 = local_28 + (int)&(pCVar5->N).oldSlice;
        if (*piVar7 < local_28[(int)pCVar5]) {
          local_28[(int)&(pCVar5->N).objID + 2] = local_28[(int)&(pCVar5->N).objID + 2] + 1;
          *piVar7 = *piVar7 + 1;
          pAVar9[1].stateType_ = STATE_PURGATORY;
          *(AIHigh_Player **)&pAVar9[1].schedulingOff_ = this;
        }
      }
      ppCVar8 = ppCVar8 + 1;
      iVar3 = iVar3 + 1;
    }
    iVar10 = 0;
    if ((local_18 < iVar4) || (local_14 < iVar6)) {
      ppCVar8 = &Cars_gCopCarList9;
      while (iVar10 < iVar2) {
        pAVar9 = (&highLevelAIObjs9)[(*ppCVar8)->carIndex];
        if (((((*ppCVar8)->speechInfo).speechSource & 0xc) == 8) &&
           (pAVar9[1].stateType_ != STATE_NORMAL)) {
          iVar3 = local_28[(int)&((pAVar9[1].carObj_)->N).oldSlice];
          if (iVar3 < local_28[(int)pAVar9[1].carObj_]) {
            local_28[(int)&((pAVar9[1].carObj_)->N).oldSlice] = iVar3 + 1;
            pAVar9[1].stateType_ = STATE_PURGATORY;
            *(AIHigh_Player **)&pAVar9[1].schedulingOff_ = this;
          }
        }
        ppCVar8 = ppCVar8 + 1;
        iVar10 = iVar10 + 1;
      }
    }
    iVar10 = Cars_gNumCopCars;
    if ((Cars_gNumHumanRaceCars != 1) && (iVar3 = 0, local_14 < iVar6)) {
      ppCVar8 = &Cars_gCopCarList9;
      while (iVar3 < iVar10) {
        pAVar9 = (&highLevelAIObjs9)[(*ppCVar8)->carIndex];
        if (((((((*ppCVar8)->speechInfo).speechSource & 0xc) == 8) &&
             (pAVar9[1].carObj_ == (Car_tObj *)0x0)) && (local_14 < iVar6)) && (local_14 == 0)) {
          local_14 = 1;
          pAVar9[1].stateType_ = STATE_CHASE;
          *(AIHigh_Player **)&pAVar9[1].schedulingOff_ = this;
        }
        ppCVar8 = ppCVar8 + 1;
        iVar3 = iVar3 + 1;
      }
    }
    iVar3 = 0;
    if ((iVar4 <= local_28[2]) && (iVar3 = 1, local_28[3] < iVar6)) {
      iVar3 = 0;
    }
  }
  return iVar3;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SetupBlockade__13AIHigh_Player(struct AIHigh_Player *this /*$s4*/)
 // line 184, offset 0x80061784
	/* begin block 1 */
		// Start line: 185
		// Start offset: 0x80061784
		// Variables:
	// 		int copLoop; // $s3
	// 		int blockadeHandle; // $a1
	// 		struct copLevel_t *pLevel; // $s3
	// 		union trigger_t *blockade; // $s0
	// 		int used; // stack offset -56
	// 		int nCopsNeeded[2]; // stack offset -80
	// 		int requestSpikeBeltAtSlice; // $s6
	// 		int nCopsAvail[2]; // stack offset -72
	// 		int totalRoadWidth; // $a1
	// 		int blockadeSlice; // $s2
	// 		int blockadeType; // $v1
	// 		int blockadeFlags; // $s7
	// 		void * saySpikeBelt; // stack offset -52
	// 		struct AIHigh_Cop *blockadeCar; // $s5
	// 		int posIndex; // $s1

		/* begin block 1.1 */
			// Start line: 185
			// Start offset: 0x80061784

			/* begin block 1.1.1 */
				// Start line: 185
				// Start offset: 0x80061784
			/* end block 1.1.1 */
			// End offset: 0x80061784
			// End Line: 185
		/* end block 1.1 */
		// End offset: 0x80061784
		// End Line: 185

		/* begin block 1.2 */
			// Start line: 220
			// Start offset: 0x8006186C
			// Variables:
		// 		int loop; // $s2
		/* end block 1.2 */
		// End offset: 0x80061920
		// End Line: 237

		/* begin block 1.3 */
			// Start line: 264
			// Start offset: 0x80061934
			// Variables:
		// 		int needed[2]; // stack offset -64

			/* begin block 1.3.1 */
				// Start line: 264
				// Start offset: 0x80061934

				/* begin block 1.3.1.1 */
					// Start line: 272
					// Start offset: 0x8006196C
					// Variables:
				// 		struct AIHigh_Cop *thisCop; // $a0

					/* begin block 1.3.1.1.1 */
						// Start line: 274
						// Start offset: 0x80061978

						/* begin block 1.3.1.1.1.1 */
							// Start line: 275
							// Start offset: 0x800619A0
							// Variables:
						// 		struct AIHigh_BasicCop *this; // $a0

							/* begin block 1.3.1.1.1.1.1 */
								// Start line: 275
								// Start offset: 0x800619A0
							/* end block 1.3.1.1.1.1.1 */
							// End offset: 0x800619A0
							// End Line: 275
						/* end block 1.3.1.1.1.1 */
						// End offset: 0x800619A0
						// End Line: 275

						/* begin block 1.3.1.1.1.2 */
							// Start line: 275
							// Start offset: 0x800619B0
							// Variables:
						// 		struct AIHigh_BasicCop *this; // $a0

							/* begin block 1.3.1.1.1.2.1 */
								// Start line: 275
								// Start offset: 0x800619B0
							/* end block 1.3.1.1.1.2.1 */
							// End offset: 0x800619B0
							// End Line: 275
						/* end block 1.3.1.1.1.2 */
						// End offset: 0x800619B0
						// End Line: 275

						/* begin block 1.3.1.1.1.3 */
							// Start line: 276
							// Start offset: 0x800619D4

							/* begin block 1.3.1.1.1.3.1 */
								// Start line: 276
								// Start offset: 0x800619D4
								// Variables:
							// 		struct AIHigh_BasicCop *this; // $a0

								/* begin block 1.3.1.1.1.3.1.1 */
									// Start line: 276
									// Start offset: 0x800619D4
								/* end block 1.3.1.1.1.3.1.1 */
								// End offset: 0x800619D4
								// End Line: 276
							/* end block 1.3.1.1.1.3.1 */
							// End offset: 0x800619D4
							// End Line: 276

							/* begin block 1.3.1.1.1.3.2 */
								// Start line: 276
								// Start offset: 0x800619D4
								// Variables:
							// 		struct AIHigh_BasicCop *this; // $a0

								/* begin block 1.3.1.1.1.3.2.1 */
									// Start line: 276
									// Start offset: 0x800619D4
								/* end block 1.3.1.1.1.3.2.1 */
								// End offset: 0x800619D4
								// End Line: 276
							/* end block 1.3.1.1.1.3.2 */
							// End offset: 0x800619D4
							// End Line: 276
						/* end block 1.3.1.1.1.3 */
						// End offset: 0x80061A14
						// End Line: 278
					/* end block 1.3.1.1.1 */
					// End offset: 0x80061A14
					// End Line: 278
				/* end block 1.3.1.1 */
				// End offset: 0x80061A14
				// End Line: 278
			/* end block 1.3.1 */
			// End offset: 0x80061A20
			// End Line: 280
		/* end block 1.3 */
		// End offset: 0x80061A20
		// End Line: 280

		/* begin block 1.4 */
			// Start line: 283
			// Start offset: 0x80061A20

			/* begin block 1.4.1 */
				// Start line: 292
				// Start offset: 0x80061A9C
				// Variables:
			// 		struct AIHigh_Cop *thisCop; // $a0
			// 		struct blockade_t *blockade; // $s0

				/* begin block 1.4.1.1 */
					// Start line: 294
					// Start offset: 0x80061AB4

					/* begin block 1.4.1.1.1 */
						// Start line: 296
						// Start offset: 0x80061AEC
						// Variables:
					// 		struct AIHigh_BasicCop *this; // $a0

						/* begin block 1.4.1.1.1.1 */
							// Start line: 296
							// Start offset: 0x80061AEC
						/* end block 1.4.1.1.1.1 */
						// End offset: 0x80061AEC
						// End Line: 296
					/* end block 1.4.1.1.1 */
					// End offset: 0x80061AEC
					// End Line: 296

					/* begin block 1.4.1.1.2 */
						// Start line: 297
						// Start offset: 0x80061AFC

						/* begin block 1.4.1.1.2.1 */
							// Start line: 298
							// Start offset: 0x80061AFC

							/* begin block 1.4.1.1.2.1.1 */
								// Start line: 298
								// Start offset: 0x80061AFC
								// Variables:
							// 		struct AIHigh_BasicCop *this; // $a0

								/* begin block 1.4.1.1.2.1.1.1 */
									// Start line: 298
									// Start offset: 0x80061AFC
								/* end block 1.4.1.1.2.1.1.1 */
								// End offset: 0x80061AFC
								// End Line: 298
							/* end block 1.4.1.1.2.1.1 */
							// End offset: 0x80061AFC
							// End Line: 298

							/* begin block 1.4.1.1.2.1.2 */
								// Start line: 299
								// Start offset: 0x80061B1C
								// Variables:
							// 		int addToSlice; // $v0

								/* begin block 1.4.1.1.2.1.2.1 */
									// Start line: 302
									// Start offset: 0x80061B28
									// Variables:
								// 		struct AIHigh_BasicCop *this; // $a0

									/* begin block 1.4.1.1.2.1.2.1.1 */
										// Start line: 302
										// Start offset: 0x80061B28
									/* end block 1.4.1.1.2.1.2.1.1 */
									// End offset: 0x80061B28
									// End Line: 302
								/* end block 1.4.1.1.2.1.2.1 */
								// End offset: 0x80061B28
								// End Line: 302

								/* begin block 1.4.1.1.2.1.2.2 */
									// Start line: 302
									// Start offset: 0x80061B28
									// Variables:
								// 		struct AICop_PerpChaseInfo *this; // $fp

									/* begin block 1.4.1.1.2.1.2.2.1 */
										// Start line: 302
										// Start offset: 0x80061B28
									/* end block 1.4.1.1.2.1.2.2.1 */
									// End offset: 0x80061B28
									// End Line: 302
								/* end block 1.4.1.1.2.1.2.2 */
								// End offset: 0x80061B28
								// End Line: 302

								/* begin block 1.4.1.1.2.1.2.3 */
									// Start line: 349
									// Start offset: 0x80061DB0

									/* begin block 1.4.1.1.2.1.2.3.1 */
										// Start line: 349
										// Start offset: 0x80061DB0
									/* end block 1.4.1.1.2.1.2.3.1 */
									// End offset: 0x80061DB0
									// End Line: 349
								/* end block 1.4.1.1.2.1.2.3 */
								// End offset: 0x80061DB0
								// End Line: 349
							/* end block 1.4.1.1.2.1.2 */
							// End offset: 0x80061DB0
							// End Line: 349

							/* begin block 1.4.1.1.2.1.3 */
								// Start line: 355
								// Start offset: 0x80061DB8

								/* begin block 1.4.1.1.2.1.3.1 */
									// Start line: 355
									// Start offset: 0x80061DB8

									/* begin block 1.4.1.1.2.1.3.1.1 */
										// Start line: 356
										// Start offset: 0x80061DC8
										// Variables:
									// 		int addToSlice; // $v0

										/* begin block 1.4.1.1.2.1.3.1.1.1 */
											// Start line: 359
											// Start offset: 0x80061DD4
											// Variables:
										// 		struct AIHigh_BasicCop *this; // $a0

											/* begin block 1.4.1.1.2.1.3.1.1.1.1 */
												// Start line: 359
												// Start offset: 0x80061DD4
											/* end block 1.4.1.1.2.1.3.1.1.1.1 */
											// End offset: 0x80061DD4
											// End Line: 359
										/* end block 1.4.1.1.2.1.3.1.1.1 */
										// End offset: 0x80061DD4
										// End Line: 359

										/* begin block 1.4.1.1.2.1.3.1.1.2 */
											// Start line: 359
											// Start offset: 0x80061DD4

											/* begin block 1.4.1.1.2.1.3.1.1.2.1 */
												// Start line: 359
												// Start offset: 0x80061DD4
											/* end block 1.4.1.1.2.1.3.1.1.2.1 */
											// End offset: 0x80061DD4
											// End Line: 359
										/* end block 1.4.1.1.2.1.3.1.1.2 */
										// End offset: 0x80061DD4
										// End Line: 359

										/* begin block 1.4.1.1.2.1.3.1.1.3 */
											// Start line: 408
											// Start offset: 0x800620E0

											/* begin block 1.4.1.1.2.1.3.1.1.3.1 */
												// Start line: 408
												// Start offset: 0x800620E0
											/* end block 1.4.1.1.2.1.3.1.1.3.1 */
											// End offset: 0x800620E0
											// End Line: 408
										/* end block 1.4.1.1.2.1.3.1.1.3 */
										// End offset: 0x800620E0
										// End Line: 408
									/* end block 1.4.1.1.2.1.3.1.1 */
									// End offset: 0x800620E8
									// End Line: 411
								/* end block 1.4.1.1.2.1.3.1 */
								// End offset: 0x800620E8
								// End Line: 411
							/* end block 1.4.1.1.2.1.3 */
							// End offset: 0x800620E8
							// End Line: 411
						/* end block 1.4.1.1.2.1 */
						// End offset: 0x800620E8
						// End Line: 411
					/* end block 1.4.1.1.2 */
					// End offset: 0x800620E8
					// End Line: 411
				/* end block 1.4.1.1 */
				// End offset: 0x800620E8
				// End Line: 411
			/* end block 1.4.1 */
			// End offset: 0x800620E8
			// End Line: 411
		/* end block 1.4 */
		// End offset: 0x800620F0
		// End Line: 415

		/* begin block 1.5 */
			// Start line: 417
			// Start offset: 0x800620F0

			/* begin block 1.5.1 */
				// Start line: 418
				// Start offset: 0x800620F8

				/* begin block 1.5.1.1 */
					// Start line: 418
					// Start offset: 0x800620F8
					// Variables:
				// 		struct AIHigh_BasicCop *this; // $s5

					/* begin block 1.5.1.1.1 */
						// Start line: 418
						// Start offset: 0x800620F8
					/* end block 1.5.1.1.1 */
					// End offset: 0x800620F8
					// End Line: 418
				/* end block 1.5.1.1 */
				// End offset: 0x800620F8
				// End Line: 418

				/* begin block 1.5.1.2 */
					// Start line: 419
					// Start offset: 0x800620F8

					/* begin block 1.5.1.2.1 */
						// Start line: 422
						// Start offset: 0x8006210C

						/* begin block 1.5.1.2.1.1 */
							// Start line: 422
							// Start offset: 0x8006210C
							// Variables:
						// 		struct AIHigh_Base *this; // $s5

							/* begin block 1.5.1.2.1.1.1 */
								// Start line: 422
								// Start offset: 0x8006210C
							/* end block 1.5.1.2.1.1.1 */
							// End offset: 0x8006210C
							// End Line: 422
						/* end block 1.5.1.2.1.1 */
						// End offset: 0x8006210C
						// End Line: 422
					/* end block 1.5.1.2.1 */
					// End offset: 0x8006210C
					// End Line: 422

					/* begin block 1.5.1.2.2 */
						// Start line: 424
						// Start offset: 0x80062144

						/* begin block 1.5.1.2.2.1 */
							// Start line: 424
							// Start offset: 0x80062144
							// Variables:
						// 		struct AIHigh_Base *this; // $s5

							/* begin block 1.5.1.2.2.1.1 */
								// Start line: 424
								// Start offset: 0x80062144
							/* end block 1.5.1.2.2.1.1 */
							// End offset: 0x80062144
							// End Line: 424
						/* end block 1.5.1.2.2.1 */
						// End offset: 0x80062144
						// End Line: 424
					/* end block 1.5.1.2.2 */
					// End offset: 0x8006216C
					// End Line: 424
				/* end block 1.5.1.2 */
				// End offset: 0x8006216C
				// End Line: 424

				/* begin block 1.5.1.3 */
					// Start line: 424
					// Start offset: 0x8006216C
					// Variables:
				// 		struct AIHigh_Base *this; // $s5

					/* begin block 1.5.1.3.1 */
						// Start line: 424
						// Start offset: 0x8006216C
					/* end block 1.5.1.3.1 */
					// End offset: 0x8006216C
					// End Line: 424
				/* end block 1.5.1.3 */
				// End offset: 0x8006216C
				// End Line: 424

				/* begin block 1.5.1.4 */
					// Start line: 427
					// Start offset: 0x8006216C
					// Variables:
				// 		struct AIHigh_Base *this; // $s5

					/* begin block 1.5.1.4.1 */
						// Start line: 427
						// Start offset: 0x8006216C
					/* end block 1.5.1.4.1 */
					// End offset: 0x8006216C
					// End Line: 427
				/* end block 1.5.1.4 */
				// End offset: 0x8006216C
				// End Line: 427
			/* end block 1.5.1 */
			// End offset: 0x800621DC
			// End Line: 430
		/* end block 1.5 */
		// End offset: 0x800621DC
		// End Line: 430
	/* end block 1 */
	// End offset: 0x800621DC
	// End Line: 430

	/* begin block 2 */
		// Start line: 388
	/* end block 2 */
	// End Line: 389

	/* begin block 3 */
		// Start line: 402
	/* end block 3 */
	// End Line: 403

	/* begin block 4 */
		// Start line: 402
	/* end block 4 */
	// End Line: 403

/* WARNING: Removing unreachable block (ram,0x80061cc8) */
/* WARNING: Removing unreachable block (ram,0x800620a4) */
/* WARNING: Removing unreachable block (ram,0x80062054) */
/* WARNING: Removing unreachable block (ram,0x80061c78) */
/* WARNING: Type propagation algorithm not settling */

void SetupBlockade__13AIHigh_Player(AIHigh_Player *this)

{
  short sVar1;
  bool bVar2;
  trigger_t *pabVar3;
  Car_tObj *pCVar4;
  Car_tObj *pCVar5;
  Speaker *pSVar6;
  int *piVar7;
  Trk_NewSlice *pTVar8;
  code *pcVar9;
  Car_tObj *pCVar10;
  uint uVar11;
  AIHigh_Base *pAVar12;
  Car_tObj **ppCVar13;
  uint uVar14;
  int slice;
  int iVar15;
  Car_tObj *pCVar16;
  copLevel_t *pcVar17;
  AIHigh_Base *pAVar18;
  int local_50;
  int local_4c;
  Car_tObj *local_48 [2];
  int local_40 [4];
  Car_tObj *local_30;
  
  pCVar10 = (this->AIHigh_BasicPerp).AIHigh_Base.carObj_;
  pcVar17 = (this->perpChaseInfo_).chaseLevel_;
  slice = (pCVar10->script).lastReactionIndex[3] * 0x53;
  if (slice < 0) {
    slice = (int)(pCVar10->N).simRoadInfo.slice + slice;
    if (slice < 0) {
      slice = slice + gNumSlices;
    }
  }
  else {
    slice = (int)(pCVar10->N).simRoadInfo.slice + slice;
    if (gNumSlices <= slice) {
      slice = slice - gNumSlices;
    }
  }
  local_50 = pcVar17->copBlockaders[0];
  local_4c = pcVar17->copBlockaders[1];
  slice = CheckForClosestTriggerOfType__24AITrigger_TriggerManageri11triggerTypei
                    (triggerManagerCops,slice,TRIGGER_COP_ROADBLOCK,
                     (((this->AIHigh_BasicPerp).AIHigh_Base.carObj_)->script).lastReactionIndex[3]);
  if (slice == -1) {
LAB_80062130:
    CheckForNewLevel__13AIHigh_Playeri(this,1);
  }
  else {
    iVar15 = 0;
    pabVar3 = GetTrigger__24AITrigger_TriggerManageriPi(triggerManagerCops,slice,local_40 + 2);
    do {
      bVar2 = false;
      pCVar10 = AILife_IsSliceInAnyVisibleArea__Fi(*(int *)(*pabVar3 + 4));
      if ((pCVar10 != (Car_tObj *)0x0) ||
         (pCVar10 = AILife_IsSliceCloseToAnyCopCar__Fi(*(int *)(*pabVar3 + 4)),
         pCVar10 != (Car_tObj *)0x0)) {
        bVar2 = true;
      }
      if (!bVar2) break;
      slice = *(int *)(*pabVar3 + 4) + 1;
      if (gNumSlices <= slice) {
        slice = *(int *)(*pabVar3 + 4) - (gNumSlices + -1);
      }
      slice = CheckForClosestTriggerOfType__24AITrigger_TriggerManageri11triggerTypei
                        (triggerManagerCops,slice,TRIGGER_COP_ROADBLOCK,
                         (((this->AIHigh_BasicPerp).AIHigh_Base.carObj_)->script).lastReactionIndex
                         [3]);
      if (slice == -1) goto LAB_80062130;
      iVar15 = iVar15 + 1;
      pabVar3 = GetTrigger__24AITrigger_TriggerManageriPi(triggerManagerCops,slice,local_40 + 2);
    } while (iVar15 < 4);
    slice = Cars_gNumCopCars;
    pCVar16 = *(Car_tObj **)(*pabVar3 + 4);
    pCVar10 = (Car_tObj *)0xffffffff;
    if (pcVar17->spikeBelt != 0) {
      pCVar10 = pCVar16;
    }
    iVar15 = 0;
    ppCVar13 = &Cars_gCopCarList9;
    local_48[0] = (Car_tObj *)0x0;
    local_48[1] = (Car_tObj *)0x0;
    while (pAVar18 = (AIHigh_Base *)0x0, iVar15 < slice) {
      pAVar18 = (&highLevelAIObjs9)[(*ppCVar13)->carIndex];
      bVar2 = false;
      if (((((*ppCVar13)->speechInfo).speechSource & 4) != 0) &&
         (pAVar18[1].stateType_ == STATE_PURGATORY)) {
        bVar2 = local_40[(int)pAVar18[1].carObj_] != 0;
      }
      if (bVar2) {
        piVar7 = local_40 + (int)pAVar18[1].carObj_;
        *piVar7 = *piVar7 + -1;
        local_48[(int)pAVar18[1].carObj_] =
             (Car_tObj *)((int)&(local_48[(int)pAVar18[1].carObj_]->N).objID + 1);
      }
      ppCVar13 = ppCVar13 + 1;
      iVar15 = iVar15 + 1;
    }
    randtemp = fastRandom * randSeed;
    uVar11 = randtemp >> 8 & 0xffff;
    uVar14 = 0;
    slice = 0;
    pCVar5 = (Car_tObj *)&DAT_00000001;
    local_40[3] = 0;
    fastRandom = randtemp & 0xffff;
    pCVar4 = (Car_tObj *)
             (uint)(byte)(&gBlockadeTypes)
                         [uVar11 - (((uint)((ulonglong)uVar11 * 0xcccccccd >> 0x20) & 0xfffffffc) +
                                   uVar11 / 5)];
    local_40[0] = local_50;
    local_40[1] = local_4c;
    while (slice < Cars_gNumCopCars) {
      pAVar12 = (&highLevelAIObjs9)[(&Cars_gCopCarList9)[slice]->carIndex];
      if (((((&Cars_gCopCarList9)[slice]->speechInfo).speechSource & 4) != 0) &&
         ((&pAVar12->carObj_)[8] == pCVar5)) {
        if (((&pAVar12->carObj_)[6] == pCVar5) && (local_4c != 0)) {
          if (pAVar18 == (AIHigh_Base *)0x0) {
            pAVar18 = pAVar12;
          }
          local_4c = local_4c + -1;
          *(undefined2 *)(&pAVar12->carObj_ + 0x14) = 0;
          (&pAVar12->carObj_)[10] = pCVar4;
          (&pAVar12->carObj_)[0xb] = (Car_tObj *)(this->perpChaseInfo_).chaseLevelIndex_;
          (&pAVar12->carObj_)[8] = (Car_tObj *)0x2;
          iVar15 = (((int)(uVar14 + (uVar14 >> 0x1f)) >> 1) * 2 + 3) *
                   (((this->AIHigh_BasicPerp).AIHigh_Base.carObj_)->script).lastReactionIndex[3];
          if (iVar15 < 0) {
            pCVar4 = (Car_tObj *)((int)&(pCVar16->N).objID + iVar15);
            if ((int)pCVar4 < 0) {
              pCVar4 = (Car_tObj *)((int)&(pCVar4->N).objID + gNumSlices);
            }
          }
          else {
            pCVar4 = (Car_tObj *)((int)&(pCVar16->N).objID + iVar15);
            if (gNumSlices <= (int)pCVar4) {
              pCVar4 = (Car_tObj *)((int)pCVar4 - gNumSlices);
            }
          }
          (&pAVar12->carObj_)[0xd] = pCVar4;
          (&pAVar12->carObj_)[0xe] =
               (Car_tObj *)
               (((this->AIHigh_BasicPerp).AIHigh_Base.carObj_)->script).lastReactionIndex[3];
          pTVar8 = BWorldSm_slices + (int)(&pAVar12->carObj_)[0xd];
          iVar15 = (uint)pTVar8->avgPavedWidthLf * 0x8000 * (uint)(pTVar8->laneCount >> 4);
          uVar11 = iVar15 + (uint)pTVar8->avgPavedWidthRt * 0x8000 * ((uint)pTVar8->laneCount & 0xf)
          ;
          if ((local_48[1] == pCVar5) && (local_48[0] == (Car_tObj *)0x0)) {
            (&pAVar12->carObj_)[0xf] = (Car_tObj *)((uVar11 >> 1) - iVar15);
            pCVar4 = (Car_tObj *)0xff;
          }
          else {
            iVar15 = (int)uVar11 >> 2;
            if ((uVar14 & 1) == 0) {
              (&pAVar12->carObj_)[0xf] =
                   (Car_tObj *)
                   (iVar15 - (uint)BWorldSm_slices[(int)(&pAVar12->carObj_)[0xd]].avgPavedWidthLf *
                             0x8000 * (uint)(BWorldSm_slices[(int)(&pAVar12->carObj_)[0xd]].
                                             laneCount >> 4));
              pCVar4 = (Car_tObj *)0xbe;
            }
            else {
              pCVar4 = (Car_tObj *)0xffffff42;
              (&pAVar12->carObj_)[0xf] =
                   (Car_tObj *)
                   (iVar15 * 3 -
                   (uint)BWorldSm_slices[(int)(&pAVar12->carObj_)[0xd]].avgPavedWidthLf * 0x8000 *
                   (uint)(BWorldSm_slices[(int)(&pAVar12->carObj_)[0xd]].laneCount >> 4));
            }
          }
          (&pAVar12->carObj_)[0x10] = pCVar4;
          randtemp = fastRandom * randSeed;
          *(AIHigh_Player **)(&pAVar12->carObj_ + 9) = this;
          (&pAVar12->carObj_)[0x11] = (Car_tObj *)0x0;
          (&pAVar12->carObj_)[0x12] =
               (Car_tObj *)(&DAT_0000d999 + ((randtemp >> 8 & 0xffff) * 0x14ccd >> 0x10));
          fastRandom = randtemp & 0xffff;
          local_30 = pCVar5;
          iVar15 = AIWorld_ApxSplineDistance__FP8Car_tObji
                             ((this->AIHigh_BasicPerp).AIHigh_Base.carObj_,
                              (int)(&pAVar12->carObj_)[0xd]);
          if (iVar15 < 0) {
            iVar15 = iVar15 + 0xffff;
          }
          (&pAVar12->carObj_)[0x13] = (Car_tObj *)-(iVar15 >> 0x10);
          if ((int)(Car_tObj *)-(iVar15 >> 0x10) *
              (((this->AIHigh_BasicPerp).AIHigh_Base.carObj_)->script).lastReactionIndex[3] < 0) {
            (&pAVar12->carObj_)[0x13] = (Car_tObj *)0x0;
          }
        }
        else {
          if (local_50 == 0) goto LAB_800620e8;
          if (pAVar18 == (AIHigh_Base *)0x0) {
            pAVar18 = pAVar12;
          }
          local_50 = local_50 + -1;
          *(undefined2 *)(&pAVar12->carObj_ + 0x14) = 0;
          (&pAVar12->carObj_)[10] = pCVar4;
          (&pAVar12->carObj_)[0xb] = (Car_tObj *)(this->perpChaseInfo_).chaseLevelIndex_;
          (&pAVar12->carObj_)[8] = (Car_tObj *)0x2;
          iVar15 = (((int)(uVar14 + (uVar14 >> 0x1f)) >> 1) * 2 + 3) *
                   (((this->AIHigh_BasicPerp).AIHigh_Base.carObj_)->script).lastReactionIndex[3];
          if (iVar15 < 0) {
            pCVar4 = (Car_tObj *)((int)&(pCVar16->N).objID + iVar15);
            if ((int)pCVar4 < 0) {
              pCVar4 = (Car_tObj *)((int)&(pCVar4->N).objID + gNumSlices);
            }
          }
          else {
            pCVar4 = (Car_tObj *)((int)&(pCVar16->N).objID + iVar15);
            if (gNumSlices <= (int)pCVar4) {
              pCVar4 = (Car_tObj *)((int)pCVar4 - gNumSlices);
            }
          }
          (&pAVar12->carObj_)[0xd] = pCVar4;
          uVar11 = fastRandom * randSeed;
          (&pAVar12->carObj_)[0xe] =
               (Car_tObj *)
               (((this->AIHigh_BasicPerp).AIHigh_Base.carObj_)->script).lastReactionIndex[3];
          fastRandom = uVar11 & 0xffff;
          if ((uVar11 >> 8 & 0xffff) * 1000 >> 0x10 < 300) {
            (&pAVar12->carObj_)[0x11] = pCVar5;
          }
          else {
            (&pAVar12->carObj_)[0x11] = (Car_tObj *)0x0;
          }
          randtemp = fastRandom * randSeed;
          (&pAVar12->carObj_)[0x12] =
               (Car_tObj *)(&DAT_0000d999 + ((randtemp >> 8 & 0xffff) * 0x14ccd >> 0x10));
          fastRandom = randtemp & 0xffff;
          local_30 = pCVar5;
          iVar15 = AIWorld_ApxSplineDistance__FP8Car_tObji
                             ((this->AIHigh_BasicPerp).AIHigh_Base.carObj_,
                              (int)(&pAVar12->carObj_)[0xd]);
          if (iVar15 < 0) {
            iVar15 = iVar15 + 0xffff;
          }
          (&pAVar12->carObj_)[0x13] = (Car_tObj *)-(iVar15 >> 0x10);
          if ((int)(Car_tObj *)-(iVar15 >> 0x10) *
              (((this->AIHigh_BasicPerp).AIHigh_Base.carObj_)->script).lastReactionIndex[3] < 0) {
            (&pAVar12->carObj_)[0x13] = (Car_tObj *)0x0;
          }
          pTVar8 = BWorldSm_slices + (int)(&pAVar12->carObj_)[0xd];
          iVar15 = (uint)pTVar8->avgPavedWidthLf * 0x8000 * (uint)(pTVar8->laneCount >> 4);
          uVar11 = iVar15 + (uint)pTVar8->avgPavedWidthRt * 0x8000 * ((uint)pTVar8->laneCount & 0xf)
          ;
          if ((local_48[0] == local_30) && (local_48[1] == (Car_tObj *)0x0)) {
            (&pAVar12->carObj_)[0xf] = (Car_tObj *)((uVar11 >> 1) - iVar15);
            pCVar5 = (Car_tObj *)0xff;
          }
          else {
            iVar15 = (int)uVar11 >> 2;
            if ((uVar14 & 1) == 0) {
              (&pAVar12->carObj_)[0xf] =
                   (Car_tObj *)
                   (iVar15 - (uint)BWorldSm_slices[(int)(&pAVar12->carObj_)[0xd]].avgPavedWidthLf *
                             0x8000 * (uint)(BWorldSm_slices[(int)(&pAVar12->carObj_)[0xd]].
                                             laneCount >> 4));
              pCVar5 = (Car_tObj *)0xbe;
            }
            else {
              pCVar5 = (Car_tObj *)0xffffff42;
              (&pAVar12->carObj_)[0xf] =
                   (Car_tObj *)
                   (iVar15 * 3 -
                   (uint)BWorldSm_slices[(int)(&pAVar12->carObj_)[0xd]].avgPavedWidthLf * 0x8000 *
                   (uint)(BWorldSm_slices[(int)(&pAVar12->carObj_)[0xd]].laneCount >> 4));
            }
          }
          (&pAVar12->carObj_)[0x10] = pCVar5;
          *(AIHigh_Player **)(&pAVar12->carObj_ + 9) = this;
        }
        pCVar4 = (Car_tObj *)0x0;
        if (pCVar10 != (Car_tObj *)0xffffffff) {
          local_40[3] = 1;
          (&pAVar12->carObj_)[0xc] = pCVar10;
          pCVar10 = (Car_tObj *)0xffffffff;
        }
        *(Car_tObj **)&(this->perpChaseInfo_).blockadeDone_ = local_30;
        uVar14 = uVar14 + 1;
        pCVar5 = local_30;
      }
LAB_800620e8:
      slice = slice + 1;
    }
    if (pAVar18 != (AIHigh_Base *)0x0) {
      *(undefined2 *)&pAVar18[3].stateType_ = 1;
      if (local_40[3] == 0) {
        pSVar6 = Mobile__6SpeechP8Car_tObj(pAVar18->carObj_);
        sVar1 = *(short *)(*(int *)pSVar6->_vf + 0x50);
        pcVar9 = *(code **)(*(int *)pSVar6->_vf + 0x54);
      }
      else {
        pSVar6 = Mobile__6SpeechP8Car_tObj(pAVar18->carObj_);
        sVar1 = *(short *)(*(int *)pSVar6->_vf + 0x58);
        pcVar9 = *(code **)(*(int *)pSVar6->_vf + 0x5c);
      }
      (*pcVar9)((int)&(pSVar6->fPosition).flags + (int)sVar1);
      pSVar6 = Mobile__6SpeechP8Car_tObj(pAVar18->carObj_);
      (**(code **)(*(int *)pSVar6->_vf + 0x34))
                ((int)&(pSVar6->fPosition).flags + (int)*(short *)(*(int *)pSVar6->_vf + 0x30),
                 (this->AIHigh_BasicPerp).AIHigh_Base.carObj_);
      pSVar6 = Dispatch__6Speech();
      (**(code **)(*(int *)pSVar6->_vf + 0x24))
                ((int)&(pSVar6->fPosition).flags + (int)*(short *)(*(int *)pSVar6->_vf + 0x20));
      pSVar6 = Dispatch__6Speech();
      (**(code **)(*(int *)pSVar6->_vf + 0x2c))
                ((int)&(pSVar6->fPosition).flags + (int)*(short *)(*(int *)pSVar6->_vf + 0x28),
                 pAVar18->carObj_);
    }
  }
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ CheckForNewLevel__13AIHigh_Playeri(struct AIHigh_Player *this /*$s2*/, int force /*$s1*/)
 // line 434, offset 0x8006220c
	/* begin block 1 */
		// Start line: 435
		// Start offset: 0x8006220C
		// Variables:
	// 		int chaseLevel; // $s0
	// 		int oldChaseLevel; // $s3

		/* begin block 1.1 */
			// Start line: 435
			// Start offset: 0x8006220C
			// Variables:
		// 		struct AICop_PerpChaseInfo *this; // $v1

			/* begin block 1.1.1 */
				// Start line: 435
				// Start offset: 0x8006220C
			/* end block 1.1.1 */
			// End offset: 0x8006220C
			// End Line: 435
		/* end block 1.1 */
		// End offset: 0x8006220C
		// End Line: 435

		/* begin block 1.2 */
			// Start line: 435
			// Start offset: 0x8006220C

			/* begin block 1.2.1 */
				// Start line: 440
				// Start offset: 0x8006224C

				/* begin block 1.2.1.1 */
					// Start line: 440
					// Start offset: 0x8006224C
					// Variables:
				// 		struct AICop_PerpChaseInfo *this; // $s0

					/* begin block 1.2.1.1.1 */
						// Start line: 440
						// Start offset: 0x8006224C

						/* begin block 1.2.1.1.1.1 */
							// Start line: 440
							// Start offset: 0x80062264
							// Variables:
						// 		struct AICop_PerpChaseInfo *this; // $s0

							/* begin block 1.2.1.1.1.1.1 */
								// Start line: 440
								// Start offset: 0x80062264

								/* begin block 1.2.1.1.1.1.1.1 */
									// Start line: 440
									// Start offset: 0x80062264
									// Variables:
								// 		struct AICop_PerpChaseInfo *this; // $s0

									/* begin block 1.2.1.1.1.1.1.1.1 */
										// Start line: 440
										// Start offset: 0x80062264

										/* begin block 1.2.1.1.1.1.1.1.1.1 */
											// Start line: 440
											// Start offset: 0x80062264
											// Variables:
										// 		struct AICop_PerpChaseInfo *this; // $s0

											/* begin block 1.2.1.1.1.1.1.1.1.1.1 */
												// Start line: 440
												// Start offset: 0x80062264
											/* end block 1.2.1.1.1.1.1.1.1.1.1 */
											// End offset: 0x80062264
											// End Line: 440
										/* end block 1.2.1.1.1.1.1.1.1.1 */
										// End offset: 0x80062264
										// End Line: 440
									/* end block 1.2.1.1.1.1.1.1.1 */
									// End offset: 0x800622B0
									// End Line: 440
								/* end block 1.2.1.1.1.1.1.1 */
								// End offset: 0x800622B0
								// End Line: 440

								/* begin block 1.2.1.1.1.1.1.2 */
									// Start line: 440
									// Start offset: 0x800622B0
									// Variables:
								// 		struct AICop_PerpChaseInfo *this; // $s0

									/* begin block 1.2.1.1.1.1.1.2.1 */
										// Start line: 440
										// Start offset: 0x800622B0
									/* end block 1.2.1.1.1.1.1.2.1 */
									// End offset: 0x80062328
									// End Line: 440
								/* end block 1.2.1.1.1.1.1.2 */
								// End offset: 0x80062328
								// End Line: 440
							/* end block 1.2.1.1.1.1.1 */
							// End offset: 0x80062328
							// End Line: 440
						/* end block 1.2.1.1.1.1 */
						// End offset: 0x80062328
						// End Line: 440
					/* end block 1.2.1.1.1 */
					// End offset: 0x80062328
					// End Line: 440
				/* end block 1.2.1.1 */
				// End offset: 0x80062328
				// End Line: 440

				/* begin block 1.2.1.2 */
					// Start line: 440
					// Start offset: 0x80062328

					/* begin block 1.2.1.2.1 */
						// Start line: 440
						// Start offset: 0x80062328
					/* end block 1.2.1.2.1 */
					// End offset: 0x80062328
					// End Line: 440
				/* end block 1.2.1.2 */
				// End offset: 0x80062328
				// End Line: 440
			/* end block 1.2.1 */
			// End offset: 0x80062334
			// End Line: 444
		/* end block 1.2 */
		// End offset: 0x80062334
		// End Line: 444

		/* begin block 1.3 */
			// Start line: 476
			// Start offset: 0x80062334

			/* begin block 1.3.1 */
				// Start line: 476
				// Start offset: 0x80062334

				/* begin block 1.3.1.1 */
					// Start line: 476
					// Start offset: 0x80062334
				/* end block 1.3.1.1 */
				// End offset: 0x80062334
				// End Line: 476
			/* end block 1.3.1 */
			// End offset: 0x80062334
			// End Line: 476

			/* begin block 1.3.2 */
				// Start line: 482
				// Start offset: 0x80062360

				/* begin block 1.3.2.1 */
					// Start line: 482
					// Start offset: 0x80062360

					/* begin block 1.3.2.1.1 */
						// Start line: 491
						// Start offset: 0x80062368

						/* begin block 1.3.2.1.1.1 */
							// Start line: 491
							// Start offset: 0x80062368
						/* end block 1.3.2.1.1.1 */
						// End offset: 0x80062380
						// End Line: 491
					/* end block 1.3.2.1.1 */
					// End offset: 0x80062380
					// End Line: 491

					/* begin block 1.3.2.1.2 */
						// Start line: 491
						// Start offset: 0x8006238C

						/* begin block 1.3.2.1.2.1 */
							// Start line: 491
							// Start offset: 0x8006238C
						/* end block 1.3.2.1.2.1 */
						// End offset: 0x8006238C
						// End Line: 491
					/* end block 1.3.2.1.2 */
					// End offset: 0x8006238C
					// End Line: 491

					/* begin block 1.3.2.1.3 */
						// Start line: 492
						// Start offset: 0x80062398

						/* begin block 1.3.2.1.3.1 */
							// Start line: 493
							// Start offset: 0x80062398

							/* begin block 1.3.2.1.3.1.1 */
								// Start line: 493
								// Start offset: 0x80062398
								// Variables:
							// 		struct AICop_PerpChaseInfo *this; // $a0

								/* begin block 1.3.2.1.3.1.1.1 */
									// Start line: 493
									// Start offset: 0x80062398
								/* end block 1.3.2.1.3.1.1.1 */
								// End offset: 0x80062398
								// End Line: 493
							/* end block 1.3.2.1.3.1.1 */
							// End offset: 0x80062398
							// End Line: 493

							/* begin block 1.3.2.1.3.1.2 */
								// Start line: 495
								// Start offset: 0x800623B4

								/* begin block 1.3.2.1.3.1.2.1 */
									// Start line: 495
									// Start offset: 0x800623B4

									/* begin block 1.3.2.1.3.1.2.1.1 */
										// Start line: 495
										// Start offset: 0x800623B4
									/* end block 1.3.2.1.3.1.2.1.1 */
									// End offset: 0x800623B4
									// End Line: 495
								/* end block 1.3.2.1.3.1.2.1 */
								// End offset: 0x800623B4
								// End Line: 495
							/* end block 1.3.2.1.3.1.2 */
							// End offset: 0x800623B8
							// End Line: 495
						/* end block 1.3.2.1.3.1 */
						// End offset: 0x800623B8
						// End Line: 495

						/* begin block 1.3.2.1.3.2 */
							// Start line: 495
							// Start offset: 0x800623B8
							// Variables:
						// 		struct AICop_PerpChaseInfo *this; // $s1
						// 		int level; // $s0

							/* begin block 1.3.2.1.3.2.1 */
								// Start line: 495
								// Start offset: 0x800623B8

								/* begin block 1.3.2.1.3.2.1.1 */
									// Start line: 495
									// Start offset: 0x800623D0
									// Variables:
								// 		struct AICop_PerpChaseInfo *this; // $s1

									/* begin block 1.3.2.1.3.2.1.1.1 */
										// Start line: 495
										// Start offset: 0x800623D0

										/* begin block 1.3.2.1.3.2.1.1.1.1 */
											// Start line: 495
											// Start offset: 0x800623D0
											// Variables:
										// 		struct AICop_PerpChaseInfo *this; // $s1

											/* begin block 1.3.2.1.3.2.1.1.1.1.1 */
												// Start line: 495
												// Start offset: 0x800623D0

												/* begin block 1.3.2.1.3.2.1.1.1.1.1.1 */
													// Start line: 495
													// Start offset: 0x800623D0
													// Variables:
												// 		struct AICop_PerpChaseInfo *this; // $s1

													/* begin block 1.3.2.1.3.2.1.1.1.1.1.1.1 */
														// Start line: 495
														// Start offset: 0x800623D0
													/* end block 1.3.2.1.3.2.1.1.1.1.1.1.1 */
													// End offset: 0x800623D0
													// End Line: 495
												/* end block 1.3.2.1.3.2.1.1.1.1.1.1 */
												// End offset: 0x800623D0
												// End Line: 495
											/* end block 1.3.2.1.3.2.1.1.1.1.1 */
											// End offset: 0x8006241C
											// End Line: 495
										/* end block 1.3.2.1.3.2.1.1.1.1 */
										// End offset: 0x8006241C
										// End Line: 495

										/* begin block 1.3.2.1.3.2.1.1.1.2 */
											// Start line: 495
											// Start offset: 0x8006241C
											// Variables:
										// 		struct AICop_PerpChaseInfo *this; // $s1

											/* begin block 1.3.2.1.3.2.1.1.1.2.1 */
												// Start line: 495
												// Start offset: 0x8006241C
											/* end block 1.3.2.1.3.2.1.1.1.2.1 */
											// End offset: 0x80062494
											// End Line: 495
										/* end block 1.3.2.1.3.2.1.1.1.2 */
										// End offset: 0x80062494
										// End Line: 495
									/* end block 1.3.2.1.3.2.1.1.1 */
									// End offset: 0x80062494
									// End Line: 495
								/* end block 1.3.2.1.3.2.1.1 */
								// End offset: 0x80062494
								// End Line: 495
							/* end block 1.3.2.1.3.2.1 */
							// End offset: 0x80062498
							// End Line: 495
						/* end block 1.3.2.1.3.2 */
						// End offset: 0x80062498
						// End Line: 495
					/* end block 1.3.2.1.3 */
					// End offset: 0x80062498
					// End Line: 496
				/* end block 1.3.2.1 */
				// End offset: 0x80062498
				// End Line: 496
			/* end block 1.3.2 */
			// End offset: 0x80062498
			// End Line: 496
		/* end block 1.3 */
		// End offset: 0x80062498
		// End Line: 496

		/* begin block 1.4 */
			// Start line: 504
			// Start offset: 0x80062498

			/* begin block 1.4.1 */
				// Start line: 504
				// Start offset: 0x80062498
				// Variables:
			// 		struct AICop_PerpChaseInfo *this; // $v1

				/* begin block 1.4.1.1 */
					// Start line: 504
					// Start offset: 0x80062498
				/* end block 1.4.1.1 */
				// End offset: 0x80062498
				// End Line: 504
			/* end block 1.4.1 */
			// End offset: 0x80062498
			// End Line: 504

			/* begin block 1.4.2 */
				// Start line: 505
				// Start offset: 0x800624AC

				/* begin block 1.4.2.1 */
					// Start line: 505
					// Start offset: 0x800624AC
					// Variables:
				// 		struct AITrigger_TriggerManager *this; // $v0

					/* begin block 1.4.2.1.1 */
						// Start line: 505
						// Start offset: 0x800624AC
					/* end block 1.4.2.1.1 */
					// End offset: 0x800624AC
					// End Line: 505
				/* end block 1.4.2.1 */
				// End offset: 0x800624AC
				// End Line: 505

				/* begin block 1.4.2.2 */
					// Start line: 505
					// Start offset: 0x800624AC

					/* begin block 1.4.2.2.1 */
						// Start line: 505
						// Start offset: 0x800624AC
					/* end block 1.4.2.2.1 */
					// End offset: 0x800624AC
					// End Line: 505
				/* end block 1.4.2.2 */
				// End offset: 0x800624AC
				// End Line: 505
			/* end block 1.4.2 */
			// End offset: 0x800624D0
			// End Line: 506
		/* end block 1.4 */
		// End offset: 0x800624D0
		// End Line: 506
	/* end block 1 */
	// End offset: 0x800624D0
	// End Line: 506

	/* begin block 2 */
		// Start line: 1145
	/* end block 2 */
	// End Line: 1146

	/* begin block 3 */
		// Start line: 1148
	/* end block 3 */
	// End Line: 1149

	/* begin block 4 */
		// Start line: 1148
	/* end block 4 */
	// End Line: 1149

/* WARNING: Removing unreachable block (ram,0x800622e0) */
/* WARNING: Removing unreachable block (ram,0x8006244c) */

void CheckForNewLevel__13AIHigh_Playeri(AIHigh_Player *this,int force)

{
  uint uVar1;
  copLevel_t *pcVar2;
  int iVar3;
  undefined *puVar4;
  int iVar5;
  int iVar6;
  int iVar7;
  
  iVar5 = (this->perpChaseInfo_).chaseLevelIndex_;
  if (1 < (((this->AIHigh_BasicPerp).AIHigh_Base.carObj_)->stats).finishType) {
    (this->perpChaseInfo_).chaseLevelIndex_ = 0;
    if ((this->perpChaseInfo_).bestChaseLevelIndex_ < 0) {
      (this->perpChaseInfo_).bestChaseLevelIndex_ = 0;
    }
    pcVar2 = ((this->perpChaseInfo_).copGameInfo_)->levels + (this->perpChaseInfo_).chaseLevelIndex_
    ;
    (this->perpChaseInfo_).chaseLevel_ = pcVar2;
    iVar5 = pcVar2->engagementLapFraction * AITune_gRoughLapTime;
    if (iVar5 < 0) {
      iVar5 = iVar5 + 0xffff;
    }
    iVar3 = (iVar5 >> 0x10) << 5;
    iVar6 = 0x10000 / iVar3;
    if (iVar3 == 0) {
      trap(0x1c00);
    }
    (this->perpChaseInfo_).engagementTime_ = (iVar5 >> 0x10) << 0x15;
    (this->perpChaseInfo_).engagementPercentIncreasePerTick_ = iVar6;
    if (GameSetup_gData.numLaps == 2) {
      puVar4 = &DAT_00013333;
    }
    else {
      puVar4 = &DAT_0000a8f5;
      if (GameSetup_gData.numLaps != 4) goto LAB_80062328;
    }
    uVar1 = fixedmult(iVar6,(int)puVar4);
    (this->perpChaseInfo_).engagementPercentIncreasePerTick_ = uVar1;
LAB_80062328:
    (this->perpChaseInfo_).blockadeDone_ = 0;
    (this->AIHigh_BasicPerp).basicPerpInfo_.crime_ = CRIME_NONE;
    return;
  }
  iVar3 = *(int *)(this->AIHigh_BasicPerp).AIHigh_Base._vf;
  (**(code **)(iVar3 + 0x1c))
            ((int)&(this->AIHigh_BasicPerp).AIHigh_Base.carObj_ + (int)*(short *)(iVar3 + 0x18));
  if ((this->AIHigh_BasicPerp).basicPerpInfo_.crime_ == CRIME_NONE) goto LAB_8006249c;
  if (force == 0) {
    iVar3 = (this->perpChaseInfo_).engagementTime_;
    if (iVar3 < 0) {
      iVar3 = iVar3 + 0xffff;
    }
    if (0 < iVar3 >> 0x10) goto LAB_8006249c;
  }
  iVar3 = ((this->perpChaseInfo_).copGameInfo_)->numLevels;
  iVar6 = iVar5 + 1;
  if (iVar3 <= iVar6) {
    iVar6 = iVar3 + -2;
  }
  (this->perpChaseInfo_).chaseLevelIndex_ = iVar6;
  if ((this->perpChaseInfo_).bestChaseLevelIndex_ < iVar6) {
    (this->perpChaseInfo_).bestChaseLevelIndex_ = iVar6;
  }
  pcVar2 = ((this->perpChaseInfo_).copGameInfo_)->levels + (this->perpChaseInfo_).chaseLevelIndex_;
  (this->perpChaseInfo_).chaseLevel_ = pcVar2;
  iVar3 = pcVar2->engagementLapFraction * AITune_gRoughLapTime;
  if (iVar3 < 0) {
    iVar3 = iVar3 + 0xffff;
  }
  iVar6 = (iVar3 >> 0x10) << 5;
  iVar7 = 0x10000 / iVar6;
  if (iVar6 == 0) {
    trap(0x1c00);
  }
  (this->perpChaseInfo_).engagementTime_ = (iVar3 >> 0x10) << 0x15;
  (this->perpChaseInfo_).engagementPercentIncreasePerTick_ = iVar7;
  if (GameSetup_gData.numLaps == 2) {
    puVar4 = &DAT_00013333;
LAB_80062488:
    uVar1 = fixedmult(iVar7,(int)puVar4);
    (this->perpChaseInfo_).engagementPercentIncreasePerTick_ = uVar1;
  }
  else {
    puVar4 = &DAT_0000a8f5;
    if (GameSetup_gData.numLaps == 4) goto LAB_80062488;
  }
  (this->perpChaseInfo_).blockadeDone_ = 0;
LAB_8006249c:
  if (iVar5 == (this->perpChaseInfo_).chaseLevelIndex_) {
    return;
  }
  this->newTriggerProb_ =
       triggerManagerCops->invNumTriggers_ * ((this->perpChaseInfo_).chaseLevel_)->copsPerLap;
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ HandleSpeech__13AIHigh_Player(struct AIHigh_Player *this /*$s0*/)
 // line 517, offset 0x800624ec
	/* begin block 1 */
		// Start line: 518
		// Start offset: 0x800624EC
		// Variables:
	// 		int highestRankedCopIndex; // $s1
	// 		int arrestType; // $s0
	// 		int player; // $a0
	/* end block 1 */
	// End offset: 0x800625EC
	// End Line: 664

	/* begin block 2 */
		// Start line: 1309
	/* end block 2 */
	// End Line: 1310

	/* begin block 3 */
		// Start line: 1315
	/* end block 3 */
	// End Line: 1316

	/* begin block 4 */
		// Start line: 1315
	/* end block 4 */
	// End Line: 1316

void HandleSpeech__13AIHigh_Player(AIHigh_Player *this)

{
  Speaker *pSVar1;
  int iVar2;
  int player;
  __95 _Var3;
  
  iVar2 = (this->AIHigh_BasicPerp).positionVSCopList_[0].carIndex;
  if (iVar2 == -1) {
    iVar2 = Cars_gCopCarList9->carIndex;
  }
  player = (this->AIHigh_BasicPerp).positionVSCopList_[1].carIndex;
  if ((player != -1) && (player < iVar2)) {
    iVar2 = player;
  }
  player = (this->AIHigh_BasicPerp).positionVSCopList_[2].carIndex;
  if ((player != -1) && (player < iVar2)) {
    iVar2 = player;
  }
  _Var3 = (this->AIHigh_BasicPerp).pullOverMode_;
  player = ((this->AIHigh_BasicPerp).AIHigh_Base.carObj_)->carIndex;
  if (_Var3 == PULLOVER_WARNING) {
    Hud_Perp_OverlayOn__Fii(player,0);
    player = 2;
    goto LAB_800625d0;
  }
  if (1 < (int)_Var3) {
    if (_Var3 == PULLOVER_BUST) {
      Hud_Perp_OverlayOn__Fii(player,1);
      player = 8;
      if (2 < this->numBusts_) {
        player = this->numBusts_ + 6;
      }
      goto LAB_800625d0;
    }
    if (_Var3 == PULLOVER_EOG) {
      Hud_Perp_OverlayOn__Fii(player,2);
      player = 1;
      goto LAB_800625d0;
    }
  }
  player = 4;
LAB_800625d0:
  if (AICop_gRoadBlockState != kAICop_RoadBlockState_None) {
    AICop_gRoadBlockState = kAICop_RoadBlockState_PerpPassed;
  }
  pSVar1 = Mobile__6SpeechP8Car_tObj((&Cars_gList9)[iVar2]);
  (**(code **)(*(int *)pSVar1->_vf + 0x4c))
            ((int)&(pSVar1->fPosition).flags + (int)*(short *)(*(int *)pSVar1->_vf + 0x48),player);
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ MaintainAvailableCops__13AIHigh_Player(struct AIHigh_Player *this /*$a0*/)
 // line 669, offset 0x80062638
	/* begin block 1 */
		// Start line: 670
		// Start offset: 0x80062638
		// Variables:
	// 		int need[2]; // stack offset -24
	// 		int got[2]; // stack offset -16
	// 		int availableCops; // $t1

		/* begin block 1.1 */
			// Start line: 693
			// Start offset: 0x8006268C
			// Variables:
		// 		int playLoop; // $a3

			/* begin block 1.1.1 */
				// Start line: 693
				// Start offset: 0x800626A8
				// Variables:
			// 		struct Car_tObj *playerCarObj; // $v0
			// 		struct AIHigh_Player *playerHighObj; // $a1

				/* begin block 1.1.1.1 */
					// Start line: 698
					// Start offset: 0x800626B4
					// Variables:
				// 		struct AICop_PerpChaseInfo *this; // $a1

					/* begin block 1.1.1.1.1 */
						// Start line: 698
						// Start offset: 0x800626B4
					/* end block 1.1.1.1.1 */
					// End offset: 0x800626B4
					// End Line: 698
				/* end block 1.1.1.1 */
				// End offset: 0x800626B4
				// End Line: 698

				/* begin block 1.1.1.2 */
					// Start line: 698
					// Start offset: 0x800626B4

					/* begin block 1.1.1.2.1 */
						// Start line: 698
						// Start offset: 0x800626B4
					/* end block 1.1.1.2.1 */
					// End offset: 0x800626B4
					// End Line: 698
				/* end block 1.1.1.2 */
				// End offset: 0x800626B4
				// End Line: 698

				/* begin block 1.1.1.3 */
					// Start line: 698
					// Start offset: 0x800626B4

					/* begin block 1.1.1.3.1 */
						// Start line: 698
						// Start offset: 0x800626B4
					/* end block 1.1.1.3.1 */
					// End offset: 0x800626B4
					// End Line: 698
				/* end block 1.1.1.3 */
				// End offset: 0x800626B4
				// End Line: 698

				/* begin block 1.1.1.4 */
					// Start line: 698
					// Start offset: 0x800626B4

					/* begin block 1.1.1.4.1 */
						// Start line: 698
						// Start offset: 0x800626B4
					/* end block 1.1.1.4.1 */
					// End offset: 0x800626B4
					// End Line: 698
				/* end block 1.1.1.4 */
				// End offset: 0x800626B4
				// End Line: 698
			/* end block 1.1.1 */
			// End offset: 0x800626B4
			// End Line: 698
		/* end block 1.1 */
		// End offset: 0x8006273C
		// End Line: 705

		/* begin block 1.2 */
			// Start line: 710
			// Start offset: 0x8006273C
			// Variables:
		// 		int copLoop; // $t0
		// 		int playLoop; // $a3

			/* begin block 1.2.1 */
				// Start line: 710
				// Start offset: 0x8006275C
				// Variables:
			// 		struct Car_tObj *copCarObj; // $a0
			// 		struct AIHigh_Cop *copHighObj; // $a1

				/* begin block 1.2.1.1 */
					// Start line: 714
					// Start offset: 0x80062768

					/* begin block 1.2.1.1.1 */
						// Start line: 716
						// Start offset: 0x80062790
						// Variables:
					// 		struct AIHigh_BasicCop *this; // $a1

						/* begin block 1.2.1.1.1.1 */
							// Start line: 716
							// Start offset: 0x80062790
						/* end block 1.2.1.1.1.1 */
						// End offset: 0x80062790
						// End Line: 716
					/* end block 1.2.1.1.1 */
					// End offset: 0x80062790
					// End Line: 716

					/* begin block 1.2.1.1.2 */
						// Start line: 716
						// Start offset: 0x800627A0
						// Variables:
					// 		struct AIHigh_BasicCop *this; // $a1

						/* begin block 1.2.1.1.2.1 */
							// Start line: 716
							// Start offset: 0x800627A0
						/* end block 1.2.1.1.2.1 */
						// End offset: 0x800627A0
						// End Line: 716
					/* end block 1.2.1.1.2 */
					// End offset: 0x800627A0
					// End Line: 716

					/* begin block 1.2.1.1.3 */
						// Start line: 717
						// Start offset: 0x800627B4

						/* begin block 1.2.1.1.3.1 */
							// Start line: 717
							// Start offset: 0x800627B4
							// Variables:
						// 		struct AIHigh_BasicCop *this; // $a1

							/* begin block 1.2.1.1.3.1.1 */
								// Start line: 717
								// Start offset: 0x800627B4
							/* end block 1.2.1.1.3.1.1 */
							// End offset: 0x800627B4
							// End Line: 717
						/* end block 1.2.1.1.3.1 */
						// End offset: 0x800627B4
						// End Line: 717
					/* end block 1.2.1.1.3 */
					// End offset: 0x800627B4
					// End Line: 717
				/* end block 1.2.1.1 */
				// End offset: 0x800627F4
				// End Line: 724
			/* end block 1.2.1 */
			// End offset: 0x800627F4
			// End Line: 724
		/* end block 1.2 */
		// End offset: 0x80062800
		// End Line: 726

		/* begin block 1.3 */
			// Start line: 729
			// Start offset: 0x80062800
			// Variables:
		// 		int copLoop; // $a3

			/* begin block 1.3.1 */
				// Start line: 729
				// Start offset: 0x80062820
				// Variables:
			// 		struct Car_tObj *copCarObj; // $a1

				/* begin block 1.3.1.1 */
					// Start line: 732
					// Start offset: 0x80062830

					/* begin block 1.3.1.1.1 */
						// Start line: 734
						// Start offset: 0x8006284C
						// Variables:
					// 		struct AIHigh_Cop *copHighObj; // $v0

						/* begin block 1.3.1.1.1.1 */
							// Start line: 736
							// Start offset: 0x8006284C
							// Variables:
						// 		struct AIHigh_BasicCop *this; // $v0

							/* begin block 1.3.1.1.1.1.1 */
								// Start line: 736
								// Start offset: 0x8006284C
							/* end block 1.3.1.1.1.1.1 */
							// End offset: 0x8006284C
							// End Line: 736
						/* end block 1.3.1.1.1.1 */
						// End offset: 0x8006284C
						// End Line: 736
					/* end block 1.3.1.1.1 */
					// End offset: 0x800628A4
					// End Line: 742
				/* end block 1.3.1.1 */
				// End offset: 0x800628A4
				// End Line: 742
			/* end block 1.3.1 */
			// End offset: 0x800628A4
			// End Line: 742
		/* end block 1.3 */
		// End offset: 0x800628B0
		// End Line: 745
	/* end block 1 */
	// End offset: 0x800628B0
	// End Line: 745

	/* begin block 2 */
		// Start line: 1627
	/* end block 2 */
	// End Line: 1628

	/* begin block 3 */
		// Start line: 1633
	/* end block 3 */
	// End Line: 1634

	/* begin block 4 */
		// Start line: 1633
	/* end block 4 */
	// End Line: 1634

void MaintainAvailableCops__13AIHigh_Player(AIHigh_Player *this)

{
  bool bVar1;
  int iVar2;
  speechSourceType sVar3;
  stateType_t sVar4;
  Car_tObj *pCVar5;
  Car_tObj **ppCVar6;
  int iVar7;
  int iVar8;
  int iVar9;
  int local_18 [4];
  
  memset(local_18,0,8);
  memset(local_18 + 2,0,8);
  iVar8 = Cars_gNumCopCars;
  iVar9 = 3;
  if ((Cars_gNumRaceCars != 1) && (iVar9 = 4, Cars_gNumHumanRaceCars == 2)) {
    iVar9 = 2;
  }
  iVar7 = 0;
  do {
    bVar1 = iVar7 < Cars_gNumRaceCars;
    iVar7 = iVar7 + 1;
  } while (bVar1);
  iVar7 = 0;
  ppCVar6 = &Cars_gCopCarList9;
  while (iVar2 = Cars_gNumCopCars, iVar7 < iVar8) {
    pCVar5 = *ppCVar6;
    bVar1 = false;
    if (((((pCVar5->speechInfo).speechSource & 4) == 0) ||
        (sVar4 = (&highLevelAIObjs9)[pCVar5->carIndex][1].stateType_, sVar4 == STATE_PURGATORY)) ||
       (sVar4 == STATE_NORMAL)) {
      bVar1 = true;
    }
    if (bVar1) {
      local_18[(int)&(((&highLevelAIObjs9)[pCVar5->carIndex][1].carObj_)->N).objID + 2] =
           local_18[(int)&(((&highLevelAIObjs9)[pCVar5->carIndex][1].carObj_)->N).objID + 2] + 1;
      iVar9 = iVar9 + -1;
      sVar3 = (pCVar5->speechInfo).speechSource | 8;
    }
    else {
      sVar3 = (pCVar5->speechInfo).speechSource & 0xfffffff7;
    }
    (pCVar5->speechInfo).speechSource = sVar3;
    ppCVar6 = ppCVar6 + 1;
    iVar7 = iVar7 + 1;
  }
  iVar8 = 0;
  ppCVar6 = &Cars_gCopCarList9;
  while ((0 < iVar9 && (iVar8 < iVar2))) {
    pCVar5 = *ppCVar6;
    if (((pCVar5->speechInfo).speechSource & 8) == 0) {
      iVar7 = local_18[(int)&(((&highLevelAIObjs9)[pCVar5->carIndex][1].carObj_)->N).objID + 2];
      if (iVar7 < local_18[(int)(&highLevelAIObjs9)[pCVar5->carIndex][1].carObj_]) {
        local_18[(int)&(((&highLevelAIObjs9)[pCVar5->carIndex][1].carObj_)->N).objID + 2] =
             iVar7 + 1;
        iVar9 = iVar9 + -1;
        (pCVar5->speechInfo).speechSource = (pCVar5->speechInfo).speechSource | 8;
      }
    }
    ppCVar6 = ppCVar6 + 1;
    iVar8 = iVar8 + 1;
  }
  return;
}



// decompiled code
// original method signature: 
// struct AIHigh_Player * /*$ra*/ __13AIHigh_PlayerP8Car_tObj(struct AIHigh_Player *this /*$s1*/, struct Car_tObj *carObj /*$a1*/)
 // line 750, offset 0x800628c0
	/* begin block 1 */
		// Start line: 751
		// Start offset: 0x800628C0
		// Variables:
	// 		struct AICop_PerpChaseInfo *this; // $a1

		/* begin block 1.1 */
			// Start line: 751
			// Start offset: 0x800628C0
			// Variables:
		// 		int gameIndex; // $v0
		// 		int lapIndex; // $a0
		// 		struct copGame_t *copGameInfo; // $v1

			/* begin block 1.1.1 */
				// Start line: 751
				// Start offset: 0x80062924
				// Variables:
			// 		struct copGame_t *copGameInfo; // $v1
			// 		struct AICop_PerpChaseInfo *this; // $a1

				/* begin block 1.1.1.1 */
					// Start line: 751
					// Start offset: 0x80062924

					/* begin block 1.1.1.1.1 */
						// Start line: 751
						// Start offset: 0x80062924
						// Variables:
					// 		struct AICop_PerpChaseInfo *this; // $a1
					// 		struct copGame_t *copGameInfo; // $v1

						/* begin block 1.1.1.1.1.1 */
							// Start line: 751
							// Start offset: 0x80062924
						/* end block 1.1.1.1.1.1 */
						// End offset: 0x80062924
						// End Line: 751
					/* end block 1.1.1.1.1 */
					// End offset: 0x80062924
					// End Line: 751
				/* end block 1.1.1.1 */
				// End offset: 0x80062924
				// End Line: 751
			/* end block 1.1.1 */
			// End offset: 0x80062924
			// End Line: 751
		/* end block 1.1 */
		// End offset: 0x80062924
		// End Line: 751
	/* end block 1 */
	// End offset: 0x80062924
	// End Line: 751

	/* begin block 2 */
		// Start line: 751
		// Start offset: 0x80062924

		/* begin block 2.1 */
			// Start line: 751
			// Start offset: 0x80062924

			/* begin block 2.1.1 */
				// Start line: 757
				// Start offset: 0x800629A0

				/* begin block 2.1.1.1 */
					// Start line: 757
					// Start offset: 0x800629A0
					// Variables:
				// 		struct AITrigger_TriggerManager *this; // $v0

					/* begin block 2.1.1.1.1 */
						// Start line: 757
						// Start offset: 0x800629A0
					/* end block 2.1.1.1.1 */
					// End offset: 0x800629A0
					// End Line: 757
				/* end block 2.1.1.1 */
				// End offset: 0x800629A0
				// End Line: 757

				/* begin block 2.1.1.2 */
					// Start line: 757
					// Start offset: 0x800629A0
					// Variables:
				// 		struct AICop_PerpChaseInfo *this; // $a1

					/* begin block 2.1.1.2.1 */
						// Start line: 757
						// Start offset: 0x800629A0
					/* end block 2.1.1.2.1 */
					// End offset: 0x800629A0
					// End Line: 757
				/* end block 2.1.1.2 */
				// End offset: 0x800629A0
				// End Line: 757

				/* begin block 2.1.1.3 */
					// Start line: 757
					// Start offset: 0x800629A0
					// Variables:
				// 		struct AICop_PerpChaseInfo *this; // $s0

					/* begin block 2.1.1.3.1 */
						// Start line: 757
						// Start offset: 0x800629A0

						/* begin block 2.1.1.3.1.1 */
							// Start line: 762
							// Start offset: 0x800629E8
							// Variables:
						// 		struct AICop_PerpChaseInfo *this; // $s0

							/* begin block 2.1.1.3.1.1.1 */
								// Start line: 762
								// Start offset: 0x800629E8

								/* begin block 2.1.1.3.1.1.1.1 */
									// Start line: 762
									// Start offset: 0x800629E8
									// Variables:
								// 		struct AICop_PerpChaseInfo *this; // $s0

									/* begin block 2.1.1.3.1.1.1.1.1 */
										// Start line: 762
										// Start offset: 0x800629E8

										/* begin block 2.1.1.3.1.1.1.1.1.1 */
											// Start line: 762
											// Start offset: 0x800629E8
											// Variables:
										// 		struct AICop_PerpChaseInfo *this; // $s0

											/* begin block 2.1.1.3.1.1.1.1.1.1.1 */
												// Start line: 762
												// Start offset: 0x800629E8
											/* end block 2.1.1.3.1.1.1.1.1.1.1 */
											// End offset: 0x800629E8
											// End Line: 762
										/* end block 2.1.1.3.1.1.1.1.1.1 */
										// End offset: 0x800629E8
										// End Line: 762
									/* end block 2.1.1.3.1.1.1.1.1 */
									// End offset: 0x80062A34
									// End Line: 762
								/* end block 2.1.1.3.1.1.1.1 */
								// End offset: 0x80062A34
								// End Line: 762

								/* begin block 2.1.1.3.1.1.1.2 */
									// Start line: 762
									// Start offset: 0x80062A34
									// Variables:
								// 		struct AICop_PerpChaseInfo *this; // $s0

									/* begin block 2.1.1.3.1.1.1.2.1 */
										// Start line: 762
										// Start offset: 0x80062A34
									/* end block 2.1.1.3.1.1.1.2.1 */
									// End offset: 0x80062AA8
									// End Line: 762
								/* end block 2.1.1.3.1.1.1.2 */
								// End offset: 0x80062AA8
								// End Line: 762
							/* end block 2.1.1.3.1.1.1 */
							// End offset: 0x80062AA8
							// End Line: 762
						/* end block 2.1.1.3.1.1 */
						// End offset: 0x80062AA8
						// End Line: 762
					/* end block 2.1.1.3.1 */
					// End offset: 0x80062AAC
					// End Line: 762
				/* end block 2.1.1.3 */
				// End offset: 0x80062AAC
				// End Line: 762
			/* end block 2.1.1 */
			// End offset: 0x80062AAC
			// End Line: 763
		/* end block 2.1 */
		// End offset: 0x80062AAC
		// End Line: 763
	/* end block 2 */
	// End offset: 0x80062AAC
	// End Line: 763

	/* begin block 3 */
		// Start line: 1794
	/* end block 3 */
	// End Line: 1795

	/* begin block 4 */
		// Start line: 1800
	/* end block 4 */
	// End Line: 1801

	/* begin block 5 */
		// Start line: 1800
	/* end block 5 */
	// End Line: 1801

/* WARNING: Removing unreachable block (ram,0x80062a64) */
/* WARNING: Type propagation algorithm not settling */

AIHigh_Player * __13AIHigh_PlayerP8Car_tObj(AIHigh_Player *this,Car_tObj *carObj)

{
  int iVar1;
  Car_tObj *pCVar2;
  uint uVar3;
  copLevel_t *pcVar4;
  int iVar5;
  undefined *puVar6;
  int iVar7;
  
  __16AIHigh_BasicPerpP8Car_tObj((AIHigh_BasicPerp *)this,carObj);
  *(undefined4 *)(this->AIHigh_BasicPerp).AIHigh_Base._vf = 0x80055098;
  if (GameSetup_gData.commMode == 1) {
    iVar1 = 2;
  }
  else {
    iVar1 = (uint)(0 < Cars_gNumAIRaceCars) << 2;
  }
  iVar1 = iVar1 + (uint)(GameSetup_gData.numLaps != 2);
  (this->perpChaseInfo_).copGameInfo_ = copGame + iVar1;
  (this->perpChaseInfo_).chaseLevelIndex_ = 0;
  (this->perpChaseInfo_).engagementTime_ = 0;
  (this->perpChaseInfo_).bestChaseLevelIndex_ = 0;
  pcVar4 = copGame[iVar1].levels;
  (this->perpChaseInfo_).blockadeDone_ = 0;
  (this->perpChaseInfo_).copFreeTicks_ = 0;
  (this->perpChaseInfo_).totalEngagementPercent_ = 0;
  (this->perpChaseInfo_).engagementPercentIncreasePerTick_ = 0;
  (this->perpChaseInfo_).chaseLevel_ = pcVar4 + (this->perpChaseInfo_).chaseLevelIndex_;
  this->numWarnings_ = 0;
  this->numBusts_ = 0;
  if (GameSetup_gData.cops == 0) {
    return this;
  }
  pCVar2 = (this->AIHigh_BasicPerp).AIHigh_Base.carObj_;
  this->newTriggerProb_ =
       triggerManagerCops->invNumTriggers_ * ((this->perpChaseInfo_).chaseLevel_)->copsPerLap;
  this->lastTriggerCheckSlice_ = (int)(pCVar2->N).simRoadInfo.slice;
  (this->perpChaseInfo_).chaseLevelIndex_ = 0;
  if ((this->perpChaseInfo_).bestChaseLevelIndex_ < 0) {
    (this->perpChaseInfo_).bestChaseLevelIndex_ = 0;
  }
  pcVar4 = ((this->perpChaseInfo_).copGameInfo_)->levels + (this->perpChaseInfo_).chaseLevelIndex_;
  (this->perpChaseInfo_).chaseLevel_ = pcVar4;
  iVar1 = pcVar4->engagementLapFraction * AITune_gRoughLapTime;
  if (iVar1 < 0) {
    iVar1 = iVar1 + 0xffff;
  }
  iVar5 = (iVar1 >> 0x10) << 5;
  iVar7 = 0x10000 / iVar5;
  if (iVar5 == 0) {
    trap(0x1c00);
  }
  (this->perpChaseInfo_).engagementTime_ = (iVar1 >> 0x10) << 0x15;
  (this->perpChaseInfo_).engagementPercentIncreasePerTick_ = iVar7;
  if (GameSetup_gData.numLaps == 2) {
    puVar6 = &DAT_00013333;
  }
  else {
    puVar6 = &DAT_0000a8f5;
    if (GameSetup_gData.numLaps != 4) goto LAB_80062aa8;
  }
  uVar3 = fixedmult(iVar7,(int)puVar6);
  (this->perpChaseInfo_).engagementPercentIncreasePerTick_ = uVar3;
LAB_80062aa8:
  (this->perpChaseInfo_).blockadeDone_ = 0;
  return this;
}



// decompiled code
// original method signature: 
// void /*$ra*/ HandleCops__13AIHigh_Player(struct AIHigh_Player *this /*$s1*/)
 // line 808, offset 0x80062ac4
	/* begin block 1 */
		// Start line: 809
		// Start offset: 0x80062AC4
		// Variables:
	// 		struct copLevel_t *pLevel; // $s2

		/* begin block 1.1 */
			// Start line: 809
			// Start offset: 0x80062AC4
			// Variables:
		// 		struct AICop_PerpChaseInfo *this; // $s0

			/* begin block 1.1.1 */
				// Start line: 809
				// Start offset: 0x80062AC4
			/* end block 1.1.1 */
			// End offset: 0x80062AC4
			// End Line: 809
		/* end block 1.1 */
		// End offset: 0x80062AC4
		// End Line: 809

		/* begin block 1.2 */
			// Start line: 844
			// Start offset: 0x80062B30

			/* begin block 1.2.1 */
				// Start line: 844
				// Start offset: 0x80062B30
			/* end block 1.2.1 */
			// End offset: 0x80062B30
			// End Line: 844
		/* end block 1.2 */
		// End offset: 0x80062B30
		// End Line: 844

		/* begin block 1.3 */
			// Start line: 844
			// Start offset: 0x80062B30

			/* begin block 1.3.1 */
				// Start line: 844
				// Start offset: 0x80062B30
			/* end block 1.3.1 */
			// End offset: 0x80062B30
			// End Line: 844
		/* end block 1.3 */
		// End offset: 0x80062B30
		// End Line: 844

		/* begin block 1.4 */
			// Start line: 844
			// Start offset: 0x80062B30
			// Variables:
		// 		struct AICop_PerpChaseInfo *this; // $a1
		// 		int ticks; // $a2
		// 		int totalCopsEngaged; // $v0

			/* begin block 1.4.1 */
				// Start line: 844
				// Start offset: 0x80062B30

				/* begin block 1.4.1.1 */
					// Start line: 844
					// Start offset: 0x80062B30

					/* begin block 1.4.1.1.1 */
						// Start line: 844
						// Start offset: 0x80062B6C

						/* begin block 1.4.1.1.1.1 */
							// Start line: 844
							// Start offset: 0x80062B6C

							/* begin block 1.4.1.1.1.1.1 */
								// Start line: 844
								// Start offset: 0x80062B98

								/* begin block 1.4.1.1.1.1.1.1 */
									// Start line: 844
									// Start offset: 0x80062BAC

									/* begin block 1.4.1.1.1.1.1.1.1 */
										// Start line: 844
										// Start offset: 0x80062BAC
										// Variables:
									// 		struct AICop_PerpChaseInfo *this; // $a1

										/* begin block 1.4.1.1.1.1.1.1.1.1 */
											// Start line: 844
											// Start offset: 0x80062BAC
										/* end block 1.4.1.1.1.1.1.1.1.1 */
										// End offset: 0x80062BC0
										// End Line: 844
									/* end block 1.4.1.1.1.1.1.1.1 */
									// End offset: 0x80062BC0
									// End Line: 844

									/* begin block 1.4.1.1.1.1.1.1.2 */
										// Start line: 844
										// Start offset: 0x80062BC0
										// Variables:
									// 		struct AICop_PerpChaseInfo *this; // $a1

										/* begin block 1.4.1.1.1.1.1.1.2.1 */
											// Start line: 844
											// Start offset: 0x80062BC0

											/* begin block 1.4.1.1.1.1.1.1.2.1.1 */
												// Start line: 844
												// Start offset: 0x80062BC0
												// Variables:
											// 		struct AICop_PerpChaseInfo *this; // $a1

												/* begin block 1.4.1.1.1.1.1.1.2.1.1.1 */
													// Start line: 844
													// Start offset: 0x80062BC0
												/* end block 1.4.1.1.1.1.1.1.2.1.1.1 */
												// End offset: 0x80062BC0
												// End Line: 844
											/* end block 1.4.1.1.1.1.1.1.2.1.1 */
											// End offset: 0x80062BC0
											// End Line: 844
										/* end block 1.4.1.1.1.1.1.1.2.1 */
										// End offset: 0x80062BF0
										// End Line: 844
									/* end block 1.4.1.1.1.1.1.1.2 */
									// End offset: 0x80062BF0
									// End Line: 844
								/* end block 1.4.1.1.1.1.1.1 */
								// End offset: 0x80062C08
								// End Line: 844
							/* end block 1.4.1.1.1.1.1 */
							// End offset: 0x80062C08
							// End Line: 844
						/* end block 1.4.1.1.1.1 */
						// End offset: 0x80062C08
						// End Line: 844
					/* end block 1.4.1.1.1 */
					// End offset: 0x80062C08
					// End Line: 844
				/* end block 1.4.1.1 */
				// End offset: 0x80062C38
				// End Line: 844
			/* end block 1.4.1 */
			// End offset: 0x80062C38
			// End Line: 844
		/* end block 1.4 */
		// End offset: 0x80062C38
		// End Line: 844
	/* end block 1 */
	// End offset: 0x80062C4C
	// End Line: 856

	/* begin block 2 */
		// Start line: 1876
	/* end block 2 */
	// End Line: 1877

	/* begin block 3 */
		// Start line: 1922
	/* end block 3 */
	// End Line: 1923

	/* begin block 4 */
		// Start line: 1922
	/* end block 4 */
	// End Line: 1923

	/* begin block 5 */
		// Start line: 1929
	/* end block 5 */
	// End Line: 1930

/* WARNING: Type propagation algorithm not settling */

void HandleCops__13AIHigh_Player(AIHigh_Player *this)

{
  int iVar1;
  Car_tObj *pCVar2;
  int iVar3;
  int iVar4;
  int iVar5;
  int iVar6;
  copLevel_t *pcVar7;
  
  pcVar7 = (this->perpChaseInfo_).chaseLevel_;
  if (Cars_gNumCopCars != 0) {
    MaintainAvailableCops__13AIHigh_Player(this);
    iVar1 = CheckIfABlockadeCanBeSetup__13AIHigh_Player(this);
    if (iVar1 != 0) {
      SetupBlockade__13AIHigh_Player(this);
    }
    if (pcVar7->numBlockaders == 0) {
      CleanupBlockaders__13AIHigh_Playeri(this,0);
    }
    iVar1 = AI_elapsedTime;
    pCVar2 = (this->AIHigh_BasicPerp).AIHigh_Base.carObj_;
    iVar5 = (pCVar2->script).lastActionTime;
    iVar3 = (pCVar2->script).lastReactionIndex[3];
    if ((this->AIHigh_BasicPerp).basicPerpInfo_.copsAssigned_[0] +
        (this->AIHigh_BasicPerp).basicPerpInfo_.copsAssigned_[1] < 1) {
      (this->perpChaseInfo_).copFreeTicks_ = (this->perpChaseInfo_).copFreeTicks_ + AI_elapsedTime;
    }
    else {
      (this->perpChaseInfo_).copFreeTicks_ = 0;
      iVar6 = (this->perpChaseInfo_).engagementTime_;
      iVar4 = iVar6;
      if (iVar6 < 0) {
        iVar4 = iVar6 + 0xffff;
      }
      if (-2 < iVar4 >> 0x10) {
        iVar4 = iVar1 << 0xf;
        if ((uint)(iVar5 * iVar3) >> 0x1f == 0) {
          iVar4 = iVar1 << 0x10;
        }
        (this->perpChaseInfo_).engagementTime_ = iVar6 - iVar4;
        iVar3 = (this->perpChaseInfo_).engagementTime_;
        if (iVar3 < 0) {
          iVar3 = iVar3 + 0xffff;
        }
        iVar5 = ((this->perpChaseInfo_).chaseLevel_)->engagementLapFraction * AITune_gRoughLapTime;
        if (iVar5 < 0) {
          iVar5 = iVar5 + 0xffff;
        }
        if (iVar3 >> 0x10 < (iVar5 >> 0x10) * 0x20 + -0x80) {
          (this->perpChaseInfo_).totalEngagementPercent_ =
               (this->perpChaseInfo_).totalEngagementPercent_ +
               (this->perpChaseInfo_).engagementPercentIncreasePerTick_ * iVar1;
        }
      }
    }
    CheckForNewLevel__13AIHigh_Playeri(this,0);
    HandlePullOver__13AIHigh_Player(this);
  }
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ CleanupBlockaders__13AIHigh_Playeri(struct AIHigh_Player *this /*$s3*/, int forceClearAll /*$a1*/)
 // line 871, offset 0x80062c64
	/* begin block 1 */
		// Start line: 872
		// Start offset: 0x80062C64
		// Variables:
	// 		int clearWaitingBlockaders; // $s2

		/* begin block 1.1 */
			// Start line: 880
			// Start offset: 0x80062CBC
			// Variables:
		// 		int copLoop; // $s1

			/* begin block 1.1.1 */
				// Start line: 880
				// Start offset: 0x80062CD0
				// Variables:
			// 		struct AIHigh_Cop *thisCop; // $a0
			// 		struct blockade_t *blockade; // $a1

				/* begin block 1.1.1.1 */
					// Start line: 882
					// Start offset: 0x80062CE8
					// Variables:
				// 		struct AIHigh_BasicCop *this; // $a0

					/* begin block 1.1.1.1.1 */
						// Start line: 882
						// Start offset: 0x80062CE8
					/* end block 1.1.1.1.1 */
					// End offset: 0x80062CE8
					// End Line: 882
				/* end block 1.1.1.1 */
				// End offset: 0x80062CE8
				// End Line: 882
			/* end block 1.1.1 */
			// End offset: 0x80062D50
			// End Line: 901
		/* end block 1.1 */
		// End offset: 0x80062D5C
		// End Line: 903
	/* end block 1 */
	// End offset: 0x80062D5C
	// End Line: 903

	/* begin block 2 */
		// Start line: 2052
	/* end block 2 */
	// End Line: 2053

	/* begin block 3 */
		// Start line: 2055
	/* end block 3 */
	// End Line: 2056

	/* begin block 4 */
		// Start line: 2055
	/* end block 4 */
	// End Line: 2056

void CleanupBlockaders__13AIHigh_Playeri(AIHigh_Player *this,int forceClearAll)

{
  bool bVar1;
  Car_tObj *pCVar2;
  blockadeMode_t bVar3;
  AIHigh_Cop *this_00;
  Car_tObj **ppCVar4;
  int iVar5;
  
  pCVar2 = (this->AIHigh_BasicPerp).AIHigh_Base.carObj_;
  bVar1 = false;
  if (((0 < (pCVar2->stats).numArrests) || (1 < (pCVar2->stats).finishType)) || (forceClearAll != 0)
     ) {
    bVar1 = true;
  }
  iVar5 = 0;
  ppCVar4 = &Cars_gCopCarList9;
  while (iVar5 < Cars_gNumCopCars) {
    this_00 = (AIHigh_Cop *)(&highLevelAIObjs9)[(*ppCVar4)->carIndex];
    bVar3 = (this_00->AIHigh_BasicCop).blockade_.mode;
    if ((((bVar3 == BLOCKADEMODE_SETUP) || (bVar3 == BLOCKADEMODE_SETUP_FOR_OTHER)) ||
        ((bVar3 == BLOCKADEMODE_WAITING && (bVar1)))) &&
       ((this_00->AIHigh_BasicCop).blockade_.target == this)) {
      (this_00->AIHigh_BasicCop).blockade_.mode = BLOCKADEMODE_NONE;
      AssignToPlayer__10AIHigh_CopP13AIHigh_Player(this_00,(AIHigh_Player *)0x0);
    }
    ppCVar4 = ppCVar4 + 1;
    iVar5 = iVar5 + 1;
  }
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ HandlePullOver__13AIHigh_Player(struct AIHigh_Player *this /*$s1*/)
 // line 906, offset 0x80062d7c
	/* begin block 1 */
		// Start line: 907
		// Start offset: 0x80062D7C

		/* begin block 1.1 */
			// Start line: 907
			// Start offset: 0x80062D7C

			/* begin block 1.1.1 */
				// Start line: 911
				// Start offset: 0x80062DA0

				/* begin block 1.1.1.1 */
					// Start line: 912
					// Start offset: 0x80062DA0

					/* begin block 1.1.1.1.1 */
						// Start line: 914
						// Start offset: 0x80062DBC

						/* begin block 1.1.1.1.1.1 */
							// Start line: 937
							// Start offset: 0x80062E6C
							// Variables:
						// 		struct AICop_PerpChaseInfo *this; // $s0

							/* begin block 1.1.1.1.1.1.1 */
								// Start line: 937
								// Start offset: 0x80062E6C

								/* begin block 1.1.1.1.1.1.1.1 */
									// Start line: 937
									// Start offset: 0x80062E84
									// Variables:
								// 		struct AICop_PerpChaseInfo *this; // $s0

									/* begin block 1.1.1.1.1.1.1.1.1 */
										// Start line: 937
										// Start offset: 0x80062E84

										/* begin block 1.1.1.1.1.1.1.1.1.1 */
											// Start line: 937
											// Start offset: 0x80062E84
											// Variables:
										// 		struct AICop_PerpChaseInfo *this; // $s0

											/* begin block 1.1.1.1.1.1.1.1.1.1.1 */
												// Start line: 937
												// Start offset: 0x80062E84

												/* begin block 1.1.1.1.1.1.1.1.1.1.1.1 */
													// Start line: 937
													// Start offset: 0x80062E84
													// Variables:
												// 		struct AICop_PerpChaseInfo *this; // $s0

													/* begin block 1.1.1.1.1.1.1.1.1.1.1.1.1 */
														// Start line: 937
														// Start offset: 0x80062E84
													/* end block 1.1.1.1.1.1.1.1.1.1.1.1.1 */
													// End offset: 0x80062E84
													// End Line: 937
												/* end block 1.1.1.1.1.1.1.1.1.1.1.1 */
												// End offset: 0x80062E84
												// End Line: 937
											/* end block 1.1.1.1.1.1.1.1.1.1.1 */
											// End offset: 0x80062ED0
											// End Line: 937
										/* end block 1.1.1.1.1.1.1.1.1.1 */
										// End offset: 0x80062ED0
										// End Line: 937

										/* begin block 1.1.1.1.1.1.1.1.1.2 */
											// Start line: 937
											// Start offset: 0x80062ED0
											// Variables:
										// 		struct AICop_PerpChaseInfo *this; // $s0

											/* begin block 1.1.1.1.1.1.1.1.1.2.1 */
												// Start line: 937
												// Start offset: 0x80062ED0
											/* end block 1.1.1.1.1.1.1.1.1.2.1 */
											// End offset: 0x80062F48
											// End Line: 937
										/* end block 1.1.1.1.1.1.1.1.1.2 */
										// End offset: 0x80062F48
										// End Line: 937
									/* end block 1.1.1.1.1.1.1.1.1 */
									// End offset: 0x80062F48
									// End Line: 937
								/* end block 1.1.1.1.1.1.1.1 */
								// End offset: 0x80062F48
								// End Line: 937
							/* end block 1.1.1.1.1.1.1 */
							// End offset: 0x80062F48
							// End Line: 937
						/* end block 1.1.1.1.1.1 */
						// End offset: 0x80062F48
						// End Line: 937

						/* begin block 1.1.1.1.1.2 */
							// Start line: 937
							// Start offset: 0x80062F48

							/* begin block 1.1.1.1.1.2.1 */
								// Start line: 937
								// Start offset: 0x80062F48
							/* end block 1.1.1.1.1.2.1 */
							// End offset: 0x80062F48
							// End Line: 937
						/* end block 1.1.1.1.1.2 */
						// End offset: 0x80062F48
						// End Line: 937
					/* end block 1.1.1.1.1 */
					// End offset: 0x80063008
					// End Line: 967
				/* end block 1.1.1.1 */
				// End offset: 0x80063008
				// End Line: 967
			/* end block 1.1.1 */
			// End offset: 0x80063008
			// End Line: 967

			/* begin block 1.1.2 */
				// Start line: 971
				// Start offset: 0x80063010

				/* begin block 1.1.2.1 */
					// Start line: 971
					// Start offset: 0x80063010

					/* begin block 1.1.2.1.1 */
						// Start line: 972
						// Start offset: 0x80063020
						// Variables:
					// 		int chaseTime; // $a3

						/* begin block 1.1.2.1.1.1 */
							// Start line: 976
							// Start offset: 0x80063020
							// Variables:
						// 		struct AICop_PerpChaseInfo *this; // $a1

							/* begin block 1.1.2.1.1.1.1 */
								// Start line: 976
								// Start offset: 0x80063020

								/* begin block 1.1.2.1.1.1.1.1 */
									// Start line: 976
									// Start offset: 0x80063020
									// Variables:
								// 		struct AICop_PerpChaseInfo *this; // $a1

									/* begin block 1.1.2.1.1.1.1.1.1 */
										// Start line: 976
										// Start offset: 0x80063020
									/* end block 1.1.2.1.1.1.1.1.1 */
									// End offset: 0x80063020
									// End Line: 976
								/* end block 1.1.2.1.1.1.1.1 */
								// End offset: 0x80063020
								// End Line: 976
							/* end block 1.1.2.1.1.1.1 */
							// End offset: 0x80063060
							// End Line: 978
						/* end block 1.1.2.1.1.1 */
						// End offset: 0x80063060
						// End Line: 978

						/* begin block 1.1.2.1.1.2 */
							// Start line: 978
							// Start offset: 0x80063060

							/* begin block 1.1.2.1.1.2.1 */
								// Start line: 978
								// Start offset: 0x80063060
							/* end block 1.1.2.1.1.2.1 */
							// End offset: 0x80063078
							// End Line: 978
						/* end block 1.1.2.1.1.2 */
						// End offset: 0x80063078
						// End Line: 978

						/* begin block 1.1.2.1.1.3 */
							// Start line: 978
							// Start offset: 0x80063078

							/* begin block 1.1.2.1.1.3.1 */
								// Start line: 978
								// Start offset: 0x80063078
							/* end block 1.1.2.1.1.3.1 */
							// End offset: 0x80063078
							// End Line: 978
						/* end block 1.1.2.1.1.3 */
						// End offset: 0x80063078
						// End Line: 978

						/* begin block 1.1.2.1.1.4 */
							// Start line: 978
							// Start offset: 0x80063078

							/* begin block 1.1.2.1.1.4.1 */
								// Start line: 978
								// Start offset: 0x80063078

								/* begin block 1.1.2.1.1.4.1.1 */
									// Start line: 978
									// Start offset: 0x80063078
								/* end block 1.1.2.1.1.4.1.1 */
								// End offset: 0x80063078
								// End Line: 978
							/* end block 1.1.2.1.1.4.1 */
							// End offset: 0x80063078
							// End Line: 978

							/* begin block 1.1.2.1.1.4.2 */
								// Start line: 987
								// Start offset: 0x800630C4

								/* begin block 1.1.2.1.1.4.2.1 */
									// Start line: 987
									// Start offset: 0x800630C4
								/* end block 1.1.2.1.1.4.2.1 */
								// End offset: 0x800630C4
								// End Line: 987
							/* end block 1.1.2.1.1.4.2 */
							// End offset: 0x800630C4
							// End Line: 987

							/* begin block 1.1.2.1.1.4.3 */
								// Start line: 987
								// Start offset: 0x800630C4

								/* begin block 1.1.2.1.1.4.3.1 */
									// Start line: 987
									// Start offset: 0x800630C4
								/* end block 1.1.2.1.1.4.3.1 */
								// End offset: 0x800630C4
								// End Line: 987
							/* end block 1.1.2.1.1.4.3 */
							// End offset: 0x800630C4
							// End Line: 987

							/* begin block 1.1.2.1.1.4.4 */
								// Start line: 987
								// Start offset: 0x800630F8

								/* begin block 1.1.2.1.1.4.4.1 */
									// Start line: 987
									// Start offset: 0x800630F8
								/* end block 1.1.2.1.1.4.4.1 */
								// End offset: 0x800630F8
								// End Line: 987
							/* end block 1.1.2.1.1.4.4 */
							// End offset: 0x800630F8
							// End Line: 987

							/* begin block 1.1.2.1.1.4.5 */
								// Start line: 988
								// Start offset: 0x80063128

								/* begin block 1.1.2.1.1.4.5.1 */
									// Start line: 988
									// Start offset: 0x80063128

									/* begin block 1.1.2.1.1.4.5.1.1 */
										// Start line: 988
										// Start offset: 0x80063128
									/* end block 1.1.2.1.1.4.5.1.1 */
									// End offset: 0x80063128
									// End Line: 988
								/* end block 1.1.2.1.1.4.5.1 */
								// End offset: 0x80063128
								// End Line: 988
							/* end block 1.1.2.1.1.4.5 */
							// End offset: 0x80063128
							// End Line: 988

							/* begin block 1.1.2.1.1.4.6 */
								// Start line: 994
								// Start offset: 0x80063158
								// Variables:
							// 		int lapIndex; // $v1

								/* begin block 1.1.2.1.1.4.6.1 */
									// Start line: 999
									// Start offset: 0x800631A4

									/* begin block 1.1.2.1.1.4.6.1.1 */
										// Start line: 1002
										// Start offset: 0x800631CC
										// Variables:
									// 		struct AICop_PerpChaseInfo *this; // $v1

										/* begin block 1.1.2.1.1.4.6.1.1.1 */
											// Start line: 1002
											// Start offset: 0x800631CC
										/* end block 1.1.2.1.1.4.6.1.1.1 */
										// End offset: 0x800631CC
										// End Line: 1002
									/* end block 1.1.2.1.1.4.6.1.1 */
									// End offset: 0x800631CC
									// End Line: 1002

									/* begin block 1.1.2.1.1.4.6.1.2 */
										// Start line: 1002
										// Start offset: 0x800631CC

										/* begin block 1.1.2.1.1.4.6.1.2.1 */
											// Start line: 1002
											// Start offset: 0x800631CC
										/* end block 1.1.2.1.1.4.6.1.2.1 */
										// End offset: 0x800631CC
										// End Line: 1002
									/* end block 1.1.2.1.1.4.6.1.2 */
									// End offset: 0x800631CC
									// End Line: 1002
								/* end block 1.1.2.1.1.4.6.1 */
								// End offset: 0x8006322C
								// End Line: 1010
							/* end block 1.1.2.1.1.4.6 */
							// End offset: 0x8006322C
							// End Line: 1010
						/* end block 1.1.2.1.1.4 */
						// End offset: 0x8006322C
						// End Line: 1010
					/* end block 1.1.2.1.1 */
					// End offset: 0x80063234
					// End Line: 1015
				/* end block 1.1.2.1 */
				// End offset: 0x80063234
				// End Line: 1015
			/* end block 1.1.2 */
			// End offset: 0x80063234
			// End Line: 1015
		/* end block 1.1 */
		// End offset: 0x80063234
		// End Line: 1015
	/* end block 1 */
	// End offset: 0x80063234
	// End Line: 1015

	/* begin block 2 */
		// Start line: 2121
	/* end block 2 */
	// End Line: 2122

	/* begin block 3 */
		// Start line: 2125
	/* end block 3 */
	// End Line: 2126

	/* begin block 4 */
		// Start line: 2125
	/* end block 4 */
	// End Line: 2126

/* WARNING: Removing unreachable block (ram,0x80062f00) */

void HandlePullOver__13AIHigh_Player(AIHigh_Player *this)

{
  bool bVar1;
  int player;
  uint uVar2;
  __95 _Var3;
  Car_tObj *pCVar4;
  int iVar5;
  undefined *puVar6;
  copLevel_t *pcVar7;
  int iVar8;
  
  if ((this->AIHigh_BasicPerp).pullOverMode_ == PULLOVER_NONE) {
    player = CheckIfCaught__16AIHigh_BasicPerp((AIHigh_BasicPerp *)this);
    if (player == 0) {
      return;
    }
    ((this->AIHigh_BasicPerp).AIHigh_Base.carObj_)->pullOver = 1;
    CleanupBlockaders__13AIHigh_Playeri(this,1);
    pcVar7 = (this->perpChaseInfo_).chaseLevel_;
    player = pcVar7->engagementLapFraction * AITune_gRoughLapTime;
    if (player < 0) {
      player = player + 0xffff;
    }
    iVar5 = (this->perpChaseInfo_).engagementTime_;
    if (iVar5 < 0) {
      iVar5 = iVar5 + 0xffff;
    }
    (this->AIHigh_BasicPerp).beatingTicksLeft_ = pcVar7->beatingTicks;
    (this->AIHigh_BasicPerp).lastPullOverTime_ = simGlobal.gameTicks;
    bVar1 = false;
    if ((((this->AIHigh_BasicPerp).basicPerpInfo_.crime_ != CRIME_SMASHCOP) &&
        ((((this->AIHigh_BasicPerp).AIHigh_Base.carObj_)->stats).numFines == 0)) &&
       (((this->perpChaseInfo_).copGameInfo_)->levels[(this->perpChaseInfo_).bestChaseLevelIndex_].
        numWarningsAdded != 0)) {
      bVar1 = (player >> 0x10) * 0x20 - (iVar5 >> 0x10) <
              ((this->perpChaseInfo_).chaseLevel_)->warningTicks;
    }
    if ((bVar1) && (this->numWarnings_ < 2)) {
      pCVar4 = (this->AIHigh_BasicPerp).AIHigh_Base.carObj_;
      this->numWarnings_ =
           this->numWarnings_ + ((this->perpChaseInfo_).chaseLevel_)->numWarningsAdded;
      (pCVar4->stats).numWarnings = (pCVar4->stats).numWarnings + 1;
      _Var3 = PULLOVER_WARNING;
    }
    else {
      pCVar4 = (this->AIHigh_BasicPerp).AIHigh_Base.carObj_;
      this->numBusts_ = this->numBusts_ + 1;
      (pCVar4->stats).numFines = (pCVar4->stats).numFines + 1;
      player = 2;
      if (GameSetup_gData.numLaps == 2) {
        player = 0;
      }
      else {
        if (GameSetup_gData.numLaps == 4) {
          player = 1;
        }
      }
      if (((&AIHigh_Player_kNumArrestsByLap)[player] <= this->numBusts_) ||
         ((_Var3 = PULLOVER_BUST,
          (this->perpChaseInfo_).bestChaseLevelIndex_ ==
          ((this->perpChaseInfo_).copGameInfo_)->numLevels + -1 &&
          (_Var3 = PULLOVER_BUST, Cars_gNumHumanRaceCars == 1)))) {
        (this->AIHigh_BasicPerp).pullOverMode_ = PULLOVER_EOG;
        pCVar4 = (this->AIHigh_BasicPerp).AIHigh_Base.carObj_;
        (this->AIHigh_BasicPerp).beatingTicksLeft_ =
             (this->AIHigh_BasicPerp).beatingTicksLeft_ + 0xc0;
        (pCVar4->stats).numArrests = (pCVar4->stats).numArrests + 1;
        goto LAB_8006322c;
      }
    }
    (this->AIHigh_BasicPerp).pullOverMode_ = _Var3;
LAB_8006322c:
    HandleSpeech__13AIHigh_Player(this);
    return;
  }
  player = (this->AIHigh_BasicPerp).beatingTicksLeft_ - AI_elapsedTime;
  (this->AIHigh_BasicPerp).beatingTicksLeft_ = player;
  if (0 < player) {
    return;
  }
  player = ((this->AIHigh_BasicPerp).AIHigh_Base.carObj_)->carIndex;
  if (player < 2) {
    Hud_Perp_OverlayOff__Fi(player);
  }
  (this->AIHigh_BasicPerp).lastPullOverTime_ = simGlobal.gameTicks;
  if ((this->AIHigh_BasicPerp).pullOverMode_ == PULLOVER_EOG) {
    if ((((this->AIHigh_BasicPerp).AIHigh_Base.carObj_)->carFlags & 4U) != 0) {
      AICop_numArrestedHumans = AICop_numArrestedHumans + 1;
    }
    (((this->AIHigh_BasicPerp).AIHigh_Base.carObj_)->stats).finishType = 3;
  }
  if (AICop_numArrestedHumans == Cars_gNumHumanRaceCars) {
    simVar.endSimGame = 1;
    Stats_ExtrapolateOpponentTimes__Fi(2);
  }
  (this->perpChaseInfo_).chaseLevelIndex_ = 0;
  if ((this->perpChaseInfo_).bestChaseLevelIndex_ < 0) {
    (this->perpChaseInfo_).bestChaseLevelIndex_ = 0;
  }
  pcVar7 = ((this->perpChaseInfo_).copGameInfo_)->levels + (this->perpChaseInfo_).chaseLevelIndex_;
  (this->perpChaseInfo_).chaseLevel_ = pcVar7;
  player = pcVar7->engagementLapFraction * AITune_gRoughLapTime;
  if (player < 0) {
    player = player + 0xffff;
  }
  iVar5 = (player >> 0x10) << 5;
  iVar8 = 0x10000 / iVar5;
  if (iVar5 == 0) {
    trap(0x1c00);
  }
  (this->perpChaseInfo_).engagementTime_ = (player >> 0x10) << 0x15;
  (this->perpChaseInfo_).engagementPercentIncreasePerTick_ = iVar8;
  if (GameSetup_gData.numLaps == 2) {
    puVar6 = &DAT_00013333;
  }
  else {
    puVar6 = &DAT_0000a8f5;
    if (GameSetup_gData.numLaps != 4) goto LAB_80062f48;
  }
  uVar2 = fixedmult(iVar8,(int)puVar6);
  (this->perpChaseInfo_).engagementPercentIncreasePerTick_ = uVar2;
LAB_80062f48:
  (this->perpChaseInfo_).blockadeDone_ = 0;
  (this->AIHigh_BasicPerp).basicPerpInfo_.crime_ = CRIME_NONE;
  RemoveCloseCops__16AIHigh_BasicPerp((AIHigh_BasicPerp *)this);
  if ((((this->AIHigh_BasicPerp).pullOverMode_ != PULLOVER_EOG) || (Cars_gNumHumanRaceCars != 1)) ||
     ((((this->AIHigh_BasicPerp).AIHigh_Base.carObj_)->carFlags & 8U) != 0)) {
    Cars_ResetCollidedCars__FP8Car_tObjii((this->AIHigh_BasicPerp).AIHigh_Base.carObj_,1,1);
  }
  if ((this->AIHigh_BasicPerp).pullOverMode_ == PULLOVER_EOG) {
    if ((Cars_gNumHumanRaceCars == 2) && (AICop_numArrestedHumans != 2)) {
      DashHUD_gInfo.showhud[((this->AIHigh_BasicPerp).AIHigh_Base.carObj_)->carIndex] = 0;
    }
  }
  else {
    ((this->AIHigh_BasicPerp).AIHigh_Base.carObj_)->pullOver = 0;
  }
  (this->AIHigh_BasicPerp).pullOverMode_ = PULLOVER_NONE;
  return;
}





