#ifndef AITUNE_H
#define AITUNE_H

extern int AITune_GetOneWay__Fv(); // 0x80072E68

extern int AITune_GetDriveSide__Fv(); // 0x80072EC0

extern int AITune_GetRoughLapTimes__Fv(); // 0x80072F00

extern void AITune_StartUp1__Fv(); // 0x80072F40

extern void AITune_StartUp2__Fv(); // 0x80072F78

extern void AITune_CleanUp1__Fv(); // 0x80072F80

extern void AITune_CleanUp2__Fv(); // 0x80072F88

#endif
