#include "THISDUST.H"
#include "CHUNK.H"


// decompiled code
// original method signature: 
// void /*$ra*/ InstanceGroup__5ChunkP15SerializedGroupP9SimpleMem(struct Chunk *this /*$s2*/, struct SerializedGroup *chunkGroup /*$s5*/, struct SimpleMem *mem /*$s3*/)
 // line 83, offset 0x8008b3fc
	/* begin block 1 */
		// Start line: 84
		// Start offset: 0x8008B3FC

		/* begin block 1.1 */
			// Start line: 84
			// Start offset: 0x8008B3FC

			/* begin block 1.1.1 */
				// Start line: 84
				// Start offset: 0x8008B3FC

				/* begin block 1.1.1.1 */
					// Start line: 84
					// Start offset: 0x8008B3FC
				/* end block 1.1.1.1 */
				// End offset: 0x8008B3FC
				// End Line: 84
			/* end block 1.1.1 */
			// End offset: 0x8008B3FC
			// End Line: 84
		/* end block 1.1 */
		// End offset: 0x8008B3FC
		// End Line: 84

		/* begin block 1.2 */
			// Start line: 84
			// Start offset: 0x8008B3FC

			/* begin block 1.2.1 */
				// Start line: 117
				// Start offset: 0x8008B538
				// Variables:
			// 		struct SerializedGroup *instGroup; // $s1
			// 		struct SerializedGroup *simGroup; // $s4

				/* begin block 1.2.1.1 */
					// Start line: 121
					// Start offset: 0x8008B538

					/* begin block 1.2.1.1.1 */
						// Start line: 125
						// Start offset: 0x8008B560
						// Variables:
					// 		int i; // $a2
					// 		int numElements; // $s0

						/* begin block 1.2.1.1.1.1 */
							// Start line: 126
							// Start offset: 0x8008B560
							// Variables:
						// 		struct SerializedGroup *this; // $s4

							/* begin block 1.2.1.1.1.1.1 */
								// Start line: 126
								// Start offset: 0x8008B560
							/* end block 1.2.1.1.1.1.1 */
							// End offset: 0x8008B560
							// End Line: 126
						/* end block 1.2.1.1.1.1 */
						// End offset: 0x8008B560
						// End Line: 126

						/* begin block 1.2.1.1.1.2 */
							// Start line: 126
							// Start offset: 0x8008B560
							// Variables:
						// 		struct SerializedGroup *this; // $s4

							/* begin block 1.2.1.1.1.2.1 */
								// Start line: 126
								// Start offset: 0x8008B560
							/* end block 1.2.1.1.1.2.1 */
							// End offset: 0x8008B560
							// End Line: 126
						/* end block 1.2.1.1.1.2 */
						// End offset: 0x8008B560
						// End Line: 126

						/* begin block 1.2.1.1.1.3 */
							// Start line: 130
							// Start offset: 0x8008B578
							// Variables:
						// 		struct Trk_SimpleInst *inst; // $a0

							/* begin block 1.2.1.1.1.3.1 */
								// Start line: 137
								// Start offset: 0x8008B594
								// Variables:
							// 		struct SerializedGroup *this; // $s1

								/* begin block 1.2.1.1.1.3.1.1 */
									// Start line: 137
									// Start offset: 0x8008B594
								/* end block 1.2.1.1.1.3.1.1 */
								// End offset: 0x8008B594
								// End Line: 137
							/* end block 1.2.1.1.1.3.1 */
							// End offset: 0x8008B594
							// End Line: 137

							/* begin block 1.2.1.1.1.3.2 */
								// Start line: 137
								// Start offset: 0x8008B594
								// Variables:
							// 		int index; // $v1

								/* begin block 1.2.1.1.1.3.2.1 */
									// Start line: 137
									// Start offset: 0x8008B594

									/* begin block 1.2.1.1.1.3.2.1.1 */
										// Start line: 137
										// Start offset: 0x8008B594
										// Variables:
									// 		struct SerializedGroup *this; // $s1

										/* begin block 1.2.1.1.1.3.2.1.1.1 */
											// Start line: 137
											// Start offset: 0x8008B594
										/* end block 1.2.1.1.1.3.2.1.1.1 */
										// End offset: 0x8008B594
										// End Line: 137
									/* end block 1.2.1.1.1.3.2.1.1 */
									// End offset: 0x8008B594
									// End Line: 137
								/* end block 1.2.1.1.1.3.2.1 */
								// End offset: 0x8008B5AC
								// End Line: 147
							/* end block 1.2.1.1.1.3.2 */
							// End offset: 0x8008B5CC
							// End Line: 149

							/* begin block 1.2.1.1.1.3.3 */
								// Start line: 152
								// Start offset: 0x8008B5CC

								/* begin block 1.2.1.1.1.3.3.1 */
									// Start line: 153
									// Start offset: 0x8008B5E4
								/* end block 1.2.1.1.1.3.3.1 */
								// End offset: 0x8008B600
								// End Line: 159
							/* end block 1.2.1.1.1.3.3 */
							// End offset: 0x8008B600
							// End Line: 159
						/* end block 1.2.1.1.1.3 */
						// End offset: 0x8008B600
						// End Line: 164
					/* end block 1.2.1.1.1 */
					// End offset: 0x8008B60C
					// End Line: 174
				/* end block 1.2.1.1 */
				// End offset: 0x8008B634
				// End Line: 179

				/* begin block 1.2.1.2 */
					// Start line: 183
					// Start offset: 0x8008B634

					/* begin block 1.2.1.2.1 */
						// Start line: 184
						// Start offset: 0x8008B63C
						// Variables:
					// 		int numElements; // $a0
					// 		int i; // $s0
					// 		int size; // $a3
					// 		struct Trk_SimpleInst *inst; // $v1

						/* begin block 1.2.1.2.1.1 */
							// Start line: 184
							// Start offset: 0x8008B63C
							// Variables:
						// 		struct SerializedGroup *this; // $s1

							/* begin block 1.2.1.2.1.1.1 */
								// Start line: 184
								// Start offset: 0x8008B63C
							/* end block 1.2.1.2.1.1.1 */
							// End offset: 0x8008B63C
							// End Line: 184
						/* end block 1.2.1.2.1.1 */
						// End offset: 0x8008B63C
						// End Line: 184

						/* begin block 1.2.1.2.1.2 */
							// Start line: 184
							// Start offset: 0x8008B63C
							// Variables:
						// 		struct SerializedGroup *this; // $s1

							/* begin block 1.2.1.2.1.2.1 */
								// Start line: 184
								// Start offset: 0x8008B63C
							/* end block 1.2.1.2.1.2.1 */
							// End offset: 0x8008B63C
							// End Line: 184
						/* end block 1.2.1.2.1.2 */
						// End offset: 0x8008B63C
						// End Line: 184

						/* begin block 1.2.1.2.1.3 */
							// Start line: 190
							// Start offset: 0x8008B650

							/* begin block 1.2.1.2.1.3.1 */
								// Start line: 192
								// Start offset: 0x8008B65C

								/* begin block 1.2.1.2.1.3.1.1 */
									// Start line: 193
									// Start offset: 0x8008B66C
								/* end block 1.2.1.2.1.3.1.1 */
								// End offset: 0x8008B67C
								// End Line: 196
							/* end block 1.2.1.2.1.3.1 */
							// End offset: 0x8008B68C
							// End Line: 198
						/* end block 1.2.1.2.1.3 */
						// End offset: 0x8008B68C
						// End Line: 200
					/* end block 1.2.1.2.1 */
					// End offset: 0x8008B6A0
					// End Line: 204
				/* end block 1.2.1.2 */
				// End offset: 0x8008B6C0
				// End Line: 207

				/* begin block 1.2.1.3 */
					// Start line: 210
					// Start offset: 0x8008B6C0

					/* begin block 1.2.1.3.1 */
						// Start line: 211
						// Start offset: 0x8008B6E0
						// Variables:
					// 		struct Trk_SimObject *simObjs; // $v1
					// 		int count; // $a1

						/* begin block 1.2.1.3.1.1 */
							// Start line: 211
							// Start offset: 0x8008B6E0
							// Variables:
						// 		struct SerializedGroup *this; // $s4

							/* begin block 1.2.1.3.1.1.1 */
								// Start line: 211
								// Start offset: 0x8008B6E0
							/* end block 1.2.1.3.1.1.1 */
							// End offset: 0x8008B6E0
							// End Line: 211
						/* end block 1.2.1.3.1.1 */
						// End offset: 0x8008B6E0
						// End Line: 211

						/* begin block 1.2.1.3.1.2 */
							// Start line: 211
							// Start offset: 0x8008B6E0

							/* begin block 1.2.1.3.1.2.1 */
								// Start line: 211
								// Start offset: 0x8008B6E0
							/* end block 1.2.1.3.1.2.1 */
							// End offset: 0x8008B6E0
							// End Line: 211
						/* end block 1.2.1.3.1.2 */
						// End offset: 0x8008B6E0
						// End Line: 211

						/* begin block 1.2.1.3.1.3 */
							// Start line: 214
							// Start offset: 0x8008B6FC

							/* begin block 1.2.1.3.1.3.1 */
								// Start line: 215
								// Start offset: 0x8008B708

								/* begin block 1.2.1.3.1.3.1.1 */
									// Start line: 215
									// Start offset: 0x8008B708
									// Variables:
								// 		struct Group *this; // $v0

									/* begin block 1.2.1.3.1.3.1.1.1 */
										// Start line: 215
										// Start offset: 0x8008B708
									/* end block 1.2.1.3.1.3.1.1.1 */
									// End offset: 0x8008B708
									// End Line: 215
								/* end block 1.2.1.3.1.3.1.1 */
								// End offset: 0x8008B708
								// End Line: 215
							/* end block 1.2.1.3.1.3.1 */
							// End offset: 0x8008B728
							// End Line: 218
						/* end block 1.2.1.3.1.3 */
						// End offset: 0x8008B728
						// End Line: 218
					/* end block 1.2.1.3.1 */
					// End offset: 0x8008B730
					// End Line: 218
				/* end block 1.2.1.3 */
				// End offset: 0x8008B730
				// End Line: 218
			/* end block 1.2.1 */
			// End offset: 0x8008B730
			// End Line: 218
		/* end block 1.2 */
		// End offset: 0x8008B730
		// End Line: 218

		/* begin block 1.3 */
			// Start line: 225
			// Start offset: 0x8008B730
			// Variables:
		// 		struct SerializedGroup *geomGroup; // $s1

			/* begin block 1.3.1 */
				// Start line: 225
				// Start offset: 0x8008B730

				/* begin block 1.3.1.1 */
					// Start line: 225
					// Start offset: 0x8008B730
				/* end block 1.3.1.1 */
				// End offset: 0x8008B730
				// End Line: 225
			/* end block 1.3.1 */
			// End offset: 0x8008B730
			// End Line: 225

			/* begin block 1.3.2 */
				// Start line: 225
				// Start offset: 0x8008B730

				/* begin block 1.3.2.1 */
					// Start line: 225
					// Start offset: 0x8008B730
				/* end block 1.3.2.1 */
				// End offset: 0x8008B730
				// End Line: 225
			/* end block 1.3.2 */
			// End offset: 0x8008B730
			// End Line: 225
		/* end block 1.3 */
		// End offset: 0x8008B730
		// End Line: 225
	/* end block 1 */
	// End offset: 0x8008B730
	// End Line: 225

	/* begin block 2 */
		// Start line: 151
	/* end block 2 */
	// End Line: 152

	/* begin block 3 */
		// Start line: 152
	/* end block 3 */
	// End Line: 153

	/* begin block 4 */
		// Start line: 165
	/* end block 4 */
	// End Line: 166

	/* begin block 5 */
		// Start line: 165
	/* end block 5 */
	// End Line: 166

void InstanceGroup__5ChunkP15SerializedGroupP9SimpleMem
               (Chunk *this,SerializedGroup *chunkGroup,SimpleMem *mem)

{
  char cVar1;
  SerializedGroup *source;
  Group *pGVar2;
  SerializedGroup *source_00;
  uint uVar3;
  SerializedGroup *pSVar4;
  SerializedGroup *pSVar5;
  int iVar6;
  int iVar7;
  int dataSize;
  
  source = LocateGroupType__15SerializedGroupii(chunkGroup,0x1c,0);
  this->firstSimSliceInd = *(short *)((int)&source[1].dummy + 2);
  this->boundPts[0] = *(RelCoord16 *)&source[2].m_type;
  this->boundPts[1] = *(RelCoord16 *)&source[2].m_length;
  this->boundPts[2] = *(RelCoord16 *)&source[2].dummy;
  this->boundPts[3] = *(RelCoord16 *)&source[2].m_num_elements;
  this->chunkboundPts[0] = *(RelCoord16 *)&source[3].m_type;
  this->chunkboundPts[1] = *(RelCoord16 *)&source[3].m_length;
  this->chunkboundPts[2] = *(RelCoord16 *)&source[3].dummy;
  this->chunkboundPts[3] = *(RelCoord16 *)&source[3].m_num_elements;
  this->chunkInd = *(short *)&source[1].m_num_elements;
  if (GameSetup_gData.commMode != 1) {
    pGVar2 = LocateCreateGroupType__15SerializedGroupiP9SimpleMemi(chunkGroup,3,mem,0);
    this->objInstanceBuf = pGVar2;
    pGVar2 = LocateCreateGroupType__15SerializedGroupiP9SimpleMemi(chunkGroup,0xb,mem,0);
    this->simObjBuf = pGVar2;
    goto LAB_8008b734;
  }
  source = LocateGroupType__15SerializedGroupii(chunkGroup,0xb,0);
  source_00 = LocateGroupType__15SerializedGroupii(chunkGroup,3,0);
  if (source == (SerializedGroup *)0x0) {
LAB_8008b630:
    this->simObjBuf = (Group *)0x0;
  }
  else {
    iVar7 = 0;
    pSVar4 = source + 1;
    while (iVar7 < source->m_num_elements) {
      if (*(char *)((int)&pSVar4[1].m_type + 2) != '\x7f') {
        uVar3 = (uint)*(byte *)((int)&pSVar4[1].m_type + 2);
        pSVar5 = source_00 + 1;
        if (source_00->m_num_elements <= (int)uVar3) break;
        while (uVar3 = uVar3 - 1, uVar3 != 0xffffffff) {
          pSVar5 = (SerializedGroup *)((int)&pSVar5->m_type + (int)*(short *)&pSVar5->m_type);
        }
        if (((pSVar5 == (SerializedGroup *)0x0) || (*(char *)((int)&pSVar5->m_type + 2) != '\x05'))
           || (*(char *)((int)&pSVar5[2].m_type + 3) != '\0')) break;
      }
      pSVar4 = (SerializedGroup *)&pSVar4[1].m_length;
      iVar7 = iVar7 + 1;
    }
    if (iVar7 == 0) goto LAB_8008b630;
    pGVar2 = CreateLiteGroupDataSize__15SerializedGroupP15SerializedGroupP9SimpleMemi
                       (chunkGroup,source,mem,iVar7 * 0x14);
    this->simObjBuf = pGVar2;
    pGVar2->m_num_elements = iVar7;
  }
  iVar7 = 0;
  if (source_00 == (SerializedGroup *)0x0) {
    this->objInstanceBuf = (Group *)0x0;
  }
  else {
    dataSize = 0;
    pSVar4 = source_00 + 1;
    while (iVar7 < source_00->m_num_elements) {
      cVar1 = *(char *)((int)&pSVar4->m_type + 2);
      if (cVar1 == '\x05') {
        if (*(char *)((int)&pSVar4[2].m_type + 3) != '\0') break;
      }
      else {
        if (cVar1 != '\x01') break;
      }
      iVar7 = iVar7 + 1;
      dataSize = dataSize + (int)*(short *)&pSVar4->m_type;
      pSVar4 = (SerializedGroup *)((int)&pSVar4->m_type + (int)*(short *)&pSVar4->m_type);
    }
    pGVar2 = CreateLiteGroupDataSize__15SerializedGroupP15SerializedGroupP9SimpleMemi
                       (chunkGroup,source_00,mem,dataSize);
    this->objInstanceBuf = pGVar2;
    pGVar2->m_num_elements = iVar7;
  }
  if ((this->simObjBuf != (Group *)0x0) && (this->objInstanceBuf != (Group *)0x0)) {
    dataSize = this->simObjBuf->m_num_elements;
    iVar7 = (int)source + dataSize * 0x14 + 0x10;
    while( true ) {
      iVar6 = iVar7;
      dataSize = dataSize + -1;
      if (dataSize == -1) break;
      iVar7 = iVar6 + -0x14;
      if (this->objInstanceBuf->m_num_elements <= (int)(uint)*(byte *)(iVar6 + -2)) {
        *(undefined *)(iVar6 + -2) = 0x7f;
        iVar7 = iVar6 + -0x14;
      }
    }
  }
LAB_8008b734:
  pGVar2 = LocateCreateGroupType__15SerializedGroupiP9SimpleMemi(chunkGroup,0x15,mem,0);
  this->objSpecialInstanceBuf = pGVar2;
  pGVar2 = LocateCreateGroupType__15SerializedGroupiP9SimpleMemi(chunkGroup,10,mem,0);
  this->sfxBuf = pGVar2;
  pGVar2 = LocateCreateGroupType__15SerializedGroupiP9SimpleMemi(chunkGroup,5,mem,0);
  this->simQuadBuf = pGVar2;
  pGVar2 = LocateCreateGroupType__15SerializedGroupiP9SimpleMemi(chunkGroup,6,mem,0);
  this->simSliceBuf = pGVar2;
  pGVar2 = LocateCreateGroupType__15SerializedGroupiP9SimpleMemi(chunkGroup,9,mem,0);
  this->lineBuf = pGVar2;
  source = LocateGroupType__15SerializedGroupii(chunkGroup,0x17,0);
  source_00 = LocateGroupType__15SerializedGroupii(source,0x1b,0);
  this->quadCounts[0] = *(uchar *)&source_00[1].m_num_elements;
  this->quadCounts[1] = *(uchar *)((int)&source_00[1].m_num_elements + 2);
  this->quadCounts[2] = *(uchar *)&source_00[2].m_type;
  this->quadCounts[3] = *(uchar *)((int)&source_00[2].m_type + 2);
  this->quadCounts[4] = *(uchar *)&source_00[2].m_length;
  this->quadCounts[5] = *(uchar *)((int)&source_00[2].m_length + 2);
  pGVar2 = LocateCreateGroupType__15SerializedGroupiP9SimpleMemi(source,0x19,mem,0);
  *(Group **)this->renderQuads = pGVar2 + 1;
  pGVar2 = (Group *)((int)(pGVar2 + 1) + (int)*(short *)&source_00[1].m_num_elements * 6);
  *(Group **)(this->renderQuads + 1) = pGVar2;
  pGVar2 = (Group *)((int)pGVar2 + (int)*(short *)((int)&source_00[1].m_num_elements + 2) * 6);
  *(Group **)(this->renderQuads + 2) = pGVar2;
  *(Group **)(this->renderQuads + 3) =
       (Group *)((int)pGVar2 + (int)*(short *)&source_00[2].m_length * 6);
  pGVar2 = LocateCreateGroupType__15SerializedGroupiP9SimpleMemi(source,0x1a,mem,0);
  this->stripBuf = pGVar2;
  pGVar2 = LocateCreateGroupType__15SerializedGroupiP9SimpleMemi(source,0x25,mem,0);
  this->lorezstripBuf = pGVar2;
  pGVar2 = LocateCreateGroupType__15SerializedGroupiP9SimpleMemi(source,0x18,mem,0);
  this->vertexBuf = pGVar2;
  pGVar2 = LocateCreateGroupType__15SerializedGroupiP9SimpleMemi(source,0x27,mem,0);
  this->objVertexBuf = pGVar2;
  pGVar2 = LocateCreateGroupType__15SerializedGroupiP9SimpleMemi(source,0x28,mem,0);
  this->objQuadBuf = pGVar2;
  pGVar2 = LocateCreateGroupType__15SerializedGroupiP9SimpleMemi(source,0x29,mem,0);
  this->objQuadInstanceBuf = pGVar2;
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ Chunk_UpdateSys__FP13DRender_tView(struct DRender_tView *Vi /*$a0*/)
 // line 274, offset 0x8008b920
	/* begin block 1 */
		// Start line: 275
		// Start offset: 0x8008B920
	/* end block 1 */
	// End offset: 0x8008B920
	// End Line: 275

	/* begin block 2 */
		// Start line: 571
	/* end block 2 */
	// End Line: 572

	/* begin block 3 */
		// Start line: 584
	/* end block 3 */
	// End Line: 585

	/* begin block 4 */
		// Start line: 584
	/* end block 4 */
	// End Line: 585

	/* begin block 5 */
		// Start line: 590
	/* end block 5 */
	// End Line: 591

void Chunk_UpdateSys__FP13DRender_tView(DRender_tView *Vi)

{
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ Chunk_Init__Fv()
 // line 291, offset 0x8008b928
	/* begin block 1 */
		// Start line: 292
		// Start offset: 0x8008B928
	/* end block 1 */
	// End offset: 0x8008B928
	// End Line: 292

	/* begin block 2 */
		// Start line: 607
	/* end block 2 */
	// End Line: 608

	/* begin block 3 */
		// Start line: 618
	/* end block 3 */
	// End Line: 619

	/* begin block 4 */
		// Start line: 618
	/* end block 4 */
	// End Line: 619

	/* begin block 5 */
		// Start line: 628
	/* end block 5 */
	// End Line: 629

/* WARNING: Unknown calling convention yet parameter storage is locked */

void Chunk_Init__Fv(void)

{
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ Chunk_DeInit__Fv()
 // line 310, offset 0x8008b930
	/* begin block 1 */
		// Start line: 311
		// Start offset: 0x8008B930
	/* end block 1 */
	// End offset: 0x8008B930
	// End Line: 311

	/* begin block 2 */
		// Start line: 647
	/* end block 2 */
	// End Line: 648

	/* begin block 3 */
		// Start line: 656
	/* end block 3 */
	// End Line: 657

	/* begin block 4 */
		// Start line: 656
	/* end block 4 */
	// End Line: 657

	/* begin block 5 */
		// Start line: 658
	/* end block 5 */
	// End Line: 659

/* WARNING: Unknown calling convention yet parameter storage is locked */

void Chunk_DeInit__Fv(void)

{
  return;
}





