#include "THISDUST.H"
#include "GENERICPMX.H"


// decompiled code
// original method signature: 
// void /*$ra*/ GenericPMX_LoadTexture__Fv()
 // line 54, offset 0x8009b458
	/* begin block 1 */
		// Start line: 55
		// Start offset: 0x8009B458
		// Variables:
	// 		char name[255]; // stack offset -304
	// 		char *shpfile; // $s6
	// 		int np; // $s5
	// 		int i; // $s2
	// 		int recolor_flag; // $s7

		/* begin block 1.1 */
			// Start line: 78
			// Start offset: 0x8009B4F4

			/* begin block 1.1.1 */
				// Start line: 85
				// Start offset: 0x8009B520

				/* begin block 1.1.1.1 */
					// Start line: 87
					// Start offset: 0x8009B52C
					// Variables:
				// 		struct Draw_tPixMap *pmx; // $s0
				/* end block 1.1.1.1 */
				// End offset: 0x8009B52C
				// End Line: 87
			/* end block 1.1.1 */
			// End offset: 0x8009B52C
			// End Line: 87
		/* end block 1.1 */
		// End offset: 0x8009B580
		// End Line: 89

		/* begin block 1.2 */
			// Start line: 91
			// Start offset: 0x8009B580
			// Variables:
		// 		struct Draw_tPixMap *pmx; // $s1
		/* end block 1.2 */
		// End offset: 0x8009B580
		// End Line: 91

		/* begin block 1.3 */
			// Start line: 91
			// Start offset: 0x8009B580
			// Variables:
		// 		struct Draw_tPixMap *pmx; // $s0
		/* end block 1.3 */
		// End offset: 0x8009B580
		// End Line: 91

		/* begin block 1.4 */
			// Start line: 91
			// Start offset: 0x8009B580
			// Variables:
		// 		struct Draw_tPixMap *pmx; // $s1
		/* end block 1.4 */
		// End offset: 0x8009B580
		// End Line: 91

		/* begin block 1.5 */
			// Start line: 91
			// Start offset: 0x8009B580
			// Variables:
		// 		struct Draw_tPixMap *pmx; // $s0
		/* end block 1.5 */
		// End offset: 0x8009B580
		// End Line: 91

		/* begin block 1.6 */
			// Start line: 91
			// Start offset: 0x8009B580
			// Variables:
		// 		struct Draw_tPixMap *pmx; // $s0
		/* end block 1.6 */
		// End offset: 0x8009B580
		// End Line: 91

		/* begin block 1.7 */
			// Start line: 91
			// Start offset: 0x8009B580

			/* begin block 1.7.1 */
				// Start line: 105
				// Start offset: 0x8009B6E8

				/* begin block 1.7.1.1 */
					// Start line: 106
					// Start offset: 0x8009B6E8
					// Variables:
				// 		struct Draw_tPixMap *pmx; // $s0
				/* end block 1.7.1.1 */
				// End offset: 0x8009B6E8
				// End Line: 106

				/* begin block 1.7.1.2 */
					// Start line: 106
					// Start offset: 0x8009B6E8
					// Variables:
				// 		struct Draw_tPixMap *pmx; // $s2
				/* end block 1.7.1.2 */
				// End offset: 0x8009B6E8
				// End Line: 106

				/* begin block 1.7.1.3 */
					// Start line: 106
					// Start offset: 0x8009B6E8
					// Variables:
				// 		struct Draw_tPixMap *pmx; // $s0
				/* end block 1.7.1.3 */
				// End offset: 0x8009B6E8
				// End Line: 106
			/* end block 1.7.1 */
			// End offset: 0x8009B7D4
			// End Line: 112
		/* end block 1.7 */
		// End offset: 0x8009B7D4
		// End Line: 112

		/* begin block 1.8 */
			// Start line: 115
			// Start offset: 0x8009B7D4
			// Variables:
		// 		struct Draw_tPixMap *pmx; // $s0
		/* end block 1.8 */
		// End offset: 0x8009B7D4
		// End Line: 115

		/* begin block 1.9 */
			// Start line: 115
			// Start offset: 0x8009B7D4
			// Variables:
		// 		struct Draw_tPixMap *pmx; // $s1
		/* end block 1.9 */
		// End offset: 0x8009B7D4
		// End Line: 115

		/* begin block 1.10 */
			// Start line: 115
			// Start offset: 0x8009B7D4
			// Variables:
		// 		struct Draw_tPixMap *pmx; // $s0
		/* end block 1.10 */
		// End offset: 0x8009B7D4
		// End Line: 115

		/* begin block 1.11 */
			// Start line: 115
			// Start offset: 0x8009B7D4
			// Variables:
		// 		struct Draw_tPixMap *pmx; // $s1
		/* end block 1.11 */
		// End offset: 0x8009B7D4
		// End Line: 115

		/* begin block 1.12 */
			// Start line: 115
			// Start offset: 0x8009B7D4
			// Variables:
		// 		struct Draw_tPixMap *pmx; // $s0
		/* end block 1.12 */
		// End offset: 0x8009B7D4
		// End Line: 115

		/* begin block 1.13 */
			// Start line: 115
			// Start offset: 0x8009B7D4
			// Variables:
		// 		struct Draw_tPixMap *pmx; // $s1
		/* end block 1.13 */
		// End offset: 0x8009B7D4
		// End Line: 115

		/* begin block 1.14 */
			// Start line: 115
			// Start offset: 0x8009B7D4
			// Variables:
		// 		struct Draw_tPixMap *pmx; // $s0
		/* end block 1.14 */
		// End offset: 0x8009B7D4
		// End Line: 115

		/* begin block 1.15 */
			// Start line: 115
			// Start offset: 0x8009B7D4
			// Variables:
		// 		struct Draw_tPixMap *pmx; // $s1
		/* end block 1.15 */
		// End offset: 0x8009B7D4
		// End Line: 115

		/* begin block 1.16 */
			// Start line: 115
			// Start offset: 0x8009B7D4
			// Variables:
		// 		struct Draw_tPixMap *pmx; // $s0
		/* end block 1.16 */
		// End offset: 0x8009B7D4
		// End Line: 115

		/* begin block 1.17 */
			// Start line: 115
			// Start offset: 0x8009B7D4

			/* begin block 1.17.1 */
				// Start line: 126
				// Start offset: 0x8009B9F0

				/* begin block 1.17.1.1 */
					// Start line: 130
					// Start offset: 0x8009B9FC
					// Variables:
				// 		struct Draw_tPixMap *pmx; // $s0
				/* end block 1.17.1.1 */
				// End offset: 0x8009B9FC
				// End Line: 130
			/* end block 1.17.1 */
			// End offset: 0x8009B9FC
			// End Line: 130
		/* end block 1.17 */
		// End offset: 0x8009BA50
		// End Line: 132

		/* begin block 1.18 */
			// Start line: 141
			// Start offset: 0x8009BA50

			/* begin block 1.18.1 */
				// Start line: 142
				// Start offset: 0x8009BA78
				// Variables:
			// 		struct shapetbl *shape; // $v0
			// 		char shpname[5]; // stack offset -48

				/* begin block 1.18.1.1 */
					// Start line: 148
					// Start offset: 0x8009BA78

					/* begin block 1.18.1.1.1 */
						// Start line: 153
						// Start offset: 0x8009BAA0

						/* begin block 1.18.1.1.1.1 */
							// Start line: 154
							// Start offset: 0x8009BAA0
							// Variables:
						// 		struct Draw_tPixMap *pmx; // $s0
						/* end block 1.18.1.1.1.1 */
						// End offset: 0x8009BAA0
						// End Line: 154
					/* end block 1.18.1.1.1 */
					// End offset: 0x8009BAA0
					// End Line: 154
				/* end block 1.18.1.1 */
				// End offset: 0x8009BAE8
				// End Line: 156
			/* end block 1.18.1 */
			// End offset: 0x8009BAE8
			// End Line: 156
		/* end block 1.18 */
		// End offset: 0x8009BAEC
		// End Line: 158

		/* begin block 1.19 */
			// Start line: 161
			// Start offset: 0x8009BAEC
			// Variables:
		// 		struct Draw_tPixMap *pmx; // $s0
		/* end block 1.19 */
		// End offset: 0x8009BAEC
		// End Line: 161

		/* begin block 1.20 */
			// Start line: 161
			// Start offset: 0x8009BAEC

			/* begin block 1.20.1 */
				// Start line: 165
				// Start offset: 0x8009BB40

				/* begin block 1.20.1.1 */
					// Start line: 166
					// Start offset: 0x8009BB40

					/* begin block 1.20.1.1.1 */
						// Start line: 166
						// Start offset: 0x8009BB58

						/* begin block 1.20.1.1.1.1 */
							// Start line: 169
							// Start offset: 0x8009BB64
							// Variables:
						// 		struct Draw_tPixMap *pmx; // $s0
						/* end block 1.20.1.1.1.1 */
						// End offset: 0x8009BB64
						// End Line: 169

						/* begin block 1.20.1.1.1.2 */
							// Start line: 169
							// Start offset: 0x8009BB64
							// Variables:
						// 		struct Draw_tPixMap *pmx; // $v0
						/* end block 1.20.1.1.1.2 */
						// End offset: 0x8009BB64
						// End Line: 169
					/* end block 1.20.1.1.1 */
					// End offset: 0x8009BB64
					// End Line: 169
				/* end block 1.20.1.1 */
				// End offset: 0x8009BBFC
				// End Line: 175
			/* end block 1.20.1 */
			// End offset: 0x8009BBFC
			// End Line: 175

			/* begin block 1.20.2 */
				// Start line: 178
				// Start offset: 0x8009BBFC

				/* begin block 1.20.2.1 */
					// Start line: 179
					// Start offset: 0x8009BBFC

					/* begin block 1.20.2.1.1 */
						// Start line: 180
						// Start offset: 0x8009BC18

						/* begin block 1.20.2.1.1.1 */
							// Start line: 181
							// Start offset: 0x8009BC18
							// Variables:
						// 		struct Draw_tPixMap *pmx; // $s0
						/* end block 1.20.2.1.1.1 */
						// End offset: 0x8009BC60
						// End Line: 181
					/* end block 1.20.2.1.1 */
					// End offset: 0x8009BC60
					// End Line: 181
				/* end block 1.20.2.1 */
				// End offset: 0x8009BC60
				// End Line: 181

				/* begin block 1.20.2.2 */
					// Start line: 183
					// Start offset: 0x8009BC60

					/* begin block 1.20.2.2.1 */
						// Start line: 184
						// Start offset: 0x8009BC74

						/* begin block 1.20.2.2.1.1 */
							// Start line: 186
							// Start offset: 0x8009BC74
							// Variables:
						// 		struct Draw_tPixMap *pmx; // $s1
						/* end block 1.20.2.2.1.1 */
						// End offset: 0x8009BC74
						// End Line: 186

						/* begin block 1.20.2.2.1.2 */
							// Start line: 186
							// Start offset: 0x8009BC74
							// Variables:
						// 		struct Draw_tPixMap *pmx; // $s0
						/* end block 1.20.2.2.1.2 */
						// End offset: 0x8009BC74
						// End Line: 186

						/* begin block 1.20.2.2.1.3 */
							// Start line: 186
							// Start offset: 0x8009BC74
							// Variables:
						// 		struct Draw_tPixMap *pmx; // $s0
						/* end block 1.20.2.2.1.3 */
						// End offset: 0x8009BC74
						// End Line: 186

						/* begin block 1.20.2.2.1.4 */
							// Start line: 186
							// Start offset: 0x8009BC74
						/* end block 1.20.2.2.1.4 */
						// End offset: 0x8009BD64
						// End Line: 195
					/* end block 1.20.2.2.1 */
					// End offset: 0x8009BD64
					// End Line: 195
				/* end block 1.20.2.2 */
				// End offset: 0x8009BD64
				// End Line: 195
			/* end block 1.20.2 */
			// End offset: 0x8009BD64
			// End Line: 195
		/* end block 1.20 */
		// End offset: 0x8009BD64
		// End Line: 195
	/* end block 1 */
	// End offset: 0x8009BD64
	// End Line: 201

	/* begin block 2 */
		// Start line: 108
	/* end block 2 */
	// End Line: 109

	/* begin block 3 */
		// Start line: 108
	/* end block 3 */
	// End Line: 109

/* WARNING: Unknown calling convention yet parameter storage is locked */

void GenericPMX_LoadTexture__Fv(void)

{
  bool bVar1;
  char *n;
  Draw_tPixMap *pmx;
  char *__format;
  Draw_tPixMap **ppDVar2;
  Draw_tPixMap **ppDVar3;
  int iVar4;
  int iVar5;
  int iVar6;
  int iVar7;
  char acStack304 [256];
  int aiStack48 [2];
  
  if ((GameSetup_gData.track & 0xfU) == 4) {
    if (GameSetup_gData.Weather == 0) {
      __format = s__sSfx4_psh_80055fa0;
    }
    else {
      __format = s__sSfx4w_psh_80055f94;
    }
  }
  else {
    __format = s__sSfx_psh_80055fac;
  }
  sprintf(acStack304,__format,PTR_801164cc);
  __format = (char *)loadfileadr(acStack304,0);
  Texture_ResetPaletteSharing__Fv();
  iVar4 = 0;
  ppDVar2 = gDLPixmap10;
  iVar6 = 0;
  while (iVar4 < 10) {
    sprintf(acStack304,s_LIN_d_8013d10c,iVar4);
    Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
              (__format,acStack304,0x40,0,0xa0,-1,-1,&gPixmaps + iVar6);
    *ppDVar2 = &gPixmaps + iVar6;
    ppDVar2 = ppDVar2 + 1;
    iVar4 = iVar4 + 1;
    iVar6 = iVar6 + 1;
  }
  Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
            (__format,&DAT_8013d114,0x40,0,0xa0,-1,-1,&gPixmaps + iVar6);
  gSpikeBeltPixmap = &gPixmaps + iVar6;
  Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
            (__format,&DAT_8013d11c,0x40,0,0xa0,-1,-1,&gPixmaps + iVar6 + 1);
  gDPixmap = &gPixmaps + iVar6 + 1;
  Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
            (__format,&DAT_8013d124,0x40,0,0xa0,-1,-1,&gPixmaps + iVar6 + 2);
  gShadowPixmap2[0] = &gPixmaps + iVar6 + 2;
  Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
            (__format,&DAT_8013d12c,0x40,0,0xa0,-1,-1,&gPixmaps + iVar6 + 3);
  gSkidMarkPixmap2 = &gPixmaps + iVar6 + 3;
  Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
            (__format,&DAT_8013d134,0x40,0,0xa0,-1,-1,&gPixmaps + iVar6 + 4);
  PTR_8013d1f0 = &gPixmaps + iVar6 + 4;
  ChangeTPage__FPUsi(&gSkidMarkPixmap2->tpage,2);
  ChangeTPage__FPUsi(&PTR_8013d1f0->tpage,2);
  iVar4 = iVar6 + 5;
  if (GameSetup_gData.Weather != 0) {
    Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
              (__format,&DAT_8013d13c,0x40,0,0xa0,-1,-1,&gPixmaps + iVar4);
    gWeatherPixmap3 = &gPixmaps + iVar4;
    Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
              (__format,&DAT_8013d144,0x40,0,0xa0,-1,-1,&gPixmaps + iVar6 + 6);
    iVar4 = iVar6 + 8;
    PTR_80112b80 = &gPixmaps + iVar6 + 6;
    Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
              (__format,&DAT_8013d14c,0x40,0,0xa0,-1,-1,&gPixmaps + iVar6 + 7);
    PTR_80112b84 = &gPixmaps + iVar6 + 7;
    ChangeTPage__FPUsi(&gWeatherPixmap3->tpage,1);
    ChangeTPage__FPUsi(&PTR_80112b80->tpage,1);
    ChangeTPage__FPUsi(&PTR_80112b84->tpage,1);
  }
  Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
            (__format,&DAT_8013d154,0x40,0,0xa0,-1,-1,&gPixmaps + iVar4);
  gSMokePixmap2 = &gPixmaps + iVar4;
  Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
            (__format,&DAT_8013d15c,0x40,0,0xa0,-1,-1,&gPixmaps + iVar4 + 1);
  PTR_8013d1f8 = &gPixmaps + iVar4 + 1;
  Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
            (__format,&DAT_8013d164,0,-1,-1,-1,-1,&gPixmaps + iVar4 + 2);
  gSMokePalette = &gPixmaps + iVar4 + 2;
  Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
            (__format,&DAT_8013d16c,0,-1,-1,-1,-1,&gPixmaps + iVar4 + 3);
  gDirtPalette = &gPixmaps + iVar4 + 3;
  Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
            (__format,&DAT_8013d174,0x40,0,0xa0,-1,-1,&gPixmaps + iVar4 + 4);
  gGravelPixmap2 = &gPixmaps + iVar4 + 4;
  Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
            (__format,&DAT_8013d17c,0x40,0,0xa0,-1,-1,&gPixmaps + iVar4 + 5);
  PTR_8013d208 = &gPixmaps + iVar4 + 5;
  Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
            (__format,&DAT_8013d184,0,-1,-1,-1,-1,&gPixmaps + iVar4 + 6);
  gGravelPalette = &gPixmaps + iVar4 + 6;
  Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
            (__format,&DAT_8013d18c,0,-1,-1,-1,-1,&gPixmaps + iVar4 + 7);
  gGrassPalette = &gPixmaps + iVar4 + 7;
  Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
            (__format,&DAT_8013d194,0,-1,-1,-1,-1,&gPixmaps + iVar4 + 8);
  iVar5 = 0;
  ppDVar2 = gSparkHPixmap6;
  iVar6 = iVar4 + 9;
  gSnowPalette = &gPixmaps + iVar4 + 8;
  while (iVar5 < 6) {
    sprintf(acStack304,s_SHX_d_8013d19c,iVar5);
    Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
              (__format,acStack304,0x40,0,0xa0,-1,-1,&gPixmaps + iVar6);
    *ppDVar2 = &gPixmaps + iVar6;
    ppDVar2 = ppDVar2 + 1;
    iVar5 = iVar5 + 1;
    iVar6 = iVar6 + 1;
  }
  if ((GameSetup_gData.Time == 0) && (GameSetup_gData.commMode != 1)) {
    sprintf((char *)aiStack48,s_LF_02d_8013d1a4,GameSetup_gData.track);
    n = (char *)locateshapez((int)__format,aiStack48);
    if (n != (char *)0x0) {
      pmx = &gPixmaps + iVar6;
      Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap((char *)0x0,n,0x40,0,0xa0,-1,-1,pmx);
      iVar6 = iVar6 + 1;
      gLeafPixmap = pmx;
      goto LAB_8009baf0;
    }
  }
  gLeafPixmap = (Draw_tPixMap *)0x0;
LAB_8009baf0:
  pmx = &gPixmaps + iVar6;
  Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap(__format,&DAT_8013d1ac,0x40,0,0xa0,-1,-1,pmx);
  iVar4 = iVar6 + 1;
  if (GameSetup_gData.Weather == 0) {
    iVar5 = iVar4;
    gDamagePixmap = pmx;
    if ((TrackSpec_gSpec.skyspec.flags & 8U) != 0) {
      iVar5 = iVar6 + 2;
      gDamagePixmap = pmx;
      Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
                (__format,&DAT_8013d1bc,0x40,0,0xa0,-1,-1,&gPixmaps + iVar4);
      gFlarePixmap3 = &gPixmaps + iVar4;
    }
    if ((TrackSpec_gSpec.skyspec.flags & 4U) != 0) {
      Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
                (__format,&DAT_8013d1c4,0x40,0,0xa0,-1,-1,&gPixmaps + iVar5);
      gFlarePixmap3 = &gPixmaps + iVar5;
      Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
                (__format,&DAT_8013d1cc,0x40,0,0xa0,-1,-1,&gPixmaps + iVar5 + 1);
      PTR_80112b8c = &gPixmaps + iVar5 + 1;
      Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
                (__format,&DAT_8013d1d4,0x40,0,0xa0,-1,-1,&gPixmaps + iVar5 + 2);
      PTR_80112b90 = &gPixmaps + iVar5 + 2;
      ChangeTPage__FPUsi(&gFlarePixmap3->tpage,1);
      ChangeTPage__FPUsi(&PTR_80112b8c->tpage,1);
      ChangeTPage__FPUsi(&PTR_80112b90->tpage,1);
    }
  }
  else {
    iVar6 = 0;
    ppDVar2 = gLightningPixmap16;
    iVar5 = 0x20;
    bVar1 = true;
    gDamagePixmap = pmx;
    while (bVar1) {
      sprintf(acStack304,s_LNG_d_8013d1b4,iVar6);
      iVar7 = iVar4 + 1;
      pmx = &gPixmaps + iVar4;
      Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap(__format,acStack304,0x40,0,0xa0,-1,-1,pmx);
      iVar4 = iVar4 + 2;
      ppDVar3 = (Draw_tPixMap **)((int)gLightningPixmap16 + iVar5);
      iVar5 = iVar5 + 4;
      *ppDVar2 = pmx;
      *ppDVar3 = &gPixmaps + iVar7;
      iVar6 = iVar6 + 1;
      ChangeTPage__FPUsi(&(*ppDVar2)->tpage,1);
      pmx = *ppDVar2;
      ppDVar2 = ppDVar2 + 1;
      Texture_CloneUVPmx__FP12Draw_tPixMapiT0(pmx,0,*ppDVar3);
      bVar1 = iVar6 < 8;
    }
  }
  purgememadr((int)__format);
  return;
}





