#include "NFS4.H"
#include "GENERICPMX.H"

// decompiled code
// original method signature: 
// void /*$ra*/ GenericPMX_LoadTexture__Fv()
 // line 54, offset 0x8009b458
	/* begin block 1 */
		// Start line: 55
		// Start offset: 0x8009B458
		// Variables:
	// 		char name[255]; // stack offset -304
	// 		char *shpfile; // $s6
	// 		int np; // $s5
	// 		int i; // $s2
	// 		int recolor_flag; // $s7

		/* begin block 1.1 */
			// Start line: 78
			// Start offset: 0x8009B4F4

			/* begin block 1.1.1 */
				// Start line: 85
				// Start offset: 0x8009B520

				/* begin block 1.1.1.1 */
					// Start line: 87
					// Start offset: 0x8009B52C
					// Variables:
				// 		struct Draw_tPixMap *pmx; // $s0
				/* end block 1.1.1.1 */
				// End offset: 0x8009B52C
				// End Line: 87
			/* end block 1.1.1 */
			// End offset: 0x8009B52C
			// End Line: 87
		/* end block 1.1 */
		// End offset: 0x8009B580
		// End Line: 89

		/* begin block 1.2 */
			// Start line: 91
			// Start offset: 0x8009B580
			// Variables:
		// 		struct Draw_tPixMap *pmx; // $s1
		/* end block 1.2 */
		// End offset: 0x8009B580
		// End Line: 91

		/* begin block 1.3 */
			// Start line: 91
			// Start offset: 0x8009B580
			// Variables:
		// 		struct Draw_tPixMap *pmx; // $s0
		/* end block 1.3 */
		// End offset: 0x8009B580
		// End Line: 91

		/* begin block 1.4 */
			// Start line: 91
			// Start offset: 0x8009B580
			// Variables:
		// 		struct Draw_tPixMap *pmx; // $s1
		/* end block 1.4 */
		// End offset: 0x8009B580
		// End Line: 91

		/* begin block 1.5 */
			// Start line: 91
			// Start offset: 0x8009B580
			// Variables:
		// 		struct Draw_tPixMap *pmx; // $s0
		/* end block 1.5 */
		// End offset: 0x8009B580
		// End Line: 91

		/* begin block 1.6 */
			// Start line: 91
			// Start offset: 0x8009B580
			// Variables:
		// 		struct Draw_tPixMap *pmx; // $s0
		/* end block 1.6 */
		// End offset: 0x8009B580
		// End Line: 91

		/* begin block 1.7 */
			// Start line: 91
			// Start offset: 0x8009B580

			/* begin block 1.7.1 */
				// Start line: 105
				// Start offset: 0x8009B6E8

				/* begin block 1.7.1.1 */
					// Start line: 106
					// Start offset: 0x8009B6E8
					// Variables:
				// 		struct Draw_tPixMap *pmx; // $s0
				/* end block 1.7.1.1 */
				// End offset: 0x8009B6E8
				// End Line: 106

				/* begin block 1.7.1.2 */
					// Start line: 106
					// Start offset: 0x8009B6E8
					// Variables:
				// 		struct Draw_tPixMap *pmx; // $s2
				/* end block 1.7.1.2 */
				// End offset: 0x8009B6E8
				// End Line: 106

				/* begin block 1.7.1.3 */
					// Start line: 106
					// Start offset: 0x8009B6E8
					// Variables:
				// 		struct Draw_tPixMap *pmx; // $s0
				/* end block 1.7.1.3 */
				// End offset: 0x8009B6E8
				// End Line: 106
			/* end block 1.7.1 */
			// End offset: 0x8009B7D4
			// End Line: 112
		/* end block 1.7 */
		// End offset: 0x8009B7D4
		// End Line: 112

		/* begin block 1.8 */
			// Start line: 115
			// Start offset: 0x8009B7D4
			// Variables:
		// 		struct Draw_tPixMap *pmx; // $s0
		/* end block 1.8 */
		// End offset: 0x8009B7D4
		// End Line: 115

		/* begin block 1.9 */
			// Start line: 115
			// Start offset: 0x8009B7D4
			// Variables:
		// 		struct Draw_tPixMap *pmx; // $s1
		/* end block 1.9 */
		// End offset: 0x8009B7D4
		// End Line: 115

		/* begin block 1.10 */
			// Start line: 115
			// Start offset: 0x8009B7D4
			// Variables:
		// 		struct Draw_tPixMap *pmx; // $s0
		/* end block 1.10 */
		// End offset: 0x8009B7D4
		// End Line: 115

		/* begin block 1.11 */
			// Start line: 115
			// Start offset: 0x8009B7D4
			// Variables:
		// 		struct Draw_tPixMap *pmx; // $s1
		/* end block 1.11 */
		// End offset: 0x8009B7D4
		// End Line: 115

		/* begin block 1.12 */
			// Start line: 115
			// Start offset: 0x8009B7D4
			// Variables:
		// 		struct Draw_tPixMap *pmx; // $s0
		/* end block 1.12 */
		// End offset: 0x8009B7D4
		// End Line: 115

		/* begin block 1.13 */
			// Start line: 115
			// Start offset: 0x8009B7D4
			// Variables:
		// 		struct Draw_tPixMap *pmx; // $s1
		/* end block 1.13 */
		// End offset: 0x8009B7D4
		// End Line: 115

		/* begin block 1.14 */
			// Start line: 115
			// Start offset: 0x8009B7D4
			// Variables:
		// 		struct Draw_tPixMap *pmx; // $s0
		/* end block 1.14 */
		// End offset: 0x8009B7D4
		// End Line: 115

		/* begin block 1.15 */
			// Start line: 115
			// Start offset: 0x8009B7D4
			// Variables:
		// 		struct Draw_tPixMap *pmx; // $s1
		/* end block 1.15 */
		// End offset: 0x8009B7D4
		// End Line: 115

		/* begin block 1.16 */
			// Start line: 115
			// Start offset: 0x8009B7D4
			// Variables:
		// 		struct Draw_tPixMap *pmx; // $s0
		/* end block 1.16 */
		// End offset: 0x8009B7D4
		// End Line: 115

		/* begin block 1.17 */
			// Start line: 115
			// Start offset: 0x8009B7D4

			/* begin block 1.17.1 */
				// Start line: 126
				// Start offset: 0x8009B9F0

				/* begin block 1.17.1.1 */
					// Start line: 130
					// Start offset: 0x8009B9FC
					// Variables:
				// 		struct Draw_tPixMap *pmx; // $s0
				/* end block 1.17.1.1 */
				// End offset: 0x8009B9FC
				// End Line: 130
			/* end block 1.17.1 */
			// End offset: 0x8009B9FC
			// End Line: 130
		/* end block 1.17 */
		// End offset: 0x8009BA50
		// End Line: 132

		/* begin block 1.18 */
			// Start line: 141
			// Start offset: 0x8009BA50

			/* begin block 1.18.1 */
				// Start line: 142
				// Start offset: 0x8009BA78
				// Variables:
			// 		struct shapetbl *shape; // $v0
			// 		char shpname[5]; // stack offset -48

				/* begin block 1.18.1.1 */
					// Start line: 148
					// Start offset: 0x8009BA78

					/* begin block 1.18.1.1.1 */
						// Start line: 153
						// Start offset: 0x8009BAA0

						/* begin block 1.18.1.1.1.1 */
							// Start line: 154
							// Start offset: 0x8009BAA0
							// Variables:
						// 		struct Draw_tPixMap *pmx; // $s0
						/* end block 1.18.1.1.1.1 */
						// End offset: 0x8009BAA0
						// End Line: 154
					/* end block 1.18.1.1.1 */
					// End offset: 0x8009BAA0
					// End Line: 154
				/* end block 1.18.1.1 */
				// End offset: 0x8009BAE8
				// End Line: 156
			/* end block 1.18.1 */
			// End offset: 0x8009BAE8
			// End Line: 156
		/* end block 1.18 */
		// End offset: 0x8009BAEC
		// End Line: 158

		/* begin block 1.19 */
			// Start line: 161
			// Start offset: 0x8009BAEC
			// Variables:
		// 		struct Draw_tPixMap *pmx; // $s0
		/* end block 1.19 */
		// End offset: 0x8009BAEC
		// End Line: 161

		/* begin block 1.20 */
			// Start line: 161
			// Start offset: 0x8009BAEC

			/* begin block 1.20.1 */
				// Start line: 165
				// Start offset: 0x8009BB40

				/* begin block 1.20.1.1 */
					// Start line: 166
					// Start offset: 0x8009BB40

					/* begin block 1.20.1.1.1 */
						// Start line: 166
						// Start offset: 0x8009BB58

						/* begin block 1.20.1.1.1.1 */
							// Start line: 169
							// Start offset: 0x8009BB64
							// Variables:
						// 		struct Draw_tPixMap *pmx; // $s0
						/* end block 1.20.1.1.1.1 */
						// End offset: 0x8009BB64
						// End Line: 169

						/* begin block 1.20.1.1.1.2 */
							// Start line: 169
							// Start offset: 0x8009BB64
							// Variables:
						// 		struct Draw_tPixMap *pmx; // $v0
						/* end block 1.20.1.1.1.2 */
						// End offset: 0x8009BB64
						// End Line: 169
					/* end block 1.20.1.1.1 */
					// End offset: 0x8009BB64
					// End Line: 169
				/* end block 1.20.1.1 */
				// End offset: 0x8009BBFC
				// End Line: 175
			/* end block 1.20.1 */
			// End offset: 0x8009BBFC
			// End Line: 175

			/* begin block 1.20.2 */
				// Start line: 178
				// Start offset: 0x8009BBFC

				/* begin block 1.20.2.1 */
					// Start line: 179
					// Start offset: 0x8009BBFC

					/* begin block 1.20.2.1.1 */
						// Start line: 180
						// Start offset: 0x8009BC18

						/* begin block 1.20.2.1.1.1 */
							// Start line: 181
							// Start offset: 0x8009BC18
							// Variables:
						// 		struct Draw_tPixMap *pmx; // $s0
						/* end block 1.20.2.1.1.1 */
						// End offset: 0x8009BC60
						// End Line: 181
					/* end block 1.20.2.1.1 */
					// End offset: 0x8009BC60
					// End Line: 181
				/* end block 1.20.2.1 */
				// End offset: 0x8009BC60
				// End Line: 181

				/* begin block 1.20.2.2 */
					// Start line: 183
					// Start offset: 0x8009BC60

					/* begin block 1.20.2.2.1 */
						// Start line: 184
						// Start offset: 0x8009BC74

						/* begin block 1.20.2.2.1.1 */
							// Start line: 186
							// Start offset: 0x8009BC74
							// Variables:
						// 		struct Draw_tPixMap *pmx; // $s1
						/* end block 1.20.2.2.1.1 */
						// End offset: 0x8009BC74
						// End Line: 186

						/* begin block 1.20.2.2.1.2 */
							// Start line: 186
							// Start offset: 0x8009BC74
							// Variables:
						// 		struct Draw_tPixMap *pmx; // $s0
						/* end block 1.20.2.2.1.2 */
						// End offset: 0x8009BC74
						// End Line: 186

						/* begin block 1.20.2.2.1.3 */
							// Start line: 186
							// Start offset: 0x8009BC74
							// Variables:
						// 		struct Draw_tPixMap *pmx; // $s0
						/* end block 1.20.2.2.1.3 */
						// End offset: 0x8009BC74
						// End Line: 186

						/* begin block 1.20.2.2.1.4 */
							// Start line: 186
							// Start offset: 0x8009BC74
						/* end block 1.20.2.2.1.4 */
						// End offset: 0x8009BD64
						// End Line: 195
					/* end block 1.20.2.2.1 */
					// End offset: 0x8009BD64
					// End Line: 195
				/* end block 1.20.2.2 */
				// End offset: 0x8009BD64
				// End Line: 195
			/* end block 1.20.2 */
			// End offset: 0x8009BD64
			// End Line: 195
		/* end block 1.20 */
		// End offset: 0x8009BD64
		// End Line: 195
	/* end block 1 */
	// End offset: 0x8009BD64
	// End Line: 201

void GenericPMX_LoadTexture__Fv(void)
{
  bool bVar1;
  char *n;
  Draw_tPixMap *pmx;
  char *__format;
  int iVar2;
  int iVar3;
  Draw_tPixMap **ppDVar4;
  Draw_tPixMap **ppDVar5;
  int iVar6;
  int iVar7;
  int iVar8;
  char acStack304 [256];
  char acStack48 [8];
  
  iVar7 = 0;
  if (true) {
    __format = "%sSfx.psh";
  }
  else {
    if (DAT_80113234 == 0) {
      __format = "%sSfx4.psh";
    }
    else {
      __format = "%sSfx4w.psh";
    }
  }
  sprintf(acStack304,__format,0);
  __format = (char *)loadfileadr(acStack304,0);
  Texture_ResetPaletteSharing__Fv();
  iVar6 = 0;
  ppDVar4 = (Draw_tPixMap **)&_gDLPixmap;
  while (iVar6 < 10) {
    sprintf(acStack304,"LIN%d",iVar6);
    iVar2 = iVar7 * 0x10;
    iVar7 = iVar7 + 1;
    Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
              (__format,acStack304,0x40,0,0xa0,-1,-1,(Draw_tPixMap *)(&gPixmaps + iVar2));
    *ppDVar4 = (Draw_tPixMap *)(&gPixmaps + iVar2);
    ppDVar4 = ppDVar4 + 1;
    iVar6 = iVar6 + 1;
  }
  Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
            (__format,"spik",0x40,0,0xa0,-1,-1,(Draw_tPixMap *)(&gPixmaps + iVar7 * 0x10));
  pDGp00000c94 = (Draw_tPixMap *)(&gPixmaps + iVar7 * 0x10);
  Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
            (__format,"DEBG",0x40,0,0xa0,-1,-1,(Draw_tPixMap *)(&gPixmaps + (iVar7 + 1) * 0x10));
  pDGp00000c90 = (Draw_tPixMap *)(&gPixmaps + (iVar7 + 1) * 0x10);
  Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
            (__format,"SHAD",0x40,0,0xa0,-1,-1,(Draw_tPixMap *)(&gPixmaps + (iVar7 + 2) * 0x10));
  pDGp00000c98 = (Draw_tPixMap *)(&gPixmaps + (iVar7 + 2) * 0x10);
  Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
            (__format,"SKD0",0x40,0,0xa0,-1,-1,(Draw_tPixMap *)(&gPixmaps + (iVar7 + 3) * 0x10));
  pDGp00000ca0 = (Draw_tPixMap *)(&gPixmaps + (iVar7 + 3) * 0x10);
  Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
            (__format,"SKD1",0x40,0,0xa0,-1,-1,(Draw_tPixMap *)(&gPixmaps + (iVar7 + 4) * 0x10));
  pDGp00000ca4 = (Draw_tPixMap *)(&gPixmaps + (iVar7 + 4) * 0x10);
  ChangeTPage__FPUsi(&pDGp00000ca0->tpage,2);
  ChangeTPage__FPUsi(&pDGp00000ca4->tpage,2);
  iVar6 = iVar7 + 5;
  if (DAT_80113234 != 0) {
    Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
              (__format,"FLAK",0x40,0,0xa0,-1,-1,(Draw_tPixMap *)(&gPixmaps + iVar6 * 0x10));
    _gWeatherPixmap = (Draw_tPixMap *)(&gPixmaps + iVar6 * 0x10);
    Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
              (__format,"FLA1",0x40,0,0xa0,-1,-1,(Draw_tPixMap *)(&gPixmaps + (iVar7 + 6) * 0x10));
    iVar6 = iVar7 + 8;
    DAT_80112b80 = (Draw_tPixMap *)(&gPixmaps + (iVar7 + 6) * 0x10);
    Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
              (__format,"SPLT",0x40,0,0xa0,-1,-1,(Draw_tPixMap *)(&gPixmaps + (iVar7 + 7) * 0x10));
    DAT_80112b84 = (Draw_tPixMap *)(&gPixmaps + (iVar7 + 7) * 0x10);
    ChangeTPage__FPUsi(&_gWeatherPixmap->tpage,1);
    ChangeTPage__FPUsi(&DAT_80112b80->tpage,1);
    ChangeTPage__FPUsi(&DAT_80112b84->tpage,1);
  }
  Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
            (__format,"SMX0",0x40,0,0xa0,-1,-1,(Draw_tPixMap *)(&gPixmaps + iVar6 * 0x10));
  pDGp00000ca8 = (Draw_tPixMap *)(&gPixmaps + iVar6 * 0x10);
  Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
            (__format,"SMX1",0x40,0,0xa0,-1,-1,(Draw_tPixMap *)(&gPixmaps + (iVar6 + 1) * 0x10));
  pDGp00000cac = (Draw_tPixMap *)(&gPixmaps + (iVar6 + 1) * 0x10);
  Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
            (__format,"SMOK",0,-1,-1,-1,-1,(Draw_tPixMap *)(&gPixmaps + (iVar6 + 2) * 0x10));
  pDGp00000cb0 = (Draw_tPixMap *)(&gPixmaps + (iVar6 + 2) * 0x10);
  Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
            (__format,"DIRT",0,-1,-1,-1,-1,(Draw_tPixMap *)(&gPixmaps + (iVar6 + 3) * 0x10));
  pDGp00000cb4 = (Draw_tPixMap *)(&gPixmaps + (iVar6 + 3) * 0x10);
  Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
            (__format,"GRX0",0x40,0,0xa0,-1,-1,(Draw_tPixMap *)(&gPixmaps + (iVar6 + 4) * 0x10));
  pDGp00000cb8 = (Draw_tPixMap *)(&gPixmaps + (iVar6 + 4) * 0x10);
  Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
            (__format,"GRX1",0x40,0,0xa0,-1,-1,(Draw_tPixMap *)(&gPixmaps + (iVar6 + 5) * 0x10));
  pDGp00000cbc = (Draw_tPixMap *)(&gPixmaps + (iVar6 + 5) * 0x10);
  Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
            (__format,"GRAV",0,-1,-1,-1,-1,(Draw_tPixMap *)(&gPixmaps + (iVar6 + 6) * 0x10));
  pDGp00000cc0 = (Draw_tPixMap *)(&gPixmaps + (iVar6 + 6) * 0x10);
  Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
            (__format,"GRAS",0,-1,-1,-1,-1,(Draw_tPixMap *)(&gPixmaps + (iVar6 + 7) * 0x10));
  iVar2 = iVar6 + 9;
  pDGp00000cc4 = (Draw_tPixMap *)(&gPixmaps + (iVar6 + 7) * 0x10);
  Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
            (__format,"SNOW",0,-1,-1,-1,-1,(Draw_tPixMap *)(&gPixmaps + (iVar6 + 8) * 0x10));
  iVar7 = 0;
  ppDVar4 = (Draw_tPixMap **)&_gSparkHPixmap;
  pDGp00000cc8 = (Draw_tPixMap *)(&gPixmaps + (iVar6 + 8) * 0x10);
  while (iVar7 < 6) {
    sprintf(acStack304,"SHX%d",iVar7);
    iVar6 = iVar2 * 0x10;
    iVar2 = iVar2 + 1;
    Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
              (__format,acStack304,0x40,0,0xa0,-1,-1,(Draw_tPixMap *)(&gPixmaps + iVar6));
    *ppDVar4 = (Draw_tPixMap *)(&gPixmaps + iVar6);
    ppDVar4 = ppDVar4 + 1;
    iVar7 = iVar7 + 1;
  }
  if ((DAT_80113240 == 0) && (DAT_801131f8 != 1)) {
    sprintf(acStack48,"LF%02d",0);
    n = (char *)locateshapez(__format,acStack48);
    iVar7 = iVar2 * 0x10;
    if (n != (char *)0x0) {
      iVar2 = iVar2 + 1;
      Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
                ((char *)0x0,n,0x40,0,0xa0,-1,-1,(Draw_tPixMap *)(&gPixmaps + iVar7));
      pDGp00000ccc = (Draw_tPixMap *)(&gPixmaps + iVar7);
      goto LAB_8009baf0;
    }
  }
  pDGp00000ccc = (Draw_tPixMap *)0x0;
LAB_8009baf0:
  pmx = (Draw_tPixMap *)(&gPixmaps + iVar2 * 0x10);
  Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap(__format,"DAMG",0x40,0,0xa0,-1,-1,pmx);
  iVar7 = iVar2 + 1;
  if (DAT_80113234 == 0) {
    iVar6 = iVar7 * 0x10;
    pDGp00000cd0 = pmx;
    if (false) {
      iVar7 = iVar2 + 2;
      pDGp00000cd0 = pmx;
      Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
                (__format,"MONF",0x40,0,0xa0,-1,-1,(Draw_tPixMap *)(&gPixmaps + iVar6));
      _gFlarePixmap = (Draw_tPixMap *)(&gPixmaps + iVar6);
    }
    if (false) {
      Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
                (__format,"FLR0",0x40,0,0xa0,-1,-1,(Draw_tPixMap *)(&gPixmaps + iVar7 * 0x10));
      _gFlarePixmap = (Draw_tPixMap *)(&gPixmaps + iVar7 * 0x10);
      Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
                (__format,"FLR1",0x40,0,0xa0,-1,-1,(Draw_tPixMap *)(&gPixmaps + (iVar7 + 1) * 0x10))
      ;
      DAT_80112b8c = (Draw_tPixMap *)(&gPixmaps + (iVar7 + 1) * 0x10);
      Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
                (__format,"RBOW",0x40,0,0xa0,-1,-1,(Draw_tPixMap *)(&gPixmaps + (iVar7 + 2) * 0x10))
      ;
      DAT_80112b90 = (Draw_tPixMap *)(&gPixmaps + (iVar7 + 2) * 0x10);
      ChangeTPage__FPUsi(&_gFlarePixmap->tpage,1);
      ChangeTPage__FPUsi(&DAT_80112b8c->tpage,1);
      ChangeTPage__FPUsi(&DAT_80112b90->tpage,1);
    }
  }
  else {
    iVar6 = 0;
    ppDVar4 = (Draw_tPixMap **)&_gLightningPixmap;
    iVar2 = 0x20;
    bVar1 = true;
    pDGp00000cd0 = pmx;
    while (bVar1) {
      sprintf(acStack304,"LNG%d",iVar6);
      iVar3 = iVar7 * 0x10;
      iVar8 = iVar7 + 1;
      Texture_LoadPmx__FPcT0iiiiiP12Draw_tPixMap
                (__format,acStack304,0x40,0,0xa0,-1,-1,(Draw_tPixMap *)(&gPixmaps + iVar3));
      iVar7 = iVar7 + 2;
      ppDVar5 = (Draw_tPixMap **)((int)&_gLightningPixmap + iVar2);
      iVar2 = iVar2 + 4;
      *ppDVar4 = (Draw_tPixMap *)(&gPixmaps + iVar3);
      *ppDVar5 = (Draw_tPixMap *)(&gPixmaps + iVar8 * 0x10);
      iVar6 = iVar6 + 1;
      ChangeTPage__FPUsi(&(*ppDVar4)->tpage,1);
      pmx = *ppDVar4;
      ppDVar4 = ppDVar4 + 1;
      Texture_CloneUVPmx__FP12Draw_tPixMapiT0(pmx,0,*ppDVar5);
      bVar1 = iVar6 < 8;
    }
  }
  purgememadr(__format);
  return;


}





