#include "THISDUST.H"
#include "MINFRONT.H"


// decompiled code
// original method signature: 
// int * /*$ra*/ MinFront_ParseOptions__Fv()
 // line 781, offset 0x800128f0
	/* begin block 1 */
		// Start line: 782
		// Start offset: 0x800128F0
		// Variables:
	// 		int *stream; // $s0
	/* end block 1 */
	// End offset: 0x800128F0
	// End Line: 782

	/* begin block 2 */
		// Start line: 1562
	/* end block 2 */
	// End Line: 1563

	/* begin block 3 */
		// Start line: 1562
	/* end block 3 */
	// End Line: 1563

/* WARNING: Unknown calling convention yet parameter storage is locked */

int * MinFront_ParseOptions__Fv(void)

{
  int *piVar1;
  
  piVar1 = (int *)reservememadr(s_FE_Data_Stream_8001000c,0x2000,0x10);
  *piVar1 = 0;
  resizememadr((int)piVar1,4);
  return piVar1;
}





