#include "NFS4.H"
#include "MINFRONT.H"

// decompiled code
// original method signature: 
// int * /*$ra*/ MinFront_ParseOptions__Fv()
 // line 781, offset 0x800128f0
	/* begin block 1 */
		// Start line: 782
		// Start offset: 0x800128F0
		// Variables:
	// 		int *stream; // $s0
	/* end block 1 */
	// End offset: 0x800128F0
	// End Line: 782

int * MinFront_ParseOptions__Fv(void)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}





