#ifndef NFS3_H
#define NFS3_H


extern void Nfs2_SystemNLibStartUp__Fv(); // 0x800A3DEC

extern void Nfs2_BefuddleCode__Fv(); // 0x800A3E50

extern void Nfs2_ResetGame__Fv(); // 0x800A3EA8

extern void NFS4_LoadPerps__Fv(); // 0x800A3F08

extern void Nfs2_GameModuleStartUp__FPi(int *FrontEndDataStream); // 0x800A41A8

extern void Nfs2_CleanUpGameModule__Fv(); // 0x800A4354

extern void LoadFrontendOverlay__Fv(); // 0x800A44F8

extern void LoadOverlay__Fv(); // 0x800A454C

extern void NFS4_LoadingIcon__Fv(); // 0x800A45B8

extern void NFS3_CheckForFileOperations__Fv(); // 0x800A46DC

extern int main(); // 0x800A4730


#endif
