#include "NFS4.H"
#include "FEDIALOG.H"

// decompiled code
// original method signature: 
// short /*$ra*/ ShouldTimeOut__11tDialogBase(struct tDialogBase *this /*$a0*/)
 // line 73, offset 0x800186c8
	/* begin block 1 */
		// Start line: 74
		// Start offset: 0x800186C8

		/* begin block 1.1 */
			// Start line: 75
			// Start offset: 0x800186C8

			/* begin block 1.1.1 */
				// Start line: 75
				// Start offset: 0x800186D8

				/* begin block 1.1.1.1 */
					// Start line: 75
					// Start offset: 0x800186D8
				/* end block 1.1.1.1 */
				// End offset: 0x800186D8
				// End Line: 75
			/* end block 1.1.1 */
			// End offset: 0x800186D8
			// End Line: 75
		/* end block 1.1 */
		// End offset: 0x800186F8
		// End Line: 77
	/* end block 1 */
	// End offset: 0x800186F8
	// End Line: 77

/* WARNING: Control flow encountered bad instruction data */

short ShouldTimeOut__11tDialogBase(tDialogBase *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ InitializeClass__11tDialogBase()
 // line 83, offset 0x80018700
	/* begin block 1 */
		// Start line: 84
		// Start offset: 0x80018700
	/* end block 1 */
	// End offset: 0x80018700
	// End Line: 84

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void InitializeClass__11tDialogBase(void)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ DrawAllDialogs__11tDialogBase()
 // line 90, offset 0x80018720
	/* begin block 1 */
		// Start line: 91
		// Start offset: 0x80018720

		/* begin block 1.1 */
			// Start line: 91
			// Start offset: 0x80018720
			// Variables:
		// 		short i; // $s1
		/* end block 1.1 */
		// End offset: 0x800187D8
		// End Line: 102
	/* end block 1 */
	// End offset: 0x800187D8
	// End Line: 102

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void DrawAllDialogs__11tDialogBase(void)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ HideAllDialogs__11tDialogBase()
 // line 107, offset 0x800187f0
	/* begin block 1 */
		// Start line: 108
		// Start offset: 0x800187F0

		/* begin block 1.1 */
			// Start line: 109
			// Start offset: 0x800187F0
			// Variables:
		// 		short i; // $v1
		/* end block 1.1 */
		// End offset: 0x80018828
		// End Line: 112
	/* end block 1 */
	// End offset: 0x80018828
	// End Line: 112

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void HideAllDialogs__11tDialogBase(void)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// struct tDialogBase * /*$ra*/ GetTopMostDialog__11tDialogBase()
 // line 117, offset 0x80018830
	/* begin block 1 */
		// Start line: 118
		// Start offset: 0x80018830
	/* end block 1 */
	// End offset: 0x80018830
	// End Line: 121

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

tDialogBase * GetTopMostDialog__11tDialogBase(void)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Display__11tDialogBase(struct tDialogBase *this /*$s1*/)
 // line 126, offset 0x80018840
	/* begin block 1 */
		// Start line: 127
		// Start offset: 0x80018840

		/* begin block 1.1 */
			// Start line: 129
			// Start offset: 0x80018864
			// Variables:
		// 		short i; // $a1
		/* end block 1.1 */
		// End offset: 0x800188B4
		// End Line: 144

		/* begin block 1.2 */
			// Start line: 147
			// Start offset: 0x800188B4

			/* begin block 1.2.1 */
				// Start line: 147
				// Start offset: 0x800188B4
			/* end block 1.2.1 */
			// End offset: 0x800188B4
			// End Line: 147
		/* end block 1.2 */
		// End offset: 0x800188B4
		// End Line: 147
	/* end block 1 */
	// End offset: 0x800188F0
	// End Line: 154

/* WARNING: Control flow encountered bad instruction data */

void Display__11tDialogBase(tDialogBase *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Hide__11tDialogBase(struct tDialogBase *this /*$s2*/)
 // line 159, offset 0x80018904
	/* begin block 1 */
		// Start line: 160
		// Start offset: 0x80018904

		/* begin block 1.1 */
			// Start line: 162
			// Start offset: 0x8001892C
			// Variables:
		// 		short i; // $s0
		/* end block 1.1 */
		// End offset: 0x800189A0
		// End Line: 181
	/* end block 1 */
	// End offset: 0x800189A0
	// End Line: 181

/* WARNING: Control flow encountered bad instruction data */

void Hide__11tDialogBase(tDialogBase *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Draw__11tDialogBase(struct tDialogBase *this /*$s0*/)
 // line 200, offset 0x800189b8
	/* begin block 1 */
		// Start line: 201
		// Start offset: 0x800189B8
	/* end block 1 */
	// End offset: 0x800189B8
	// End Line: 201

/* WARNING: Control flow encountered bad instruction data */

void Draw__11tDialogBase(tDialogBase *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ ProcessInput__11tDialogBase7tPlayerR13tInputKeyTypeR12tMenuCommand(struct tDialogBase *this /*$a0*/, enum tInputKeyType *keyval /*$s1*/)
 // line 217, offset 0x80018ac8
	/* begin block 1 */
		// Start line: 218
		// Start offset: 0x80018AC8
	/* end block 1 */
	// End offset: 0x80018AF8
	// End Line: 246

/* WARNING: Control flow encountered bad instruction data */

void ProcessInput__11tDialogBase7tPlayerR13tInputKeyTypeR12tMenuCommand
               (tDialogBase *this,tInputKeyType *keyval)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ AddItem__11tDialogHelpss(struct tDialogHelp *this /*$s0*/, short textID /*$a1*/, short controllerID /*$a2*/)
 // line 260, offset 0x80018b0c
	/* begin block 1 */
		// Start line: 261
		// Start offset: 0x80018B0C
	/* end block 1 */
	// End offset: 0x80018B7C
	// End Line: 266

/* WARNING: Control flow encountered bad instruction data */

void AddItem__11tDialogHelpss(tDialogHelp *this,short textID,short controllerID)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ CalculateDimensions__11tDialogHelp(struct tDialogHelp *this /*$s3*/)
 // line 286, offset 0x80018b90
	/* begin block 1 */
		// Start line: 287
		// Start offset: 0x80018B90
		// Variables:
	// 		struct tHelpData helpArray[1]; // stack offset -56
	// 		short i; // $s1
	// 		int newWidth; // $v0
	// 		enum tPlayer player; // $s5

		/* begin block 1.1 */
			// Start line: 322
			// Start offset: 0x80018C38

			/* begin block 1.1.1 */
				// Start line: 323
				// Start offset: 0x80018C60
				// Variables:
			// 		void * showLeftRight; // $s2
			// 		void * showCross; // $s4
			// 		struct tMenu *menu; // $s0

				/* begin block 1.1.1.1 */
					// Start line: 324
					// Start offset: 0x80018C60
					// Variables:
				// 		struct tFEApplication *this; // $v0
				// 		enum tPlayer player; // $s5

					/* begin block 1.1.1.1.1 */
						// Start line: 324
						// Start offset: 0x80018C60
					/* end block 1.1.1.1.1 */
					// End offset: 0x80018C60
					// End Line: 324
				/* end block 1.1.1.1 */
				// End offset: 0x80018C60
				// End Line: 324

				/* begin block 1.1.1.2 */
					// Start line: 331
					// Start offset: 0x80018C80

					/* begin block 1.1.1.2.1 */
						// Start line: 331
						// Start offset: 0x80018C80
						// Variables:
					// 		enum tPlayer player; // $s5

						/* begin block 1.1.1.2.1.1 */
							// Start line: 331
							// Start offset: 0x80018C80
						/* end block 1.1.1.2.1.1 */
						// End offset: 0x80018C80
						// End Line: 331
					/* end block 1.1.1.2.1 */
					// End offset: 0x80018C80
					// End Line: 331

					/* begin block 1.1.1.2.2 */
						// Start line: 331
						// Start offset: 0x80018C80

						/* begin block 1.1.1.2.2.1 */
							// Start line: 331
							// Start offset: 0x80018C80
						/* end block 1.1.1.2.2.1 */
						// End offset: 0x80018C80
						// End Line: 331
					/* end block 1.1.1.2.2 */
					// End offset: 0x80018C80
					// End Line: 331

					/* begin block 1.1.1.2.3 */
						// Start line: 333
						// Start offset: 0x80018C9C

						/* begin block 1.1.1.2.3.1 */
							// Start line: 333
							// Start offset: 0x80018C9C

							/* begin block 1.1.1.2.3.1.1 */
								// Start line: 333
								// Start offset: 0x80018C9C
							/* end block 1.1.1.2.3.1.1 */
							// End offset: 0x80018C9C
							// End Line: 333
						/* end block 1.1.1.2.3.1 */
						// End offset: 0x80018C9C
						// End Line: 333

						/* begin block 1.1.1.2.3.2 */
							// Start line: 334
							// Start offset: 0x80018CB4

							/* begin block 1.1.1.2.3.2.1 */
								// Start line: 335
								// Start offset: 0x80018CB4

								/* begin block 1.1.1.2.3.2.1.1 */
									// Start line: 335
									// Start offset: 0x80018CB4

									/* begin block 1.1.1.2.3.2.1.1.1 */
										// Start line: 335
										// Start offset: 0x80018CB4
									/* end block 1.1.1.2.3.2.1.1.1 */
									// End offset: 0x80018CB4
									// End Line: 335
								/* end block 1.1.1.2.3.2.1.1 */
								// End offset: 0x80018CB4
								// End Line: 335
							/* end block 1.1.1.2.3.2.1 */
							// End offset: 0x80018CC8
							// End Line: 338
						/* end block 1.1.1.2.3.2 */
						// End offset: 0x80018CC8
						// End Line: 338
					/* end block 1.1.1.2.3 */
					// End offset: 0x80018CC8
					// End Line: 338
				/* end block 1.1.1.2 */
				// End offset: 0x80018CC8
				// End Line: 340

				/* begin block 1.1.1.3 */
					// Start line: 347
					// Start offset: 0x80018D0C

					/* begin block 1.1.1.3.1 */
						// Start line: 348
						// Start offset: 0x80018D14

						/* begin block 1.1.1.3.1.1 */
							// Start line: 349
							// Start offset: 0x80018D14

							/* begin block 1.1.1.3.1.1.1 */
								// Start line: 349
								// Start offset: 0x80018D14
								// Variables:
							// 		struct tMenu *this; // $s0

								/* begin block 1.1.1.3.1.1.1.1 */
									// Start line: 349
									// Start offset: 0x80018D14
								/* end block 1.1.1.3.1.1.1.1 */
								// End offset: 0x80018D14
								// End Line: 349
							/* end block 1.1.1.3.1.1.1 */
							// End offset: 0x80018D14
							// End Line: 349

							/* begin block 1.1.1.3.1.1.2 */
								// Start line: 349
								// Start offset: 0x80018D28
								// Variables:
							// 		struct tMenu *this; // $s0

								/* begin block 1.1.1.3.1.1.2.1 */
									// Start line: 349
									// Start offset: 0x80018D28
								/* end block 1.1.1.3.1.1.2.1 */
								// End offset: 0x80018D28
								// End Line: 349
							/* end block 1.1.1.3.1.1.2 */
							// End offset: 0x80018D28
							// End Line: 349
						/* end block 1.1.1.3.1.1 */
						// End offset: 0x80018D58
						// End Line: 352
					/* end block 1.1.1.3.1 */
					// End offset: 0x80018D58
					// End Line: 352
				/* end block 1.1.1.3 */
				// End offset: 0x80018D58
				// End Line: 352

				/* begin block 1.1.1.4 */
					// Start line: 355
					// Start offset: 0x80018D58

					/* begin block 1.1.1.4.1 */
						// Start line: 355
						// Start offset: 0x80018D58
						// Variables:
					// 		struct tFEApplication *this; // $v0
					// 		enum tPlayer player; // $s5

						/* begin block 1.1.1.4.1.1 */
							// Start line: 355
							// Start offset: 0x80018D58
						/* end block 1.1.1.4.1.1 */
						// End offset: 0x80018D58
						// End Line: 355
					/* end block 1.1.1.4.1 */
					// End offset: 0x80018D58
					// End Line: 355
				/* end block 1.1.1.4 */
				// End offset: 0x80018D84
				// End Line: 356

				/* begin block 1.1.1.5 */
					// Start line: 357
					// Start offset: 0x80018D84

					/* begin block 1.1.1.5.1 */
						// Start line: 357
						// Start offset: 0x80018D84
						// Variables:
					// 		struct tMenu *this; // $s0

						/* begin block 1.1.1.5.1.1 */
							// Start line: 357
							// Start offset: 0x80018D84
						/* end block 1.1.1.5.1.1 */
						// End offset: 0x80018D84
						// End Line: 357
					/* end block 1.1.1.5.1 */
					// End offset: 0x80018D84
					// End Line: 357
				/* end block 1.1.1.5 */
				// End offset: 0x80018DA0
				// End Line: 358

				/* begin block 1.1.1.6 */
					// Start line: 360
					// Start offset: 0x80018DA0

					/* begin block 1.1.1.6.1 */
						// Start line: 360
						// Start offset: 0x80018DA0
						// Variables:
					// 		struct tMenu *this; // $s0

						/* begin block 1.1.1.6.1.1 */
							// Start line: 360
							// Start offset: 0x80018DA0
						/* end block 1.1.1.6.1.1 */
						// End offset: 0x80018DA0
						// End Line: 360
					/* end block 1.1.1.6.1 */
					// End offset: 0x80018DA0
					// End Line: 360

					/* begin block 1.1.1.6.2 */
						// Start line: 363
						// Start offset: 0x80018DBC

						/* begin block 1.1.1.6.2.1 */
							// Start line: 363
							// Start offset: 0x80018DBC

							/* begin block 1.1.1.6.2.1.1 */
								// Start line: 363
								// Start offset: 0x80018DBC
								// Variables:
							// 		struct tMenu *this; // $s0

								/* begin block 1.1.1.6.2.1.1.1 */
									// Start line: 363
									// Start offset: 0x80018DBC
								/* end block 1.1.1.6.2.1.1.1 */
								// End offset: 0x80018DEC
								// End Line: 363
							/* end block 1.1.1.6.2.1.1 */
							// End offset: 0x80018DEC
							// End Line: 363

							/* begin block 1.1.1.6.2.1.2 */
								// Start line: 366
								// Start offset: 0x80018DF4

								/* begin block 1.1.1.6.2.1.2.1 */
									// Start line: 366
									// Start offset: 0x80018DF4

									/* begin block 1.1.1.6.2.1.2.1.1 */
										// Start line: 366
										// Start offset: 0x80018DF4
										// Variables:
									// 		struct tMenu *this; // $s0

										/* begin block 1.1.1.6.2.1.2.1.1.1 */
											// Start line: 366
											// Start offset: 0x80018DF4
										/* end block 1.1.1.6.2.1.2.1.1.1 */
										// End offset: 0x80018DF4
										// End Line: 366
									/* end block 1.1.1.6.2.1.2.1.1 */
									// End offset: 0x80018DF4
									// End Line: 366
								/* end block 1.1.1.6.2.1.2.1 */
								// End offset: 0x80018E14
								// End Line: 367
							/* end block 1.1.1.6.2.1.2 */
							// End offset: 0x80018E14
							// End Line: 367
						/* end block 1.1.1.6.2.1 */
						// End offset: 0x80018E14
						// End Line: 367
					/* end block 1.1.1.6.2 */
					// End offset: 0x80018E14
					// End Line: 367
				/* end block 1.1.1.6 */
				// End offset: 0x80018E14
				// End Line: 367
			/* end block 1.1.1 */
			// End offset: 0x80018E14
			// End Line: 367
		/* end block 1.1 */
		// End offset: 0x80018E14
		// End Line: 367

		/* begin block 1.2 */
			// Start line: 426
			// Start offset: 0x80019034

			/* begin block 1.2.1 */
				// Start line: 426
				// Start offset: 0x80019034
			/* end block 1.2.1 */
			// End offset: 0x80019034
			// End Line: 426
		/* end block 1.2 */
		// End offset: 0x80019034
		// End Line: 426

		/* begin block 1.3 */
			// Start line: 426
			// Start offset: 0x80019034

			/* begin block 1.3.1 */
				// Start line: 432
				// Start offset: 0x80019068
			/* end block 1.3.1 */
			// End offset: 0x800190F0
			// End Line: 437
		/* end block 1.3 */
		// End offset: 0x800190F0
		// End Line: 437
	/* end block 1 */
	// End offset: 0x800190F0
	// End Line: 452

/* WARNING: Control flow encountered bad instruction data */

void CalculateDimensions__11tDialogHelp(tDialogHelp *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Draw__11tDialogHelp(struct tDialogHelp *this /*$s2*/)
 // line 459, offset 0x8001912c
	/* begin block 1 */
		// Start line: 460
		// Start offset: 0x8001912C
		// Variables:
	// 		short i; // $s3
	// 		short j; // $a1
	// 		char buffer[80]; // stack offset -112
	// 		short y; // $s4
	// 		long ticks; // $a0
	// 		int numLetters; // $s5

		/* begin block 1.1 */
			// Start line: 460
			// Start offset: 0x8001912C

			/* begin block 1.1.1 */
				// Start line: 460
				// Start offset: 0x8001912C
			/* end block 1.1.1 */
			// End offset: 0x8001912C
			// End Line: 460
		/* end block 1.1 */
		// End offset: 0x8001912C
		// End Line: 460

		/* begin block 1.2 */
			// Start line: 488
			// Start offset: 0x80019190

			/* begin block 1.2.1 */
				// Start line: 493
				// Start offset: 0x800191B4

				/* begin block 1.2.1.1 */
					// Start line: 501
					// Start offset: 0x800191F4

					/* begin block 1.2.1.1.1 */
						// Start line: 502
						// Start offset: 0x80019204
						// Variables:
					// 		int control; // $a1
					/* end block 1.2.1.1.1 */
					// End offset: 0x800192EC
					// End Line: 522
				/* end block 1.2.1.1 */
				// End offset: 0x800192EC
				// End Line: 522
			/* end block 1.2.1 */
			// End offset: 0x800193E0
			// End Line: 541
		/* end block 1.2 */
		// End offset: 0x800193E8
		// End Line: 543
	/* end block 1 */
	// End offset: 0x800193F0
	// End Line: 546

/* WARNING: Control flow encountered bad instruction data */

void Draw__11tDialogHelp(tDialogHelp *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ CalculateDimensions__20tDialogMessageString(struct tDialogMessageString *this /*$s0*/)
 // line 551, offset 0x80019418
	/* begin block 1 */
		// Start line: 552
		// Start offset: 0x80019418
		// Variables:
	// 		int ticks; // $t0

		/* begin block 1.1 */
			// Start line: 552
			// Start offset: 0x80019418

			/* begin block 1.1.1 */
				// Start line: 552
				// Start offset: 0x80019418
			/* end block 1.1.1 */
			// End offset: 0x80019418
			// End Line: 552
		/* end block 1.1 */
		// End offset: 0x80019418
		// End Line: 552

		/* begin block 1.2 */
			// Start line: 581
			// Start offset: 0x80019500

			/* begin block 1.2.1 */
				// Start line: 581
				// Start offset: 0x80019500
			/* end block 1.2.1 */
			// End offset: 0x80019500
			// End Line: 581
		/* end block 1.2 */
		// End offset: 0x80019500
		// End Line: 581

		/* begin block 1.3 */
			// Start line: 581
			// Start offset: 0x80019500

			/* begin block 1.3.1 */
				// Start line: 587
				// Start offset: 0x80019520
			/* end block 1.3.1 */
			// End offset: 0x80019520
			// End Line: 588
		/* end block 1.3 */
		// End offset: 0x800195CC
		// End Line: 597
	/* end block 1 */
	// End offset: 0x800195CC
	// End Line: 600

/* WARNING: Control flow encountered bad instruction data */

void CalculateDimensions__20tDialogMessageString(tDialogMessageString *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Draw__20tDialogMessageString(struct tDialogMessageString *this /*$s0*/)
 // line 607, offset 0x8001962c
	/* begin block 1 */
		// Start line: 608
		// Start offset: 0x8001962C
		// Variables:
	// 		int col; // $s1
	// 		struct RECT r; // stack offset -24

		/* begin block 1.1 */
			// Start line: 608
			// Start offset: 0x8001962C

			/* begin block 1.1.1 */
				// Start line: 608
				// Start offset: 0x8001962C
			/* end block 1.1.1 */
			// End offset: 0x8001962C
			// End Line: 608
		/* end block 1.1 */
		// End offset: 0x8001962C
		// End Line: 608

		/* begin block 1.2 */
			// Start line: 629
			// Start offset: 0x80019694

			/* begin block 1.2.1 */
				// Start line: 629
				// Start offset: 0x80019694
			/* end block 1.2.1 */
			// End offset: 0x80019694
			// End Line: 629
		/* end block 1.2 */
		// End offset: 0x80019694
		// End Line: 629
	/* end block 1 */
	// End offset: 0x8001977C
	// End Line: 651

/* WARNING: Control flow encountered bad instruction data */

void Draw__20tDialogMessageString(tDialogMessageString *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ ProcessInput__17tDialogBackUpOnly7tPlayerR13tInputKeyTypeR12tMenuCommand(struct tDialogBackUpOnly *this /*$a0*/, enum tPlayer fromPlayer /*$a1*/, enum tInputKeyType *keyval /*$a2*/)
 // line 654, offset 0x80019790
	/* begin block 1 */
		// Start line: 655
		// Start offset: 0x80019790
	/* end block 1 */
	// End offset: 0x800197D8
	// End Line: 669

/* WARNING: Control flow encountered bad instruction data */

void ProcessInput__17tDialogBackUpOnly7tPlayerR13tInputKeyTypeR12tMenuCommand
               (tDialogBackUpOnly *this,tPlayer fromPlayer,tInputKeyType *keyval)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// short /*$ra*/ Run__18tDialogInteractive(struct tDialogInteractive *this /*$s3*/)
 // line 684, offset 0x800197e8
	/* begin block 1 */
		// Start line: 685
		// Start offset: 0x800197E8

		/* begin block 1.1 */
			// Start line: 691
			// Start offset: 0x80019848
			// Variables:
		// 		enum tInputKeyType keyVal[2]; // stack offset -56
		// 		struct tMenuCommand command; // stack offset -48
		// 		unsigned long debounce; // $s6

			/* begin block 1.1.1 */
				// Start line: 695
				// Start offset: 0x80019858
				// Variables:
			// 		int i; // $s1

				/* begin block 1.1.1.1 */
					// Start line: 708
					// Start offset: 0x80019868

					/* begin block 1.1.1.1.1 */
						// Start line: 714
						// Start offset: 0x80019888

						/* begin block 1.1.1.1.1.1 */
							// Start line: 715
							// Start offset: 0x80019898

							/* begin block 1.1.1.1.1.1.1 */
								// Start line: 716
								// Start offset: 0x80019898

								/* begin block 1.1.1.1.1.1.1.1 */
									// Start line: 716
									// Start offset: 0x80019898

									/* begin block 1.1.1.1.1.1.1.1.1 */
										// Start line: 716
										// Start offset: 0x80019898
									/* end block 1.1.1.1.1.1.1.1.1 */
									// End offset: 0x80019898
									// End Line: 716
								/* end block 1.1.1.1.1.1.1.1 */
								// End offset: 0x80019898
								// End Line: 716

								/* begin block 1.1.1.1.1.1.1.2 */
									// Start line: 716
									// Start offset: 0x800198B0
									// Variables:
								// 		enum tPlayer player; // $s1

									/* begin block 1.1.1.1.1.1.1.2.1 */
										// Start line: 716
										// Start offset: 0x800198B0
									/* end block 1.1.1.1.1.1.1.2.1 */
									// End offset: 0x800198B0
									// End Line: 716
								/* end block 1.1.1.1.1.1.1.2 */
								// End offset: 0x800198B0
								// End Line: 716

								/* begin block 1.1.1.1.1.1.1.3 */
									// Start line: 717
									// Start offset: 0x800198C8

									/* begin block 1.1.1.1.1.1.1.3.1 */
										// Start line: 717
										// Start offset: 0x800198C8
										// Variables:
									// 		enum tPlayer player; // $s1

										/* begin block 1.1.1.1.1.1.1.3.1.1 */
											// Start line: 717
											// Start offset: 0x800198C8
										/* end block 1.1.1.1.1.1.1.3.1.1 */
										// End offset: 0x800198C8
										// End Line: 717
									/* end block 1.1.1.1.1.1.1.3.1 */
									// End offset: 0x800198C8
									// End Line: 717
								/* end block 1.1.1.1.1.1.1.3 */
								// End offset: 0x800198F4
								// End Line: 719
							/* end block 1.1.1.1.1.1.1 */
							// End offset: 0x800198F4
							// End Line: 719
						/* end block 1.1.1.1.1.1 */
						// End offset: 0x800198F4
						// End Line: 719
					/* end block 1.1.1.1.1 */
					// End offset: 0x800198F4
					// End Line: 719

					/* begin block 1.1.1.1.2 */
						// Start line: 723
						// Start offset: 0x800198F4

						/* begin block 1.1.1.1.2.1 */
							// Start line: 724
							// Start offset: 0x80019904

							/* begin block 1.1.1.1.2.1.1 */
								// Start line: 725
								// Start offset: 0x80019904

								/* begin block 1.1.1.1.2.1.1.1 */
									// Start line: 725
									// Start offset: 0x80019904
									// Variables:
								// 		struct tDialogBase *this; // $a0

									/* begin block 1.1.1.1.2.1.1.1.1 */
										// Start line: 725
										// Start offset: 0x80019904
									/* end block 1.1.1.1.2.1.1.1.1 */
									// End offset: 0x80019904
									// End Line: 725
								/* end block 1.1.1.1.2.1.1.1 */
								// End offset: 0x80019904
								// End Line: 725
							/* end block 1.1.1.1.2.1.1 */
							// End offset: 0x8001992C
							// End Line: 728
						/* end block 1.1.1.1.2.1 */
						// End offset: 0x8001992C
						// End Line: 728
					/* end block 1.1.1.1.2 */
					// End offset: 0x8001992C
					// End Line: 728
				/* end block 1.1.1.1 */
				// End offset: 0x8001995C
				// End Line: 733
			/* end block 1.1.1 */
			// End offset: 0x8001996C
			// End Line: 734
		/* end block 1.1 */
		// End offset: 0x8001996C
		// End Line: 735
	/* end block 1 */
	// End offset: 0x80019980
	// End Line: 737

/* WARNING: Control flow encountered bad instruction data */

short Run__18tDialogInteractive(tDialogInteractive *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ CalculateDimensions__12tDialogYesNo(struct tDialogYesNo *this /*$s0*/)
 // line 748, offset 0x800199d4
	/* begin block 1 */
		// Start line: 749
		// Start offset: 0x800199D4

		/* begin block 1.1 */
			// Start line: 749
			// Start offset: 0x800199D4

			/* begin block 1.1.1 */
				// Start line: 752
				// Start offset: 0x800199F8

				/* begin block 1.1.1.1 */
					// Start line: 752
					// Start offset: 0x800199F8

					/* begin block 1.1.1.1.1 */
						// Start line: 752
						// Start offset: 0x800199F8
					/* end block 1.1.1.1.1 */
					// End offset: 0x800199F8
					// End Line: 752
				/* end block 1.1.1.1 */
				// End offset: 0x800199F8
				// End Line: 752
			/* end block 1.1.1 */
			// End offset: 0x80019A7C
			// End Line: 760
		/* end block 1.1 */
		// End offset: 0x80019A7C
		// End Line: 760
	/* end block 1 */
	// End offset: 0x80019A7C
	// End Line: 760

/* WARNING: Control flow encountered bad instruction data */

void CalculateDimensions__12tDialogYesNo(tDialogYesNo *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// struct tDialogYesNo * /*$ra*/ __12tDialogYesNo(struct tDialogYesNo *this /*$s0*/)
 // line 765, offset 0x80019a8c
	/* begin block 1 */
		// Start line: 766
		// Start offset: 0x80019A8C
		// Variables:
	// 		struct tDialogInteractive *this; // $s0

		/* begin block 1.1 */
			// Start line: 766
			// Start offset: 0x80019A8C
			// Variables:
		// 		struct tDialogMessageString *this; // $s0

			/* begin block 1.1.1 */
				// Start line: 766
				// Start offset: 0x80019A8C
				// Variables:
			// 		struct tDialogBase *this; // $s0

				/* begin block 1.1.1.1 */
					// Start line: 766
					// Start offset: 0x80019A8C
				/* end block 1.1.1.1 */
				// End offset: 0x80019A8C
				// End Line: 766
			/* end block 1.1.1 */
			// End offset: 0x80019A8C
			// End Line: 766

			/* begin block 1.1.2 */
				// Start line: 766
				// Start offset: 0x80019A8C
			/* end block 1.1.2 */
			// End offset: 0x80019A8C
			// End Line: 766
		/* end block 1.1 */
		// End offset: 0x80019A8C
		// End Line: 766

		/* begin block 1.2 */
			// Start line: 766
			// Start offset: 0x80019A8C
		/* end block 1.2 */
		// End offset: 0x80019A8C
		// End Line: 766
	/* end block 1 */
	// End offset: 0x80019A8C
	// End Line: 766

	/* begin block 2 */
		// Start line: 766
		// Start offset: 0x80019A8C
	/* end block 2 */
	// End offset: 0x80019A8C
	// End Line: 766

/* WARNING: Control flow encountered bad instruction data */

tDialogYesNo * __12tDialogYesNo(tDialogYesNo *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Draw__12tDialogYesNo(struct tDialogYesNo *this /*$s2*/)
 // line 773, offset 0x80019b44
	/* begin block 1 */
		// Start line: 774
		// Start offset: 0x80019B44
		// Variables:
	// 		int i; // $s3
	// 		int x; // $s4
	// 		int y; // $s0
	// 		int col; // $s1

		/* begin block 1.1 */
			// Start line: 783
			// Start offset: 0x80019BA0

			/* begin block 1.1.1 */
				// Start line: 783
				// Start offset: 0x80019BA0
			/* end block 1.1.1 */
			// End offset: 0x80019BA0
			// End Line: 783
		/* end block 1.1 */
		// End offset: 0x80019BA0
		// End Line: 783

		/* begin block 1.2 */
			// Start line: 783
			// Start offset: 0x80019BA0

			/* begin block 1.2.1 */
				// Start line: 788
				// Start offset: 0x80019BBC

				/* begin block 1.2.1.1 */
					// Start line: 789
					// Start offset: 0x80019BBC

					/* begin block 1.2.1.1.1 */
						// Start line: 798
						// Start offset: 0x80019BE4

						/* begin block 1.2.1.1.1.1 */
							// Start line: 800
							// Start offset: 0x80019C04

							/* begin block 1.2.1.1.1.1.1 */
								// Start line: 800
								// Start offset: 0x80019C04
							/* end block 1.2.1.1.1.1.1 */
							// End offset: 0x80019C04
							// End Line: 800
						/* end block 1.2.1.1.1.1 */
						// End offset: 0x80019C04
						// End Line: 800
					/* end block 1.2.1.1.1 */
					// End offset: 0x80019C04
					// End Line: 800
				/* end block 1.2.1.1 */
				// End offset: 0x80019C98
				// End Line: 813
			/* end block 1.2.1 */
			// End offset: 0x80019C98
			// End Line: 813
		/* end block 1.2 */
		// End offset: 0x80019C98
		// End Line: 813
	/* end block 1 */
	// End offset: 0x80019C98
	// End Line: 816

/* WARNING: Control flow encountered bad instruction data */

void Draw__12tDialogYesNo(tDialogYesNo *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ ProcessInput__12tDialogYesNo7tPlayerR13tInputKeyTypeR12tMenuCommand(struct tDialogYesNo *this /*$s0*/, enum tPlayer fromPlayer /*$a1*/, enum tInputKeyType *keyVal /*$a2*/, struct tMenuCommand *command /*$a3*/)
 // line 823, offset 0x80019ccc
	/* begin block 1 */
		// Start line: 824
		// Start offset: 0x80019CCC

		/* begin block 1.1 */
			// Start line: 828
			// Start offset: 0x80019CF4

			/* begin block 1.1.1 */
				// Start line: 828
				// Start offset: 0x80019CF4
				// Variables:
			// 		struct tDialogMessageString *this; // $s0

				/* begin block 1.1.1.1 */
					// Start line: 828
					// Start offset: 0x80019CF4
				/* end block 1.1.1.1 */
				// End offset: 0x80019CF4
				// End Line: 828
			/* end block 1.1.1 */
			// End offset: 0x80019CF4
			// End Line: 828
		/* end block 1.1 */
		// End offset: 0x80019D08
		// End Line: 829
	/* end block 1 */
	// End offset: 0x80019D88
	// End Line: 850

/* WARNING: Control flow encountered bad instruction data */

void ProcessInput__12tDialogYesNo7tPlayerR13tInputKeyTypeR12tMenuCommand
               (tDialogYesNo *this,tPlayer fromPlayer,tInputKeyType *keyVal,tMenuCommand *command)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ ProcessInput__15tDialogYesNoMem7tPlayerR13tInputKeyTypeR12tMenuCommand(struct tDialogYesNoMem *this /*$s2*/, enum tPlayer fromPlayer /*$s3*/, enum tInputKeyType *keyVal /*$s4*/, struct tMenuCommand *command /*$s5*/)
 // line 859, offset 0x80019d98
	/* begin block 1 */
		// Start line: 860
		// Start offset: 0x80019D98
		// Variables:
	// 		int card; // $s1
	// 		void * fMemCardGone; // $s0
	/* end block 1 */
	// End offset: 0x80019E58
	// End Line: 902

/* WARNING: Control flow encountered bad instruction data */

void ProcessInput__15tDialogYesNoMem7tPlayerR13tInputKeyTypeR12tMenuCommand
               (tDialogYesNoMem *this,tPlayer fromPlayer,tInputKeyType *keyVal,tMenuCommand *command
               )

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ ProcessInput__15tDialogYesNoTri7tPlayerR13tInputKeyTypeR12tMenuCommand(struct tDialogYesNoTri *this /*$a0*/, enum tPlayer fromPlayer /*$a1*/, enum tInputKeyType *keyVal /*$a2*/, struct tMenuCommand *command /*$a3*/)
 // line 909, offset 0x80019e7c
	/* begin block 1 */
		// Start line: 910
		// Start offset: 0x80019E7C
	/* end block 1 */
	// End offset: 0x80019EAC
	// End Line: 917

/* WARNING: Control flow encountered bad instruction data */

void ProcessInput__15tDialogYesNoTri7tPlayerR13tInputKeyTypeR12tMenuCommand
               (tDialogYesNoTri *this,tPlayer fromPlayer,tInputKeyType *keyVal,tMenuCommand *command
               )

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ ProcessInput__21tDialogNoInputMessage7tPlayerR13tInputKeyTypeR12tMenuCommand(struct tDialogNoInputMessage *this /*$a0*/)
 // line 921, offset 0x80019ebc
	/* begin block 1 */
		// Start line: 922
		// Start offset: 0x80019EBC
	/* end block 1 */
	// End offset: 0x80019EBC
	// End Line: 922

/* WARNING: Control flow encountered bad instruction data */

void ProcessInput__21tDialogNoInputMessage7tPlayerR13tInputKeyTypeR12tMenuCommand
               (tDialogNoInputMessage *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}




