#include "NFS4.H"
#include "FELINES.H"

// decompiled code
// original method signature: 
// void /*$ra*/ PSXDrawBrightEndLine__Fiiiiiiii(int col /*$a0*/, int x /*$a1*/, int y /*$a2*/, int w /*$a3*/, int h /*stack 16*/, int side /*stack 20*/, int fade /*stack 24*/, int darksides /*stack 28*/)
 // line 24, offset 0x8004bb38
	/* begin block 1 */
		// Start line: 25
		// Start offset: 0x8004BB38
	/* end block 1 */
	// End offset: 0x8004BB38
	// End Line: 25

void PSXDrawBrightEndLine__Fiiiiiiii( (int col,int x,int y,int w,int h,int side,int fade,int darksides)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ PSXTransDrawBrightEndLine__Fiiiiiiiii(int col /*$s3*/, int x /*$s2*/, int y /*$s4*/, int w /*$s5*/, int h /*stack 16*/, int side /*stack 20*/, int fade /*stack 24*/, int darksides /*stack 28*/, int opacity /*stack 32*/)
 // line 30, offset 0x8004bb78
	/* begin block 1 */
		// Start line: 31
		// Start offset: 0x8004BB78
		// Variables:
	// 		int ww; // $s1
	// 		int hh; // $s0
	// 		int BrightCol; // $v1
	// 		int endbit; // $a3
	/* end block 1 */
	// End offset: 0x8004BDCC
	// End Line: 115

void PSXTransDrawBrightEndLine__Fiiiiiiiii( (int col,int x,int y,int w,int h,int side,int fade,int darksides,int opacity)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}





