#include "NFS4.H"
#include "FEMENUOPTIONS.H"

// decompiled code
// original method signature: 
// void /*$ra*/ CalcPulsateYellow__Fv()
 // line 77, offset 0x8001bf48
	/* begin block 1 */
		// Start line: 78
		// Start offset: 0x8001BF48
		// Variables:
	// 		int pulsateval; // $a1

		/* begin block 1.1 */
			// Start line: 78
			// Start offset: 0x8001BF48

			/* begin block 1.1.1 */
				// Start line: 78
				// Start offset: 0x8001BF48
			/* end block 1.1.1 */
			// End offset: 0x8001BF48
			// End Line: 78
		/* end block 1.1 */
		// End offset: 0x8001BF48
		// End Line: 78
	/* end block 1 */
	// End offset: 0x8001BF84
	// End Line: 83

void CalcPulsateYellow__Fv(void)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ DrawLeftFlare__FiiiRi(int y /*$s4*/, int fSelFade /*$a1*/, int fFadeVal /*$a2*/, int *flareextra /*$a3*/)
 // line 86, offset 0x8001bfa0
	/* begin block 1 */
		// Start line: 87
		// Start offset: 0x8001BFA0
		// Variables:
	// 		int flare_intensity; // $s1
	// 		int glintFade; // $s3

		/* begin block 1.1 */
			// Start line: 101
			// Start offset: 0x8001C068

			/* begin block 1.1.1 */
				// Start line: 102
				// Start offset: 0x8001C070
				// Variables:
			// 		int x; // $s0
			/* end block 1.1.1 */
			// End offset: 0x8001C0DC
			// End Line: 109
		/* end block 1.1 */
		// End offset: 0x8001C0DC
		// End Line: 109
	/* end block 1 */
	// End offset: 0x8001C0DC
	// End Line: 109

void DrawLeftFlare__FiiiRi(int y,int fSelFade,int fFadeVal,int *flareextra)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ SubtractiveBox__Fiiiiiiii(int x /*$s1*/, int y /*$t4*/, int w /*$a2*/, int h /*$a3*/, int col1 /*stack 16*/, int col2 /*stack 20*/, int col3 /*stack 24*/, int col4 /*stack 28*/)
 // line 115, offset 0x8001c0fc
	/* begin block 1 */
		// Start line: 116
		// Start offset: 0x8001C0FC
		// Variables:
	// 		struct DR_MODE *dr_mode; // $s0
	// 		struct POLY_G4 *prim; // $t0
	/* end block 1 */
	// End offset: 0x8001C0FC
	// End Line: 116

void SubtractiveBox__Fiiiiiiii(int x,int y,int w,int h,int col1,int col2,int col3,int col4)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ TransitionOff__27tMenuItemGoToMenuButtonFade(struct tMenuItemGoToMenuButtonFade *this /*$a0*/)
 // line 168, offset 0x8001c25c
	/* begin block 1 */
		// Start line: 169
		// Start offset: 0x8001C25C
	/* end block 1 */
	// End offset: 0x8001C25C
	// End Line: 170

void TransitionOff__27tMenuItemGoToMenuButtonFade(tMenuItemGoToMenuButtonFade *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ TransitionOn__27tMenuItemGoToMenuButtonFade(struct tMenuItemGoToMenuButtonFade *this /*$a0*/)
 // line 173, offset 0x8001c268
	/* begin block 1 */
		// Start line: 174
		// Start offset: 0x8001C268
	/* end block 1 */
	// End offset: 0x8001C268
	// End Line: 176

void TransitionOn__27tMenuItemGoToMenuButtonFade(tMenuItemGoToMenuButtonFade *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// unsigned int /*$ra*/ TransitionIsFinished__27tMenuItemGoToMenuButtonFade(struct tMenuItemGoToMenuButtonFade *this /*$a0*/)
 // line 183, offset 0x8001c284
	/* begin block 1 */
		// Start line: 184
		// Start offset: 0x8001C284
	/* end block 1 */
	// End offset: 0x8001C2D0
	// End Line: 192

uint TransitionIsFinished__27tMenuItemGoToMenuButtonFade(tMenuItemGoToMenuButtonFade *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ UpdateTransition__27tMenuItemGoToMenuButtonFadeb(struct tMenuItemGoToMenuButtonFade *this /*$s0*/, unsigned int selected /*$s1*/)
 // line 195, offset 0x8001c2dc
	/* begin block 1 */
		// Start line: 196
		// Start offset: 0x8001C2DC
	/* end block 1 */
	// End offset: 0x8001C31C
	// End Line: 198

void UpdateTransition__27tMenuItemGoToMenuButtonFadeb( (tMenuItemGoToMenuButtonFade *this,uint selected)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// struct tMenuItemLeftRightFade * /*$ra*/ __22tMenuItemLeftRightFadeUiP13tListIterator(struct tMenuItemLeftRightFade *this /*$s0*/, unsigned int textDescription /*$a1*/, struct tListIterator *dataPtr /*$a2*/)
 // line 204, offset 0x8001c358
	/* begin block 1 */
		// Start line: 205
		// Start offset: 0x8001C358
	/* end block 1 */
	// End offset: 0x8001C358
	// End Line: 205

tMenuItemLeftRightFade * __22tMenuItemLeftRightFadeUiP13tListIterator( (tMenuItemLeftRightFade *this,uint textDescription,tListIterator *dataPtr)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ TransitionOff__22tMenuItemLeftRightFade(struct tMenuItemLeftRightFade *this /*$a0*/)
 // line 215, offset 0x8001c394
	/* begin block 1 */
		// Start line: 216
		// Start offset: 0x8001C394
	/* end block 1 */
	// End offset: 0x8001C394
	// End Line: 217

void TransitionOff__22tMenuItemLeftRightFade(tMenuItemLeftRightFade *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ TransitionOn__22tMenuItemLeftRightFade(struct tMenuItemLeftRightFade *this /*$a0*/)
 // line 221, offset 0x8001c3ac
	/* begin block 1 */
		// Start line: 222
		// Start offset: 0x8001C3AC
	/* end block 1 */
	// End offset: 0x8001C3AC
	// End Line: 223

void TransitionOn__22tMenuItemLeftRightFade(tMenuItemLeftRightFade *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// unsigned int /*$ra*/ TransitionIsFinished__22tMenuItemLeftRightFade(struct tMenuItemLeftRightFade *this /*$a0*/)
 // line 231, offset 0x8001c3d0
	/* begin block 1 */
		// Start line: 232
		// Start offset: 0x8001C3D0
	/* end block 1 */
	// End offset: 0x8001C42C
	// End Line: 242

uint TransitionIsFinished__22tMenuItemLeftRightFade(tMenuItemLeftRightFade *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ UpdateTransition__22tMenuItemLeftRightFadeb(struct tMenuItemLeftRightFade *this /*$s0*/, unsigned int selected /*$s1*/)
 // line 245, offset 0x8001c438
	/* begin block 1 */
		// Start line: 246
		// Start offset: 0x8001C438
	/* end block 1 */
	// End offset: 0x8001C478
	// End Line: 248

void UpdateTransition__22tMenuItemLeftRightFadeb(tMenuItemLeftRightFade *this,uint selected)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// struct tOptionsMenu * /*$ra*/ __12tOptionsMenuUiP7tScreenP5tMenuT3PFR12tMenuCommand_vsiiP9tMenuIteme(struct tOptionsMenu *this /*$s0*/, unsigned int flags /*$a1*/, struct tScreen *screenHandler /*$a2*/, struct tMenu *nextMenu /*$a3*/, struct tMenu *optionsMenu /*stack 16*/, void (*OnButtonPress)() /*stack 20*/, int title /*stack 24*/, int firstframe /*stack 28*/, int numframes /*stack 32*/, struct tMenuItem *firstItem /*stack 36*/)
 // line 267, offset 0x8001c4b4
	/* begin block 1 */
		// Start line: 268
		// Start offset: 0x8001C4B4
	/* end block 1 */
	// End offset: 0x8001C4B4
	// End Line: 268

tOptionsMenu * __12tOptionsMenuUiP7tScreenP5tMenuT3PFR12tMenuCommand_vsiiP9tMenuIteme( (tOptionsMenu *this,uint flags,tScreen *screenHandler,tMenu *nextMenu,tMenu *optionsMenu, OnButtonPress *OnButtonPress,int title,int firstframe,int numframes,tMenuItem *firstItem)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// autogenerated function stub: 
// void /*$ra*/ _._12tOptionsMenu(struct tOptionsMenu *this /*$a0*/, int __in_chrg /*$a1*/)
void _._12tOptionsMenu _._12tOptionsMenu(tOptionsMenu *this /*$a0*/this, int __in_chrg /*$a1*/ __in_chrg)
{ // line 281, offset 0x8001c544
	/* begin block 1 */
		// Start line: 282
		// Start offset: 0x8001C544
	/* end block 1 */
	// End offset: 0x8001C544
	// End Line: 282

}


// decompiled code
// original method signature: 
// long /*$ra*/ DebounceKeys__12tOptionsMenu(struct tOptionsMenu *this /*$a0*/)
 // line 286, offset 0x8001c56c
	/* begin block 1 */
		// Start line: 287
		// Start offset: 0x8001C56C

		/* begin block 1.1 */
			// Start line: 287
			// Start offset: 0x8001C56C

			/* begin block 1.1.1 */
				// Start line: 288
				// Start offset: 0x8001C594

				/* begin block 1.1.1.1 */
					// Start line: 288
					// Start offset: 0x8001C594
				/* end block 1.1.1.1 */
				// End offset: 0x8001C594
				// End Line: 288
			/* end block 1.1.1 */
			// End offset: 0x8001C594
			// End Line: 288
		/* end block 1.1 */
		// End offset: 0x8001C5C8
		// End Line: 290
	/* end block 1 */
	// End offset: 0x8001C5C8
	// End Line: 290

long DebounceKeys__12tOptionsMenu(tOptionsMenu *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ TransitionOff__12tOptionsMenu(struct tOptionsMenu *this /*$s1*/)
 // line 293, offset 0x8001c5d8
	/* begin block 1 */
		// Start line: 294
		// Start offset: 0x8001C5D8
		// Variables:
	// 		short i; // $s0
	/* end block 1 */
	// End offset: 0x8001C654
	// End Line: 304

void TransitionOff__12tOptionsMenu(tOptionsMenu *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ TransitionOn__12tOptionsMenu(struct tOptionsMenu *this /*$s1*/)
 // line 308, offset 0x8001c670
	/* begin block 1 */
		// Start line: 309
		// Start offset: 0x8001C670
		// Variables:
	// 		short i; // $s0
	/* end block 1 */
	// End offset: 0x8001C6F8
	// End Line: 321

void TransitionOn__12tOptionsMenu(tOptionsMenu *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// unsigned int /*$ra*/ TransitionIsFinished__12tOptionsMenu(struct tOptionsMenu *this /*$s1*/)
 // line 325, offset 0x8001c70c
	/* begin block 1 */
		// Start line: 326
		// Start offset: 0x8001C70C
		// Variables:
	// 		short i; // $s0

		/* begin block 1.1 */
			// Start line: 349
			// Start offset: 0x8001C7F4
			// Variables:
		// 		struct tFEApplication *this; // $v0

			/* begin block 1.1.1 */
				// Start line: 349
				// Start offset: 0x8001C7F4
			/* end block 1.1.1 */
			// End offset: 0x8001C7F4
			// End Line: 349
		/* end block 1.1 */
		// End offset: 0x8001C7F4
		// End Line: 349
	/* end block 1 */
	// End offset: 0x8001C834
	// End Line: 359

uint TransitionIsFinished__12tOptionsMenu(tOptionsMenu *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ UpdateTransition__12tOptionsMenu(struct tOptionsMenu *this /*$s1*/)
 // line 364, offset 0x8001c854
	/* begin block 1 */
		// Start line: 365
		// Start offset: 0x8001C854
		// Variables:
	// 		short i; // $s0
	/* end block 1 */
	// End offset: 0x8001CAD0
	// End Line: 423

void UpdateTransition__12tOptionsMenu(tOptionsMenu *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ Draw__12tOptionsMenu(struct tOptionsMenu *this /*$s0*/)
 // line 426, offset 0x8001cb04
	/* begin block 1 */
		// Start line: 427
		// Start offset: 0x8001CB04
		// Variables:
	// 		short i; // $s1
	// 		struct tDrawShapeExtended drawFlags; // stack offset -40

		/* begin block 1.1 */
			// Start line: 427
			// Start offset: 0x8001CB04

			/* begin block 1.1.1 */
				// Start line: 432
				// Start offset: 0x8001CB3C

				/* begin block 1.1.1.1 */
					// Start line: 432
					// Start offset: 0x8001CB3C
				/* end block 1.1.1.1 */
				// End offset: 0x8001CB3C
				// End Line: 432
			/* end block 1.1.1 */
			// End offset: 0x8001CB3C
			// End Line: 432
		/* end block 1.1 */
		// End offset: 0x8001CB54
		// End Line: 433

		/* begin block 1.2 */
			// Start line: 434
			// Start offset: 0x8001CB54

			/* begin block 1.2.1 */
				// Start line: 434
				// Start offset: 0x8001CB54
				// Variables:
			// 		struct tMenuItem *this; // $v0

				/* begin block 1.2.1.1 */
					// Start line: 434
					// Start offset: 0x8001CB54
				/* end block 1.2.1.1 */
				// End offset: 0x8001CB54
				// End Line: 434
			/* end block 1.2.1 */
			// End offset: 0x8001CB54
			// End Line: 434
		/* end block 1.2 */
		// End offset: 0x8001CB98
		// End Line: 435

		/* begin block 1.3 */
			// Start line: 436
			// Start offset: 0x8001CBA0

			/* begin block 1.3.1 */
				// Start line: 436
				// Start offset: 0x8001CBA0
				// Variables:
			// 		struct tMenuItem *this; // $v0

				/* begin block 1.3.1.1 */
					// Start line: 436
					// Start offset: 0x8001CBA0
				/* end block 1.3.1.1 */
				// End offset: 0x8001CBA0
				// End Line: 436
			/* end block 1.3.1 */
			// End offset: 0x8001CBA0
			// End Line: 436
		/* end block 1.3 */
		// End offset: 0x8001CBD4
		// End Line: 437

		/* begin block 1.4 */
			// Start line: 440
			// Start offset: 0x8001CBDC

			/* begin block 1.4.1 */
				// Start line: 441
				// Start offset: 0x8001CBFC

				/* begin block 1.4.1.1 */
					// Start line: 442
					// Start offset: 0x8001CBFC

					/* begin block 1.4.1.1.1 */
						// Start line: 442
						// Start offset: 0x8001CBFC
					/* end block 1.4.1.1.1 */
					// End offset: 0x8001CBFC
					// End Line: 442
				/* end block 1.4.1.1 */
				// End offset: 0x8001CBFC
				// End Line: 442
			/* end block 1.4.1 */
			// End offset: 0x8001CC68
			// End Line: 443
		/* end block 1.4 */
		// End offset: 0x8001CC68
		// End Line: 443
	/* end block 1 */
	// End offset: 0x8001CCF4
	// End Line: 457

void Draw__12tOptionsMenu(tOptionsMenu *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ ProcessInput__12tOptionsMenu7tPlayerR13tInputKeyTypeR12tMenuCommand(struct tOptionsMenu *this /*$s0*/, enum tPlayer fromPlayer /*$s2*/, enum tInputKeyType *keyval /*$s1*/, struct tMenuCommand *command /*$s3*/)
 // line 462, offset 0x8001cd08
	/* begin block 1 */
		// Start line: 463
		// Start offset: 0x8001CD08
	/* end block 1 */
	// End offset: 0x8001CD60
	// End Line: 505

void ProcessInput__12tOptionsMenu7tPlayerR13tInputKeyTypeR12tMenuCommand( (tOptionsMenu *this,tPlayer fromPlayer,tInputKeyType *keyval,tMenuCommand *command)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// struct tInsideBoxMenu * /*$ra*/ __14tInsideBoxMenuUiP7tScreenP5tMenuT3PFR12tMenuCommand_vsP9tMenuIteme(struct tInsideBoxMenu *this /*$s0*/, unsigned int flags /*$a1*/, struct tScreen *screenHandler /*$a2*/, struct tMenu *nextMenu /*$a3*/, struct tMenu *optionsMenu /*stack 16*/, void (*OnButtonPress)() /*stack 20*/, int title /*stack 24*/, struct tMenuItem *firstItem /*stack 28*/)
 // line 520, offset 0x8001cd90
	/* begin block 1 */
		// Start line: 521
		// Start offset: 0x8001CD90
	/* end block 1 */
	// End offset: 0x8001CD90
	// End Line: 521

tInsideBoxMenu * __14tInsideBoxMenuUiP7tScreenP5tMenuT3PFR12tMenuCommand_vsP9tMenuIteme( (tInsideBoxMenu *this,uint flags,tScreen *screenHandler,tMenu *nextMenu,tMenu *optionsMenu ,OnButtonPress *OnButtonPress,int title,tMenuItem *firstItem)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// autogenerated function stub: 
// void /*$ra*/ _._14tInsideBoxMenu(struct tInsideBoxMenu *this /*$a0*/, int __in_chrg /*$a1*/)
void _._14tInsideBoxMenu _._14tInsideBoxMenu(tInsideBoxMenu *this /*$a0*/this, int __in_chrg /*$a1*/ __in_chrg)
{ // line 532, offset 0x8001ce04
	/* begin block 1 */
		// Start line: 533
		// Start offset: 0x8001CE04
	/* end block 1 */
	// End offset: 0x8001CE04
	// End Line: 533

}


// decompiled code
// original method signature: 
// void /*$ra*/ ProcessInput__14tInsideBoxMenu7tPlayerR13tInputKeyTypeR12tMenuCommand(struct tInsideBoxMenu *this /*$a0*/, enum tPlayer fromPlayer /*$a1*/, enum tInputKeyType *keyval /*$a2*/, struct tMenuCommand *command /*$a3*/)
 // line 537, offset 0x8001ce2c
	/* begin block 1 */
		// Start line: 538
		// Start offset: 0x8001CE2C
	/* end block 1 */
	// End offset: 0x8001CEEC
	// End Line: 554

void ProcessInput__14tInsideBoxMenu7tPlayerR13tInputKeyTypeR12tMenuCommand( (tInsideBoxMenu *this,tPlayer fromPlayer,tInputKeyType *keyval,tMenuCommand *command)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ Draw__14tInsideBoxMenusssss(struct tInsideBoxMenu *this /*$s0*/, short x /*$a1*/, short y /*$a2*/, short w /*$a3*/, int slideOffset /*stack 16*/)
 // line 558, offset 0x8001cefc
	/* begin block 1 */
		// Start line: 559
		// Start offset: 0x8001CEFC
		// Variables:
	// 		short i; // $s2
	// 		short j; // $s1
	/* end block 1 */
	// End offset: 0x8001D138
	// End Line: 603

void Draw__14tInsideBoxMenusssss(tInsideBoxMenu *this,short x,short y,short w,int slideOffset)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// struct tMenuItemSlidingMenu * /*$ra*/ __20tMenuItemSlidingMenuUissssb(struct tMenuItemSlidingMenu *this /*$s0*/, unsigned int textDescription /*$a1*/, short width /*$a2*/, short height /*$a3*/, int diffx /*stack 16*/, int diffy /*stack 20*/, unsigned int fillback /*stack 24*/)
 // line 612, offset 0x8001d160
	/* begin block 1 */
		// Start line: 613
		// Start offset: 0x8001D160
	/* end block 1 */
	// End offset: 0x8001D160
	// End Line: 613

tMenuItemSlidingMenu * __20tMenuItemSlidingMenuUissssb( (tMenuItemSlidingMenu *this,uint textDescription,short width,short height,int diffx, int diffy,uint fillback)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// autogenerated function stub: 
// void /*$ra*/ _._20tMenuItemSlidingMenu(struct tMenuItemSlidingMenu *this /*$a0*/, int __in_chrg /*$a1*/)
void _._20tMenuItemSlidingMenu _._20tMenuItemSlidingMenu(tMenuItemSlidingMenu *this /*$a0*/this, int __in_chrg /*$a1*/ __in_chrg)
{ // line 628, offset 0x8001d208
	/* begin block 1 */
		// Start line: 629
		// Start offset: 0x8001D208
	/* end block 1 */
	// End offset: 0x8001D208
	// End Line: 629

}


// decompiled code
// original method signature: 
// void /*$ra*/ TransitionOff__20tMenuItemSlidingMenu(struct tMenuItemSlidingMenu *this /*$a0*/)
 // line 634, offset 0x8001d230
	/* begin block 1 */
		// Start line: 635
		// Start offset: 0x8001D230
	/* end block 1 */
	// End offset: 0x8001D254
	// End Line: 642

void TransitionOff__20tMenuItemSlidingMenu(tMenuItemSlidingMenu *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ TransitionOn__20tMenuItemSlidingMenu(struct tMenuItemSlidingMenu *this /*$a0*/)
 // line 648, offset 0x8001d25c
	/* begin block 1 */
		// Start line: 649
		// Start offset: 0x8001D25C
	/* end block 1 */
	// End offset: 0x8001D25C
	// End Line: 651

void TransitionOn__20tMenuItemSlidingMenu(tMenuItemSlidingMenu *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// unsigned int /*$ra*/ TransitionIsFinished__20tMenuItemSlidingMenu(struct tMenuItemSlidingMenu *this /*$a0*/)
 // line 661, offset 0x8001d294
	/* begin block 1 */
		// Start line: 662
		// Start offset: 0x8001D294
	/* end block 1 */
	// End offset: 0x8001D310
	// End Line: 677

uint TransitionIsFinished__20tMenuItemSlidingMenu(tMenuItemSlidingMenu *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ UpdateTransition__20tMenuItemSlidingMenub(struct tMenuItemSlidingMenu *this /*$s0*/, unsigned int selected /*$s1*/)
 // line 680, offset 0x8001d31c
	/* begin block 1 */
		// Start line: 681
		// Start offset: 0x8001D31C
	/* end block 1 */
	// End offset: 0x8001D35C
	// End Line: 690

void UpdateTransition__20tMenuItemSlidingMenub(tMenuItemSlidingMenu *this,uint selected)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// long /*$ra*/ DebounceKeys__20tMenuItemSlidingMenu(struct tMenuItemSlidingMenu *this /*$a0*/)
 // line 696, offset 0x8001d398
	/* begin block 1 */
		// Start line: 697
		// Start offset: 0x8001D398
	/* end block 1 */
	// End offset: 0x8001D3D0
	// End Line: 699

long DebounceKeys__20tMenuItemSlidingMenu(tMenuItemSlidingMenu *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ Draw__20tMenuItemSlidingMenub(struct tMenuItemSlidingMenu *this /*$a0*/, unsigned int selected /*$a3*/)
 // line 705, offset 0x8001d3e0
	/* begin block 1 */
		// Start line: 706
		// Start offset: 0x8001D3E0
	/* end block 1 */
	// End offset: 0x8001D3E0
	// End Line: 706

void Draw__20tMenuItemSlidingMenub(tMenuItemSlidingMenu *this,uint selected)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ UpdatefOpenHeight__20tMenuItemSlidingMenub(struct tMenuItemSlidingMenu *this /*$a0*/, unsigned int selected /*$a1*/)
 // line 711, offset 0x8001d41c
	/* begin block 1 */
		// Start line: 712
		// Start offset: 0x8001D41C
	/* end block 1 */
	// End offset: 0x8001D634
	// End Line: 770

void UpdatefOpenHeight__20tMenuItemSlidingMenub(tMenuItemSlidingMenu *this,uint selected)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ Draw__20tMenuItemSlidingMenuiib(struct tMenuItemSlidingMenu *this /*$s6*/, int offx /*$s0*/, int offy /*$s1*/, unsigned int selected /*$a3*/)
 // line 777, offset 0x8001d63c
	/* begin block 1 */
		// Start line: 778
		// Start offset: 0x8001D63C
		// Variables:
	// 		int ColText; // stack offset -64
	// 		int x; // stack offset -60
	// 		int y; // stack offset -56
	// 		struct tTexture_ShapeInfo *shape; // stack offset -52
	// 		static int flareextra; // offset 0x0
	// 		unsigned int fPlayList; // stack offset -48

		/* begin block 1.1 */
			// Start line: 809
			// Start offset: 0x8001D728

			/* begin block 1.1.1 */
				// Start line: 810
				// Start offset: 0x8001D748
				// Variables:
			// 		struct tDrawShapeExtended drawFlags; // stack offset -88
			// 		int width; // $s0
			/* end block 1.1.1 */
			// End offset: 0x8001D824
			// End Line: 818
		/* end block 1.1 */
		// End offset: 0x8001D824
		// End Line: 818

		/* begin block 1.2 */
			// Start line: 821
			// Start offset: 0x8001D824

			/* begin block 1.2.1 */
				// Start line: 822
				// Start offset: 0x8001D834
				// Variables:
			// 		int xx; // $s4
			// 		int yy; // $s5
			// 		int ww; // $fp
			// 		int hh; // $s2
			// 		struct DRAWENV *drenv; // stack offset -44
			// 		struct DR_AREA *daprim; // $a0
			// 		struct RECT full; // stack offset -88
			// 		struct RECT temp; // stack offset -80
			// 		int gray; // $s1
			// 		struct tTexture_ShapeInfo *shapetop; // $s7
			// 		struct tTexture_ShapeInfo *shapebottom; // $s3
			/* end block 1.2.1 */
			// End offset: 0x8001DC50
			// End Line: 884
		/* end block 1.2 */
		// End offset: 0x8001DC50
		// End Line: 884
	/* end block 1 */
	// End offset: 0x8001DC50
	// End Line: 884

void Draw__20tMenuItemSlidingMenuiib(tMenuItemSlidingMenu *this,int offx,int offy,uint selected)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ ProcessInput__20tMenuItemSlidingMenu7tPlayerR13tInputKeyTypeR12tMenuCommand(struct tMenuItemSlidingMenu *this /*$s0*/, enum tPlayer fromPlayer /*$s2*/, enum tInputKeyType *keyval /*$s1*/, struct tMenuCommand *command /*$s3*/)
 // line 890, offset 0x8001dc80
	/* begin block 1 */
		// Start line: 891
		// Start offset: 0x8001DC80
	/* end block 1 */
	// End offset: 0x8001DCFC
	// End Line: 901

void ProcessInput__20tMenuItemSlidingMenu7tPlayerR13tInputKeyTypeR12tMenuCommand( (tMenuItemSlidingMenu *this,tPlayer fromPlayer,tInputKeyType *keyval, tMenuCommand *command)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ SetMenu__20tMenuItemSlidingMenubP14tInsideBoxMenu(struct tMenuItemSlidingMenu *this /*$a0*/, unsigned int bothmenus /*$a1*/, struct tInsideBoxMenu *menu /*$a2*/)
 // line 904, offset 0x8001dd28
	/* begin block 1 */
		// Start line: 905
		// Start offset: 0x8001DD28

		/* begin block 1.1 */
			// Start line: 911
			// Start offset: 0x8001DD34

			/* begin block 1.1.1 */
				// Start line: 912
				// Start offset: 0x8001DD44

				/* begin block 1.1.1.1 */
					// Start line: 912
					// Start offset: 0x8001DD44
					// Variables:
				// 		struct tMenuItem *this; // $a0

					/* begin block 1.1.1.1.1 */
						// Start line: 912
						// Start offset: 0x8001DD44
					/* end block 1.1.1.1.1 */
					// End offset: 0x8001DD44
					// End Line: 912
				/* end block 1.1.1.1 */
				// End offset: 0x8001DD44
				// End Line: 912
			/* end block 1.1.1 */
			// End offset: 0x8001DD44
			// End Line: 912

			/* begin block 1.1.2 */
				// Start line: 917
				// Start offset: 0x8001DD58

				/* begin block 1.1.2.1 */
					// Start line: 917
					// Start offset: 0x8001DD58
					// Variables:
				// 		struct tMenuItem *this; // $a0

					/* begin block 1.1.2.1.1 */
						// Start line: 917
						// Start offset: 0x8001DD58
					/* end block 1.1.2.1.1 */
					// End offset: 0x8001DD64
					// End Line: 917
				/* end block 1.1.2.1 */
				// End offset: 0x8001DD64
				// End Line: 917
			/* end block 1.1.2 */
			// End offset: 0x8001DD64
			// End Line: 919
		/* end block 1.1 */
		// End offset: 0x8001DD64
		// End Line: 919
	/* end block 1 */
	// End offset: 0x8001DD64
	// End Line: 919

void SetMenu__20tMenuItemSlidingMenubP14tInsideBoxMenu( (tMenuItemSlidingMenu *this,uint bothmenus,tInsideBoxMenu *menu)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ UpdatefOpenHeight__25tMenuItemSlidingActivatedb(struct tMenuItemSlidingActivated *this /*$a0*/)
 // line 925, offset 0x8001dd6c
	/* begin block 1 */
		// Start line: 926
		// Start offset: 0x8001DD6C
	/* end block 1 */
	// End offset: 0x8001DDCC
	// End Line: 932

void UpdatefOpenHeight__25tMenuItemSlidingActivatedb(tMenuItemSlidingActivated *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ TransitionOff__25tMenuItemSlidingActivated(struct tMenuItemSlidingActivated *this /*$a0*/)
 // line 937, offset 0x8001ddd4
	/* begin block 1 */
		// Start line: 938
		// Start offset: 0x8001DDD4
	/* end block 1 */
	// End offset: 0x8001DDF8
	// End Line: 945

void TransitionOff__25tMenuItemSlidingActivated(tMenuItemSlidingActivated *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ TransitionOn__25tMenuItemSlidingActivated(struct tMenuItemSlidingActivated *this /*$a0*/)
 // line 949, offset 0x8001de00
	/* begin block 1 */
		// Start line: 950
		// Start offset: 0x8001DE00
	/* end block 1 */
	// End offset: 0x8001DE00
	// End Line: 951

void TransitionOn__25tMenuItemSlidingActivated(tMenuItemSlidingActivated *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// unsigned int /*$ra*/ TransitionIsFinished__25tMenuItemSlidingActivated(struct tMenuItemSlidingActivated *this /*$a0*/)
 // line 964, offset 0x8001de40
	/* begin block 1 */
		// Start line: 965
		// Start offset: 0x8001DE40
	/* end block 1 */
	// End offset: 0x8001DEBC
	// End Line: 980

uint TransitionIsFinished__25tMenuItemSlidingActivated(tMenuItemSlidingActivated *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ UpdateTransition__25tMenuItemSlidingActivatedb(struct tMenuItemSlidingActivated *this /*$s0*/, unsigned int selected /*$s1*/)
 // line 983, offset 0x8001dec8
	/* begin block 1 */
		// Start line: 984
		// Start offset: 0x8001DEC8
	/* end block 1 */
	// End offset: 0x8001DF08
	// End Line: 986

void UpdateTransition__25tMenuItemSlidingActivatedb(tMenuItemSlidingActivated *this,uint selected)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ ProcessInput__25tMenuItemSlidingActivated7tPlayerR13tInputKeyTypeR12tMenuCommand(struct tMenuItemSlidingActivated *this /*$s1*/, enum tPlayer fromPlayer /*$s3*/, enum tInputKeyType *keyval /*$s2*/, struct tMenuCommand *command /*$s4*/)
 // line 990, offset 0x8001df44
	/* begin block 1 */
		// Start line: 991
		// Start offset: 0x8001DF44
	/* end block 1 */
	// End offset: 0x8001E108
	// End Line: 1045

void ProcessInput__25tMenuItemSlidingActivated7tPlayerR13tInputKeyTypeR12tMenuCommand( (tMenuItemSlidingActivated *this,tPlayer fromPlayer,tInputKeyType *keyval, tMenuCommand *command)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ MyLeftRightDraw__22tMenuItemLeftRightFadeii(struct tMenuItemLeftRightFade *this /*$s0*/, int x /*$s2*/, int y /*$s1*/)
 // line 1063, offset 0x8001e13c
	/* begin block 1 */
		// Start line: 1064
		// Start offset: 0x8001E13C
		// Variables:
	// 		struct tDrawShapeExtended aCol; // stack offset -40
	// 		int ColText; // $s0
	/* end block 1 */
	// End offset: 0x8001E13C
	// End Line: 1064

void MyLeftRightDraw__22tMenuItemLeftRightFadeii(tMenuItemLeftRightFade *this,int x,int y)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ Draw__31tMenuItemDisplayLeftRightChoiceiib(struct tMenuItemDisplayLeftRightChoice *this /*$s3*/, int offx /*$s0*/, int offy /*$s2*/)
 // line 1085, offset 0x8001e230
	/* begin block 1 */
		// Start line: 1086
		// Start offset: 0x8001E230
		// Variables:
	// 		int ColText; // $s2
	/* end block 1 */
	// End offset: 0x8001E304
	// End Line: 1100

void Draw__31tMenuItemDisplayLeftRightChoiceiib( (tMenuItemDisplayLeftRightChoice *this,int offx,int offy)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ TransitionOn__29tMenuItemOnOffLeftRightChoice(struct tMenuItemOnOffLeftRightChoice *this /*$s0*/)
 // line 1105, offset 0x8001e320
	/* begin block 1 */
		// Start line: 1106
		// Start offset: 0x8001E320
	/* end block 1 */
	// End offset: 0x8001E320
	// End Line: 1106

void TransitionOn__29tMenuItemOnOffLeftRightChoice(tMenuItemOnOffLeftRightChoice *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ Draw__29tMenuItemOnOffLeftRightChoiceiib(struct tMenuItemOnOffLeftRightChoice *this /*$s2*/, int offx /*$s0*/, int offy /*$s3*/)
 // line 1111, offset 0x8001e384
	/* begin block 1 */
		// Start line: 1112
		// Start offset: 0x8001E384
		// Variables:
	// 		int ColTextOn; // stack offset -32
	// 		int ColTextOff; // stack offset -28
	/* end block 1 */
	// End offset: 0x8001E4E0
	// End Line: 1139

void Draw__29tMenuItemOnOffLeftRightChoiceiib(tMenuItemOnOffLeftRightChoice *this,int offx,int offy)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// struct tMenuItemLeftRightAudioSlider * /*$ra*/ __29tMenuItemLeftRightAudioSliderUiP13tListIteratori(struct tMenuItemLeftRightAudioSlider *this /*$s0*/, unsigned int textDescription /*$a1*/, struct tListIterator *dataPtr /*$a2*/, int AudioArt /*$s1*/)
 // line 1152, offset 0x8001e4fc
	/* begin block 1 */
		// Start line: 1153
		// Start offset: 0x8001E4FC
	/* end block 1 */
	// End offset: 0x8001E4FC
	// End Line: 1153

tMenuItemLeftRightAudioSlider * __29tMenuItemLeftRightAudioSliderUiP13tListIteratori( (tMenuItemLeftRightAudioSlider *this,uint textDescription,tListIterator *dataPtr, int AudioArt)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// autogenerated function stub: 
// void /*$ra*/ _._29tMenuItemLeftRightAudioSlider(struct tMenuItemLeftRightAudioSlider *this /*$a0*/, int __in_chrg /*$a1*/)
void _._29tMenuItemLeftRightAudioSlider _._29tMenuItemLeftRightAudioSlider(tMenuItemLeftRightAudioSlider *this /*$a0*/this, int __in_chrg /*$a1*/ __in_chrg)
{ // line 1160, offset 0x8001e548
	/* begin block 1 */
		// Start line: 1161
		// Start offset: 0x8001E548
	/* end block 1 */
	// End offset: 0x8001E548
	// End Line: 1161

}


// decompiled code
// original method signature: 
// void /*$ra*/ Draw__29tMenuItemLeftRightAudioSlideriib(struct tMenuItemLeftRightAudioSlider *this /*$s3*/, int ox /*$s0*/, int oy /*$s1*/)
 // line 1167, offset 0x8001e570
	/* begin block 1 */
		// Start line: 1168
		// Start offset: 0x8001E570
		// Variables:
	// 		int coltext; // $s0
	// 		struct tDrawShapeExtended tCol; // stack offset -48

		/* begin block 1.1 */
			// Start line: 1168
			// Start offset: 0x8001E570

			/* begin block 1.1.1 */
				// Start line: 1168
				// Start offset: 0x8001E570
			/* end block 1.1.1 */
			// End offset: 0x8001E570
			// End Line: 1168
		/* end block 1.1 */
		// End offset: 0x8001E570
		// End Line: 1168

		/* begin block 1.2 */
			// Start line: 1168
			// Start offset: 0x8001E570

			/* begin block 1.2.1 */
				// Start line: 1168
				// Start offset: 0x8001E570
			/* end block 1.2.1 */
			// End offset: 0x8001E570
			// End Line: 1168
		/* end block 1.2 */
		// End offset: 0x8001E570
		// End Line: 1168

		/* begin block 1.3 */
			// Start line: 1200
			// Start offset: 0x8001E6D0
			// Variables:
		// 		struct tListIterator *this; // $v0

			/* begin block 1.3.1 */
				// Start line: 1200
				// Start offset: 0x8001E6D0
			/* end block 1.3.1 */
			// End offset: 0x8001E6D0
			// End Line: 1200
		/* end block 1.3 */
		// End offset: 0x8001E6D0
		// End Line: 1200

		/* begin block 1.4 */
			// Start line: 1200
			// Start offset: 0x8001E6D0

			/* begin block 1.4.1 */
				// Start line: 1200
				// Start offset: 0x8001E6D0
			/* end block 1.4.1 */
			// End offset: 0x8001E6D0
			// End Line: 1200
		/* end block 1.4 */
		// End offset: 0x8001E6D0
		// End Line: 1200
	/* end block 1 */
	// End offset: 0x8001E760
	// End Line: 1200

void Draw__29tMenuItemLeftRightAudioSlideriib(tMenuItemLeftRightAudioSlider *this,int ox,int oy)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// int /*$ra*/ Percentage__29tMenuItemLeftRightAudioSlider(struct tMenuItemLeftRightAudioSlider *this /*$s0*/)
 // line 1204, offset 0x8001e77c
	/* begin block 1 */
		// Start line: 1205
		// Start offset: 0x8001E77C
		// Variables:
	// 		int percent; // $s0

		/* begin block 1.1 */
			// Start line: 1205
			// Start offset: 0x8001E77C
			// Variables:
		// 		struct tListIterator *this; // $a2

			/* begin block 1.1.1 */
				// Start line: 1205
				// Start offset: 0x8001E77C
			/* end block 1.1.1 */
			// End offset: 0x8001E77C
			// End Line: 1205
		/* end block 1.1 */
		// End offset: 0x8001E77C
		// End Line: 1205

		/* begin block 1.2 */
			// Start line: 1205
			// Start offset: 0x8001E77C

			/* begin block 1.2.1 */
				// Start line: 1205
				// Start offset: 0x8001E77C
			/* end block 1.2.1 */
			// End offset: 0x8001E77C
			// End Line: 1205
		/* end block 1.2 */
		// End offset: 0x8001E77C
		// End Line: 1205

		/* begin block 1.3 */
			// Start line: 1205
			// Start offset: 0x8001E77C

			/* begin block 1.3.1 */
				// Start line: 1205
				// Start offset: 0x8001E77C
			/* end block 1.3.1 */
			// End offset: 0x8001E77C
			// End Line: 1205
		/* end block 1.3 */
		// End offset: 0x8001E77C
		// End Line: 1205
	/* end block 1 */
	// End offset: 0x8001E83C
	// End Line: 1210

int Percentage__29tMenuItemLeftRightAudioSlider(tMenuItemLeftRightAudioSlider *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ TransitionOff__29tMenuItemLeftRightAudioSlider(struct tMenuItemLeftRightAudioSlider *this /*$a0*/)
 // line 1212, offset 0x8001e850
	/* begin block 1 */
		// Start line: 1213
		// Start offset: 0x8001E850
	/* end block 1 */
	// End offset: 0x8001E850
	// End Line: 1214

void TransitionOff__29tMenuItemLeftRightAudioSlider(tMenuItemLeftRightAudioSlider *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ TransitionOn__29tMenuItemLeftRightAudioSlider(struct tMenuItemLeftRightAudioSlider *this /*$a0*/)
 // line 1217, offset 0x8001e860
	/* begin block 1 */
		// Start line: 1218
		// Start offset: 0x8001E860
	/* end block 1 */
	// End offset: 0x8001E860
	// End Line: 1219

void TransitionOn__29tMenuItemLeftRightAudioSlider(tMenuItemLeftRightAudioSlider *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// unsigned int /*$ra*/ TransitionIsFinished__29tMenuItemLeftRightAudioSlider(struct tMenuItemLeftRightAudioSlider *this /*$a0*/)
 // line 1223, offset 0x8001e878
	/* begin block 1 */
		// Start line: 1224
		// Start offset: 0x8001E878
	/* end block 1 */
	// End offset: 0x8001E8C8
	// End Line: 1232

uint TransitionIsFinished__29tMenuItemLeftRightAudioSlider(tMenuItemLeftRightAudioSlider *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ UpdateTransition__29tMenuItemLeftRightAudioSliderb(struct tMenuItemLeftRightAudioSlider *this /*$a0*/, unsigned int selected /*$a1*/)
 // line 1234, offset 0x8001e8d4
	/* begin block 1 */
		// Start line: 1235
		// Start offset: 0x8001E8D4
	/* end block 1 */
	// End offset: 0x8001E908
	// End Line: 1236

void UpdateTransition__29tMenuItemLeftRightAudioSliderb( (tMenuItemLeftRightAudioSlider *this,uint selected)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// struct tInsideBoxSongMenu * /*$ra*/ __18tInsideBoxSongMenuUiP7tScreenP5tMenuT3PFR12tMenuCommand_vsP9tMenuIteme(struct tInsideBoxSongMenu *this /*$s0*/, unsigned int flags /*$a1*/, struct tScreen *screenHandler /*$a2*/, struct tMenu *nextMenu /*$a3*/, struct tMenu *optionsMenu /*stack 16*/, void (*OnButtonPress)() /*stack 20*/, int title /*stack 24*/, struct tMenuItem *firstItem /*stack 28*/)
 // line 1247, offset 0x8001e920
	/* begin block 1 */
		// Start line: 1248
		// Start offset: 0x8001E920
		// Variables:
	// 		struct tInsideBoxMenu *this; // $s0
	// 		struct tMenu *optionsMenu; // $t0
	// 		void (*OnButtonPress)(); // $t1

		/* begin block 1.1 */
			// Start line: 1248
			// Start offset: 0x8001E920
		/* end block 1.1 */
		// End offset: 0x8001E920
		// End Line: 1248
	/* end block 1 */
	// End offset: 0x8001E920
	// End Line: 1248

	/* begin block 2 */
		// Start line: 1248
		// Start offset: 0x8001E920
		// Variables:
	// 		int j; // $a0
	/* end block 2 */
	// End offset: 0x8001E984
	// End Line: 1258

tInsideBoxSongMenu * __18tInsideBoxSongMenuUiP7tScreenP5tMenuT3PFR12tMenuCommand_vsP9tMenuIteme( (tInsideBoxSongMenu *this,uint flags,tScreen *screenHandler,tMenu *nextMenu, tMenu *optionsMenu,OnButtonPress *OnButtonPress,int title,tMenuItem *firstItem)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// autogenerated function stub: 
// void /*$ra*/ _._18tInsideBoxSongMenu(struct tInsideBoxSongMenu *this /*$a0*/, int __in_chrg /*$a1*/)
void _._18tInsideBoxSongMenu _._18tInsideBoxSongMenu(tInsideBoxSongMenu *this /*$a0*/this, int __in_chrg /*$a1*/ __in_chrg)
{ // line 1263, offset 0x8001e9b0
	/* begin block 1 */
		// Start line: 1264
		// Start offset: 0x8001E9B0
	/* end block 1 */
	// End offset: 0x8001E9B0
	// End Line: 1264

}


// decompiled code
// original method signature: 
// void /*$ra*/ Draw__18tInsideBoxSongMenusssss(struct tInsideBoxSongMenu *this /*$s2*/, short x /*$s7*/, short y /*$a2*/, short w /*$a3*/, int slideOffset /*stack 16*/, int maxheight /*stack 20*/)
 // line 1271, offset 0x8001e9d8
	/* begin block 1 */
		// Start line: 1272
		// Start offset: 0x8001E9D8
		// Variables:
	// 		int j; // $s1
	// 		int drawY; // $s5
	// 		int song; // $a1
	/* end block 1 */
	// End offset: 0x8001EC18
	// End Line: 1313

void Draw__18tInsideBoxSongMenusssss( (tInsideBoxSongMenu *this,short x,short y,short w,int slideOffset,int maxheight)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ DrawOneSong__18tInsideBoxSongMenussssss(struct tInsideBoxSongMenu *this /*$a0*/, short songnum /*$a1*/, short x /*$a2*/, short y /*$a3*/, int w /*stack 16*/, int fOnOffFade /*stack 20*/, int fSelFade /*stack 24*/)
 // line 1317, offset 0x8001ec48
	/* begin block 1 */
		// Start line: 1318
		// Start offset: 0x8001EC48
		// Variables:
	// 		int Col; // $s6
	// 		int ColTextOn; // stack offset -40
	// 		int ColTextOff; // stack offset -36
	// 		int ColText; // $s0
	/* end block 1 */
	// End offset: 0x8001EC48
	// End Line: 1318

void DrawOneSong__18tInsideBoxSongMenussssss( (tInsideBoxSongMenu *this,short songnum,short x,short y,int w,int fOnOffFade, int fSelFade)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// long /*$ra*/ DebounceKeys__18tInsideBoxSongMenu(struct tInsideBoxSongMenu *this /*$a0*/)
 // line 1344, offset 0x8001ee74
	/* begin block 1 */
		// Start line: 1345
		// Start offset: 0x8001EE74
	/* end block 1 */
	// End offset: 0x8001EE74
	// End Line: 1346

long DebounceKeys__18tInsideBoxSongMenu(tInsideBoxSongMenu *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ ProcessInput__18tInsideBoxSongMenu7tPlayerR13tInputKeyTypeR12tMenuCommand(struct tInsideBoxSongMenu *this /*$s0*/, enum tInputKeyType *keyval /*$s1*/)
 // line 1350, offset 0x8001ee7c
	/* begin block 1 */
		// Start line: 1351
		// Start offset: 0x8001EE7C
		// Variables:
	// 		int j; // $a1
	/* end block 1 */
	// End offset: 0x8001F070
	// End Line: 1409

void ProcessInput__18tInsideBoxSongMenu7tPlayerR13tInputKeyTypeR12tMenuCommand( (tInsideBoxSongMenu *this,tInputKeyType *keyval)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ Draw__34tMenuItemControllerLeftRightChoiceiib(struct tMenuItemControllerLeftRightChoice *this /*$s4*/, int ox /*$s0*/, int oy /*$s1*/)
 // line 1423, offset 0x8001f084
	/* begin block 1 */
		// Start line: 1424
		// Start offset: 0x8001F084
		// Variables:
	// 		struct tTexture_ShapeInfo *shape; // $s5
	// 		int Col; // $s0
	// 		int ColText; // $s1
	// 		struct tDrawShapeExtended drawFlags; // stack offset -56

		/* begin block 1.1 */
			// Start line: 1424
			// Start offset: 0x8001F084

			/* begin block 1.1.1 */
				// Start line: 1436
				// Start offset: 0x8001F114
				// Variables:
			// 		struct tDrawShapeExtended tCol; // stack offset -56
			/* end block 1.1.1 */
			// End offset: 0x8001F1A0
			// End Line: 1448
		/* end block 1.1 */
		// End offset: 0x8001F1A0
		// End Line: 1448
	/* end block 1 */
	// End offset: 0x8001F1A0
	// End Line: 1453

void Draw__34tMenuItemControllerLeftRightChoiceiib( (tMenuItemControllerLeftRightChoice *this,int ox,int oy)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// struct tInsideBoxLeftRightSlider * /*$ra*/ __25tInsideBoxLeftRightSliderUiP13tListIterator(struct tInsideBoxLeftRightSlider *this /*$s0*/, unsigned int textDescription /*$a1*/, struct tListIterator *dataPtr /*$a2*/)
 // line 1465, offset 0x8001f288
	/* begin block 1 */
		// Start line: 1466
		// Start offset: 0x8001F288
	/* end block 1 */
	// End offset: 0x8001F288
	// End Line: 1466

tInsideBoxLeftRightSlider * __25tInsideBoxLeftRightSliderUiP13tListIterator( (tInsideBoxLeftRightSlider *this,uint textDescription,tListIterator *dataPtr)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// autogenerated function stub: 
// void /*$ra*/ _._25tInsideBoxLeftRightSlider(struct tInsideBoxLeftRightSlider *this /*$a0*/, int __in_chrg /*$a1*/)
void _._25tInsideBoxLeftRightSlider _._25tInsideBoxLeftRightSlider(tInsideBoxLeftRightSlider *this /*$a0*/this, int __in_chrg /*$a1*/ __in_chrg)
{ // line 1473, offset 0x8001f2c8
	/* begin block 1 */
		// Start line: 1474
		// Start offset: 0x8001F2C8
	/* end block 1 */
	// End offset: 0x8001F2C8
	// End Line: 1474

}


// decompiled code
// original method signature: 
// void /*$ra*/ Draw__25tInsideBoxLeftRightSlideriiib(struct tInsideBoxLeftRightSlider *this /*$s0*/, int x /*$a1*/, int y /*$a2*/, int w /*$s1*/)
 // line 1480, offset 0x8001f2f0
	/* begin block 1 */
		// Start line: 1481
		// Start offset: 0x8001F2F0
		// Variables:
	// 		int col; // $s3
	// 		int coltext; // $s4

		/* begin block 1.1 */
			// Start line: 1481
			// Start offset: 0x8001F2F0
			// Variables:
		// 		struct tListIterator *this; // $v1

			/* begin block 1.1.1 */
				// Start line: 1481
				// Start offset: 0x8001F2F0
			/* end block 1.1.1 */
			// End offset: 0x8001F2F0
			// End Line: 1481
		/* end block 1.1 */
		// End offset: 0x8001F2F0
		// End Line: 1481

		/* begin block 1.2 */
			// Start line: 1481
			// Start offset: 0x8001F2F0

			/* begin block 1.2.1 */
				// Start line: 1481
				// Start offset: 0x8001F2F0
			/* end block 1.2.1 */
			// End offset: 0x8001F2F0
			// End Line: 1481
		/* end block 1.2 */
		// End offset: 0x8001F2F0
		// End Line: 1481
	/* end block 1 */
	// End offset: 0x8001F2F0
	// End Line: 1481

void Draw__25tInsideBoxLeftRightSlideriiib(tInsideBoxLeftRightSlider *this,int x,int y,int w)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// struct tInsideBoxTwoWaySlider * /*$ra*/ __22tInsideBoxTwoWaySliderUiP13tListIteratori(struct tInsideBoxTwoWaySlider *this /*$s0*/, unsigned int textDescription /*$a1*/, struct tListIterator *dataPtr /*$a2*/, int type /*$s1*/)
 // line 1497, offset 0x8001f474
	/* begin block 1 */
		// Start line: 1498
		// Start offset: 0x8001F474
	/* end block 1 */
	// End offset: 0x8001F474
	// End Line: 1498

tInsideBoxTwoWaySlider * __22tInsideBoxTwoWaySliderUiP13tListIteratori( (tInsideBoxTwoWaySlider *this,uint textDescription,tListIterator *dataPtr,int type)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// autogenerated function stub: 
// void /*$ra*/ _._22tInsideBoxTwoWaySlider(struct tInsideBoxTwoWaySlider *this /*$a0*/, int __in_chrg /*$a1*/)
void _._22tInsideBoxTwoWaySlider _._22tInsideBoxTwoWaySlider(tInsideBoxTwoWaySlider *this /*$a0*/this, int __in_chrg /*$a1*/ __in_chrg)
{ // line 1508, offset 0x8001f4c8
	/* begin block 1 */
		// Start line: 1509
		// Start offset: 0x8001F4C8
	/* end block 1 */
	// End offset: 0x8001F4C8
	// End Line: 1509

}


// decompiled code
// original method signature: 
// void /*$ra*/ ProcessInput__22tInsideBoxTwoWaySlider7tPlayerR13tInputKeyTypeR12tMenuCommand(struct tInsideBoxTwoWaySlider *this /*$s1*/, enum tInputKeyType *keyval /*$s0*/)
 // line 1512, offset 0x8001f4f0
	/* begin block 1 */
		// Start line: 1513
		// Start offset: 0x8001F4F0
	/* end block 1 */
	// End offset: 0x8001F58C
	// End Line: 1537

void ProcessInput__22tInsideBoxTwoWaySlider7tPlayerR13tInputKeyTypeR12tMenuCommand( (tInsideBoxTwoWaySlider *this,tInputKeyType *keyval)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ Draw__22tInsideBoxTwoWaySlideriiib(struct tInsideBoxTwoWaySlider *this /*$s6*/, int x /*$s0*/, int y /*$s1*/, int w /*$s2*/)
 // line 1543, offset 0x8001f5a0
	/* begin block 1 */
		// Start line: 1544
		// Start offset: 0x8001F5A0
		// Variables:
	// 		int ww; // $s1
	// 		int col; // $s0
	// 		int col2; // $s4
	// 		int coltext; // $s5

		/* begin block 1.1 */
			// Start line: 1550
			// Start offset: 0x8001F5E8
			// Variables:
		// 		struct tListIterator *this; // $v1

			/* begin block 1.1.1 */
				// Start line: 1550
				// Start offset: 0x8001F5E8
			/* end block 1.1.1 */
			// End offset: 0x8001F5E8
			// End Line: 1550
		/* end block 1.1 */
		// End offset: 0x8001F5E8
		// End Line: 1550

		/* begin block 1.2 */
			// Start line: 1550
			// Start offset: 0x8001F5E8

			/* begin block 1.2.1 */
				// Start line: 1550
				// Start offset: 0x8001F5E8
			/* end block 1.2.1 */
			// End offset: 0x8001F5E8
			// End Line: 1550
		/* end block 1.2 */
		// End offset: 0x8001F5E8
		// End Line: 1550

		/* begin block 1.3 */
			// Start line: 1550
			// Start offset: 0x8001F5E8
			// Variables:
		// 		struct tListIterator *this; // $v0

			/* begin block 1.3.1 */
				// Start line: 1550
				// Start offset: 0x8001F5E8
			/* end block 1.3.1 */
			// End offset: 0x8001F5E8
			// End Line: 1550
		/* end block 1.3 */
		// End offset: 0x8001F5E8
		// End Line: 1550

		/* begin block 1.4 */
			// Start line: 1550
			// Start offset: 0x8001F5E8

			/* begin block 1.4.1 */
				// Start line: 1550
				// Start offset: 0x8001F5E8
			/* end block 1.4.1 */
			// End offset: 0x8001F5E8
			// End Line: 1550
		/* end block 1.4 */
		// End offset: 0x8001F5E8
		// End Line: 1550
	/* end block 1 */
	// End offset: 0x8001F5E8
	// End Line: 1556

void Draw__22tInsideBoxTwoWaySlideriiib(tInsideBoxTwoWaySlider *this,int x,int y,int w)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// char /*$ra*/ GetCurrentStickRange__Fi(int player /*$a0*/)
 // line 1578, offset 0x8001f860
	/* begin block 1 */
		// Start line: 1579
		// Start offset: 0x8001F860
		// Variables:
	// 		int range1; // $a1
	// 		int range2; // $v0
	/* end block 1 */
	// End offset: 0x8001F8B4
	// End Line: 1583

char GetCurrentStickRange__Fi(int player)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// char /*$ra*/ GetCurrentStickRange2__Fi(int player /*$a0*/)
 // line 1586, offset 0x8001f8bc
	/* begin block 1 */
		// Start line: 1587
		// Start offset: 0x8001F8BC
		// Variables:
	// 		int range1; // $a1
	// 		int range2; // $v0
	/* end block 1 */
	// End offset: 0x8001F910
	// End Line: 1591

char GetCurrentStickRange2__Fi(int player)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ Calibrate__22tInsideBoxTwoWaySlider(struct tInsideBoxTwoWaySlider *this /*$s0*/)
 // line 1595, offset 0x8001f918
	/* begin block 1 */
		// Start line: 1596
		// Start offset: 0x8001F918
		// Variables:
	// 		int range; // $a1
	// 		int player; // $s2
	/* end block 1 */
	// End offset: 0x8001FC20
	// End Line: 1679

void Calibrate__22tInsideBoxTwoWaySlider(tInsideBoxTwoWaySlider *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// struct tUserNameMenuItem * /*$ra*/ __17tUserNameMenuItemUi(struct tUserNameMenuItem *this /*$s0*/, unsigned int textDescription /*$a1*/)
 // line 1688, offset 0x8001fc38
	/* begin block 1 */
		// Start line: 1689
		// Start offset: 0x8001FC38
		// Variables:
	// 		short i; // $a0
	/* end block 1 */
	// End offset: 0x8001FC98
	// End Line: 1698

tUserNameMenuItem * __17tUserNameMenuItemUi(tUserNameMenuItem *this,uint textDescription)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// unsigned int /*$ra*/ CheckForCheats__FPc(char *fData /*$s0*/)
 // line 1701, offset 0x8001fcac
	/* begin block 1 */
		// Start line: 1702
		// Start offset: 0x8001FCAC
		// Variables:
	// 		int len; // $v1
	/* end block 1 */
	// End offset: 0x8001FD14
	// End Line: 1709

uint CheckForCheats__FPc(char *fData)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ ProcessInput__17tUserNameMenuItem7tPlayerR13tInputKeyTypeR12tMenuCommand(struct tUserNameMenuItem *this /*$s0*/, enum tInputKeyType *keyval /*$s1*/)
 // line 1712, offset 0x8001fd2c
	/* begin block 1 */
		// Start line: 1713
		// Start offset: 0x8001FD2C

		/* begin block 1.1 */
			// Start line: 1713
			// Start offset: 0x8001FD2C

			/* begin block 1.1.1 */
				// Start line: 1718
				// Start offset: 0x8001FD90

				/* begin block 1.1.1.1 */
					// Start line: 1779
					// Start offset: 0x8001FEF0

					/* begin block 1.1.1.1.1 */
						// Start line: 1791
						// Start offset: 0x8001FF4C

						/* begin block 1.1.1.1.1.1 */
							// Start line: 1791
							// Start offset: 0x8001FF4C

							/* begin block 1.1.1.1.1.1.1 */
								// Start line: 1792
								// Start offset: 0x8001FF64

								/* begin block 1.1.1.1.1.1.1.1 */
									// Start line: 1793
									// Start offset: 0x8001FF64

									/* begin block 1.1.1.1.1.1.1.1.1 */
										// Start line: 1798
										// Start offset: 0x8001FF84

										/* begin block 1.1.1.1.1.1.1.1.1.1 */
											// Start line: 1799
											// Start offset: 0x8001FF84

											/* begin block 1.1.1.1.1.1.1.1.1.1.1 */
												// Start line: 1799
												// Start offset: 0x8001FF84
												// Variables:
											// 		struct tFEApplication *this; // $v0

												/* begin block 1.1.1.1.1.1.1.1.1.1.1.1 */
													// Start line: 1799
													// Start offset: 0x8001FF84
												/* end block 1.1.1.1.1.1.1.1.1.1.1.1 */
												// End offset: 0x8001FF84
												// End Line: 1799
											/* end block 1.1.1.1.1.1.1.1.1.1.1 */
											// End offset: 0x8001FF84
											// End Line: 1799

											/* begin block 1.1.1.1.1.1.1.1.1.1.2 */
												// Start line: 1799
												// Start offset: 0x8001FF84

												/* begin block 1.1.1.1.1.1.1.1.1.1.2.1 */
													// Start line: 1799
													// Start offset: 0x8001FF84
												/* end block 1.1.1.1.1.1.1.1.1.1.2.1 */
												// End offset: 0x8001FF84
												// End Line: 1799
											/* end block 1.1.1.1.1.1.1.1.1.1.2 */
											// End offset: 0x8001FF84
											// End Line: 1799
										/* end block 1.1.1.1.1.1.1.1.1.1 */
										// End offset: 0x8001FFAC
										// End Line: 1805
									/* end block 1.1.1.1.1.1.1.1.1 */
									// End offset: 0x8001FFAC
									// End Line: 1808
								/* end block 1.1.1.1.1.1.1.1 */
								// End offset: 0x8001FFAC
								// End Line: 1808
							/* end block 1.1.1.1.1.1.1 */
							// End offset: 0x8001FFB4
							// End Line: 1810
						/* end block 1.1.1.1.1.1 */
						// End offset: 0x80020060
						// End Line: 1836
					/* end block 1.1.1.1.1 */
					// End offset: 0x80020060
					// End Line: 1836
				/* end block 1.1.1.1 */
				// End offset: 0x80020060
				// End Line: 1836
			/* end block 1.1.1 */
			// End offset: 0x80020060
			// End Line: 1840
		/* end block 1.1 */
		// End offset: 0x80020060
		// End Line: 1840
	/* end block 1 */
	// End offset: 0x800200CC
	// End Line: 1850

void ProcessInput__17tUserNameMenuItem7tPlayerR13tInputKeyTypeR12tMenuCommand( (tUserNameMenuItem *this,tInputKeyType *keyval)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// int /*$ra*/ SpecialCharacter__Fc(char current /*$a0*/)
 // line 1853, offset 0x800200ec
	/* begin block 1 */
		// Start line: 1854
		// Start offset: 0x800200EC
		// Variables:
	// 		int ret; // $a1
	/* end block 1 */
	// End offset: 0x80020174
	// End Line: 1870

int SpecialCharacter__Fc(char current)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ Draw__17tUserNameMenuItemb(struct tUserNameMenuItem *this /*$s2*/)
 // line 1874, offset 0x8002017c
	/* begin block 1 */
		// Start line: 1875
		// Start offset: 0x8002017C
		// Variables:
	// 		int x; // stack offset -48
	// 		int y; // $fp
	// 		struct tTexture_ShapeInfo *shape; // $s6

		/* begin block 1.1 */
			// Start line: 1875
			// Start offset: 0x8002017C

			/* begin block 1.1.1 */
				// Start line: 1886
				// Start offset: 0x800201E4
				// Variables:
			// 		short j; // $s0
			// 		char output[2]; // stack offset -104
			// 		int ColText; // $s3
			// 		int Col; // $s7
			// 		struct tDrawShapeExtended tCol; // stack offset -96
			// 		short sl; // stack offset -44
			// 		short startx; // $s1
			// 		int xx; // $s1
			// 		int yy; // $s0

				/* begin block 1.1.1.1 */
					// Start line: 1919
					// Start offset: 0x8002035C

					/* begin block 1.1.1.1.1 */
						// Start line: 1923
						// Start offset: 0x80020394
						// Variables:
					// 		struct tDrawShapeExtended fFlags; // stack offset -72
					// 		char current; // $v1

						/* begin block 1.1.1.1.1.1 */
							// Start line: 1925
							// Start offset: 0x80020394

							/* begin block 1.1.1.1.1.1.1 */
								// Start line: 1932
								// Start offset: 0x800203E8

								/* begin block 1.1.1.1.1.1.1.1 */
									// Start line: 1932
									// Start offset: 0x800203E8

									/* begin block 1.1.1.1.1.1.1.1.1 */
										// Start line: 1938
										// Start offset: 0x80020408

										/* begin block 1.1.1.1.1.1.1.1.1.1 */
											// Start line: 1938
											// Start offset: 0x80020408

											/* begin block 1.1.1.1.1.1.1.1.1.1.1 */
												// Start line: 1944
												// Start offset: 0x80020428
												// Variables:
											// 		int shapetodraw; // $v0
											/* end block 1.1.1.1.1.1.1.1.1.1.1 */
											// End offset: 0x80020490
											// End Line: 1953
										/* end block 1.1.1.1.1.1.1.1.1.1 */
										// End offset: 0x80020490
										// End Line: 1953
									/* end block 1.1.1.1.1.1.1.1.1 */
									// End offset: 0x80020490
									// End Line: 1953
								/* end block 1.1.1.1.1.1.1.1 */
								// End offset: 0x80020490
								// End Line: 1953
							/* end block 1.1.1.1.1.1.1 */
							// End offset: 0x80020490
							// End Line: 1953
						/* end block 1.1.1.1.1.1 */
						// End offset: 0x80020490
						// End Line: 1953
					/* end block 1.1.1.1.1 */
					// End offset: 0x80020490
					// End Line: 1953
				/* end block 1.1.1.1 */
				// End offset: 0x80020490
				// End Line: 1953
			/* end block 1.1.1 */
			// End offset: 0x80020490
			// End Line: 1953
		/* end block 1.1 */
		// End offset: 0x80020490
		// End Line: 1953
	/* end block 1 */
	// End offset: 0x80020490
	// End Line: 1960

void Draw__17tUserNameMenuItemb(tUserNameMenuItem *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ TransitionOff__17tUserNameMenuItem(struct tUserNameMenuItem *this /*$a0*/)
 // line 1973, offset 0x80020574
	/* begin block 1 */
		// Start line: 1974
		// Start offset: 0x80020574
	/* end block 1 */
	// End offset: 0x80020574
	// End Line: 1975

void TransitionOff__17tUserNameMenuItem(tUserNameMenuItem *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ TransitionOn__17tUserNameMenuItem(struct tUserNameMenuItem *this /*$s1*/)
 // line 1978, offset 0x80020580
	/* begin block 1 */
		// Start line: 1979
		// Start offset: 0x80020580
		// Variables:
	// 		short i; // $s2
	// 		short NumberOfRows[6]; // stack offset -40
	/* end block 1 */
	// End offset: 0x80020798
	// End Line: 2014

void TransitionOn__17tUserNameMenuItem(tUserNameMenuItem *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// unsigned int /*$ra*/ TransitionIsFinished__17tUserNameMenuItem(struct tUserNameMenuItem *this /*$a0*/)
 // line 2018, offset 0x800207b4
	/* begin block 1 */
		// Start line: 2019
		// Start offset: 0x800207B4

		/* begin block 1.1 */
			// Start line: 2020
			// Start offset: 0x800207B4

			/* begin block 1.1.1 */
				// Start line: 2024
				// Start offset: 0x800207D4

				/* begin block 1.1.1.1 */
					// Start line: 2024
					// Start offset: 0x800207D4

					/* begin block 1.1.1.1.1 */
						// Start line: 2026
						// Start offset: 0x800207F8

						/* begin block 1.1.1.1.1.1 */
							// Start line: 2026
							// Start offset: 0x800207F8

							/* begin block 1.1.1.1.1.1.1 */
								// Start line: 2026
								// Start offset: 0x800207F8

								/* begin block 1.1.1.1.1.1.1.1 */
									// Start line: 2026
									// Start offset: 0x800207F8
								/* end block 1.1.1.1.1.1.1.1 */
								// End offset: 0x800207F8
								// End Line: 2026
							/* end block 1.1.1.1.1.1.1 */
							// End offset: 0x800207F8
							// End Line: 2026
						/* end block 1.1.1.1.1.1 */
						// End offset: 0x80020814
						// End Line: 2027
					/* end block 1.1.1.1.1 */
					// End offset: 0x80020814
					// End Line: 2027
				/* end block 1.1.1.1 */
				// End offset: 0x80020814
				// End Line: 2027
			/* end block 1.1.1 */
			// End offset: 0x80020814
			// End Line: 2027
		/* end block 1.1 */
		// End offset: 0x80020814
		// End Line: 2027
	/* end block 1 */
	// End offset: 0x80020814
	// End Line: 2029

uint TransitionIsFinished__17tUserNameMenuItem(tUserNameMenuItem *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ UpdateTransition__17tUserNameMenuItemb(struct tUserNameMenuItem *this /*$s0*/, unsigned int selected /*$s1*/)
 // line 2032, offset 0x80020820
	/* begin block 1 */
		// Start line: 2033
		// Start offset: 0x80020820
	/* end block 1 */
	// End offset: 0x80020860
	// End Line: 2037

void UpdateTransition__17tUserNameMenuItemb(tUserNameMenuItem *this,uint selected)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ Draw__19tMemoryCardMenuItemb(struct tMemoryCardMenuItem *this /*$s2*/)
 // line 2048, offset 0x8002089c
	/* begin block 1 */
		// Start line: 2049
		// Start offset: 0x8002089C
		// Variables:
	// 		int fEnableFade; // $s0
	// 		int fEnableSlide; // $s3
	// 		int x; // $s4
	// 		int y; // $s6
	// 		int ColText; // $s1
	// 		int Col; // $s0
	// 		struct tDrawShapeExtended tCol; // stack offset -56
	// 		int fWidth; // $s0
	// 		struct tTexture_ShapeInfo *shape; // $s1

		/* begin block 1.1 */
			// Start line: 2049
			// Start offset: 0x8002089C

			/* begin block 1.1.1 */
				// Start line: 2049
				// Start offset: 0x8002089C
				// Variables:
			// 		struct tMenuItem *this; // $s2

				/* begin block 1.1.1.1 */
					// Start line: 2049
					// Start offset: 0x8002089C
				/* end block 1.1.1.1 */
				// End offset: 0x8002089C
				// End Line: 2049
			/* end block 1.1.1 */
			// End offset: 0x8002089C
			// End Line: 2049
		/* end block 1.1 */
		// End offset: 0x800208F4
		// End Line: 2050
	/* end block 1 */
	// End offset: 0x80020ACC
	// End Line: 2082

void Draw__19tMemoryCardMenuItemb(tMemoryCardMenuItem *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ ProcessInput__35tInsideBoxControllerLeftRightSlider7tPlayerR13tInputKeyTypeR12tMenuCommand(struct tInsideBoxControllerLeftRightSlider *this /*$s0*/, enum tPlayer fromPlayer /*$s2*/, enum tInputKeyType *keyval /*$s1*/, struct tMenuCommand *command /*$s3*/)
 // line 2088, offset 0x80020af4
	/* begin block 1 */
		// Start line: 2089
		// Start offset: 0x80020AF4

		/* begin block 1.1 */
			// Start line: 2089
			// Start offset: 0x80020AF4

			/* begin block 1.1.1 */
				// Start line: 2091
				// Start offset: 0x80020B34

				/* begin block 1.1.1.1 */
					// Start line: 2092
					// Start offset: 0x80020B34

					/* begin block 1.1.1.1.1 */
						// Start line: 2092
						// Start offset: 0x80020B40
						// Variables:
					// 		struct tListIterator *this; // $v1

						/* begin block 1.1.1.1.1.1 */
							// Start line: 2092
							// Start offset: 0x80020B40
						/* end block 1.1.1.1.1.1 */
						// End offset: 0x80020B40
						// End Line: 2092
					/* end block 1.1.1.1.1 */
					// End offset: 0x80020B40
					// End Line: 2092

					/* begin block 1.1.1.1.2 */
						// Start line: 2093
						// Start offset: 0x80020B7C

						/* begin block 1.1.1.1.2.1 */
							// Start line: 2093
							// Start offset: 0x80020B7C
							// Variables:
						// 		struct tScreenControllerConfig *this; // $v1

							/* begin block 1.1.1.1.2.1.1 */
								// Start line: 2093
								// Start offset: 0x80020B7C
							/* end block 1.1.1.1.2.1.1 */
							// End offset: 0x80020B88
							// End Line: 2093
						/* end block 1.1.1.1.2.1 */
						// End offset: 0x80020B88
						// End Line: 2093
					/* end block 1.1.1.1.2 */
					// End offset: 0x80020B88
					// End Line: 2093
				/* end block 1.1.1.1 */
				// End offset: 0x80020B88
				// End Line: 2093
			/* end block 1.1.1 */
			// End offset: 0x80020B88
			// End Line: 2093
		/* end block 1.1 */
		// End offset: 0x80020B88
		// End Line: 2093
	/* end block 1 */
	// End offset: 0x80020B88
	// End Line: 2095

void ProcessInput__35tInsideBoxControllerLeftRightSlider7tPlayerR13tInputKeyTypeR12tMenuCommand( (tInsideBoxControllerLeftRightSlider *this,tPlayer fromPlayer,tInputKeyType *keyval, tMenuCommand *command)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}





