#ifndef FEMENU_H
#define FEMENU_H

extern void TransitionOff__9tMenuItem(struct tMenuItem *this); // 0x80025AB0

extern void TransitionOn__9tMenuItem(struct tMenuItem *this); // 0x80025AA8


// decompiled code
// original method signature: 
// void /*$ra*/ TransitionOff__9tMenuItem(struct tMenuItem *this /*$a0*/)
 // line 274, offset 0x80025ab0
	/* begin block 1 */
		// Start line: 275
		// Start offset: 0x80025AB0
	/* end block 1 */
	// End offset: 0x80025AB0
	// End Line: 275

/* WARNING: Control flow encountered bad instruction data */

void TransitionOff__9tMenuItem(tMenuItem *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ TransitionOn__9tMenuItem(struct tMenuItem *this /*$a0*/)
 // line 275, offset 0x80025aa8
	/* begin block 1 */
		// Start line: 276
		// Start offset: 0x80025AA8
	/* end block 1 */
	// End offset: 0x80025AA8
	// End Line: 276

/* WARNING: Control flow encountered bad instruction data */

void TransitionOn__9tMenuItem(tMenuItem *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}




#endif
