#include "NFS4.H"
#include "FEMENUDEFS.H"

// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_SetOnePlayer__FR12tMenuCommand(struct tMenuCommand *command /*$a0*/)
 // line 145, offset 0x8002c0e0
	/* begin block 1 */
		// Start line: 146
		// Start offset: 0x8002C0E0
	/* end block 1 */
	// End offset: 0x8002C11C
	// End Line: 154

/* WARNING: Control flow encountered bad instruction data */

void MenuExtended_SetOnePlayer__FR12tMenuCommand(tMenuCommand *command)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_SetTwoPlayer__FR12tMenuCommand(struct tMenuCommand *command /*$a0*/)
 // line 158, offset 0x8002c12c
	/* begin block 1 */
		// Start line: 159
		// Start offset: 0x8002C12C
	/* end block 1 */
	// End offset: 0x8002C16C
	// End Line: 168

/* WARNING: Control flow encountered bad instruction data */

void MenuExtended_SetTwoPlayer__FR12tMenuCommand(tMenuCommand *command)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_SetTestDrive__FR12tMenuCommand()
 // line 172, offset 0x8002c17c
	/* begin block 1 */
		// Start line: 173
		// Start offset: 0x8002C17C
	/* end block 1 */
	// End offset: 0x8002C17C
	// End Line: 174

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void MenuExtended_SetTestDrive__FR12tMenuCommand(void)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_SetSingleRace__FR12tMenuCommand()
 // line 180, offset 0x8002c198
	/* begin block 1 */
		// Start line: 181
		// Start offset: 0x8002C198
	/* end block 1 */
	// End offset: 0x8002C198
	// End Line: 181

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void MenuExtended_SetSingleRace__FR12tMenuCommand(void)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_SetTournament__FR12tMenuCommand()
 // line 195, offset 0x8002c1d8
	/* begin block 1 */
		// Start line: 196
		// Start offset: 0x8002C1D8
	/* end block 1 */
	// End offset: 0x8002C1D8
	// End Line: 196

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void MenuExtended_SetTournament__FR12tMenuCommand(void)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_SetSpecialEvent__FR12tMenuCommand()
 // line 204, offset 0x8002c220
	/* begin block 1 */
		// Start line: 205
		// Start offset: 0x8002C220
	/* end block 1 */
	// End offset: 0x8002C220
	// End Line: 205

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void MenuExtended_SetSpecialEvent__FR12tMenuCommand(void)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_SetSoloRace__FR12tMenuCommand()
 // line 213, offset 0x8002c268
	/* begin block 1 */
		// Start line: 214
		// Start offset: 0x8002C268
	/* end block 1 */
	// End offset: 0x8002C268
	// End Line: 215

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void MenuExtended_SetSoloRace__FR12tMenuCommand(void)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_GoToTwoPlayerSingleRace__FR12tMenuCommand(struct tMenuCommand *command /*$s1*/)
 // line 221, offset 0x8002c288
	/* begin block 1 */
		// Start line: 222
		// Start offset: 0x8002C288
		// Variables:
	// 		struct tDialogYesNoTri YesNoDialog; // stack offset -184

		/* begin block 1.1 */
			// Start line: 222
			// Start offset: 0x8002C288
			// Variables:
		// 		struct tDialogYesNoTri *this; // $s0
		/* end block 1.1 */
		// End offset: 0x8002C288
		// End Line: 222

		/* begin block 1.2 */
			// Start line: 222
			// Start offset: 0x8002C288

			/* begin block 1.2.1 */
				// Start line: 226
				// Start offset: 0x8002C2D0

				/* begin block 1.2.1.1 */
					// Start line: 226
					// Start offset: 0x8002C2D0

					/* begin block 1.2.1.1.1 */
						// Start line: 226
						// Start offset: 0x8002C2D0
					/* end block 1.2.1.1.1 */
					// End offset: 0x8002C2D0
					// End Line: 226
				/* end block 1.2.1.1 */
				// End offset: 0x8002C2D0
				// End Line: 226

				/* begin block 1.2.1.2 */
					// Start line: 226
					// Start offset: 0x8002C2D0

					/* begin block 1.2.1.2.1 */
						// Start line: 226
						// Start offset: 0x8002C2D0
					/* end block 1.2.1.2.1 */
					// End offset: 0x8002C2D0
					// End Line: 226
				/* end block 1.2.1.2 */
				// End offset: 0x8002C2D0
				// End Line: 226
			/* end block 1.2.1 */
			// End offset: 0x8002C30C
			// End Line: 232
		/* end block 1.2 */
		// End offset: 0x8002C37C
		// End Line: 244

		/* begin block 1.3 */
			// Start line: 223
			// Start offset: 0x8002C37C

			/* begin block 1.3.1 */
				// Start line: 223
				// Start offset: 0x8002C37C

				/* begin block 1.3.1.1 */
					// Start line: 223
					// Start offset: 0x8002C37C

					/* begin block 1.3.1.1.1 */
						// Start line: 223
						// Start offset: 0x8002C37C

						/* begin block 1.3.1.1.1.1 */
							// Start line: 223
							// Start offset: 0x8002C37C
						/* end block 1.3.1.1.1.1 */
						// End offset: 0x8002C37C
						// End Line: 223
					/* end block 1.3.1.1.1 */
					// End offset: 0x8002C37C
					// End Line: 223
				/* end block 1.3.1.1 */
				// End offset: 0x8002C37C
				// End Line: 223
			/* end block 1.3.1 */
			// End offset: 0x8002C37C
			// End Line: 223
		/* end block 1.3 */
		// End offset: 0x8002C37C
		// End Line: 223
	/* end block 1 */
	// End offset: 0x8002C37C
	// End Line: 223

/* WARNING: Control flow encountered bad instruction data */

void MenuExtended_GoToTwoPlayerSingleRace__FR12tMenuCommand(tMenuCommand *command)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_SetDuelRace__FR12tMenuCommand()
 // line 247, offset 0x8002c39c
	/* begin block 1 */
		// Start line: 248
		// Start offset: 0x8002C39C
	/* end block 1 */
	// End offset: 0x8002C39C
	// End Line: 248

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void MenuExtended_SetDuelRace__FR12tMenuCommand(void)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_SetFullGrid__FR12tMenuCommand()
 // line 255, offset 0x8002c3dc
	/* begin block 1 */
		// Start line: 256
		// Start offset: 0x8002C3DC
	/* end block 1 */
	// End offset: 0x8002C3DC
	// End Line: 256

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void MenuExtended_SetFullGrid__FR12tMenuCommand(void)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// int /*$ra*/ AskTheUserToSaveTheGame__Fv()
 // line 274, offset 0x8002c41c
	/* begin block 1 */
		// Start line: 275
		// Start offset: 0x8002C41C

		/* begin block 1.1 */
			// Start line: 275
			// Start offset: 0x8002C41C

			/* begin block 1.1.1 */
				// Start line: 276
				// Start offset: 0x8002C438
				// Variables:
			// 		struct tDialogYesNo YesNoDialog; // stack offset -176
			// 		int answer; // $s0

				/* begin block 1.1.1.1 */
					// Start line: 276
					// Start offset: 0x8002C438
					// Variables:
				// 		struct tDialogMessageString *this; // $s0

					/* begin block 1.1.1.1.1 */
						// Start line: 276
						// Start offset: 0x8002C438
					/* end block 1.1.1.1.1 */
					// End offset: 0x8002C438
					// End Line: 276
				/* end block 1.1.1.1 */
				// End offset: 0x8002C438
				// End Line: 276

				/* begin block 1.1.1.2 */
					// Start line: 276
					// Start offset: 0x8002C438

					/* begin block 1.1.1.2.1 */
						// Start line: 276
						// Start offset: 0x8002C438
					/* end block 1.1.1.2.1 */
					// End offset: 0x8002C438
					// End Line: 276
				/* end block 1.1.1.2 */
				// End offset: 0x8002C438
				// End Line: 276

				/* begin block 1.1.1.3 */
					// Start line: 276
					// Start offset: 0x8002C438

					/* begin block 1.1.1.3.1 */
						// Start line: 276
						// Start offset: 0x8002C438

						/* begin block 1.1.1.3.1.1 */
							// Start line: 276
							// Start offset: 0x8002C438

							/* begin block 1.1.1.3.1.1.1 */
								// Start line: 276
								// Start offset: 0x8002C438

								/* begin block 1.1.1.3.1.1.1.1 */
									// Start line: 276
									// Start offset: 0x8002C438
								/* end block 1.1.1.3.1.1.1.1 */
								// End offset: 0x8002C438
								// End Line: 276
							/* end block 1.1.1.3.1.1.1 */
							// End offset: 0x8002C438
							// End Line: 276
						/* end block 1.1.1.3.1.1 */
						// End offset: 0x8002C438
						// End Line: 276
					/* end block 1.1.1.3.1 */
					// End offset: 0x8002C438
					// End Line: 276
				/* end block 1.1.1.3 */
				// End offset: 0x8002C438
				// End Line: 276
			/* end block 1.1.1 */
			// End offset: 0x8002C438
			// End Line: 291
		/* end block 1.1 */
		// End offset: 0x8002C438
		// End Line: 291
	/* end block 1 */
	// End offset: 0x8002C484
	// End Line: 291

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

int AskTheUserToSaveTheGame__Fv(void)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_TransitionFromPostGameToMainMenu__FR12tMenuCommand(struct tMenuCommand *command /*$a0*/)
 // line 295, offset 0x8002c494
	/* begin block 1 */
		// Start line: 296
		// Start offset: 0x8002C494
	/* end block 1 */
	// End offset: 0x8002C494
	// End Line: 297

/* WARNING: Control flow encountered bad instruction data */

void MenuExtended_TransitionFromPostGameToMainMenu__FR12tMenuCommand(tMenuCommand *command)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_TransitionFromPostGameToMainMenuAndSaveGame__FR12tMenuCommand(struct tMenuCommand *command /*$s0*/)
 // line 301, offset 0x8002c4b0
	/* begin block 1 */
		// Start line: 302
		// Start offset: 0x8002C4B0
	/* end block 1 */
	// End offset: 0x8002C4EC
	// End Line: 309

/* WARNING: Control flow encountered bad instruction data */

void MenuExtended_TransitionFromPostGameToMainMenuAndSaveGame__FR12tMenuCommand
               (tMenuCommand *command)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_GoToCarSelect__FR12tMenuCommand(struct tMenuCommand *command /*$s2*/)
 // line 313, offset 0x8002c4fc
	/* begin block 1 */
		// Start line: 314
		// Start offset: 0x8002C4FC
		// Variables:
	// 		struct tTrackInformation trackInfo; // stack offset -64

		/* begin block 1.1 */
			// Start line: 314
			// Start offset: 0x8002C4FC
			// Variables:
		// 		struct tFEApplication *this; // $v1

			/* begin block 1.1.1 */
				// Start line: 314
				// Start offset: 0x8002C4FC
			/* end block 1.1.1 */
			// End offset: 0x8002C4FC
			// End Line: 314
		/* end block 1.1 */
		// End offset: 0x8002C4FC
		// End Line: 314

		/* begin block 1.2 */
			// Start line: 314
			// Start offset: 0x8002C4FC

			/* begin block 1.2.1 */
				// Start line: 321
				// Start offset: 0x8002C554

				/* begin block 1.2.1.1 */
					// Start line: 321
					// Start offset: 0x8002C554

					/* begin block 1.2.1.1.1 */
						// Start line: 321
						// Start offset: 0x8002C554
					/* end block 1.2.1.1.1 */
					// End offset: 0x8002C554
					// End Line: 321
				/* end block 1.2.1.1 */
				// End offset: 0x8002C554
				// End Line: 321
			/* end block 1.2.1 */
			// End offset: 0x8002C570
			// End Line: 324
		/* end block 1.2 */
		// End offset: 0x8002C570
		// End Line: 324

		/* begin block 1.3 */
			// Start line: 363
			// Start offset: 0x8002C680

			/* begin block 1.3.1 */
				// Start line: 364
				// Start offset: 0x8002C6A8

				/* begin block 1.3.1.1 */
					// Start line: 366
					// Start offset: 0x8002C6A8

					/* begin block 1.3.1.1.1 */
						// Start line: 367
						// Start offset: 0x8002C6C8

						/* begin block 1.3.1.1.1.1 */
							// Start line: 367
							// Start offset: 0x8002C6C8

							/* begin block 1.3.1.1.1.1.1 */
								// Start line: 367
								// Start offset: 0x8002C6C8
							/* end block 1.3.1.1.1.1.1 */
							// End offset: 0x8002C6C8
							// End Line: 367
						/* end block 1.3.1.1.1.1 */
						// End offset: 0x8002C6C8
						// End Line: 367
					/* end block 1.3.1.1.1 */
					// End offset: 0x8002C6C8
					// End Line: 367

					/* begin block 1.3.1.1.2 */
						// Start line: 368
						// Start offset: 0x8002C6D8

						/* begin block 1.3.1.1.2.1 */
							// Start line: 368
							// Start offset: 0x8002C6D8

							/* begin block 1.3.1.1.2.1.1 */
								// Start line: 368
								// Start offset: 0x8002C6D8
							/* end block 1.3.1.1.2.1.1 */
							// End offset: 0x8002C6D8
							// End Line: 368
						/* end block 1.3.1.1.2.1 */
						// End offset: 0x8002C6D8
						// End Line: 368
					/* end block 1.3.1.1.2 */
					// End offset: 0x8002C6D8
					// End Line: 368
				/* end block 1.3.1.1 */
				// End offset: 0x8002C6D8
				// End Line: 368

				/* begin block 1.3.1.2 */
					// Start line: 369
					// Start offset: 0x8002C6E4

					/* begin block 1.3.1.2.1 */
						// Start line: 369
						// Start offset: 0x8002C6E4
					/* end block 1.3.1.2.1 */
					// End offset: 0x8002C6E4
					// End Line: 369
				/* end block 1.3.1.2 */
				// End offset: 0x8002C6E4
				// End Line: 369

				/* begin block 1.3.1.3 */
					// Start line: 376
					// Start offset: 0x8002C6F8

					/* begin block 1.3.1.3.1 */
						// Start line: 377
						// Start offset: 0x8002C708

						/* begin block 1.3.1.3.1.1 */
							// Start line: 377
							// Start offset: 0x8002C708

							/* begin block 1.3.1.3.1.1.1 */
								// Start line: 377
								// Start offset: 0x8002C708
							/* end block 1.3.1.3.1.1.1 */
							// End offset: 0x8002C708
							// End Line: 377
						/* end block 1.3.1.3.1.1 */
						// End offset: 0x8002C708
						// End Line: 377
					/* end block 1.3.1.3.1 */
					// End offset: 0x8002C708
					// End Line: 377

					/* begin block 1.3.1.3.2 */
						// Start line: 378
						// Start offset: 0x8002C718

						/* begin block 1.3.1.3.2.1 */
							// Start line: 378
							// Start offset: 0x8002C718

							/* begin block 1.3.1.3.2.1.1 */
								// Start line: 379
								// Start offset: 0x8002C728

								/* begin block 1.3.1.3.2.1.1.1 */
									// Start line: 379
									// Start offset: 0x8002C728

									/* begin block 1.3.1.3.2.1.1.1.1 */
										// Start line: 379
										// Start offset: 0x8002C728
									/* end block 1.3.1.3.2.1.1.1.1 */
									// End offset: 0x8002C728
									// End Line: 379
								/* end block 1.3.1.3.2.1.1.1 */
								// End offset: 0x8002C728
								// End Line: 379
							/* end block 1.3.1.3.2.1.1 */
							// End offset: 0x8002C728
							// End Line: 379

							/* begin block 1.3.1.3.2.1.2 */
								// Start line: 381
								// Start offset: 0x8002C738

								/* begin block 1.3.1.3.2.1.2.1 */
									// Start line: 381
									// Start offset: 0x8002C738

									/* begin block 1.3.1.3.2.1.2.1.1 */
										// Start line: 381
										// Start offset: 0x8002C738
									/* end block 1.3.1.3.2.1.2.1.1 */
									// End offset: 0x8002C744
									// End Line: 381
								/* end block 1.3.1.3.2.1.2.1 */
								// End offset: 0x8002C744
								// End Line: 381
							/* end block 1.3.1.3.2.1.2 */
							// End offset: 0x8002C744
							// End Line: 381
						/* end block 1.3.1.3.2.1 */
						// End offset: 0x8002C744
						// End Line: 381
					/* end block 1.3.1.3.2 */
					// End offset: 0x8002C744
					// End Line: 381
				/* end block 1.3.1.3 */
				// End offset: 0x8002C744
				// End Line: 381
			/* end block 1.3.1 */
			// End offset: 0x8002C744
			// End Line: 382
		/* end block 1.3 */
		// End offset: 0x8002C744
		// End Line: 382

		/* begin block 1.4 */
			// Start line: 413
			// Start offset: 0x8002C828

			/* begin block 1.4.1 */
				// Start line: 415
				// Start offset: 0x8002C84C

				/* begin block 1.4.1.1 */
					// Start line: 416
					// Start offset: 0x8002C84C

					/* begin block 1.4.1.1.1 */
						// Start line: 416
						// Start offset: 0x8002C84C
					/* end block 1.4.1.1.1 */
					// End offset: 0x8002C878
					// End Line: 417
				/* end block 1.4.1.1 */
				// End offset: 0x8002C878
				// End Line: 417
			/* end block 1.4.1 */
			// End offset: 0x8002C878
			// End Line: 419
		/* end block 1.4 */
		// End offset: 0x8002C878
		// End Line: 419
	/* end block 1 */
	// End offset: 0x8002C878
	// End Line: 419

/* WARNING: Control flow encountered bad instruction data */

void MenuExtended_GoToCarSelect__FR12tMenuCommand(tMenuCommand *command)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_GoToDealer__FR12tMenuCommand(struct tMenuCommand *command /*$a2*/)
 // line 423, offset 0x8002c890
	/* begin block 1 */
		// Start line: 424
		// Start offset: 0x8002C890
	/* end block 1 */
	// End offset: 0x8002C890
	// End Line: 424

/* WARNING: Control flow encountered bad instruction data */

void MenuExtended_GoToDealer__FR12tMenuCommand(tMenuCommand *command)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_GoToSeller__FR12tMenuCommand(struct tMenuCommand *command /*$a2*/)
 // line 432, offset 0x8002c8f8
	/* begin block 1 */
		// Start line: 433
		// Start offset: 0x8002C8F8
	/* end block 1 */
	// End offset: 0x8002C8F8
	// End Line: 433

/* WARNING: Control flow encountered bad instruction data */

void MenuExtended_GoToSeller__FR12tMenuCommand(tMenuCommand *command)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_GoToUpgrades__FR12tMenuCommand(struct tMenuCommand *command /*$a0*/)
 // line 441, offset 0x8002c960
	/* begin block 1 */
		// Start line: 442
		// Start offset: 0x8002C960
	/* end block 1 */
	// End offset: 0x8002C960
	// End Line: 442

/* WARNING: Control flow encountered bad instruction data */

void MenuExtended_GoToUpgrades__FR12tMenuCommand(tMenuCommand *command)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void * /*$ra*/ GenericMenuSaveGame__Fi(int showdialog /*$s0*/)
 // line 448, offset 0x8002c9a0
	/* begin block 1 */
		// Start line: 449
		// Start offset: 0x8002C9A0
		// Variables:
	// 		void * successful; // $s0
	// 		void * uninitafter; // $s2

		/* begin block 1.1 */
			// Start line: 449
			// Start offset: 0x8002C9A0
			// Variables:
		// 		struct tScreenMemcard *this; // $v1

			/* begin block 1.1.1 */
				// Start line: 449
				// Start offset: 0x8002C9A0
			/* end block 1.1.1 */
			// End offset: 0x8002C9A0
			// End Line: 449
		/* end block 1.1 */
		// End offset: 0x8002C9A0
		// End Line: 449

		/* begin block 1.2 */
			// Start line: 449
			// Start offset: 0x8002C9A0

			/* begin block 1.2.1 */
				// Start line: 457
				// Start offset: 0x8002C9F0

				/* begin block 1.2.1.1 */
					// Start line: 457
					// Start offset: 0x8002C9F0
					// Variables:
				// 		struct tDialogMessageString *this; // $s0

					/* begin block 1.2.1.1.1 */
						// Start line: 457
						// Start offset: 0x8002C9F0
					/* end block 1.2.1.1.1 */
					// End offset: 0x8002C9F0
					// End Line: 457
				/* end block 1.2.1.1 */
				// End offset: 0x8002C9F0
				// End Line: 457

				/* begin block 1.2.1.2 */
					// Start line: 460
					// Start offset: 0x8002CA10

					/* begin block 1.2.1.2.1 */
						// Start line: 460
						// Start offset: 0x8002CA10

						/* begin block 1.2.1.2.1.1 */
							// Start line: 460
							// Start offset: 0x8002CA10
						/* end block 1.2.1.2.1.1 */
						// End offset: 0x8002CA10
						// End Line: 460
					/* end block 1.2.1.2.1 */
					// End offset: 0x8002CA10
					// End Line: 460
				/* end block 1.2.1.2 */
				// End offset: 0x8002CA2C
				// End Line: 461
			/* end block 1.2.1 */
			// End offset: 0x8002CA68
			// End Line: 467
		/* end block 1.2 */
		// End offset: 0x8002CA68
		// End Line: 467

		/* begin block 1.3 */
			// Start line: 471
			// Start offset: 0x8002CA68
			// Variables:
		// 		struct tScreenMemcard *this; // $a0

			/* begin block 1.3.1 */
				// Start line: 471
				// Start offset: 0x8002CA68
			/* end block 1.3.1 */
			// End offset: 0x8002CA68
			// End Line: 471
		/* end block 1.3 */
		// End offset: 0x8002CA68
		// End Line: 471
	/* end block 1 */
	// End offset: 0x8002CA90
	// End Line: 477

/* WARNING: Control flow encountered bad instruction data */

void * GenericMenuSaveGame__Fi(int showdialog)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void * /*$ra*/ PinkSlipsPreSave__Fv()
 // line 484, offset 0x8002cabc
	/* begin block 1 */
		// Start line: 485
		// Start offset: 0x8002CABC

		/* begin block 1.1 */
			// Start line: 485
			// Start offset: 0x8002CABC

			/* begin block 1.1.1 */
				// Start line: 487
				// Start offset: 0x8002CADC
				// Variables:
			// 		void * ret; // $s1
			// 		struct tDialogYesNoTri YesNoDialog; // stack offset -184
			// 		int answer; // $v1

				/* begin block 1.1.1.1 */
					// Start line: 488
					// Start offset: 0x8002CADC
					// Variables:
				// 		struct tDialogYesNoTri *this; // $s0
				/* end block 1.1.1.1 */
				// End offset: 0x8002CADC
				// End Line: 488

				/* begin block 1.1.1.2 */
					// Start line: 488
					// Start offset: 0x8002CADC

					/* begin block 1.1.1.2.1 */
						// Start line: 488
						// Start offset: 0x8002CADC
					/* end block 1.1.1.2.1 */
					// End offset: 0x8002CADC
					// End Line: 488
				/* end block 1.1.1.2 */
				// End offset: 0x8002CADC
				// End Line: 488

				/* begin block 1.1.1.3 */
					// Start line: 488
					// Start offset: 0x8002CADC

					/* begin block 1.1.1.3.1 */
						// Start line: 488
						// Start offset: 0x8002CADC
					/* end block 1.1.1.3.1 */
					// End offset: 0x8002CADC
					// End Line: 488
				/* end block 1.1.1.3 */
				// End offset: 0x8002CADC
				// End Line: 488

				/* begin block 1.1.1.4 */
					// Start line: 488
					// Start offset: 0x8002CADC

					/* begin block 1.1.1.4.1 */
						// Start line: 504
						// Start offset: 0x8002CB4C

						/* begin block 1.1.1.4.1.1 */
							// Start line: 504
							// Start offset: 0x8002CB4C

							/* begin block 1.1.1.4.1.1.1 */
								// Start line: 504
								// Start offset: 0x8002CB4C

								/* begin block 1.1.1.4.1.1.1.1 */
									// Start line: 504
									// Start offset: 0x8002CB4C

									/* begin block 1.1.1.4.1.1.1.1.1 */
										// Start line: 504
										// Start offset: 0x8002CB4C

										/* begin block 1.1.1.4.1.1.1.1.1.1 */
											// Start line: 504
											// Start offset: 0x8002CB4C

											/* begin block 1.1.1.4.1.1.1.1.1.1.1 */
												// Start line: 504
												// Start offset: 0x8002CB4C

												/* begin block 1.1.1.4.1.1.1.1.1.1.1.1 */
													// Start line: 504
													// Start offset: 0x8002CB4C

													/* begin block 1.1.1.4.1.1.1.1.1.1.1.1.1 */
														// Start line: 504
														// Start offset: 0x8002CB4C
													/* end block 1.1.1.4.1.1.1.1.1.1.1.1.1 */
													// End offset: 0x8002CB4C
													// End Line: 504
												/* end block 1.1.1.4.1.1.1.1.1.1.1.1 */
												// End offset: 0x8002CB4C
												// End Line: 504
											/* end block 1.1.1.4.1.1.1.1.1.1.1 */
											// End offset: 0x8002CB4C
											// End Line: 504
										/* end block 1.1.1.4.1.1.1.1.1.1 */
										// End offset: 0x8002CB4C
										// End Line: 504
									/* end block 1.1.1.4.1.1.1.1.1 */
									// End offset: 0x8002CB4C
									// End Line: 504
								/* end block 1.1.1.4.1.1.1.1 */
								// End offset: 0x8002CB4C
								// End Line: 504
							/* end block 1.1.1.4.1.1.1 */
							// End offset: 0x8002CB58
							// End Line: 504
						/* end block 1.1.1.4.1.1 */
						// End offset: 0x8002CB58
						// End Line: 504
					/* end block 1.1.1.4.1 */
					// End offset: 0x8002CB58
					// End Line: 504
				/* end block 1.1.1.4 */
				// End offset: 0x8002CB58
				// End Line: 504

				/* begin block 1.1.1.5 */
					// Start line: 503
					// Start offset: 0x8002CB58

					/* begin block 1.1.1.5.1 */
						// Start line: 485
						// Start offset: 0x8002CB58

						/* begin block 1.1.1.5.1.1 */
							// Start line: 485
							// Start offset: 0x8002CB58

							/* begin block 1.1.1.5.1.1.1 */
								// Start line: 485
								// Start offset: 0x8002CB58

								/* begin block 1.1.1.5.1.1.1.1 */
									// Start line: 485
									// Start offset: 0x8002CB58

									/* begin block 1.1.1.5.1.1.1.1.1 */
										// Start line: 485
										// Start offset: 0x8002CB58
									/* end block 1.1.1.5.1.1.1.1.1 */
									// End offset: 0x8002CB58
									// End Line: 485
								/* end block 1.1.1.5.1.1.1.1 */
								// End offset: 0x8002CB58
								// End Line: 485
							/* end block 1.1.1.5.1.1.1 */
							// End offset: 0x8002CB58
							// End Line: 485
						/* end block 1.1.1.5.1.1 */
						// End offset: 0x8002CB58
						// End Line: 485
					/* end block 1.1.1.5.1 */
					// End offset: 0x8002CB58
					// End Line: 485
				/* end block 1.1.1.5 */
				// End offset: 0x8002CB58
				// End Line: 485
			/* end block 1.1.1 */
			// End offset: 0x8002CB6C
			// End Line: 504
		/* end block 1.1 */
		// End offset: 0x8002CB70
		// End Line: 505
	/* end block 1 */
	// End offset: 0x8002CB70
	// End Line: 505

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void * PinkSlipsPreSave__Fv(void)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_GoToBestOfOne__FR12tMenuCommand(struct tMenuCommand *command /*$s0*/)
 // line 508, offset 0x8002cb84
	/* begin block 1 */
		// Start line: 509
		// Start offset: 0x8002CB84
	/* end block 1 */
	// End offset: 0x8002CBBC
	// End Line: 519

/* WARNING: Control flow encountered bad instruction data */

void MenuExtended_GoToBestOfOne__FR12tMenuCommand(tMenuCommand *command)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_GoToBestOfThree__FR12tMenuCommand(struct tMenuCommand *command /*$s0*/)
 // line 523, offset 0x8002cbe0
	/* begin block 1 */
		// Start line: 524
		// Start offset: 0x8002CBE0
	/* end block 1 */
	// End offset: 0x8002CC18
	// End Line: 533

/* WARNING: Control flow encountered bad instruction data */

void MenuExtended_GoToBestOfThree__FR12tMenuCommand(tMenuCommand *command)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_GoToBestOfFive__FR12tMenuCommand(struct tMenuCommand *command /*$s0*/)
 // line 537, offset 0x8002cc3c
	/* begin block 1 */
		// Start line: 538
		// Start offset: 0x8002CC3C
	/* end block 1 */
	// End offset: 0x8002CC74
	// End Line: 547

/* WARNING: Control flow encountered bad instruction data */

void MenuExtended_GoToBestOfFive__FR12tMenuCommand(tMenuCommand *command)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_GoToRace__FR12tMenuCommand(struct tMenuCommand *command /*$s3*/)
 // line 551, offset 0x8002cc98
	/* begin block 1 */
		// Start line: 552
		// Start offset: 0x8002CC98
		// Variables:
	// 		struct tDialogMessageString *popUp; // $s1
	// 		struct tCarInfo carInfo; // stack offset -232

		/* begin block 1.1 */
			// Start line: 552
			// Start offset: 0x8002CC98
			// Variables:
		// 		struct tFEApplication *this; // $v1

			/* begin block 1.1.1 */
				// Start line: 552
				// Start offset: 0x8002CC98
			/* end block 1.1.1 */
			// End offset: 0x8002CC98
			// End Line: 552
		/* end block 1.1 */
		// End offset: 0x8002CC98
		// End Line: 552

		/* begin block 1.2 */
			// Start line: 552
			// Start offset: 0x8002CC98

			/* begin block 1.2.1 */
				// Start line: 558
				// Start offset: 0x8002CCE0

				/* begin block 1.2.1.1 */
					// Start line: 559
					// Start offset: 0x8002CCE0

					/* begin block 1.2.1.1.1 */
						// Start line: 561
						// Start offset: 0x8002CD14

						/* begin block 1.2.1.1.1.1 */
							// Start line: 561
							// Start offset: 0x8002CD14
							// Variables:
						// 		struct tDialogMessageString *this; // $s1

							/* begin block 1.2.1.1.1.1.1 */
								// Start line: 561
								// Start offset: 0x8002CD14
							/* end block 1.2.1.1.1.1.1 */
							// End offset: 0x8002CD14
							// End Line: 561
						/* end block 1.2.1.1.1.1 */
						// End offset: 0x8002CD14
						// End Line: 561
					/* end block 1.2.1.1.1 */
					// End offset: 0x8002CD14
					// End Line: 565
				/* end block 1.2.1.1 */
				// End offset: 0x8002CD14
				// End Line: 565
			/* end block 1.2.1 */
			// End offset: 0x8002CD14
			// End Line: 565
		/* end block 1.2 */
		// End offset: 0x8002CD14
		// End Line: 565

		/* begin block 1.3 */
			// Start line: 569
			// Start offset: 0x8002CD14

			/* begin block 1.3.1 */
				// Start line: 570
				// Start offset: 0x8002CD28

				/* begin block 1.3.1.1 */
					// Start line: 571
					// Start offset: 0x8002CD28

					/* begin block 1.3.1.1.1 */
						// Start line: 572
						// Start offset: 0x8002CD44

						/* begin block 1.3.1.1.1.1 */
							// Start line: 572
							// Start offset: 0x8002CD44
							// Variables:
						// 		struct tDialogMessageString *this; // $s1

							/* begin block 1.3.1.1.1.1.1 */
								// Start line: 572
								// Start offset: 0x8002CD44
							/* end block 1.3.1.1.1.1.1 */
							// End offset: 0x8002CD44
							// End Line: 572
						/* end block 1.3.1.1.1.1 */
						// End offset: 0x8002CD44
						// End Line: 572
					/* end block 1.3.1.1.1 */
					// End offset: 0x8002CD4C
					// End Line: 580
				/* end block 1.3.1.1 */
				// End offset: 0x8002CD4C
				// End Line: 580
			/* end block 1.3.1 */
			// End offset: 0x8002CD4C
			// End Line: 580
		/* end block 1.3 */
		// End offset: 0x8002CD4C
		// End Line: 580

		/* begin block 1.4 */
			// Start line: 585
			// Start offset: 0x8002CD4C

			/* begin block 1.4.1 */
				// Start line: 586
				// Start offset: 0x8002CD60

				/* begin block 1.4.1.1 */
					// Start line: 587
					// Start offset: 0x8002CD60

					/* begin block 1.4.1.1.1 */
						// Start line: 589
						// Start offset: 0x8002CD84

						/* begin block 1.4.1.1.1.1 */
							// Start line: 589
							// Start offset: 0x8002CD84
							// Variables:
						// 		struct tDialogMessageString *this; // $s1

							/* begin block 1.4.1.1.1.1.1 */
								// Start line: 589
								// Start offset: 0x8002CD84
							/* end block 1.4.1.1.1.1.1 */
							// End offset: 0x8002CD84
							// End Line: 589
						/* end block 1.4.1.1.1.1 */
						// End offset: 0x8002CD84
						// End Line: 589
					/* end block 1.4.1.1.1 */
					// End offset: 0x8002CD8C
					// End Line: 593
				/* end block 1.4.1.1 */
				// End offset: 0x8002CD8C
				// End Line: 593
			/* end block 1.4.1 */
			// End offset: 0x8002CD8C
			// End Line: 593
		/* end block 1.4 */
		// End offset: 0x8002CD8C
		// End Line: 593

		/* begin block 1.5 */
			// Start line: 597
			// Start offset: 0x8002CD8C

			/* begin block 1.5.1 */
				// Start line: 598
				// Start offset: 0x8002CDA0

				/* begin block 1.5.1.1 */
					// Start line: 599
					// Start offset: 0x8002CDA0

					/* begin block 1.5.1.1.1 */
						// Start line: 601
						// Start offset: 0x8002CDC0

						/* begin block 1.5.1.1.1.1 */
							// Start line: 601
							// Start offset: 0x8002CDC0
							// Variables:
						// 		struct tDialogMessageString *this; // $s1

							/* begin block 1.5.1.1.1.1.1 */
								// Start line: 601
								// Start offset: 0x8002CDC0
							/* end block 1.5.1.1.1.1.1 */
							// End offset: 0x8002CDC0
							// End Line: 601
						/* end block 1.5.1.1.1.1 */
						// End offset: 0x8002CDC0
						// End Line: 601
					/* end block 1.5.1.1.1 */
					// End offset: 0x8002CDD8
					// End Line: 605
				/* end block 1.5.1.1 */
				// End offset: 0x8002CDD8
				// End Line: 605
			/* end block 1.5.1 */
			// End offset: 0x8002CDD8
			// End Line: 605
		/* end block 1.5 */
		// End offset: 0x8002CDD8
		// End Line: 605
	/* end block 1 */
	// End offset: 0x8002CDD8
	// End Line: 605

/* WARNING: Control flow encountered bad instruction data */

void MenuExtended_GoToRace__FR12tMenuCommand(tMenuCommand *command)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_GoTo2PlayerRace__FR12tMenuCommand(struct tMenuCommand *command /*$s3*/)
 // line 610, offset 0x8002cdf4
	/* begin block 1 */
		// Start line: 611
		// Start offset: 0x8002CDF4
		// Variables:
	// 		struct tDialogMessageString *popUp; // $s2
	// 		struct tCarInfo carInfo; // stack offset -232

		/* begin block 1.1 */
			// Start line: 611
			// Start offset: 0x8002CDF4
			// Variables:
		// 		struct tFEApplication *this; // $v0

			/* begin block 1.1.1 */
				// Start line: 611
				// Start offset: 0x8002CDF4
			/* end block 1.1.1 */
			// End offset: 0x8002CDF4
			// End Line: 611
		/* end block 1.1 */
		// End offset: 0x8002CDF4
		// End Line: 611

		/* begin block 1.2 */
			// Start line: 620
			// Start offset: 0x8002CE38

			/* begin block 1.2.1 */
				// Start line: 621
				// Start offset: 0x8002CE48

				/* begin block 1.2.1.1 */
					// Start line: 622
					// Start offset: 0x8002CE48

					/* begin block 1.2.1.1.1 */
						// Start line: 624
						// Start offset: 0x8002CE74

						/* begin block 1.2.1.1.1.1 */
							// Start line: 624
							// Start offset: 0x8002CE74
							// Variables:
						// 		struct tDialogMessageString *this; // $s2

							/* begin block 1.2.1.1.1.1.1 */
								// Start line: 624
								// Start offset: 0x8002CE74
							/* end block 1.2.1.1.1.1.1 */
							// End offset: 0x8002CE74
							// End Line: 624
						/* end block 1.2.1.1.1.1 */
						// End offset: 0x8002CE74
						// End Line: 624
					/* end block 1.2.1.1.1 */
					// End offset: 0x8002CE74
					// End Line: 628
				/* end block 1.2.1.1 */
				// End offset: 0x8002CE74
				// End Line: 628
			/* end block 1.2.1 */
			// End offset: 0x8002CE74
			// End Line: 628
		/* end block 1.2 */
		// End offset: 0x8002CE74
		// End Line: 628

		/* begin block 1.3 */
			// Start line: 632
			// Start offset: 0x8002CE74

			/* begin block 1.3.1 */
				// Start line: 633
				// Start offset: 0x8002CE8C

				/* begin block 1.3.1.1 */
					// Start line: 633
					// Start offset: 0x8002CE8C
					// Variables:
				// 		struct tFEApplication *this; // $v0

					/* begin block 1.3.1.1.1 */
						// Start line: 633
						// Start offset: 0x8002CE8C
					/* end block 1.3.1.1.1 */
					// End offset: 0x8002CE8C
					// End Line: 633
				/* end block 1.3.1.1 */
				// End offset: 0x8002CE8C
				// End Line: 633

				/* begin block 1.3.1.2 */
					// Start line: 633
					// Start offset: 0x8002CE8C

					/* begin block 1.3.1.2.1 */
						// Start line: 636
						// Start offset: 0x8002CEC0

						/* begin block 1.3.1.2.1.1 */
							// Start line: 636
							// Start offset: 0x8002CEC0
							// Variables:
						// 		struct tDialogMessageString *this; // $s2

							/* begin block 1.3.1.2.1.1.1 */
								// Start line: 636
								// Start offset: 0x8002CEC0
							/* end block 1.3.1.2.1.1.1 */
							// End offset: 0x8002CEC0
							// End Line: 636
						/* end block 1.3.1.2.1.1 */
						// End offset: 0x8002CEC0
						// End Line: 636
					/* end block 1.3.1.2.1 */
					// End offset: 0x8002CEC8
					// End Line: 640
				/* end block 1.3.1.2 */
				// End offset: 0x8002CEC8
				// End Line: 640
			/* end block 1.3.1 */
			// End offset: 0x8002CEC8
			// End Line: 640
		/* end block 1.3 */
		// End offset: 0x8002CEC8
		// End Line: 640

		/* begin block 1.4 */
			// Start line: 645
			// Start offset: 0x8002CEC8

			/* begin block 1.4.1 */
				// Start line: 646
				// Start offset: 0x8002CEDC

				/* begin block 1.4.1.1 */
					// Start line: 646
					// Start offset: 0x8002CEDC
					// Variables:
				// 		struct tFEApplication *this; // $v0

					/* begin block 1.4.1.1.1 */
						// Start line: 646
						// Start offset: 0x8002CEDC
					/* end block 1.4.1.1.1 */
					// End offset: 0x8002CEDC
					// End Line: 646
				/* end block 1.4.1.1 */
				// End offset: 0x8002CEDC
				// End Line: 646

				/* begin block 1.4.1.2 */
					// Start line: 646
					// Start offset: 0x8002CEDC

					/* begin block 1.4.1.2.1 */
						// Start line: 649
						// Start offset: 0x8002CF0C

						/* begin block 1.4.1.2.1.1 */
							// Start line: 649
							// Start offset: 0x8002CF0C
							// Variables:
						// 		struct tDialogMessageString *this; // $s2

							/* begin block 1.4.1.2.1.1.1 */
								// Start line: 649
								// Start offset: 0x8002CF0C
							/* end block 1.4.1.2.1.1.1 */
							// End offset: 0x8002CF0C
							// End Line: 649
						/* end block 1.4.1.2.1.1 */
						// End offset: 0x8002CF0C
						// End Line: 649
					/* end block 1.4.1.2.1 */
					// End offset: 0x8002CF24
					// End Line: 653
				/* end block 1.4.1.2 */
				// End offset: 0x8002CF24
				// End Line: 653
			/* end block 1.4.1 */
			// End offset: 0x8002CF24
			// End Line: 653
		/* end block 1.4 */
		// End offset: 0x8002CF24
		// End Line: 653
	/* end block 1 */
	// End offset: 0x8002CF24
	// End Line: 653

/* WARNING: Control flow encountered bad instruction data */

void MenuExtended_GoTo2PlayerRace__FR12tMenuCommand(tMenuCommand *command)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_GoToTournTrackInfo__FR12tMenuCommand(struct tMenuCommand *command /*$s3*/)
 // line 658, offset 0x8002cf40
	/* begin block 1 */
		// Start line: 659
		// Start offset: 0x8002CF40
		// Variables:
	// 		struct tTourneyInfo *tourn; // $s2

		/* begin block 1.1 */
			// Start line: 659
			// Start offset: 0x8002CF40

			/* begin block 1.1.1 */
				// Start line: 659
				// Start offset: 0x8002CF40
			/* end block 1.1.1 */
			// End offset: 0x8002CF40
			// End Line: 659
		/* end block 1.1 */
		// End offset: 0x8002CF40
		// End Line: 659

		/* begin block 1.2 */
			// Start line: 659
			// Start offset: 0x8002CF40

			/* begin block 1.2.1 */
				// Start line: 665
				// Start offset: 0x8002CFB0

				/* begin block 1.2.1.1 */
					// Start line: 670
					// Start offset: 0x8002CFB0

					/* begin block 1.2.1.1.1 */
						// Start line: 670
						// Start offset: 0x8002CFB0

						/* begin block 1.2.1.1.1.1 */
							// Start line: 670
							// Start offset: 0x8002CFB0
						/* end block 1.2.1.1.1.1 */
						// End offset: 0x8002CFB0
						// End Line: 670
					/* end block 1.2.1.1.1 */
					// End offset: 0x8002CFB0
					// End Line: 670

					/* begin block 1.2.1.1.2 */
						// Start line: 671
						// Start offset: 0x8002CFC4

						/* begin block 1.2.1.1.2.1 */
							// Start line: 671
							// Start offset: 0x8002CFC4
							// Variables:
						// 		struct tFEApplication *this; // $s0

							/* begin block 1.2.1.1.2.1.1 */
								// Start line: 671
								// Start offset: 0x8002CFC4
							/* end block 1.2.1.1.2.1.1 */
							// End offset: 0x8002CFC4
							// End Line: 671
						/* end block 1.2.1.1.2.1 */
						// End offset: 0x8002CFC4
						// End Line: 671

						/* begin block 1.2.1.1.2.2 */
							// Start line: 671
							// Start offset: 0x8002CFC4

							/* begin block 1.2.1.1.2.2.1 */
								// Start line: 671
								// Start offset: 0x8002CFC4
							/* end block 1.2.1.1.2.2.1 */
							// End offset: 0x8002CFC4
							// End Line: 671
						/* end block 1.2.1.1.2.2 */
						// End offset: 0x8002CFC4
						// End Line: 671
					/* end block 1.2.1.1.2 */
					// End offset: 0x8002CFE8
					// End Line: 675

					/* begin block 1.2.1.1.3 */
						// Start line: 678
						// Start offset: 0x8002CFE8
						// Variables:
					// 		struct tDialogYesNo popUp; // stack offset -192

						/* begin block 1.2.1.1.3.1 */
							// Start line: 679
							// Start offset: 0x8002CFE8
							// Variables:
						// 		struct tDialogMessageString *this; // $s0

							/* begin block 1.2.1.1.3.1.1 */
								// Start line: 679
								// Start offset: 0x8002CFE8
							/* end block 1.2.1.1.3.1.1 */
							// End offset: 0x8002CFE8
							// End Line: 679
						/* end block 1.2.1.1.3.1 */
						// End offset: 0x8002CFE8
						// End Line: 679

						/* begin block 1.2.1.1.3.2 */
							// Start line: 679
							// Start offset: 0x8002CFE8

							/* begin block 1.2.1.1.3.2.1 */
								// Start line: 679
								// Start offset: 0x8002CFE8
							/* end block 1.2.1.1.3.2.1 */
							// End offset: 0x8002CFE8
							// End Line: 679
						/* end block 1.2.1.1.3.2 */
						// End offset: 0x8002CFE8
						// End Line: 679

						/* begin block 1.2.1.1.3.3 */
							// Start line: 679
							// Start offset: 0x8002CFE8

							/* begin block 1.2.1.1.3.3.1 */
								// Start line: 682
								// Start offset: 0x8002D028

								/* begin block 1.2.1.1.3.3.1.1 */
									// Start line: 682
									// Start offset: 0x8002D028
									// Variables:
								// 		long amount; // $v1

									/* begin block 1.2.1.1.3.3.1.1.1 */
										// Start line: 682
										// Start offset: 0x8002D028
									/* end block 1.2.1.1.3.3.1.1.1 */
									// End offset: 0x8002D028
									// End Line: 682
								/* end block 1.2.1.1.3.3.1.1 */
								// End offset: 0x8002D028
								// End Line: 682
							/* end block 1.2.1.1.3.3.1 */
							// End offset: 0x8002D028
							// End Line: 682

							/* begin block 1.2.1.1.3.3.2 */
								// Start line: 689
								// Start offset: 0x8002D038

								/* begin block 1.2.1.1.3.3.2.1 */
									// Start line: 689
									// Start offset: 0x8002D038

									/* begin block 1.2.1.1.3.3.2.1.1 */
										// Start line: 689
										// Start offset: 0x8002D038

										/* begin block 1.2.1.1.3.3.2.1.1.1 */
											// Start line: 689
											// Start offset: 0x8002D038

											/* begin block 1.2.1.1.3.3.2.1.1.1.1 */
												// Start line: 689
												// Start offset: 0x8002D038

												/* begin block 1.2.1.1.3.3.2.1.1.1.1.1 */
													// Start line: 689
													// Start offset: 0x8002D038
												/* end block 1.2.1.1.3.3.2.1.1.1.1.1 */
												// End offset: 0x8002D038
												// End Line: 689
											/* end block 1.2.1.1.3.3.2.1.1.1.1 */
											// End offset: 0x8002D038
											// End Line: 689
										/* end block 1.2.1.1.3.3.2.1.1.1 */
										// End offset: 0x8002D038
										// End Line: 689
									/* end block 1.2.1.1.3.3.2.1.1 */
									// End offset: 0x8002D038
									// End Line: 689
								/* end block 1.2.1.1.3.3.2.1 */
								// End offset: 0x8002D038
								// End Line: 689
							/* end block 1.2.1.1.3.3.2 */
							// End offset: 0x8002D038
							// End Line: 689
						/* end block 1.2.1.1.3.3 */
						// End offset: 0x8002D038
						// End Line: 689

						/* begin block 1.2.1.1.3.4 */
							// Start line: 684
							// Start offset: 0x8002D038

							/* begin block 1.2.1.1.3.4.1 */
								// Start line: 684
								// Start offset: 0x8002D038

								/* begin block 1.2.1.1.3.4.1.1 */
									// Start line: 684
									// Start offset: 0x8002D038

									/* begin block 1.2.1.1.3.4.1.1.1 */
										// Start line: 684
										// Start offset: 0x8002D038
									/* end block 1.2.1.1.3.4.1.1.1 */
									// End offset: 0x8002D05C
									// End Line: 684
								/* end block 1.2.1.1.3.4.1.1 */
								// End offset: 0x8002D05C
								// End Line: 684
							/* end block 1.2.1.1.3.4.1 */
							// End offset: 0x8002D05C
							// End Line: 684
						/* end block 1.2.1.1.3.4 */
						// End offset: 0x8002D05C
						// End Line: 684
					/* end block 1.2.1.1.3 */
					// End offset: 0x8002D05C
					// End Line: 689
				/* end block 1.2.1.1 */
				// End offset: 0x8002D05C
				// End Line: 689
			/* end block 1.2.1 */
			// End offset: 0x8002D05C
			// End Line: 689
		/* end block 1.2 */
		// End offset: 0x8002D05C
		// End Line: 689
	/* end block 1 */
	// End offset: 0x8002D08C
	// End Line: 693

/* WARNING: Control flow encountered bad instruction data */

void MenuExtended_GoToTournTrackInfo__FR12tMenuCommand(tMenuCommand *command)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_GoToSpecialEventTrackInfo__FR12tMenuCommand(struct tMenuCommand *command /*$s3*/)
 // line 696, offset 0x8002d0a8
	/* begin block 1 */
		// Start line: 697
		// Start offset: 0x8002D0A8
		// Variables:
	// 		struct tTourneyInfo *tourn; // $s2

		/* begin block 1.1 */
			// Start line: 697
			// Start offset: 0x8002D0A8

			/* begin block 1.1.1 */
				// Start line: 697
				// Start offset: 0x8002D0A8
			/* end block 1.1.1 */
			// End offset: 0x8002D0A8
			// End Line: 697
		/* end block 1.1 */
		// End offset: 0x8002D0A8
		// End Line: 697

		/* begin block 1.2 */
			// Start line: 697
			// Start offset: 0x8002D0A8

			/* begin block 1.2.1 */
				// Start line: 706
				// Start offset: 0x8002D11C

				/* begin block 1.2.1.1 */
					// Start line: 708
					// Start offset: 0x8002D11C

					/* begin block 1.2.1.1.1 */
						// Start line: 708
						// Start offset: 0x8002D11C

						/* begin block 1.2.1.1.1.1 */
							// Start line: 708
							// Start offset: 0x8002D11C
						/* end block 1.2.1.1.1.1 */
						// End offset: 0x8002D11C
						// End Line: 708
					/* end block 1.2.1.1.1 */
					// End offset: 0x8002D11C
					// End Line: 708

					/* begin block 1.2.1.1.2 */
						// Start line: 709
						// Start offset: 0x8002D130

						/* begin block 1.2.1.1.2.1 */
							// Start line: 709
							// Start offset: 0x8002D130
							// Variables:
						// 		struct tFEApplication *this; // $s0

							/* begin block 1.2.1.1.2.1.1 */
								// Start line: 709
								// Start offset: 0x8002D130
							/* end block 1.2.1.1.2.1.1 */
							// End offset: 0x8002D130
							// End Line: 709
						/* end block 1.2.1.1.2.1 */
						// End offset: 0x8002D130
						// End Line: 709

						/* begin block 1.2.1.1.2.2 */
							// Start line: 709
							// Start offset: 0x8002D130

							/* begin block 1.2.1.1.2.2.1 */
								// Start line: 709
								// Start offset: 0x8002D130
							/* end block 1.2.1.1.2.2.1 */
							// End offset: 0x8002D130
							// End Line: 709
						/* end block 1.2.1.1.2.2 */
						// End offset: 0x8002D130
						// End Line: 709
					/* end block 1.2.1.1.2 */
					// End offset: 0x8002D154
					// End Line: 713

					/* begin block 1.2.1.1.3 */
						// Start line: 716
						// Start offset: 0x8002D154
						// Variables:
					// 		struct tDialogYesNo popUp; // stack offset -192

						/* begin block 1.2.1.1.3.1 */
							// Start line: 717
							// Start offset: 0x8002D154
							// Variables:
						// 		struct tDialogMessageString *this; // $s0

							/* begin block 1.2.1.1.3.1.1 */
								// Start line: 717
								// Start offset: 0x8002D154
							/* end block 1.2.1.1.3.1.1 */
							// End offset: 0x8002D154
							// End Line: 717
						/* end block 1.2.1.1.3.1 */
						// End offset: 0x8002D154
						// End Line: 717

						/* begin block 1.2.1.1.3.2 */
							// Start line: 717
							// Start offset: 0x8002D154

							/* begin block 1.2.1.1.3.2.1 */
								// Start line: 717
								// Start offset: 0x8002D154
							/* end block 1.2.1.1.3.2.1 */
							// End offset: 0x8002D154
							// End Line: 717
						/* end block 1.2.1.1.3.2 */
						// End offset: 0x8002D154
						// End Line: 717

						/* begin block 1.2.1.1.3.3 */
							// Start line: 717
							// Start offset: 0x8002D154

							/* begin block 1.2.1.1.3.3.1 */
								// Start line: 720
								// Start offset: 0x8002D194

								/* begin block 1.2.1.1.3.3.1.1 */
									// Start line: 720
									// Start offset: 0x8002D194
									// Variables:
								// 		long amount; // $v1

									/* begin block 1.2.1.1.3.3.1.1.1 */
										// Start line: 720
										// Start offset: 0x8002D194
									/* end block 1.2.1.1.3.3.1.1.1 */
									// End offset: 0x8002D194
									// End Line: 720
								/* end block 1.2.1.1.3.3.1.1 */
								// End offset: 0x8002D194
								// End Line: 720
							/* end block 1.2.1.1.3.3.1 */
							// End offset: 0x8002D194
							// End Line: 720

							/* begin block 1.2.1.1.3.3.2 */
								// Start line: 727
								// Start offset: 0x8002D1A4

								/* begin block 1.2.1.1.3.3.2.1 */
									// Start line: 727
									// Start offset: 0x8002D1A4

									/* begin block 1.2.1.1.3.3.2.1.1 */
										// Start line: 727
										// Start offset: 0x8002D1A4

										/* begin block 1.2.1.1.3.3.2.1.1.1 */
											// Start line: 727
											// Start offset: 0x8002D1A4

											/* begin block 1.2.1.1.3.3.2.1.1.1.1 */
												// Start line: 727
												// Start offset: 0x8002D1A4

												/* begin block 1.2.1.1.3.3.2.1.1.1.1.1 */
													// Start line: 727
													// Start offset: 0x8002D1A4
												/* end block 1.2.1.1.3.3.2.1.1.1.1.1 */
												// End offset: 0x8002D1A4
												// End Line: 727
											/* end block 1.2.1.1.3.3.2.1.1.1.1 */
											// End offset: 0x8002D1A4
											// End Line: 727
										/* end block 1.2.1.1.3.3.2.1.1.1 */
										// End offset: 0x8002D1A4
										// End Line: 727
									/* end block 1.2.1.1.3.3.2.1.1 */
									// End offset: 0x8002D1A4
									// End Line: 727
								/* end block 1.2.1.1.3.3.2.1 */
								// End offset: 0x8002D1A4
								// End Line: 727
							/* end block 1.2.1.1.3.3.2 */
							// End offset: 0x8002D1A4
							// End Line: 727
						/* end block 1.2.1.1.3.3 */
						// End offset: 0x8002D1A4
						// End Line: 727

						/* begin block 1.2.1.1.3.4 */
							// Start line: 722
							// Start offset: 0x8002D1A4

							/* begin block 1.2.1.1.3.4.1 */
								// Start line: 722
								// Start offset: 0x8002D1A4

								/* begin block 1.2.1.1.3.4.1.1 */
									// Start line: 722
									// Start offset: 0x8002D1A4

									/* begin block 1.2.1.1.3.4.1.1.1 */
										// Start line: 722
										// Start offset: 0x8002D1A4
									/* end block 1.2.1.1.3.4.1.1.1 */
									// End offset: 0x8002D1C8
									// End Line: 722
								/* end block 1.2.1.1.3.4.1.1 */
								// End offset: 0x8002D1C8
								// End Line: 722
							/* end block 1.2.1.1.3.4.1 */
							// End offset: 0x8002D1C8
							// End Line: 722
						/* end block 1.2.1.1.3.4 */
						// End offset: 0x8002D1C8
						// End Line: 722
					/* end block 1.2.1.1.3 */
					// End offset: 0x8002D1C8
					// End Line: 727
				/* end block 1.2.1.1 */
				// End offset: 0x8002D1C8
				// End Line: 727
			/* end block 1.2.1 */
			// End offset: 0x8002D1C8
			// End Line: 727
		/* end block 1.2 */
		// End offset: 0x8002D1C8
		// End Line: 727
	/* end block 1 */
	// End offset: 0x8002D1F8
	// End Line: 731

/* WARNING: Control flow encountered bad instruction data */

void MenuExtended_GoToSpecialEventTrackInfo__FR12tMenuCommand(tMenuCommand *command)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_EnterUserName__FR12tMenuCommand(struct tMenuCommand *command /*$a0*/)
 // line 734, offset 0x8002d214
	/* begin block 1 */
		// Start line: 735
		// Start offset: 0x8002D214

		/* begin block 1.1 */
			// Start line: 736
			// Start offset: 0x8002D214
			// Variables:
		// 		struct tUserNameMenuItem *this; // $a1
		// 		char *data; // $v1

			/* begin block 1.1.1 */
				// Start line: 736
				// Start offset: 0x8002D214
			/* end block 1.1.1 */
			// End offset: 0x8002D214
			// End Line: 736
		/* end block 1.1 */
		// End offset: 0x8002D214
		// End Line: 736

		/* begin block 1.2 */
			// Start line: 736
			// Start offset: 0x8002D214
			// Variables:
		// 		struct tScreenUserName *this; // $v0
		// 		struct tOptionsMenu *m; // $a2

			/* begin block 1.2.1 */
				// Start line: 736
				// Start offset: 0x8002D214
			/* end block 1.2.1 */
			// End offset: 0x8002D214
			// End Line: 736
		/* end block 1.2 */
		// End offset: 0x8002D214
		// End Line: 736
	/* end block 1 */
	// End offset: 0x8002D214
	// End Line: 736

/* WARNING: Control flow encountered bad instruction data */

void MenuExtended_EnterUserName__FR12tMenuCommand(tMenuCommand *command)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_GoToShowroom__FR12tMenuCommand(struct tMenuCommand *command /*$a0*/)
 // line 750, offset 0x8002d278
	/* begin block 1 */
		// Start line: 751
		// Start offset: 0x8002D278
	/* end block 1 */
	// End offset: 0x8002D278
	// End Line: 751

/* WARNING: Control flow encountered bad instruction data */

void MenuExtended_GoToShowroom__FR12tMenuCommand(tMenuCommand *command)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_GoToDealerShowroom__FR12tMenuCommand(struct tMenuCommand *command /*$a0*/)
 // line 757, offset 0x8002d2b8
	/* begin block 1 */
		// Start line: 758
		// Start offset: 0x8002D2B8
	/* end block 1 */
	// End offset: 0x8002D2B8
	// End Line: 758

/* WARNING: Control flow encountered bad instruction data */

void MenuExtended_GoToDealerShowroom__FR12tMenuCommand(tMenuCommand *command)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_SetHPSoloRace__FR12tMenuCommand()
 // line 764, offset 0x8002d2f8
	/* begin block 1 */
		// Start line: 765
		// Start offset: 0x8002D2F8

		/* begin block 1.1 */
			// Start line: 766
			// Start offset: 0x8002D2F8

			/* begin block 1.1.1 */
				// Start line: 766
				// Start offset: 0x8002D2F8
			/* end block 1.1.1 */
			// End offset: 0x8002D2F8
			// End Line: 766
		/* end block 1.1 */
		// End offset: 0x8002D2F8
		// End Line: 766
	/* end block 1 */
	// End offset: 0x8002D2F8
	// End Line: 766

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void MenuExtended_SetHPSoloRace__FR12tMenuCommand(void)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_SetHPDuelRace__FR12tMenuCommand()
 // line 772, offset 0x8002d324
	/* begin block 1 */
		// Start line: 773
		// Start offset: 0x8002D324

		/* begin block 1.1 */
			// Start line: 774
			// Start offset: 0x8002D324

			/* begin block 1.1.1 */
				// Start line: 774
				// Start offset: 0x8002D324
			/* end block 1.1.1 */
			// End offset: 0x8002D324
			// End Line: 774
		/* end block 1.1 */
		// End offset: 0x8002D324
		// End Line: 774
	/* end block 1 */
	// End offset: 0x8002D324
	// End Line: 774

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void MenuExtended_SetHPDuelRace__FR12tMenuCommand(void)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_SetHotPursuit__FR12tMenuCommand()
 // line 780, offset 0x8002d350
	/* begin block 1 */
		// Start line: 781
		// Start offset: 0x8002D350

		/* begin block 1.1 */
			// Start line: 782
			// Start offset: 0x8002D350

			/* begin block 1.1.1 */
				// Start line: 786
				// Start offset: 0x8002D378

				/* begin block 1.1.1.1 */
					// Start line: 786
					// Start offset: 0x8002D378

					/* begin block 1.1.1.1.1 */
						// Start line: 786
						// Start offset: 0x8002D378
					/* end block 1.1.1.1.1 */
					// End offset: 0x8002D378
					// End Line: 786
				/* end block 1.1.1.1 */
				// End offset: 0x8002D378
				// End Line: 786
			/* end block 1.1.1 */
			// End offset: 0x8002D378
			// End Line: 786

			/* begin block 1.1.2 */
				// Start line: 788
				// Start offset: 0x8002D388

				/* begin block 1.1.2.1 */
					// Start line: 788
					// Start offset: 0x8002D388

					/* begin block 1.1.2.1.1 */
						// Start line: 788
						// Start offset: 0x8002D388
					/* end block 1.1.2.1.1 */
					// End offset: 0x8002D394
					// End Line: 788
				/* end block 1.1.2.1 */
				// End offset: 0x8002D394
				// End Line: 788
			/* end block 1.1.2 */
			// End offset: 0x8002D394
			// End Line: 788
		/* end block 1.1 */
		// End offset: 0x8002D394
		// End Line: 788
	/* end block 1 */
	// End offset: 0x8002D394
	// End Line: 789

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void MenuExtended_SetHotPursuit__FR12tMenuCommand(void)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_SellCar__FR12tMenuCommand()
 // line 792, offset 0x8002d3a0
	/* begin block 1 */
		// Start line: 793
		// Start offset: 0x8002D3A0
		// Variables:
	// 		long money; // $s0

		/* begin block 1.1 */
			// Start line: 793
			// Start offset: 0x8002D3A0

			/* begin block 1.1.1 */
				// Start line: 793
				// Start offset: 0x8002D3A0
			/* end block 1.1.1 */
			// End offset: 0x8002D3A0
			// End Line: 793
		/* end block 1.1 */
		// End offset: 0x8002D3A0
		// End Line: 793

		/* begin block 1.2 */
			// Start line: 793
			// Start offset: 0x8002D3A0

			/* begin block 1.2.1 */
				// Start line: 798
				// Start offset: 0x8002D41C
				// Variables:
			// 		struct tDialogYesNo popUp; // stack offset -184

				/* begin block 1.2.1.1 */
					// Start line: 799
					// Start offset: 0x8002D41C
					// Variables:
				// 		struct tDialogMessageString *this; // $s1

					/* begin block 1.2.1.1.1 */
						// Start line: 799
						// Start offset: 0x8002D41C
					/* end block 1.2.1.1.1 */
					// End offset: 0x8002D41C
					// End Line: 799
				/* end block 1.2.1.1 */
				// End offset: 0x8002D41C
				// End Line: 799

				/* begin block 1.2.1.2 */
					// Start line: 799
					// Start offset: 0x8002D41C

					/* begin block 1.2.1.2.1 */
						// Start line: 799
						// Start offset: 0x8002D41C
					/* end block 1.2.1.2.1 */
					// End offset: 0x8002D41C
					// End Line: 799
				/* end block 1.2.1.2 */
				// End offset: 0x8002D41C
				// End Line: 799

				/* begin block 1.2.1.3 */
					// Start line: 799
					// Start offset: 0x8002D41C

					/* begin block 1.2.1.3.1 */
						// Start line: 804
						// Start offset: 0x8002D45C

						/* begin block 1.2.1.3.1.1 */
							// Start line: 805
							// Start offset: 0x8002D45C

							/* begin block 1.2.1.3.1.1.1 */
								// Start line: 805
								// Start offset: 0x8002D45C
							/* end block 1.2.1.3.1.1.1 */
							// End offset: 0x8002D45C
							// End Line: 805
						/* end block 1.2.1.3.1.1 */
						// End offset: 0x8002D45C
						// End Line: 805
					/* end block 1.2.1.3.1 */
					// End offset: 0x8002D4B0
					// End Line: 808
				/* end block 1.2.1.3 */
				// End offset: 0x8002D4B0
				// End Line: 808

				/* begin block 1.2.1.4 */
					// Start line: 793
					// Start offset: 0x8002D4B0

					/* begin block 1.2.1.4.1 */
						// Start line: 793
						// Start offset: 0x8002D4B0

						/* begin block 1.2.1.4.1.1 */
							// Start line: 793
							// Start offset: 0x8002D4B0

							/* begin block 1.2.1.4.1.1.1 */
								// Start line: 793
								// Start offset: 0x8002D4B0
							/* end block 1.2.1.4.1.1.1 */
							// End offset: 0x8002D4B0
							// End Line: 793
						/* end block 1.2.1.4.1.1 */
						// End offset: 0x8002D4B0
						// End Line: 793
					/* end block 1.2.1.4.1 */
					// End offset: 0x8002D4B0
					// End Line: 793
				/* end block 1.2.1.4 */
				// End offset: 0x8002D4B0
				// End Line: 793
			/* end block 1.2.1 */
			// End offset: 0x8002D4B0
			// End Line: 793

			/* begin block 1.2.2 */
				// Start line: 812
				// Start offset: 0x8002D4C4

				/* begin block 1.2.2.1 */
					// Start line: 812
					// Start offset: 0x8002D4C4
					// Variables:
				// 		struct tFEApplication *this; // $s0

					/* begin block 1.2.2.1.1 */
						// Start line: 812
						// Start offset: 0x8002D4C4
					/* end block 1.2.2.1.1 */
					// End offset: 0x8002D4C4
					// End Line: 812
				/* end block 1.2.2.1 */
				// End offset: 0x8002D4C4
				// End Line: 812

				/* begin block 1.2.2.2 */
					// Start line: 812
					// Start offset: 0x8002D4C4

					/* begin block 1.2.2.2.1 */
						// Start line: 812
						// Start offset: 0x8002D4C4
					/* end block 1.2.2.2.1 */
					// End offset: 0x8002D4C4
					// End Line: 812
				/* end block 1.2.2.2 */
				// End offset: 0x8002D4C4
				// End Line: 812
			/* end block 1.2.2 */
			// End offset: 0x8002D4E0
			// End Line: 815
		/* end block 1.2 */
		// End offset: 0x8002D4E0
		// End Line: 815
	/* end block 1 */
	// End offset: 0x8002D4E0
	// End Line: 815

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void MenuExtended_SellCar__FR12tMenuCommand(void)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_BuyCar__FR12tMenuCommand()
 // line 819, offset 0x8002d4f8
	/* begin block 1 */
		// Start line: 820
		// Start offset: 0x8002D4F8
		// Variables:
	// 		struct tCarInfo carInfo; // stack offset -400
	// 		struct tDialogMessageString *popUp; // $s1

		/* begin block 1.1 */
			// Start line: 820
			// Start offset: 0x8002D4F8
			// Variables:
		// 		struct tFEApplication *this; // $v0

			/* begin block 1.1.1 */
				// Start line: 820
				// Start offset: 0x8002D4F8
			/* end block 1.1.1 */
			// End offset: 0x8002D4F8
			// End Line: 820
		/* end block 1.1 */
		// End offset: 0x8002D4F8
		// End Line: 820

		/* begin block 1.2 */
			// Start line: 820
			// Start offset: 0x8002D4F8

			/* begin block 1.2.1 */
				// Start line: 827
				// Start offset: 0x8002D55C

				/* begin block 1.2.1.1 */
					// Start line: 828
					// Start offset: 0x8002D55C

					/* begin block 1.2.1.1.1 */
						// Start line: 828
						// Start offset: 0x8002D55C

						/* begin block 1.2.1.1.1.1 */
							// Start line: 828
							// Start offset: 0x8002D55C
						/* end block 1.2.1.1.1.1 */
						// End offset: 0x8002D55C
						// End Line: 828
					/* end block 1.2.1.1.1 */
					// End offset: 0x8002D55C
					// End Line: 828

					/* begin block 1.2.1.1.2 */
						// Start line: 829
						// Start offset: 0x8002D57C
						// Variables:
					// 		struct tDialogYesNo yesNo; // stack offset -192

						/* begin block 1.2.1.1.2.1 */
							// Start line: 830
							// Start offset: 0x8002D57C

							/* begin block 1.2.1.1.2.1.1 */
								// Start line: 830
								// Start offset: 0x8002D57C
							/* end block 1.2.1.1.2.1.1 */
							// End offset: 0x8002D57C
							// End Line: 830
						/* end block 1.2.1.1.2.1 */
						// End offset: 0x8002D57C
						// End Line: 830

						/* begin block 1.2.1.1.2.2 */
							// Start line: 830
							// Start offset: 0x8002D57C

							/* begin block 1.2.1.1.2.2.1 */
								// Start line: 830
								// Start offset: 0x8002D57C
							/* end block 1.2.1.1.2.2.1 */
							// End offset: 0x8002D57C
							// End Line: 830
						/* end block 1.2.1.1.2.2 */
						// End offset: 0x8002D57C
						// End Line: 830

						/* begin block 1.2.1.1.2.3 */
							// Start line: 830
							// Start offset: 0x8002D57C

							/* begin block 1.2.1.1.2.3.1 */
								// Start line: 835
								// Start offset: 0x8002D5BC

								/* begin block 1.2.1.1.2.3.1.1 */
									// Start line: 836
									// Start offset: 0x8002D5BC

									/* begin block 1.2.1.1.2.3.1.1.1 */
										// Start line: 836
										// Start offset: 0x8002D5BC
									/* end block 1.2.1.1.2.3.1.1.1 */
									// End offset: 0x8002D5BC
									// End Line: 836
								/* end block 1.2.1.1.2.3.1.1 */
								// End offset: 0x8002D5BC
								// End Line: 836
							/* end block 1.2.1.1.2.3.1 */
							// End offset: 0x8002D5E8
							// End Line: 837
						/* end block 1.2.1.1.2.3 */
						// End offset: 0x8002D5E8
						// End Line: 837

						/* begin block 1.2.1.1.2.4 */
							// Start line: 820
							// Start offset: 0x8002D5E8

							/* begin block 1.2.1.1.2.4.1 */
								// Start line: 820
								// Start offset: 0x8002D5E8

								/* begin block 1.2.1.1.2.4.1.1 */
									// Start line: 820
									// Start offset: 0x8002D5E8

									/* begin block 1.2.1.1.2.4.1.1.1 */
										// Start line: 820
										// Start offset: 0x8002D5E8
									/* end block 1.2.1.1.2.4.1.1.1 */
									// End offset: 0x8002D5E8
									// End Line: 820
								/* end block 1.2.1.1.2.4.1.1 */
								// End offset: 0x8002D5E8
								// End Line: 820
							/* end block 1.2.1.1.2.4.1 */
							// End offset: 0x8002D5E8
							// End Line: 820
						/* end block 1.2.1.1.2.4 */
						// End offset: 0x8002D5E8
						// End Line: 820
					/* end block 1.2.1.1.2 */
					// End offset: 0x8002D5E8
					// End Line: 820

					/* begin block 1.2.1.1.3 */
						// Start line: 841
						// Start offset: 0x8002D5FC

						/* begin block 1.2.1.1.3.1 */
							// Start line: 842
							// Start offset: 0x8002D5FC
							// Variables:
						// 		struct tDialogMessageString *this; // $s1

							/* begin block 1.2.1.1.3.1.1 */
								// Start line: 842
								// Start offset: 0x8002D5FC
							/* end block 1.2.1.1.3.1.1 */
							// End offset: 0x8002D5FC
							// End Line: 842
						/* end block 1.2.1.1.3.1 */
						// End offset: 0x8002D5FC
						// End Line: 842
					/* end block 1.2.1.1.3 */
					// End offset: 0x8002D5FC
					// End Line: 842
				/* end block 1.2.1.1 */
				// End offset: 0x8002D5FC
				// End Line: 842
			/* end block 1.2.1 */
			// End offset: 0x8002D5FC
			// End Line: 842

			/* begin block 1.2.2 */
				// Start line: 848
				// Start offset: 0x8002D618

				/* begin block 1.2.2.1 */
					// Start line: 848
					// Start offset: 0x8002D618
					// Variables:
				// 		struct tDialogMessageString *this; // $s1

					/* begin block 1.2.2.1.1 */
						// Start line: 848
						// Start offset: 0x8002D618
					/* end block 1.2.2.1.1 */
					// End offset: 0x8002D618
					// End Line: 848
				/* end block 1.2.2.1 */
				// End offset: 0x8002D618
				// End Line: 848
			/* end block 1.2.2 */
			// End offset: 0x8002D630
			// End Line: 850
		/* end block 1.2 */
		// End offset: 0x8002D630
		// End Line: 850
	/* end block 1 */
	// End offset: 0x8002D630
	// End Line: 850

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void MenuExtended_BuyCar__FR12tMenuCommand(void)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_PurchaseUpgrade__Fi(int upgradeNumber /*$s0*/)
 // line 854, offset 0x8002d64c
	/* begin block 1 */
		// Start line: 855
		// Start offset: 0x8002D64C
		// Variables:
	// 		struct tCarInfo carInfo; // stack offset -400
	// 		int upgradeFlag; // $s2

		/* begin block 1.1 */
			// Start line: 855
			// Start offset: 0x8002D64C

			/* begin block 1.1.1 */
				// Start line: 861
				// Start offset: 0x8002D6AC

				/* begin block 1.1.1.1 */
					// Start line: 862
					// Start offset: 0x8002D6AC

					/* begin block 1.1.1.1.1 */
						// Start line: 862
						// Start offset: 0x8002D6AC

						/* begin block 1.1.1.1.1.1 */
							// Start line: 862
							// Start offset: 0x8002D6AC
						/* end block 1.1.1.1.1.1 */
						// End offset: 0x8002D6AC
						// End Line: 862
					/* end block 1.1.1.1.1 */
					// End offset: 0x8002D6AC
					// End Line: 862

					/* begin block 1.1.1.1.2 */
						// Start line: 863
						// Start offset: 0x8002D6D4
						// Variables:
					// 		struct tDialogYesNo popUp; // stack offset -192

						/* begin block 1.1.1.1.2.1 */
							// Start line: 864
							// Start offset: 0x8002D6D4

							/* begin block 1.1.1.1.2.1.1 */
								// Start line: 864
								// Start offset: 0x8002D6D4
							/* end block 1.1.1.1.2.1.1 */
							// End offset: 0x8002D6D4
							// End Line: 864
						/* end block 1.1.1.1.2.1 */
						// End offset: 0x8002D6D4
						// End Line: 864

						/* begin block 1.1.1.1.2.2 */
							// Start line: 864
							// Start offset: 0x8002D6D4

							/* begin block 1.1.1.1.2.2.1 */
								// Start line: 864
								// Start offset: 0x8002D6D4
							/* end block 1.1.1.1.2.2.1 */
							// End offset: 0x8002D6D4
							// End Line: 864
						/* end block 1.1.1.1.2.2 */
						// End offset: 0x8002D6D4
						// End Line: 864

						/* begin block 1.1.1.1.2.3 */
							// Start line: 864
							// Start offset: 0x8002D6D4

							/* begin block 1.1.1.1.2.3.1 */
								// Start line: 869
								// Start offset: 0x8002D714

								/* begin block 1.1.1.1.2.3.1.1 */
									// Start line: 870
									// Start offset: 0x8002D714

									/* begin block 1.1.1.1.2.3.1.1.1 */
										// Start line: 870
										// Start offset: 0x8002D714
									/* end block 1.1.1.1.2.3.1.1.1 */
									// End offset: 0x8002D714
									// End Line: 870
								/* end block 1.1.1.1.2.3.1.1 */
								// End offset: 0x8002D714
								// End Line: 870
							/* end block 1.1.1.1.2.3.1 */
							// End offset: 0x8002D73C
							// End Line: 871
						/* end block 1.1.1.1.2.3 */
						// End offset: 0x8002D73C
						// End Line: 871

						/* begin block 1.1.1.1.2.4 */
							// Start line: 855
							// Start offset: 0x8002D73C

							/* begin block 1.1.1.1.2.4.1 */
								// Start line: 855
								// Start offset: 0x8002D73C

								/* begin block 1.1.1.1.2.4.1.1 */
									// Start line: 855
									// Start offset: 0x8002D73C

									/* begin block 1.1.1.1.2.4.1.1.1 */
										// Start line: 855
										// Start offset: 0x8002D73C
									/* end block 1.1.1.1.2.4.1.1.1 */
									// End offset: 0x8002D73C
									// End Line: 855
								/* end block 1.1.1.1.2.4.1.1 */
								// End offset: 0x8002D73C
								// End Line: 855
							/* end block 1.1.1.1.2.4.1 */
							// End offset: 0x8002D73C
							// End Line: 855
						/* end block 1.1.1.1.2.4 */
						// End offset: 0x8002D73C
						// End Line: 855
					/* end block 1.1.1.1.2 */
					// End offset: 0x8002D73C
					// End Line: 855

					/* begin block 1.1.1.1.3 */
						// Start line: 875
						// Start offset: 0x8002D750

						/* begin block 1.1.1.1.3.1 */
							// Start line: 875
							// Start offset: 0x8002D750
							// Variables:
						// 		struct tFEApplication *this; // $s0

							/* begin block 1.1.1.1.3.1.1 */
								// Start line: 875
								// Start offset: 0x8002D750
							/* end block 1.1.1.1.3.1.1 */
							// End offset: 0x8002D750
							// End Line: 875
						/* end block 1.1.1.1.3.1 */
						// End offset: 0x8002D750
						// End Line: 875

						/* begin block 1.1.1.1.3.2 */
							// Start line: 875
							// Start offset: 0x8002D750

							/* begin block 1.1.1.1.3.2.1 */
								// Start line: 875
								// Start offset: 0x8002D750
							/* end block 1.1.1.1.3.2.1 */
							// End offset: 0x8002D750
							// End Line: 875
						/* end block 1.1.1.1.3.2 */
						// End offset: 0x8002D750
						// End Line: 875
					/* end block 1.1.1.1.3 */
					// End offset: 0x8002D76C
					// End Line: 878
				/* end block 1.1.1.1 */
				// End offset: 0x8002D76C
				// End Line: 878
			/* end block 1.1.1 */
			// End offset: 0x8002D76C
			// End Line: 878
		/* end block 1.1 */
		// End offset: 0x8002D76C
		// End Line: 878
	/* end block 1 */
	// End offset: 0x8002D76C
	// End Line: 878

/* WARNING: Control flow encountered bad instruction data */

void MenuExtended_PurchaseUpgrade__Fi(int upgradeNumber)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_PurchaseUpgrade1__FR12tMenuCommand()
 // line 883, offset 0x8002d78c
	/* begin block 1 */
		// Start line: 884
		// Start offset: 0x8002D78C
	/* end block 1 */
	// End offset: 0x8002D78C
	// End Line: 884

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void MenuExtended_PurchaseUpgrade1__FR12tMenuCommand(void)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_PurchaseUpgrade2__FR12tMenuCommand()
 // line 888, offset 0x8002d7ac
	/* begin block 1 */
		// Start line: 889
		// Start offset: 0x8002D7AC
	/* end block 1 */
	// End offset: 0x8002D7AC
	// End Line: 889

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void MenuExtended_PurchaseUpgrade2__FR12tMenuCommand(void)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_PurchaseUpgrade3__FR12tMenuCommand()
 // line 893, offset 0x8002d7cc
	/* begin block 1 */
		// Start line: 894
		// Start offset: 0x8002D7CC
	/* end block 1 */
	// End offset: 0x8002D7CC
	// End Line: 894

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void MenuExtended_PurchaseUpgrade3__FR12tMenuCommand(void)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_SaveGame__FR12tMenuCommand()
 // line 898, offset 0x8002d7ec
	/* begin block 1 */
		// Start line: 899
		// Start offset: 0x8002D7EC

		/* begin block 1.1 */
			// Start line: 899
			// Start offset: 0x8002D7EC

			/* begin block 1.1.1 */
				// Start line: 900
				// Start offset: 0x8002D800

				/* begin block 1.1.1.1 */
					// Start line: 900
					// Start offset: 0x8002D800
				/* end block 1.1.1.1 */
				// End offset: 0x8002D800
				// End Line: 900
			/* end block 1.1.1 */
			// End offset: 0x8002D800
			// End Line: 900
		/* end block 1.1 */
		// End offset: 0x8002D82C
		// End Line: 902
	/* end block 1 */
	// End offset: 0x8002D82C
	// End Line: 902

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void MenuExtended_SaveGame__FR12tMenuCommand(void)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ GenericMenuLoadGame__Fi(int player /*$s2*/)
 // line 922, offset 0x8002d83c
	/* begin block 1 */
		// Start line: 923
		// Start offset: 0x8002D83C

		/* begin block 1.1 */
			// Start line: 923
			// Start offset: 0x8002D83C

			/* begin block 1.1.1 */
				// Start line: 925
				// Start offset: 0x8002D860

				/* begin block 1.1.1.1 */
					// Start line: 925
					// Start offset: 0x8002D860
					// Variables:
				// 		struct tScreenMemcard *this; // $v1

					/* begin block 1.1.1.1.1 */
						// Start line: 925
						// Start offset: 0x8002D860
					/* end block 1.1.1.1.1 */
					// End offset: 0x8002D860
					// End Line: 925
				/* end block 1.1.1.1 */
				// End offset: 0x8002D860
				// End Line: 925

				/* begin block 1.1.1.2 */
					// Start line: 925
					// Start offset: 0x8002D860
					// Variables:
				// 		struct tScreenMemcard *this; // $v1

					/* begin block 1.1.1.2.1 */
						// Start line: 925
						// Start offset: 0x8002D860
					/* end block 1.1.1.2.1 */
					// End offset: 0x8002D860
					// End Line: 925
				/* end block 1.1.1.2 */
				// End offset: 0x8002D860
				// End Line: 925
			/* end block 1.1.1 */
			// End offset: 0x8002D8A8
			// End Line: 930
		/* end block 1.1 */
		// End offset: 0x8002D8A8
		// End Line: 930
	/* end block 1 */
	// End offset: 0x8002D8A8
	// End Line: 942

/* WARNING: Control flow encountered bad instruction data */

void GenericMenuLoadGame__Fi(int player)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_LoadGame__FR12tMenuCommand()
 // line 945, offset 0x8002d8d0
	/* begin block 1 */
		// Start line: 946
		// Start offset: 0x8002D8D0
		// Variables:
	// 		struct tDialogYesNo AreYouSure; // stack offset -184

		/* begin block 1.1 */
			// Start line: 946
			// Start offset: 0x8002D8D0

			/* begin block 1.1.1 */
				// Start line: 946
				// Start offset: 0x8002D8D0

				/* begin block 1.1.1.1 */
					// Start line: 946
					// Start offset: 0x8002D8D0
				/* end block 1.1.1.1 */
				// End offset: 0x8002D8D0
				// End Line: 946
			/* end block 1.1.1 */
			// End offset: 0x8002D8D0
			// End Line: 946
		/* end block 1.1 */
		// End offset: 0x8002D8F8
		// End Line: 948

		/* begin block 1.2 */
			// Start line: 950
			// Start offset: 0x8002D8F8
			// Variables:
		// 		struct tDialogYesNo *this; // $s0

			/* begin block 1.2.1 */
				// Start line: 950
				// Start offset: 0x8002D8F8
			/* end block 1.2.1 */
			// End offset: 0x8002D8F8
			// End Line: 950
		/* end block 1.2 */
		// End offset: 0x8002D8F8
		// End Line: 950

		/* begin block 1.3 */
			// Start line: 950
			// Start offset: 0x8002D8F8

			/* begin block 1.3.1 */
				// Start line: 950
				// Start offset: 0x8002D8F8
			/* end block 1.3.1 */
			// End offset: 0x8002D8F8
			// End Line: 950
		/* end block 1.3 */
		// End offset: 0x8002D8F8
		// End Line: 950

		/* begin block 1.4 */
			// Start line: 946
			// Start offset: 0x8002D94C

			/* begin block 1.4.1 */
				// Start line: 946
				// Start offset: 0x8002D94C

				/* begin block 1.4.1.1 */
					// Start line: 946
					// Start offset: 0x8002D94C

					/* begin block 1.4.1.1.1 */
						// Start line: 946
						// Start offset: 0x8002D94C
					/* end block 1.4.1.1.1 */
					// End offset: 0x8002D958
					// End Line: 946
				/* end block 1.4.1.1 */
				// End offset: 0x8002D958
				// End Line: 946
			/* end block 1.4.1 */
			// End offset: 0x8002D958
			// End Line: 946
		/* end block 1.4 */
		// End offset: 0x8002D958
		// End Line: 946
	/* end block 1 */
	// End offset: 0x8002D958
	// End Line: 958

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void MenuExtended_LoadGame__FR12tMenuCommand(void)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_TierFinished__FR12tMenuCommand(struct tMenuCommand *command /*$s0*/)
 // line 960, offset 0x8002d968
	/* begin block 1 */
		// Start line: 961
		// Start offset: 0x8002D968
		// Variables:
	// 		struct tAwardInformation award; // stack offset -80
	/* end block 1 */
	// End offset: 0x8002D9D8
	// End Line: 977

/* WARNING: Control flow encountered bad instruction data */

void MenuExtended_TierFinished__FR12tMenuCommand(tMenuCommand *command)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void * /*$ra*/ MenuExtended_DidUserWinBeTheCop__Fv()
 // line 1011, offset 0x8002d9e8
	/* begin block 1 */
		// Start line: 1012
		// Start offset: 0x8002D9E8
		// Variables:
	// 		struct tCarInfo carInfo; // stack offset -232
	// 		struct tCarInfo *activateCar; // $s0
	// 		void * result; // $s3
	/* end block 1 */
	// End offset: 0x8002DAE4
	// End Line: 1037

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void * MenuExtended_DidUserWinBeTheCop__Fv(void)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_PostGameMenu__FR12tMenuCommand(struct tMenuCommand *command /*$s0*/)
 // line 1040, offset 0x8002db04
	/* begin block 1 */
		// Start line: 1041
		// Start offset: 0x8002DB04

		/* begin block 1.1 */
			// Start line: 1041
			// Start offset: 0x8002DB04

			/* begin block 1.1.1 */
				// Start line: 1057
				// Start offset: 0x8002DB60

				/* begin block 1.1.1.1 */
					// Start line: 1059
					// Start offset: 0x8002DB60

					/* begin block 1.1.1.1.1 */
						// Start line: 1060
						// Start offset: 0x8002DB78

						/* begin block 1.1.1.1.1.1 */
							// Start line: 1061
							// Start offset: 0x8002DB78
							// Variables:
						// 		struct tScreenTournamentStandings *this; // $v1

							/* begin block 1.1.1.1.1.1.1 */
								// Start line: 1061
								// Start offset: 0x8002DB78
							/* end block 1.1.1.1.1.1.1 */
							// End offset: 0x8002DB78
							// End Line: 1061
						/* end block 1.1.1.1.1.1 */
						// End offset: 0x8002DB78
						// End Line: 1061
					/* end block 1.1.1.1.1 */
					// End offset: 0x8002DB78
					// End Line: 1061

					/* begin block 1.1.1.1.2 */
						// Start line: 1065
						// Start offset: 0x8002DB98

						/* begin block 1.1.1.1.2.1 */
							// Start line: 1066
							// Start offset: 0x8002DB98
							// Variables:
						// 		struct tScreenTournamentStandings *this; // $v1

							/* begin block 1.1.1.1.2.1.1 */
								// Start line: 1066
								// Start offset: 0x8002DB98
							/* end block 1.1.1.1.2.1.1 */
							// End offset: 0x8002DB98
							// End Line: 1066
						/* end block 1.1.1.1.2.1 */
						// End offset: 0x8002DB98
						// End Line: 1066
					/* end block 1.1.1.1.2 */
					// End offset: 0x8002DB98
					// End Line: 1066
				/* end block 1.1.1.1 */
				// End offset: 0x8002DB98
				// End Line: 1066
			/* end block 1.1.1 */
			// End offset: 0x8002DBF4
			// End Line: 1083
		/* end block 1.1 */
		// End offset: 0x8002DBF4
		// End Line: 1083
	/* end block 1 */
	// End offset: 0x8002DBF4
	// End Line: 1083

/* WARNING: Control flow encountered bad instruction data */

void MenuExtended_PostGameMenu__FR12tMenuCommand(tMenuCommand *command)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_FinishedPlayer1GetName__FR12tMenuCommand(struct tMenuCommand *command /*$s2*/)
 // line 1090, offset 0x8002dc04
	/* begin block 1 */
		// Start line: 1091
		// Start offset: 0x8002DC04

		/* begin block 1.1 */
			// Start line: 1091
			// Start offset: 0x8002DC04

			/* begin block 1.1.1 */
				// Start line: 1094
				// Start offset: 0x8002DC4C

				/* begin block 1.1.1.1 */
					// Start line: 1094
					// Start offset: 0x8002DC4C
					// Variables:
				// 		struct tUserNameMenuItem *this; // $v1

					/* begin block 1.1.1.1.1 */
						// Start line: 1094
						// Start offset: 0x8002DC4C
					/* end block 1.1.1.1.1 */
					// End offset: 0x8002DC4C
					// End Line: 1094
				/* end block 1.1.1.1 */
				// End offset: 0x8002DC4C
				// End Line: 1094

				/* begin block 1.1.1.2 */
					// Start line: 1094
					// Start offset: 0x8002DC4C
					// Variables:
				// 		struct tScreenUserName *this; // $v0
				// 		struct tOptionsMenu *m; // $a0

					/* begin block 1.1.1.2.1 */
						// Start line: 1094
						// Start offset: 0x8002DC4C
					/* end block 1.1.1.2.1 */
					// End offset: 0x8002DC4C
					// End Line: 1094
				/* end block 1.1.1.2 */
				// End offset: 0x8002DC4C
				// End Line: 1094
			/* end block 1.1.1 */
			// End offset: 0x8002DC4C
			// End Line: 1094

			/* begin block 1.1.2 */
				// Start line: 1101
				// Start offset: 0x8002DC94
				// Variables:
			// 		struct Car_tStats *dummyCars; // $s1
			// 		short nBestCarIndex; // stack offset -24

				/* begin block 1.1.2.1 */
					// Start line: 1101
					// Start offset: 0x8002DC94

					/* begin block 1.1.2.1.1 */
						// Start line: 1101
						// Start offset: 0x8002DC94
					/* end block 1.1.2.1.1 */
					// End offset: 0x8002DC94
					// End Line: 1101
				/* end block 1.1.2.1 */
				// End offset: 0x8002DC94
				// End Line: 1101
			/* end block 1.1.2 */
			// End offset: 0x8002DCFC
			// End Line: 1121
		/* end block 1.1 */
		// End offset: 0x8002DCFC
		// End Line: 1121
	/* end block 1 */
	// End offset: 0x8002DCFC
	// End Line: 1121

/* WARNING: Control flow encountered bad instruction data */

void MenuExtended_FinishedPlayer1GetName__FR12tMenuCommand(tMenuCommand *command)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_FinishedPlayer2GetName__FR12tMenuCommand(struct tMenuCommand *command /*$s2*/)
 // line 1125, offset 0x8002dd14
	/* begin block 1 */
		// Start line: 1126
		// Start offset: 0x8002DD14
		// Variables:
	// 		struct Car_tStats *dummyCars; // $s1
	// 		short nBestCarIndex; // stack offset -24

		/* begin block 1.1 */
			// Start line: 1126
			// Start offset: 0x8002DD14

			/* begin block 1.1.1 */
				// Start line: 1126
				// Start offset: 0x8002DD14
			/* end block 1.1.1 */
			// End offset: 0x8002DD14
			// End Line: 1126
		/* end block 1.1 */
		// End offset: 0x8002DD14
		// End Line: 1126
	/* end block 1 */
	// End offset: 0x8002DD84
	// End Line: 1143

/* WARNING: Control flow encountered bad instruction data */

void MenuExtended_FinishedPlayer2GetName__FR12tMenuCommand(tMenuCommand *command)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_SetPinkSlips__FR12tMenuCommand()
 // line 1146, offset 0x8002ddb4
	/* begin block 1 */
		// Start line: 1147
		// Start offset: 0x8002DDB4
		// Variables:
	// 		short i; // $v1
	/* end block 1 */
	// End offset: 0x8002DE64
	// End Line: 1160

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void MenuExtended_SetPinkSlips__FR12tMenuCommand(void)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_AwardPinkSlipsCar__FR12tMenuCommand(struct tMenuCommand *command /*$s5*/)
 // line 1163, offset 0x8002de74
	/* begin block 1 */
		// Start line: 1164
		// Start offset: 0x8002DE74
		// Variables:
	// 		char string[80]; // stack offset -488
	// 		struct tDialogYesNo RetryCancelDialog; // stack offset -408
	// 		int fWinner; // $s3
	// 		struct tCarInfo carInfo; // stack offset -240

		/* begin block 1.1 */
			// Start line: 1164
			// Start offset: 0x8002DE74

			/* begin block 1.1.1 */
				// Start line: 1164
				// Start offset: 0x8002DE74
			/* end block 1.1.1 */
			// End offset: 0x8002DE74
			// End Line: 1164
		/* end block 1.1 */
		// End offset: 0x8002DE74
		// End Line: 1164

		/* begin block 1.2 */
			// Start line: 1164
			// Start offset: 0x8002DE74
			// Variables:
		// 		struct tScreenPinkSlipCongrats *this; // $v1

			/* begin block 1.2.1 */
				// Start line: 1164
				// Start offset: 0x8002DE74
			/* end block 1.2.1 */
			// End offset: 0x8002DE74
			// End Line: 1164
		/* end block 1.2 */
		// End offset: 0x8002DE74
		// End Line: 1164

		/* begin block 1.3 */
			// Start line: 1164
			// Start offset: 0x8002DE74
			// Variables:
		// 		struct tDialogMessageString *this; // $a0
		// 		char *mess; // $v0

			/* begin block 1.3.1 */
				// Start line: 1164
				// Start offset: 0x8002DE74
			/* end block 1.3.1 */
			// End offset: 0x8002DE74
			// End Line: 1164
		/* end block 1.3 */
		// End offset: 0x8002DE74
		// End Line: 1164

		/* begin block 1.4 */
			// Start line: 1181
			// Start offset: 0x8002DF0C

			/* begin block 1.4.1 */
				// Start line: 1181
				// Start offset: 0x8002DF0C

				/* begin block 1.4.1.1 */
					// Start line: 1181
					// Start offset: 0x8002DF0C
				/* end block 1.4.1.1 */
				// End offset: 0x8002DF0C
				// End Line: 1181
			/* end block 1.4.1 */
			// End offset: 0x8002DF0C
			// End Line: 1181
		/* end block 1.4 */
		// End offset: 0x8002DF28
		// End Line: 1182

		/* begin block 1.5 */
			// Start line: 1183
			// Start offset: 0x8002DF38
			// Variables:
		// 		struct tDialogMessageString *this; // $s0

			/* begin block 1.5.1 */
				// Start line: 1183
				// Start offset: 0x8002DF38
			/* end block 1.5.1 */
			// End offset: 0x8002DF38
			// End Line: 1183
		/* end block 1.5 */
		// End offset: 0x8002DF38
		// End Line: 1183

		/* begin block 1.6 */
			// Start line: 1204
			// Start offset: 0x8002E004

			/* begin block 1.6.1 */
				// Start line: 1204
				// Start offset: 0x8002E004

				/* begin block 1.6.1.1 */
					// Start line: 1204
					// Start offset: 0x8002E004
				/* end block 1.6.1.1 */
				// End offset: 0x8002E004
				// End Line: 1204
			/* end block 1.6.1 */
			// End offset: 0x8002E004
			// End Line: 1204
		/* end block 1.6 */
		// End offset: 0x8002E020
		// End Line: 1205

		/* begin block 1.7 */
			// Start line: 1206
			// Start offset: 0x8002E030

			/* begin block 1.7.1 */
				// Start line: 1206
				// Start offset: 0x8002E030

				/* begin block 1.7.1.1 */
					// Start line: 1206
					// Start offset: 0x8002E030

					/* begin block 1.7.1.1.1 */
						// Start line: 1206
						// Start offset: 0x8002E030
					/* end block 1.7.1.1.1 */
					// End offset: 0x8002E030
					// End Line: 1206
				/* end block 1.7.1.1 */
				// End offset: 0x8002E030
				// End Line: 1206
			/* end block 1.7.1 */
			// End offset: 0x8002E030
			// End Line: 1206
		/* end block 1.7 */
		// End offset: 0x8002E030
		// End Line: 1206
	/* end block 1 */
	// End offset: 0x8002E030
	// End Line: 1206

/* WARNING: Control flow encountered bad instruction data */

void MenuExtended_AwardPinkSlipsCar__FR12tMenuCommand(tMenuCommand *command)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_GoToGarage__FR12tMenuCommand(struct tMenuCommand *command /*$s1*/)
 // line 1222, offset 0x8002e09c
	/* begin block 1 */
		// Start line: 1223
		// Start offset: 0x8002E09C

		/* begin block 1.1 */
			// Start line: 1223
			// Start offset: 0x8002E09C
			// Variables:
		// 		struct tListIteratorCar *this; // $a0

			/* begin block 1.1.1 */
				// Start line: 1223
				// Start offset: 0x8002E09C
			/* end block 1.1.1 */
			// End offset: 0x8002E09C
			// End Line: 1223
		/* end block 1.1 */
		// End offset: 0x8002E09C
		// End Line: 1223

		/* begin block 1.2 */
			// Start line: 1223
			// Start offset: 0x8002E09C

			/* begin block 1.2.1 */
				// Start line: 1223
				// Start offset: 0x8002E09C

				/* begin block 1.2.1.1 */
					// Start line: 1223
					// Start offset: 0x8002E09C
				/* end block 1.2.1.1 */
				// End offset: 0x8002E09C
				// End Line: 1223
			/* end block 1.2.1 */
			// End offset: 0x8002E09C
			// End Line: 1223
		/* end block 1.2 */
		// End offset: 0x8002E120
		// End Line: 1231
	/* end block 1 */
	// End offset: 0x8002E120
	// End Line: 1232

/* WARNING: Control flow encountered bad instruction data */

void MenuExtended_GoToGarage__FR12tMenuCommand(tMenuCommand *command)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_GoToTournTrophyRoom__FR12tMenuCommand()
 // line 1235, offset 0x8002e144
	/* begin block 1 */
		// Start line: 1236
		// Start offset: 0x8002E144
	/* end block 1 */
	// End offset: 0x8002E144
	// End Line: 1237

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void MenuExtended_GoToTournTrophyRoom__FR12tMenuCommand(void)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_GoToSETrophyRoom__FR12tMenuCommand()
 // line 1240, offset 0x8002e150
	/* begin block 1 */
		// Start line: 1241
		// Start offset: 0x8002E150
	/* end block 1 */
	// End offset: 0x8002E150
	// End Line: 1242

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void MenuExtended_GoToSETrophyRoom__FR12tMenuCommand(void)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_SetBeginner__FR12tMenuCommand()
 // line 1245, offset 0x8002e160
	/* begin block 1 */
		// Start line: 1246
		// Start offset: 0x8002E160
	/* end block 1 */
	// End offset: 0x8002E160
	// End Line: 1247

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void MenuExtended_SetBeginner__FR12tMenuCommand(void)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_SetIntermediate__FR12tMenuCommand()
 // line 1250, offset 0x8002e16c
	/* begin block 1 */
		// Start line: 1251
		// Start offset: 0x8002E16C
	/* end block 1 */
	// End offset: 0x8002E16C
	// End Line: 1252

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void MenuExtended_SetIntermediate__FR12tMenuCommand(void)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_SetExpert__FR12tMenuCommand()
 // line 1255, offset 0x8002e17c
	/* begin block 1 */
		// Start line: 1256
		// Start offset: 0x8002E17C
	/* end block 1 */
	// End offset: 0x8002E17C
	// End Line: 1257

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void MenuExtended_SetExpert__FR12tMenuCommand(void)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_ExitTourney__FR12tMenuCommand(struct tMenuCommand *command /*$s1*/)
 // line 1260, offset 0x8002e18c
	/* begin block 1 */
		// Start line: 1261
		// Start offset: 0x8002E18C
		// Variables:
	// 		struct tDialogYesNo AreYouSure; // stack offset -184

		/* begin block 1.1 */
			// Start line: 1261
			// Start offset: 0x8002E18C
			// Variables:
		// 		struct tDialogYesNo *this; // $s0

			/* begin block 1.1.1 */
				// Start line: 1261
				// Start offset: 0x8002E18C
			/* end block 1.1.1 */
			// End offset: 0x8002E18C
			// End Line: 1261
		/* end block 1.1 */
		// End offset: 0x8002E18C
		// End Line: 1261

		/* begin block 1.2 */
			// Start line: 1261
			// Start offset: 0x8002E18C

			/* begin block 1.2.1 */
				// Start line: 1261
				// Start offset: 0x8002E18C
			/* end block 1.2.1 */
			// End offset: 0x8002E18C
			// End Line: 1261
		/* end block 1.2 */
		// End offset: 0x8002E18C
		// End Line: 1261

		/* begin block 1.3 */
			// Start line: 1261
			// Start offset: 0x8002E1FC

			/* begin block 1.3.1 */
				// Start line: 1261
				// Start offset: 0x8002E1FC

				/* begin block 1.3.1.1 */
					// Start line: 1261
					// Start offset: 0x8002E1FC

					/* begin block 1.3.1.1.1 */
						// Start line: 1261
						// Start offset: 0x8002E1FC
					/* end block 1.3.1.1.1 */
					// End offset: 0x8002E1FC
					// End Line: 1261
				/* end block 1.3.1.1 */
				// End offset: 0x8002E1FC
				// End Line: 1261
			/* end block 1.3.1 */
			// End offset: 0x8002E1FC
			// End Line: 1261
		/* end block 1.3 */
		// End offset: 0x8002E1FC
		// End Line: 1261
	/* end block 1 */
	// End offset: 0x8002E1FC
	// End Line: 1261

/* WARNING: Control flow encountered bad instruction data */

void MenuExtended_ExitTourney__FR12tMenuCommand(tMenuCommand *command)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_ExitPinkSlipsEarly__FR12tMenuCommand(struct tMenuCommand *command /*$s3*/)
 // line 1274, offset 0x8002e21c
	/* begin block 1 */
		// Start line: 1275
		// Start offset: 0x8002E21C
		// Variables:
	// 		struct tDialogYesNo AreYouSure; // stack offset -272

		/* begin block 1.1 */
			// Start line: 1275
			// Start offset: 0x8002E21C
			// Variables:
		// 		struct tDialogYesNo *this; // $s0

			/* begin block 1.1.1 */
				// Start line: 1275
				// Start offset: 0x8002E21C
			/* end block 1.1.1 */
			// End offset: 0x8002E21C
			// End Line: 1275
		/* end block 1.1 */
		// End offset: 0x8002E21C
		// End Line: 1275

		/* begin block 1.2 */
			// Start line: 1275
			// Start offset: 0x8002E21C

			/* begin block 1.2.1 */
				// Start line: 1275
				// Start offset: 0x8002E21C
			/* end block 1.2.1 */
			// End offset: 0x8002E21C
			// End Line: 1275
		/* end block 1.2 */
		// End offset: 0x8002E21C
		// End Line: 1275

		/* begin block 1.3 */
			// Start line: 1275
			// Start offset: 0x8002E21C

			/* begin block 1.3.1 */
				// Start line: 1280
				// Start offset: 0x8002E278
				// Variables:
			// 		char string[80]; // stack offset -104

				/* begin block 1.3.1.1 */
					// Start line: 1284
					// Start offset: 0x8002E278
					// Variables:
				// 		int player; // $s1

					/* begin block 1.3.1.1.1 */
						// Start line: 1286
						// Start offset: 0x8002E288

						/* begin block 1.3.1.1.1.1 */
							// Start line: 1288
							// Start offset: 0x8002E294

							/* begin block 1.3.1.1.1.1.1 */
								// Start line: 1288
								// Start offset: 0x8002E294
							/* end block 1.3.1.1.1.1.1 */
							// End offset: 0x8002E294
							// End Line: 1288
						/* end block 1.3.1.1.1.1 */
						// End offset: 0x8002E294
						// End Line: 1288
					/* end block 1.3.1.1.1 */
					// End offset: 0x8002E294
					// End Line: 1288
				/* end block 1.3.1.1 */
				// End offset: 0x8002E2EC
				// End Line: 1291
			/* end block 1.3.1 */
			// End offset: 0x8002E324
			// End Line: 1299
		/* end block 1.3 */
		// End offset: 0x8002E324
		// End Line: 1299

		/* begin block 1.4 */
			// Start line: 1275
			// Start offset: 0x8002E324

			/* begin block 1.4.1 */
				// Start line: 1275
				// Start offset: 0x8002E324

				/* begin block 1.4.1.1 */
					// Start line: 1275
					// Start offset: 0x8002E324

					/* begin block 1.4.1.1.1 */
						// Start line: 1275
						// Start offset: 0x8002E324
					/* end block 1.4.1.1.1 */
					// End offset: 0x8002E324
					// End Line: 1275
				/* end block 1.4.1.1 */
				// End offset: 0x8002E324
				// End Line: 1275
			/* end block 1.4.1 */
			// End offset: 0x8002E324
			// End Line: 1275
		/* end block 1.4 */
		// End offset: 0x8002E324
		// End Line: 1275
	/* end block 1 */
	// End offset: 0x8002E324
	// End Line: 1275

/* WARNING: Control flow encountered bad instruction data */

void MenuExtended_ExitPinkSlipsEarly__FR12tMenuCommand(tMenuCommand *command)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MenuExtended_PinkSlipsContinue__FR12tMenuCommand(struct tMenuCommand *command /*$a0*/)
 // line 1304, offset 0x8002e34c
	/* begin block 1 */
		// Start line: 1305
		// Start offset: 0x8002E34C
	/* end block 1 */
	// End offset: 0x8002E3B0
	// End Line: 1316

/* WARNING: Control flow encountered bad instruction data */

void MenuExtended_PinkSlipsContinue__FR12tMenuCommand(tMenuCommand *command)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// struct tGlobalMenuDefs * /*$ra*/ __15tGlobalMenuDefs(struct tGlobalMenuDefs *this /*stack 0*/)
 // line 1353, offset 0x8002e3b8
	/* begin block 1 */
		// Start line: 1354
		// Start offset: 0x8002E3B8
		// Variables:
	// 		struct tMenuItemOptionsLeftRightChoice *this; // $s6

		/* begin block 1.1 */
			// Start line: 1354
			// Start offset: 0x8002E3B8
		/* end block 1.1 */
		// End offset: 0x8002E3B8
		// End Line: 1354
	/* end block 1 */
	// End offset: 0x8002E3B8
	// End Line: 1354

	/* begin block 2 */
		// Start line: 1354
		// Start offset: 0x8002E3B8
		// Variables:
	// 		struct tMenuItemOptionsLeftRightChoice *this; // $s7

		/* begin block 2.1 */
			// Start line: 1354
			// Start offset: 0x8002E3B8
		/* end block 2.1 */
		// End offset: 0x8002E3B8
		// End Line: 1354
	/* end block 2 */
	// End offset: 0x8002E3B8
	// End Line: 1354

	/* begin block 3 */
		// Start line: 1354
		// Start offset: 0x8002E3B8
		// Variables:
	// 		struct tMenuItemOptionsTwoItemChoice *this; // $fp

		/* begin block 3.1 */
			// Start line: 1354
			// Start offset: 0x8002E3B8
		/* end block 3.1 */
		// End offset: 0x8002E3B8
		// End Line: 1354
	/* end block 3 */
	// End offset: 0x8002E3B8
	// End Line: 1354

	/* begin block 4 */
		// Start line: 1354
		// Start offset: 0x8002E3B8
		// Variables:
	// 		struct tMenuItemOptionsTwoItemChoice *this; // stack offset -408

		/* begin block 4.1 */
			// Start line: 1354
			// Start offset: 0x8002E3B8
		/* end block 4.1 */
		// End offset: 0x8002E3B8
		// End Line: 1354
	/* end block 4 */
	// End offset: 0x8002E3B8
	// End Line: 1354

	/* begin block 5 */
		// Start line: 1354
		// Start offset: 0x8002E3B8
		// Variables:
	// 		struct tMenuItemOptionsTwoItemChoice *this; // stack offset -404

		/* begin block 5.1 */
			// Start line: 1354
			// Start offset: 0x8002E3B8
		/* end block 5.1 */
		// End offset: 0x8002E3B8
		// End Line: 1354
	/* end block 5 */
	// End offset: 0x8002E3B8
	// End Line: 1354

	/* begin block 6 */
		// Start line: 1354
		// Start offset: 0x8002E3B8
		// Variables:
	// 		struct tMenuItemOptionsTwoItemChoice *this; // stack offset -400

		/* begin block 6.1 */
			// Start line: 1354
			// Start offset: 0x8002E3B8
		/* end block 6.1 */
		// End offset: 0x8002E3B8
		// End Line: 1354
	/* end block 6 */
	// End offset: 0x8002E3B8
	// End Line: 1354

	/* begin block 7 */
		// Start line: 1354
		// Start offset: 0x8002E3B8
		// Variables:
	// 		struct tMenuItemOptionsTwoItemChoice *this; // stack offset -396

		/* begin block 7.1 */
			// Start line: 1354
			// Start offset: 0x8002E3B8
		/* end block 7.1 */
		// End offset: 0x8002E3B8
		// End Line: 1354
	/* end block 7 */
	// End offset: 0x8002E3B8
	// End Line: 1354

	/* begin block 8 */
		// Start line: 1354
		// Start offset: 0x8002E3B8
		// Variables:
	// 		struct tBlankMenuItemGoToMenuNFS4Button *this; // $s0

		/* begin block 8.1 */
			// Start line: 1354
			// Start offset: 0x8002E3B8
		/* end block 8.1 */
		// End offset: 0x8002E3B8
		// End Line: 1354
	/* end block 8 */
	// End offset: 0x8002E3B8
	// End Line: 1354

	/* begin block 9 */
		// Start line: 1354
		// Start offset: 0x8002E3B8
		// Variables:
	// 		struct tMenuItemOptionsLeftRightChoice *this; // stack offset -268

		/* begin block 9.1 */
			// Start line: 1354
			// Start offset: 0x8002E3B8
		/* end block 9.1 */
		// End offset: 0x8002E3B8
		// End Line: 1354
	/* end block 9 */
	// End offset: 0x8002E3B8
	// End Line: 1354

	/* begin block 10 */
		// Start line: 1354
		// Start offset: 0x8002E3B8
		// Variables:
	// 		struct tMenuItemOptionsLeftRightChoice *this; // stack offset -264

		/* begin block 10.1 */
			// Start line: 1354
			// Start offset: 0x8002E3B8
		/* end block 10.1 */
		// End offset: 0x8002E3B8
		// End Line: 1354
	/* end block 10 */
	// End offset: 0x8002E3B8
	// End Line: 1354

	/* begin block 11 */
		// Start line: 1354
		// Start offset: 0x8002E3B8
		// Variables:
	// 		struct tMenuItemOptionsLeftRightChoice *this; // stack offset -260

		/* begin block 11.1 */
			// Start line: 1354
			// Start offset: 0x8002E3B8
		/* end block 11.1 */
		// End offset: 0x8002E3B8
		// End Line: 1354
	/* end block 11 */
	// End offset: 0x8002E3B8
	// End Line: 1354

	/* begin block 12 */
		// Start line: 1354
		// Start offset: 0x8002E3B8
		// Variables:
	// 		struct tMenuItemOptionsLeftRightChoice *this; // $fp

		/* begin block 12.1 */
			// Start line: 1354
			// Start offset: 0x8002E3B8
		/* end block 12.1 */
		// End offset: 0x8002E3B8
		// End Line: 1354
	/* end block 12 */
	// End offset: 0x8002E3B8
	// End Line: 1354

	/* begin block 13 */
		// Start line: 1354
		// Start offset: 0x8002E3B8
		// Variables:
	// 		struct tMenuItemOptionsLeftRightChoice *this; // stack offset -256

		/* begin block 13.1 */
			// Start line: 1354
			// Start offset: 0x8002E3B8
		/* end block 13.1 */
		// End offset: 0x8002E3B8
		// End Line: 1354
	/* end block 13 */
	// End offset: 0x8002E3B8
	// End Line: 1354

	/* begin block 14 */
		// Start line: 1354
		// Start offset: 0x8002E3B8
		// Variables:
	// 		struct tMenuItemOptionsLeftRightChoice *this; // $s3

		/* begin block 14.1 */
			// Start line: 1354
			// Start offset: 0x8002E3B8
		/* end block 14.1 */
		// End offset: 0x8002E3B8
		// End Line: 1354
	/* end block 14 */
	// End offset: 0x8002E3B8
	// End Line: 1354

	/* begin block 15 */
		// Start line: 1354
		// Start offset: 0x8002E3B8
		// Variables:
	// 		struct tMenuItemOptionsLeftRightChoice *this; // stack offset -252

		/* begin block 15.1 */
			// Start line: 1354
			// Start offset: 0x8002E3B8
		/* end block 15.1 */
		// End offset: 0x8002E3B8
		// End Line: 1354
	/* end block 15 */
	// End offset: 0x8002E3B8
	// End Line: 1354

	/* begin block 16 */
		// Start line: 1354
		// Start offset: 0x8002E3B8
		// Variables:
	// 		struct tMenuItemDisplayLeftRightChoice *this; // stack offset -192

		/* begin block 16.1 */
			// Start line: 1354
			// Start offset: 0x8002E3B8
		/* end block 16.1 */
		// End offset: 0x8002E3B8
		// End Line: 1354
	/* end block 16 */
	// End offset: 0x8002E3B8
	// End Line: 1354

	/* begin block 17 */
		// Start line: 1354
		// Start offset: 0x8002E3B8
		// Variables:
	// 		struct tMenuItemSlidingActivated *this; // $s0

		/* begin block 17.1 */
			// Start line: 1354
			// Start offset: 0x8002E3B8
		/* end block 17.1 */
		// End offset: 0x8002E3B8
		// End Line: 1354
	/* end block 17 */
	// End offset: 0x8002E3B8
	// End Line: 1354

	/* begin block 18 */
		// Start line: 1354
		// Start offset: 0x8002E3B8
		// Variables:
	// 		struct tMenuItemDisplayLeftRightChoice *this; // $s5

		/* begin block 18.1 */
			// Start line: 1354
			// Start offset: 0x8002E3B8
		/* end block 18.1 */
		// End offset: 0x8002E3B8
		// End Line: 1354
	/* end block 18 */
	// End offset: 0x8002E3B8
	// End Line: 1354

	/* begin block 19 */
		// Start line: 1354
		// Start offset: 0x8002E3B8
		// Variables:
	// 		struct tMenuItemDisplayLeftRightChoice *this; // $fp

		/* begin block 19.1 */
			// Start line: 1354
			// Start offset: 0x8002E3B8
		/* end block 19.1 */
		// End offset: 0x8002E3B8
		// End Line: 1354
	/* end block 19 */
	// End offset: 0x8002E3B8
	// End Line: 1354

	/* begin block 20 */
		// Start line: 1354
		// Start offset: 0x8002E3B8
		// Variables:
	// 		struct tMenuItemDisplayLeftRightChoice *this; // stack offset -164

		/* begin block 20.1 */
			// Start line: 1354
			// Start offset: 0x8002E3B8
		/* end block 20.1 */
		// End offset: 0x8002E3B8
		// End Line: 1354
	/* end block 20 */
	// End offset: 0x8002E3B8
	// End Line: 1354

	/* begin block 21 */
		// Start line: 1354
		// Start offset: 0x8002E3B8
		// Variables:
	// 		struct tMenuItemOnOffLeftRightChoice *this; // stack offset -160

		/* begin block 21.1 */
			// Start line: 1354
			// Start offset: 0x8002E3B8
		/* end block 21.1 */
		// End offset: 0x8002E3B8
		// End Line: 1354
	/* end block 21 */
	// End offset: 0x8002E3B8
	// End Line: 1354

	/* begin block 22 */
		// Start line: 1354
		// Start offset: 0x8002E3B8
		// Variables:
	// 		struct tMenuItemOnOffLeftRightChoice *this; // stack offset -156

		/* begin block 22.1 */
			// Start line: 1354
			// Start offset: 0x8002E3B8
		/* end block 22.1 */
		// End offset: 0x8002E3B8
		// End Line: 1354
	/* end block 22 */
	// End offset: 0x8002E3B8
	// End Line: 1354

	/* begin block 23 */
		// Start line: 1354
		// Start offset: 0x8002E3B8
		// Variables:
	// 		struct tMenuItemOnOffLeftRightChoice *this; // $s3

		/* begin block 23.1 */
			// Start line: 1354
			// Start offset: 0x8002E3B8
		/* end block 23.1 */
		// End offset: 0x8002E3B8
		// End Line: 1354
	/* end block 23 */
	// End offset: 0x8002E3B8
	// End Line: 1354

	/* begin block 24 */
		// Start line: 1354
		// Start offset: 0x8002E3B8
		// Variables:
	// 		struct tMenuItemDisplayLeftRightChoice *this; // stack offset -152

		/* begin block 24.1 */
			// Start line: 1354
			// Start offset: 0x8002E3B8
		/* end block 24.1 */
		// End offset: 0x8002E3B8
		// End Line: 1354
	/* end block 24 */
	// End offset: 0x8002E3B8
	// End Line: 1354

	/* begin block 25 */
		// Start line: 1354
		// Start offset: 0x8002E3B8
		// Variables:
	// 		struct tMenuItemDisplayLeftRightChoice *this; // $s0

		/* begin block 25.1 */
			// Start line: 1354
			// Start offset: 0x8002E3B8
		/* end block 25.1 */
		// End offset: 0x8002E3B8
		// End Line: 1354
	/* end block 25 */
	// End offset: 0x8002E3B8
	// End Line: 1354

	/* begin block 26 */
		// Start line: 1354
		// Start offset: 0x8002E3B8
		// Variables:
	// 		struct tMenuItemControllerLeftRightChoice *this; // $s0

		/* begin block 26.1 */
			// Start line: 1354
			// Start offset: 0x8002E3B8
		/* end block 26.1 */
		// End offset: 0x8002E3B8
		// End Line: 1354
	/* end block 26 */
	// End offset: 0x8002E3B8
	// End Line: 1354

	/* begin block 27 */
		// Start line: 1354
		// Start offset: 0x8002E3B8
		// Variables:
	// 		struct tInsideBoxControllerLeftRightSlider *this; // stack offset -140

		/* begin block 27.1 */
			// Start line: 1354
			// Start offset: 0x8002E3B8
		/* end block 27.1 */
		// End offset: 0x8002E3B8
		// End Line: 1354
	/* end block 27 */
	// End offset: 0x8002E3B8
	// End Line: 1354

	/* begin block 28 */
		// Start line: 1354
		// Start offset: 0x8002E3B8
		// Variables:
	// 		struct tInsideBoxControllerLeftRightSlider *this; // stack offset -132

		/* begin block 28.1 */
			// Start line: 1354
			// Start offset: 0x8002E3B8
		/* end block 28.1 */
		// End offset: 0x8002E3B8
		// End Line: 1354
	/* end block 28 */
	// End offset: 0x8002E3B8
	// End Line: 1354

	/* begin block 29 */
		// Start line: 1354
		// Start offset: 0x8002E3B8
		// Variables:
	// 		struct tMemoryCardMenuItem *this; // $fp

		/* begin block 29.1 */
			// Start line: 1354
			// Start offset: 0x8002E3B8
			// Variables:
		// 		struct tMenuItemGoToMenuButtonFade *this; // $fp

			/* begin block 29.1.1 */
				// Start line: 1354
				// Start offset: 0x8002E3B8
			/* end block 29.1.1 */
			// End offset: 0x8002E3B8
			// End Line: 1354
		/* end block 29.1 */
		// End offset: 0x8002E3B8
		// End Line: 1354

		/* begin block 29.2 */
			// Start line: 1354
			// Start offset: 0x8002E3B8
		/* end block 29.2 */
		// End offset: 0x8002E3B8
		// End Line: 1354
	/* end block 29 */
	// End offset: 0x8002E3B8
	// End Line: 1354

	/* begin block 30 */
		// Start line: 1354
		// Start offset: 0x8002E3B8
		// Variables:
	// 		struct tMemoryCardMenuItem *this; // $s0

		/* begin block 30.1 */
			// Start line: 1354
			// Start offset: 0x8002E3B8
			// Variables:
		// 		struct tMenuItemGoToMenuButtonFade *this; // $s0

			/* begin block 30.1.1 */
				// Start line: 1354
				// Start offset: 0x8002E3B8
			/* end block 30.1.1 */
			// End offset: 0x8002E3B8
			// End Line: 1354
		/* end block 30.1 */
		// End offset: 0x8002E3B8
		// End Line: 1354

		/* begin block 30.2 */
			// Start line: 1354
			// Start offset: 0x8002E3B8
		/* end block 30.2 */
		// End offset: 0x8002E3B8
		// End Line: 1354
	/* end block 30 */
	// End offset: 0x8002E3B8
	// End Line: 1354

	/* begin block 31 */
		// Start line: 1354
		// Start offset: 0x8002E3B8
		// Variables:
	// 		struct tBlankMenuItemNFS4LeftRightChoice *this; // $s0

		/* begin block 31.1 */
			// Start line: 1354
			// Start offset: 0x8002E3B8
		/* end block 31.1 */
		// End offset: 0x8002E3B8
		// End Line: 1354
	/* end block 31 */
	// End offset: 0x8002E3B8
	// End Line: 1354

	/* begin block 32 */
		// Start line: 1354
		// Start offset: 0x8002E3B8
		// Variables:
	// 		struct tBlankMenuItemGoToMenuNFS4Button *this; // $s0

		/* begin block 32.1 */
			// Start line: 1354
			// Start offset: 0x8002E3B8
		/* end block 32.1 */
		// End offset: 0x8002E3B8
		// End Line: 1354
	/* end block 32 */
	// End offset: 0x8002E3B8
	// End Line: 1354

	/* begin block 33 */
		// Start line: 1354
		// Start offset: 0x8002E3B8
		// Variables:
	// 		struct tMemoryCardMenuItem *this; // $s0

		/* begin block 33.1 */
			// Start line: 1354
			// Start offset: 0x8002E3B8
			// Variables:
		// 		struct tMenuItemGoToMenuButtonFade *this; // $s0

			/* begin block 33.1.1 */
				// Start line: 1354
				// Start offset: 0x8002E3B8
			/* end block 33.1.1 */
			// End offset: 0x8002E3B8
			// End Line: 1354
		/* end block 33.1 */
		// End offset: 0x8002E3B8
		// End Line: 1354

		/* begin block 33.2 */
			// Start line: 1354
			// Start offset: 0x8002E3B8
		/* end block 33.2 */
		// End offset: 0x8002E3B8
		// End Line: 1354
	/* end block 33 */
	// End offset: 0x8002E3B8
	// End Line: 1354

	/* begin block 34 */
		// Start line: 1354
		// Start offset: 0x8002E3B8

		/* begin block 34.1 */
			// Start line: 1354
			// Start offset: 0x8002E3B8
			// Variables:
		// 		struct tMenu *child; // $v0

			/* begin block 34.1.1 */
				// Start line: 1354
				// Start offset: 0x8002E3B8
			/* end block 34.1.1 */
			// End offset: 0x8002E3B8
			// End Line: 1354
		/* end block 34.1 */
		// End offset: 0x8002E3B8
		// End Line: 1354

		/* begin block 34.2 */
			// Start line: 1354
			// Start offset: 0x8002E3B8
			// Variables:
		// 		struct tMenu *child; // $v0

			/* begin block 34.2.1 */
				// Start line: 1354
				// Start offset: 0x8002E3B8
			/* end block 34.2.1 */
			// End offset: 0x8002E3B8
			// End Line: 1354
		/* end block 34.2 */
		// End offset: 0x8002E3B8
		// End Line: 1354

		/* begin block 34.3 */
			// Start line: 1354
			// Start offset: 0x8002E3B8
			// Variables:
		// 		struct tMenu *child; // $v0

			/* begin block 34.3.1 */
				// Start line: 1354
				// Start offset: 0x8002E3B8
			/* end block 34.3.1 */
			// End offset: 0x8002E3B8
			// End Line: 1354
		/* end block 34.3 */
		// End offset: 0x8002E3B8
		// End Line: 1354

		/* begin block 34.4 */
			// Start line: 1354
			// Start offset: 0x8002E3B8

			/* begin block 34.4.1 */
				// Start line: 1354
				// Start offset: 0x8002E3B8
			/* end block 34.4.1 */
			// End offset: 0x8002E3B8
			// End Line: 1354
		/* end block 34.4 */
		// End offset: 0x8002E3B8
		// End Line: 1354

		/* begin block 34.5 */
			// Start line: 1354
			// Start offset: 0x8002E3B8

			/* begin block 34.5.1 */
				// Start line: 1354
				// Start offset: 0x8002E3B8
			/* end block 34.5.1 */
			// End offset: 0x8002E3B8
			// End Line: 1354
		/* end block 34.5 */
		// End offset: 0x8002E3B8
		// End Line: 1354

		/* begin block 34.6 */
			// Start line: 1354
			// Start offset: 0x8002E3B8

			/* begin block 34.6.1 */
				// Start line: 1354
				// Start offset: 0x8002E3B8
			/* end block 34.6.1 */
			// End offset: 0x8002E3B8
			// End Line: 1354
		/* end block 34.6 */
		// End offset: 0x8002E3B8
		// End Line: 1354

		/* begin block 34.7 */
			// Start line: 1354
			// Start offset: 0x8002E3B8

			/* begin block 34.7.1 */
				// Start line: 1354
				// Start offset: 0x8002E3B8
			/* end block 34.7.1 */
			// End offset: 0x8002E3B8
			// End Line: 1354
		/* end block 34.7 */
		// End offset: 0x8002E3B8
		// End Line: 1354

		/* begin block 34.8 */
			// Start line: 1354
			// Start offset: 0x8002E3B8

			/* begin block 34.8.1 */
				// Start line: 1354
				// Start offset: 0x8002E3B8
			/* end block 34.8.1 */
			// End offset: 0x8002E3B8
			// End Line: 1354
		/* end block 34.8 */
		// End offset: 0x8002E3B8
		// End Line: 1354

		/* begin block 34.9 */
			// Start line: 1354
			// Start offset: 0x8002E3B8

			/* begin block 34.9.1 */
				// Start line: 1354
				// Start offset: 0x8002E3B8
			/* end block 34.9.1 */
			// End offset: 0x8002E3B8
			// End Line: 1354
		/* end block 34.9 */
		// End offset: 0x8002E3B8
		// End Line: 1354

		/* begin block 34.10 */
			// Start line: 1354
			// Start offset: 0x8002E3B8

			/* begin block 34.10.1 */
				// Start line: 1354
				// Start offset: 0x8002E3B8
			/* end block 34.10.1 */
			// End offset: 0x8002E3B8
			// End Line: 1354
		/* end block 34.10 */
		// End offset: 0x8002E3B8
		// End Line: 1354

		/* begin block 34.11 */
			// Start line: 1354
			// Start offset: 0x8002E3B8

			/* begin block 34.11.1 */
				// Start line: 1354
				// Start offset: 0x8002E3B8
			/* end block 34.11.1 */
			// End offset: 0x8002E3B8
			// End Line: 1354
		/* end block 34.11 */
		// End offset: 0x8002E3B8
		// End Line: 1354

		/* begin block 34.12 */
			// Start line: 1354
			// Start offset: 0x8002E3B8

			/* begin block 34.12.1 */
				// Start line: 1354
				// Start offset: 0x8002E3B8
			/* end block 34.12.1 */
			// End offset: 0x8002E3B8
			// End Line: 1354
		/* end block 34.12 */
		// End offset: 0x8002E3B8
		// End Line: 1354

		/* begin block 34.13 */
			// Start line: 1354
			// Start offset: 0x8002E3B8

			/* begin block 34.13.1 */
				// Start line: 1354
				// Start offset: 0x8002E3B8
			/* end block 34.13.1 */
			// End offset: 0x8002E3B8
			// End Line: 1354
		/* end block 34.13 */
		// End offset: 0x8002E3B8
		// End Line: 1354

		/* begin block 34.14 */
			// Start line: 1354
			// Start offset: 0x8002E3B8

			/* begin block 34.14.1 */
				// Start line: 1354
				// Start offset: 0x8002E3B8
			/* end block 34.14.1 */
			// End offset: 0x8002E3B8
			// End Line: 1354
		/* end block 34.14 */
		// End offset: 0x8002E3B8
		// End Line: 1354

		/* begin block 34.15 */
			// Start line: 1354
			// Start offset: 0x8002E3B8

			/* begin block 34.15.1 */
				// Start line: 1354
				// Start offset: 0x8002E3B8
			/* end block 34.15.1 */
			// End offset: 0x8002E3B8
			// End Line: 1354
		/* end block 34.15 */
		// End offset: 0x8002E3B8
		// End Line: 1354

		/* begin block 34.16 */
			// Start line: 1354
			// Start offset: 0x8002E3B8

			/* begin block 34.16.1 */
				// Start line: 1354
				// Start offset: 0x8002E3B8
			/* end block 34.16.1 */
			// End offset: 0x8002E3B8
			// End Line: 1354
		/* end block 34.16 */
		// End offset: 0x8002E3B8
		// End Line: 1354
	/* end block 34 */
	// End offset: 0x8002E3B8
	// End Line: 1354

/* WARNING: Control flow encountered bad instruction data */

tGlobalMenuDefs * __15tGlobalMenuDefs(tGlobalMenuDefs *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ _._15tGlobalMenuDefs(struct tGlobalMenuDefs *this /*$s1*/, int __in_chrg /*$s0*/)
 // line 2204, offset 0x800315d4
	/* begin block 1 */
		// Start line: 2205
		// Start offset: 0x800315D4
	/* end block 1 */
	// End offset: 0x800315D4
	// End Line: 2205

	/* begin block 2 */
		// Start line: 2205
		// Start offset: 0x800315D4

		/* begin block 2.1 */
			// Start line: 2205
			// Start offset: 0x800315D4
		/* end block 2.1 */
		// End offset: 0x800315D4
		// End Line: 2205
	/* end block 2 */
	// End offset: 0x800315D4
	// End Line: 2205

	/* begin block 3 */
		// Start line: 2205
		// Start offset: 0x800315D4
	/* end block 3 */
	// End offset: 0x800315D4
	// End Line: 2205

	/* begin block 4 */
		// Start line: 2205
		// Start offset: 0x800315D4
	/* end block 4 */
	// End offset: 0x800315D4
	// End Line: 2205

	/* begin block 5 */
		// Start line: 2205
		// Start offset: 0x800315D4
	/* end block 5 */
	// End offset: 0x800315D4
	// End Line: 2205

	/* begin block 6 */
		// Start line: 2205
		// Start offset: 0x800315D4
	/* end block 6 */
	// End offset: 0x800315D4
	// End Line: 2205

	/* begin block 7 */
		// Start line: 2205
		// Start offset: 0x800315D4
	/* end block 7 */
	// End offset: 0x800315D4
	// End Line: 2205

	/* begin block 8 */
		// Start line: 2205
		// Start offset: 0x800315D4

		/* begin block 8.1 */
			// Start line: 2205
			// Start offset: 0x800315D4
		/* end block 8.1 */
		// End offset: 0x800315D4
		// End Line: 2205
	/* end block 8 */
	// End offset: 0x800315D4
	// End Line: 2205

	/* begin block 9 */
		// Start line: 2205
		// Start offset: 0x800315D4

		/* begin block 9.1 */
			// Start line: 2205
			// Start offset: 0x800315D4
		/* end block 9.1 */
		// End offset: 0x800315D4
		// End Line: 2205
	/* end block 9 */
	// End offset: 0x800315D4
	// End Line: 2205

	/* begin block 10 */
		// Start line: 2205
		// Start offset: 0x800315D4
	/* end block 10 */
	// End offset: 0x800315D4
	// End Line: 2205

	/* begin block 11 */
		// Start line: 2205
		// Start offset: 0x800315D4
	/* end block 11 */
	// End offset: 0x800315D4
	// End Line: 2205

	/* begin block 12 */
		// Start line: 2205
		// Start offset: 0x800315D4

		/* begin block 12.1 */
			// Start line: 2205
			// Start offset: 0x800315D4
		/* end block 12.1 */
		// End offset: 0x800315D4
		// End Line: 2205
	/* end block 12 */
	// End offset: 0x800315D4
	// End Line: 2205

	/* begin block 13 */
		// Start line: 2205
		// Start offset: 0x800315D4

		/* begin block 13.1 */
			// Start line: 2205
			// Start offset: 0x800315D4
		/* end block 13.1 */
		// End offset: 0x800315D4
		// End Line: 2205
	/* end block 13 */
	// End offset: 0x800315D4
	// End Line: 2205

	/* begin block 14 */
		// Start line: 2205
		// Start offset: 0x800315D4

		/* begin block 14.1 */
			// Start line: 2205
			// Start offset: 0x800315D4
		/* end block 14.1 */
		// End offset: 0x800315D4
		// End Line: 2205
	/* end block 14 */
	// End offset: 0x800315D4
	// End Line: 2205

	/* begin block 15 */
		// Start line: 2205
		// Start offset: 0x800315D4

		/* begin block 15.1 */
			// Start line: 2205
			// Start offset: 0x800315D4
		/* end block 15.1 */
		// End offset: 0x800315D4
		// End Line: 2205
	/* end block 15 */
	// End offset: 0x800315D4
	// End Line: 2205

	/* begin block 16 */
		// Start line: 2205
		// Start offset: 0x800315D4

		/* begin block 16.1 */
			// Start line: 2205
			// Start offset: 0x800315D4
		/* end block 16.1 */
		// End offset: 0x800315D4
		// End Line: 2205
	/* end block 16 */
	// End offset: 0x800315D4
	// End Line: 2205

	/* begin block 17 */
		// Start line: 2205
		// Start offset: 0x800315D4

		/* begin block 17.1 */
			// Start line: 2205
			// Start offset: 0x800315D4
		/* end block 17.1 */
		// End offset: 0x800315D4
		// End Line: 2205
	/* end block 17 */
	// End offset: 0x800315D4
	// End Line: 2205

	/* begin block 18 */
		// Start line: 2205
		// Start offset: 0x800315D4

		/* begin block 18.1 */
			// Start line: 2205
			// Start offset: 0x800315D4
		/* end block 18.1 */
		// End offset: 0x800315D4
		// End Line: 2205
	/* end block 18 */
	// End offset: 0x800315D4
	// End Line: 2205

	/* begin block 19 */
		// Start line: 2205
		// Start offset: 0x800315D4

		/* begin block 19.1 */
			// Start line: 2205
			// Start offset: 0x800315D4
		/* end block 19.1 */
		// End offset: 0x800315D4
		// End Line: 2205
	/* end block 19 */
	// End offset: 0x800315D4
	// End Line: 2205

	/* begin block 20 */
		// Start line: 2205
		// Start offset: 0x800315D4

		/* begin block 20.1 */
			// Start line: 2205
			// Start offset: 0x800315D4
		/* end block 20.1 */
		// End offset: 0x800315D4
		// End Line: 2205
	/* end block 20 */
	// End offset: 0x800315D4
	// End Line: 2205

	/* begin block 21 */
		// Start line: 2205
		// Start offset: 0x800315D4
	/* end block 21 */
	// End offset: 0x800315D4
	// End Line: 2205

	/* begin block 22 */
		// Start line: 2205
		// Start offset: 0x800315D4

		/* begin block 22.1 */
			// Start line: 2205
			// Start offset: 0x800315D4
		/* end block 22.1 */
		// End offset: 0x800315D4
		// End Line: 2205
	/* end block 22 */
	// End offset: 0x800315D4
	// End Line: 2205

	/* begin block 23 */
		// Start line: 2205
		// Start offset: 0x800315D4
	/* end block 23 */
	// End offset: 0x800315D4
	// End Line: 2205

	/* begin block 24 */
		// Start line: 2205
		// Start offset: 0x800315D4
	/* end block 24 */
	// End offset: 0x800315D4
	// End Line: 2205

	/* begin block 25 */
		// Start line: 2205
		// Start offset: 0x800315D4
	/* end block 25 */
	// End offset: 0x800315D4
	// End Line: 2205

	/* begin block 26 */
		// Start line: 2205
		// Start offset: 0x800315D4
	/* end block 26 */
	// End offset: 0x800315D4
	// End Line: 2205

	/* begin block 27 */
		// Start line: 2205
		// Start offset: 0x800315D4
	/* end block 27 */
	// End offset: 0x800315D4
	// End Line: 2205

	/* begin block 28 */
		// Start line: 2205
		// Start offset: 0x800315D4
	/* end block 28 */
	// End offset: 0x800315D4
	// End Line: 2205

	/* begin block 29 */
		// Start line: 2205
		// Start offset: 0x800315D4
	/* end block 29 */
	// End offset: 0x800315D4
	// End Line: 2205

	/* begin block 30 */
		// Start line: 2205
		// Start offset: 0x800315D4
	/* end block 30 */
	// End offset: 0x800315D4
	// End Line: 2205

	/* begin block 31 */
		// Start line: 2205
		// Start offset: 0x800315D4
	/* end block 31 */
	// End offset: 0x800315D4
	// End Line: 2205

	/* begin block 32 */
		// Start line: 2205
		// Start offset: 0x800315D4
	/* end block 32 */
	// End offset: 0x800315D4
	// End Line: 2205

	/* begin block 33 */
		// Start line: 2205
		// Start offset: 0x800315D4
	/* end block 33 */
	// End offset: 0x800315D4
	// End Line: 2205

	/* begin block 34 */
		// Start line: 2205
		// Start offset: 0x800315D4
	/* end block 34 */
	// End offset: 0x800315D4
	// End Line: 2205

	/* begin block 35 */
		// Start line: 2205
		// Start offset: 0x800315D4
	/* end block 35 */
	// End offset: 0x800315D4
	// End Line: 2205

	/* begin block 36 */
		// Start line: 2205
		// Start offset: 0x800315D4
	/* end block 36 */
	// End offset: 0x800315D4
	// End Line: 2205

	/* begin block 37 */
		// Start line: 2205
		// Start offset: 0x800315D4
	/* end block 37 */
	// End offset: 0x800315D4
	// End Line: 2205

/* WARNING: Control flow encountered bad instruction data */

void ___15tGlobalMenuDefs(tGlobalMenuDefs *this,int __in_chrg)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}




