#include "NFS4.H"
#include "FEMISSION.H"

// decompiled code
// original method signature: 
// void /*$ra*/ Initialize__15tMissionManager(struct tMissionManager *this /*$a0*/)
 // line 59, offset 0x80034060
	/* begin block 1 */
		// Start line: 60
		// Start offset: 0x80034060
	/* end block 1 */
	// End offset: 0x80034060
	// End Line: 63

/* WARNING: Control flow encountered bad instruction data */

void Initialize__15tMissionManager(tMissionManager *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ LoadDescription__15tMissionManagerb(struct tMissionManager *this /*$s4*/, void * LoadHotPursuit /*$a1*/)
 // line 79, offset 0x8003407c
	/* begin block 1 */
		// Start line: 80
		// Start offset: 0x8003407C
		// Variables:
	// 		char *input; // $s2
	// 		char *data; // $s1
	// 		unsigned long numMissions; // $s5
	// 		unsigned long numStages; // $s3
	// 		char filename[80]; // stack offset -112
	/* end block 1 */
	// End offset: 0x80034128
	// End Line: 102

/* WARNING: Control flow encountered bad instruction data */

void LoadDescription__15tMissionManagerb(tMissionManager *this,void *LoadHotPursuit)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ ReleaseDescription__15tMissionManager(struct tMissionManager *this /*$s0*/)
 // line 139, offset 0x800341b8
	/* begin block 1 */
		// Start line: 140
		// Start offset: 0x800341B8
	/* end block 1 */
	// End offset: 0x800341E4
	// End Line: 144

/* WARNING: Control flow encountered bad instruction data */

void ReleaseDescription__15tMissionManager(tMissionManager *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// short /*$ra*/ GetMissionStages__15tMissionManagerssPP10tStageInfo(struct tMissionManager *this /*$a0*/, short tier /*$a1*/, short mission /*$a2*/, struct tStageInfo **pStages /*$a3*/)
 // line 172, offset 0x800341f4
	/* begin block 1 */
		// Start line: 173
		// Start offset: 0x800341F4
		// Variables:
	// 		struct tMissionInfo *pMissionInfo; // $v1
	/* end block 1 */
	// End offset: 0x800341F4
	// End Line: 176

/* WARNING: Control flow encountered bad instruction data */

short GetMissionStages__15tMissionManagerssPP10tStageInfo
                (tMissionManager *this,short tier,short mission,tStageInfo **pStages)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ GetMissionToRace__15tMissionManagerPP12tMissionInfo(struct tMissionManager *this /*$a0*/, struct tMissionInfo **mission /*$a1*/)
 // line 186, offset 0x8003425c
	/* begin block 1 */
		// Start line: 187
		// Start offset: 0x8003425C
		// Variables:
	// 		struct tMissionTierInfo *currentTier; // $v0
	/* end block 1 */
	// End offset: 0x8003425C
	// End Line: 188

/* WARNING: Control flow encountered bad instruction data */

void GetMissionToRace__15tMissionManagerPP12tMissionInfo
               (tMissionManager *this,tMissionInfo **mission)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}




