#include "NFS4.H"
#include "FETEXTRENDER.H"

// decompiled code
// original method signature: 
// void /*$ra*/ FETextRender_SetFont__Fi(int size /*$a0*/)
 // line 72, offset 0x80020cd8
	/* begin block 1 */
		// Start line: 73
		// Start offset: 0x80020CD8
	/* end block 1 */
	// End offset: 0x80020D3C
	// End Line: 89

/* WARNING: Control flow encountered bad instruction data */

void FETextRender_SetFont__Fi(int size)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ FETextRender_FullTextRGB__FPcssics(char *sMenuText /*$a0*/, short x /*$s2*/, short y /*$s5*/, int col /*$s7*/, int size /*stack 16*/, int justify /*stack 20*/)
 // line 94, offset 0x80020d4c
	/* begin block 1 */
		// Start line: 95
		// Start offset: 0x80020D4C
		// Variables:
	// 		char *str; // $s1
	// 		char buffer[128]; // stack offset -168
	/* end block 1 */
	// End offset: 0x80020E94
	// End Line: 128

/* WARNING: Control flow encountered bad instruction data */

void FETextRender_FullTextRGB__FPcssics
               (char *sMenuText,short x,short y,int col,int size,int justify)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ FETextRender_FullText__FPcss13tMenuTextType14tMenuTextStates(char *sMenuText /*$a0*/, short x /*$a1*/, short y /*$a2*/, enum tMenuTextType textType /*$a3*/, enum tMenuTextState textState /*stack 16*/, int justify /*stack 20*/)
 // line 136, offset 0x80020ec0
	/* begin block 1 */
		// Start line: 137
		// Start offset: 0x80020EC0
		// Variables:
	// 		int textcol; // $a3
	/* end block 1 */
	// End offset: 0x80020EC0
	// End Line: 137

/* WARNING: Control flow encountered bad instruction data */

void FETextRender_FullText__FPcss13tMenuTextType14tMenuTextStates
               (char *sMenuText,short x,short y,tMenuTextType textType,tMenuTextState textState,
               int justify)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ FETextRender_FullTextFade__FiPcss13tMenuTextType14tMenuTextStates(int fade /*$a0*/, char *sMenuText /*$s5*/, short x /*$a2*/, short y /*$a3*/, enum tMenuTextType textType /*stack 16*/, enum tMenuTextState textState /*stack 20*/, int justify /*stack 24*/)
 // line 144, offset 0x80020f44
	/* begin block 1 */
		// Start line: 145
		// Start offset: 0x80020F44
	/* end block 1 */
	// End offset: 0x80020F44
	// End Line: 145

/* WARNING: Control flow encountered bad instruction data */

void FETextRender_FullTextFade__FiPcss13tMenuTextType14tMenuTextStates
               (int fade,char *sMenuText,short x,short y,tMenuTextType textType,
               tMenuTextState textState,int justify)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ FETextRender_MenuTextPositioned__Fsss14tMenuTextState13tMenuTextType(short index /*$a0*/, short x /*$a1*/, short y /*$a2*/, enum tMenuTextState textState /*$s3*/, enum tMenuTextType textType /*stack 16*/)
 // line 152, offset 0x80021014
	/* begin block 1 */
		// Start line: 153
		// Start offset: 0x80021014
	/* end block 1 */
	// End offset: 0x80021058
	// End Line: 156

/* WARNING: Control flow encountered bad instruction data */

void FETextRender_MenuTextPositioned__Fsss14tMenuTextState13tMenuTextType
               (short index,short x,short y,tMenuTextState textState,tMenuTextType textType)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ FETextRender_MenuTextFade__Fis14tMenuTextState13tMenuTextType(int fade /*$s5*/, short index /*$a1*/, enum tMenuTextState textState /*$s4*/, enum tMenuTextType textType /*$s0*/)
 // line 171, offset 0x800210b4
	/* begin block 1 */
		// Start line: 172
		// Start offset: 0x800210B4
		// Variables:
	// 		int x; // $s3
	// 		int y; // $s2
	/* end block 1 */
	// End offset: 0x80021118
	// End Line: 180

/* WARNING: Control flow encountered bad instruction data */

void FETextRender_MenuTextFade__Fis14tMenuTextState13tMenuTextType
               (int fade,short index,tMenuTextState textState,tMenuTextType textType)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ FETextRender_MenuTextPositionedJustify__Fssss14tMenuTextState13tMenuTextType(short index /*$a0*/, short x /*$a1*/, short y /*$a2*/, short justify /*$a3*/, enum tMenuTextState state /*stack 16*/, enum tMenuTextType type /*stack 20*/)
 // line 193, offset 0x80021180
	/* begin block 1 */
		// Start line: 194
		// Start offset: 0x80021180
	/* end block 1 */
	// End offset: 0x80021180
	// End Line: 194

/* WARNING: Control flow encountered bad instruction data */

void FETextRender_MenuTextPositionedJustify__Fssss14tMenuTextState13tMenuTextType
               (short index,short x,short y,short justify,tMenuTextState state,tMenuTextType type)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ FETextRender_MenuTextPositionedJustifyFade__Fissss14tMenuTextState13tMenuTextType(int fade /*$s5*/, short index /*$a1*/, short x /*$a2*/, short y /*$a3*/, int justify /*stack 16*/, enum tMenuTextState textState /*stack 20*/, enum tMenuTextType textType /*stack 24*/)
 // line 198, offset 0x800211d4
	/* begin block 1 */
		// Start line: 199
		// Start offset: 0x800211D4
	/* end block 1 */
	// End offset: 0x80021280
	// End Line: 213

/* WARNING: Control flow encountered bad instruction data */

void FETextRender_MenuTextPositionedJustifyFade__Fissss14tMenuTextState13tMenuTextType
               (int fade,short index,short x,short y,int justify,tMenuTextState textState,
               tMenuTextType textType)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// int /*$ra*/ FETextRender_WordWrapTextRGBJustify__FPcR4RECTiiib(char *str /*$s0*/, struct RECT *r /*$s7*/, int col /*stack 8*/, int justify /*stack 12*/, int size /*stack 16*/, void * JustGrabHeight /*stack 20*/)
 // line 216, offset 0x800212a4
	/* begin block 1 */
		// Start line: 217
		// Start offset: 0x800212A4
		// Variables:
	// 		int OriginalY; // stack offset -56
	// 		short x; // $v1
	// 		unsigned short index1; // $s4
	// 		unsigned short index2; // $s1
	// 		long strLength; // $fp
	// 		char buffer[128]; // stack offset -696
	// 		char source[512]; // stack offset -568
	// 		short spacing; // stack offset -48
	/* end block 1 */
	// End offset: 0x800216DC
	// End Line: 356

/* WARNING: Control flow encountered bad instruction data */

int FETextRender_WordWrapTextRGBJustify__FPcR4RECTiiib
              (char *str,RECT *r,int col,int justify,int size,void *JustGrabHeight)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ FETextRender_WordWrapTextRGB__FPcR4RECTi(char *str /*$a0*/, struct RECT *r /*$a1*/, int Col /*$a2*/)
 // line 359, offset 0x80021718
	/* begin block 1 */
		// Start line: 360
		// Start offset: 0x80021718
	/* end block 1 */
	// End offset: 0x80021718
	// End Line: 360

/* WARNING: Control flow encountered bad instruction data */

void FETextRender_WordWrapTextRGB__FPcR4RECTi(char *str,RECT *r,int Col)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ FETextRender_WordWrapTextFade__FiPcR4RECT14tMenuTextState13tMenuTextType(int fade /*$t0*/, char *str /*$s2*/, struct RECT *r /*$s3*/, enum tMenuTextState textState /*$a3*/, enum tMenuTextType textType /*stack 16*/)
 // line 364, offset 0x80021740
	/* begin block 1 */
		// Start line: 365
		// Start offset: 0x80021740
	/* end block 1 */
	// End offset: 0x80021740
	// End Line: 365

/* WARNING: Control flow encountered bad instruction data */

void FETextRender_WordWrapTextFade__FiPcR4RECT14tMenuTextState13tMenuTextType
               (int fade,char *str,RECT *r,tMenuTextState textState,tMenuTextType textType)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ FETextRender_WordWrapText__FPcR4RECT14tMenuTextState13tMenuTextType(char *str /*$v0*/, struct RECT *r /*$v1*/, enum tMenuTextState textState /*$t0*/, enum tMenuTextType textType /*$a3*/)
 // line 375, offset 0x800217e8
	/* begin block 1 */
		// Start line: 376
		// Start offset: 0x800217E8
	/* end block 1 */
	// End offset: 0x800217E8
	// End Line: 376

/* WARNING: Control flow encountered bad instruction data */

void FETextRender_WordWrapText__FPcR4RECT14tMenuTextState13tMenuTextType
               (char *str,RECT *r,tMenuTextState textState,tMenuTextType textType)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ FETextRender_WordWrapFade__FisR4RECT14tMenuTextState13tMenuTextType(int fade /*$s1*/, short index /*$a1*/, struct RECT *r /*$s2*/, enum tMenuTextState state /*$s3*/, enum tMenuTextType type /*stack 16*/)
 // line 380, offset 0x80021824
	/* begin block 1 */
		// Start line: 381
		// Start offset: 0x80021824
	/* end block 1 */
	// End offset: 0x80021824
	// End Line: 381

/* WARNING: Control flow encountered bad instruction data */

void FETextRender_WordWrapFade__FisR4RECT14tMenuTextState13tMenuTextType
               (int fade,short index,RECT *r,tMenuTextState state,tMenuTextType type)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ FETextRender_WordWrap__FsR4RECT14tMenuTextState13tMenuTextType(short index /*$a0*/, struct RECT *r /*$v0*/, enum tMenuTextState textState /*$v1*/, enum tMenuTextType textType /*$a3*/)
 // line 388, offset 0x8002188c
	/* begin block 1 */
		// Start line: 389
		// Start offset: 0x8002188C
	/* end block 1 */
	// End offset: 0x8002188C
	// End Line: 389

/* WARNING: Control flow encountered bad instruction data */

void FETextRender_WordWrap__FsR4RECT14tMenuTextState13tMenuTextType
               (short index,RECT *r,tMenuTextState textState,tMenuTextType textType)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// int /*$ra*/ FETextRender_WordWrapHeight__FsPc(short width /*$a0*/, char *str /*$a1*/)
 // line 394, offset 0x800218c8
	/* begin block 1 */
		// Start line: 395
		// Start offset: 0x800218C8
		// Variables:
	// 		struct RECT r; // stack offset -16
	/* end block 1 */
	// End offset: 0x800218C8
	// End Line: 395

/* WARNING: Control flow encountered bad instruction data */

int FETextRender_WordWrapHeight__FsPc(short width,char *str)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ FETextRender_Title__Fs(short index /*$a0*/)
 // line 420, offset 0x80021914
	/* begin block 1 */
		// Start line: 421
		// Start offset: 0x80021914
		// Variables:
	// 		char upstr[80]; // stack offset -104
	// 		struct RECT r; // stack offset -24
	// 		short offset; // $s0

		/* begin block 1.1 */
			// Start line: 421
			// Start offset: 0x80021914

			/* begin block 1.1.1 */
				// Start line: 421
				// Start offset: 0x80021914
				// Variables:
			// 		struct tFEApplication *this; // $v0

				/* begin block 1.1.1.1 */
					// Start line: 421
					// Start offset: 0x80021914
				/* end block 1.1.1.1 */
				// End offset: 0x80021914
				// End Line: 421
			/* end block 1.1.1 */
			// End offset: 0x80021914
			// End Line: 421
		/* end block 1.1 */
		// End offset: 0x80021940
		// End Line: 427
	/* end block 1 */
	// End offset: 0x80021940
	// End Line: 429

/* WARNING: Control flow encountered bad instruction data */

void FETextRender_Title__Fs(short index)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ FETextRender_SetABR__Fib(int abr /*$a0*/, void * trans /*$a1*/)
 // line 441, offset 0x800219e8
	/* begin block 1 */
		// Start line: 442
		// Start offset: 0x800219E8
	/* end block 1 */
	// End offset: 0x800219E8
	// End Line: 442

/* WARNING: Control flow encountered bad instruction data */

void FETextRender_SetABR__Fib(int abr,void *trans)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}




