#include "NFS4.H"
#include "FETOURN.H"

// decompiled code
// original method signature: 
// void /*$ra*/ Initialize__18tTournamentManager(struct tTournamentManager *this /*$a0*/)
 // line 36, offset 0x80032228
	/* begin block 1 */
		// Start line: 37
		// Start offset: 0x80032228
		// Variables:
	// 		short i; // $a1

		/* begin block 1.1 */
			// Start line: 59
			// Start offset: 0x800322DC

			/* begin block 1.1.1 */
				// Start line: 59
				// Start offset: 0x800322DC
			/* end block 1.1.1 */
			// End offset: 0x800322DC
			// End Line: 59
		/* end block 1.1 */
		// End offset: 0x800322DC
		// End Line: 59

		/* begin block 1.2 */
			// Start line: 59
			// Start offset: 0x800322DC

			/* begin block 1.2.1 */
				// Start line: 59
				// Start offset: 0x800322DC
			/* end block 1.2.1 */
			// End offset: 0x800322DC
			// End Line: 59
		/* end block 1.2 */
		// End offset: 0x800322DC
		// End Line: 59
	/* end block 1 */
	// End offset: 0x800322DC
	// End Line: 59

/* WARNING: Control flow encountered bad instruction data */

void Initialize__18tTournamentManager(tTournamentManager *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ LoadDescription__18tTournamentManager(struct tTournamentManager *this /*$s6*/)
 // line 89, offset 0x800322fc
	/* begin block 1 */
		// Start line: 90
		// Start offset: 0x800322FC
		// Variables:
	// 		char *input; // stack offset -48
	// 		char *data; // $s2
	// 		short tier; // $fp
	// 		short tourney; // $s4
	// 		short track; // $s0
	// 		char filename[80]; // stack offset -128
	/* end block 1 */
	// End offset: 0x8003250C
	// End Line: 140

/* WARNING: Control flow encountered bad instruction data */

void LoadDescription__18tTournamentManager(tTournamentManager *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ ReleaseDescription__18tTournamentManager(struct tTournamentManager *this /*$s0*/)
 // line 145, offset 0x80032548
	/* begin block 1 */
		// Start line: 146
		// Start offset: 0x80032548
	/* end block 1 */
	// End offset: 0x80032574
	// End Line: 150

/* WARNING: Control flow encountered bad instruction data */

void ReleaseDescription__18tTournamentManager(tTournamentManager *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ UpdateTrackList__18tTournamentManagerss(struct tTournamentManager *this /*$t0*/, short tier /*$a1*/, short tournament /*$a2*/)
 // line 195, offset 0x80032584
	/* begin block 1 */
		// Start line: 196
		// Start offset: 0x80032584
		// Variables:
	// 		struct tTourneyInfo *currentTourney; // $a0
	// 		short numTracks; // $t2
	// 		short trackOffset; // $a2
	// 		short i; // $a3
	/* end block 1 */
	// End offset: 0x80032644
	// End Line: 210

/* WARNING: Control flow encountered bad instruction data */

void UpdateTrackList__18tTournamentManagerss(tTournamentManager *this,short tier,short tournament)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// short * /*$ra*/ GetTrackList__18tTournamentManagerss(struct tTournamentManager *this /*$s0*/, short tier /*$a1*/, short tournament /*$a2*/)
 // line 234, offset 0x80032654
	/* begin block 1 */
		// Start line: 235
		// Start offset: 0x80032654
	/* end block 1 */
	// End offset: 0x80032654
	// End Line: 235

/* WARNING: Control flow encountered bad instruction data */

short * GetTrackList__18tTournamentManagerss(tTournamentManager *this,short tier,short tournament)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ GetTrackToRace__18tTournamentManagerR10tTrackInfo(struct tTournamentManager *this /*$s0*/, struct tTrackInfo *track /*$s1*/)
 // line 243, offset 0x8003268c
	/* begin block 1 */
		// Start line: 244
		// Start offset: 0x8003268C

		/* begin block 1.1 */
			// Start line: 244
			// Start offset: 0x8003268C
			// Variables:
		// 		struct tTournamentManager *this; // $s0

			/* begin block 1.1.1 */
				// Start line: 244
				// Start offset: 0x8003268C
			/* end block 1.1.1 */
			// End offset: 0x8003268C
			// End Line: 244
		/* end block 1.1 */
		// End offset: 0x8003268C
		// End Line: 244
	/* end block 1 */
	// End offset: 0x8003268C
	// End Line: 244

/* WARNING: Control flow encountered bad instruction data */

void GetTrackToRace__18tTournamentManagerR10tTrackInfo(tTournamentManager *this,tTrackInfo *track)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ StartNewTournament__18tTournamentManagerUcUc(struct tTournamentManager *this /*$s3*/, unsigned char tier /*$a1*/, unsigned char tournament /*$a2*/)
 // line 264, offset 0x80032784
	/* begin block 1 */
		// Start line: 265
		// Start offset: 0x80032784
		// Variables:
	// 		short i; // $s2
	// 		struct tTourneyInfo *tourn; // $s4
	// 		struct tTrackInfo *track; // $s1

		/* begin block 1.1 */
			// Start line: 265
			// Start offset: 0x80032784
			// Variables:
		// 		struct tTournamentManager *this; // $s3

			/* begin block 1.1.1 */
				// Start line: 265
				// Start offset: 0x80032784
			/* end block 1.1.1 */
			// End offset: 0x80032784
			// End Line: 265
		/* end block 1.1 */
		// End offset: 0x80032784
		// End Line: 265
	/* end block 1 */
	// End offset: 0x80032994
	// End Line: 325

/* WARNING: Control flow encountered bad instruction data */

void StartNewTournament__18tTournamentManagerUcUc
               (tTournamentManager *this,uchar tier,uchar tournament)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// short /*$ra*/ IsTournamentFinished__18tTournamentManager(struct tTournamentManager *this /*$a1*/)
 // line 337, offset 0x800329bc
	/* begin block 1 */
		// Start line: 338
		// Start offset: 0x800329BC

		/* begin block 1.1 */
			// Start line: 338
			// Start offset: 0x800329BC
			// Variables:
		// 		struct tTournamentManager *this; // $a1

			/* begin block 1.1.1 */
				// Start line: 338
				// Start offset: 0x800329BC
			/* end block 1.1.1 */
			// End offset: 0x800329BC
			// End Line: 338
		/* end block 1.1 */
		// End offset: 0x800329BC
		// End Line: 338
	/* end block 1 */
	// End offset: 0x80032A48
	// End Line: 345

/* WARNING: Control flow encountered bad instruction data */

short IsTournamentFinished__18tTournamentManager(tTournamentManager *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// int /*$ra*/ tournPointsCompare__FPcT0(char *p1 /*$a0*/, char *p2 /*$a1*/)
 // line 349, offset 0x80032a50
	/* begin block 1 */
		// Start line: 350
		// Start offset: 0x80032A50
		// Variables:
	// 		int result; // $v1
	// 		struct Car_tStats *dummyCars; // $t0

		/* begin block 1.1 */
			// Start line: 350
			// Start offset: 0x80032A50

			/* begin block 1.1.1 */
				// Start line: 350
				// Start offset: 0x80032A50
			/* end block 1.1.1 */
			// End offset: 0x80032A50
			// End Line: 350
		/* end block 1.1 */
		// End offset: 0x80032A50
		// End Line: 350

		/* begin block 1.2 */
			// Start line: 350
			// Start offset: 0x80032A50

			/* begin block 1.2.1 */
				// Start line: 350
				// Start offset: 0x80032A50
			/* end block 1.2.1 */
			// End offset: 0x80032A50
			// End Line: 350
		/* end block 1.2 */
		// End offset: 0x80032A50
		// End Line: 350
	/* end block 1 */
	// End offset: 0x80032AD4
	// End Line: 366

/* WARNING: Control flow encountered bad instruction data */

int tournPointsCompare__FPcT0(char *p1,char *p2)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ UpdateTournFinishMoney__18tTournamentManager(struct tTournamentManager *this /*$s2*/)
 // line 370, offset 0x80032adc
	/* begin block 1 */
		// Start line: 371
		// Start offset: 0x80032ADC
		// Variables:
	// 		unsigned char i; // $s0
	// 		struct tTourneyInfo *tourn; // $s3

		/* begin block 1.1 */
			// Start line: 371
			// Start offset: 0x80032ADC
			// Variables:
		// 		struct tTournamentManager *this; // $s2

			/* begin block 1.1.1 */
				// Start line: 371
				// Start offset: 0x80032ADC
			/* end block 1.1.1 */
			// End offset: 0x80032ADC
			// End Line: 371
		/* end block 1.1 */
		// End offset: 0x80032ADC
		// End Line: 371
	/* end block 1 */
	// End offset: 0x80032BF0
	// End Line: 399

/* WARNING: Control flow encountered bad instruction data */

void UpdateTournFinishMoney__18tTournamentManager(tTournamentManager *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ UpdateTrackFinishMoney__18tTournamentManager(struct tTournamentManager *this /*$s0*/)
 // line 405, offset 0x80032c0c
	/* begin block 1 */
		// Start line: 406
		// Start offset: 0x80032C0C
		// Variables:
	// 		struct Car_tStats *dummyCars; // $a0

		/* begin block 1.1 */
			// Start line: 406
			// Start offset: 0x80032C0C

			/* begin block 1.1.1 */
				// Start line: 406
				// Start offset: 0x80032C0C
			/* end block 1.1.1 */
			// End offset: 0x80032C0C
			// End Line: 406
		/* end block 1.1 */
		// End offset: 0x80032C0C
		// End Line: 406
	/* end block 1 */
	// End offset: 0x80032C5C
	// End Line: 415

/* WARNING: Control flow encountered bad instruction data */

void UpdateTrackFinishMoney__18tTournamentManager(tTournamentManager *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ CalcTrackFinishDamageBill__18tTournamentManagerbRlT2(struct tTournamentManager *this /*$a0*/, void * recalculate /*$a1*/, long *bill /*$s1*/, long *bonus /*$s2*/)
 // line 422, offset 0x80032c6c
	/* begin block 1 */
		// Start line: 423
		// Start offset: 0x80032C6C
		// Variables:
	// 		static long retbill; // offset 0x0
	// 		static long retbonus; // offset 0x4
	// 		struct Car_tStats *dummyCars; // $s0
	// 		struct tCarInfo carInfo; // stack offset -224
	// 		int damage; // $v1
	// 		long totalcarprice; // $a1

		/* begin block 1.1 */
			// Start line: 423
			// Start offset: 0x80032C6C

			/* begin block 1.1.1 */
				// Start line: 434
				// Start offset: 0x80032C8C

				/* begin block 1.1.1.1 */
					// Start line: 434
					// Start offset: 0x80032C8C

					/* begin block 1.1.1.1.1 */
						// Start line: 434
						// Start offset: 0x80032C8C
					/* end block 1.1.1.1.1 */
					// End offset: 0x80032C8C
					// End Line: 434
				/* end block 1.1.1.1 */
				// End offset: 0x80032C8C
				// End Line: 434

				/* begin block 1.1.1.2 */
					// Start line: 434
					// Start offset: 0x80032C8C
					// Variables:
				// 		int i; // $v1
				/* end block 1.1.1.2 */
				// End offset: 0x80032CFC
				// End Line: 444
			/* end block 1.1.1 */
			// End offset: 0x80032DF8
			// End Line: 460
		/* end block 1.1 */
		// End offset: 0x80032DF8
		// End Line: 460
	/* end block 1 */
	// End offset: 0x80032DF8
	// End Line: 464

/* WARNING: Control flow encountered bad instruction data */

void CalcTrackFinishDamageBill__18tTournamentManagerbRlT2
               (tTournamentManager *this,void *recalculate,long *bill,long *bonus)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ UpdateTrackFinishPoints__18tTournamentManager(struct tTournamentManager *this /*$s0*/)
 // line 481, offset 0x80032e30
	/* begin block 1 */
		// Start line: 482
		// Start offset: 0x80032E30
		// Variables:
	// 		int i; // $a0
	// 		short k; // $a3
	// 		struct Car_tStats *dummyCars; // $t1
	// 		short numCompetitors; // $t0

		/* begin block 1.1 */
			// Start line: 482
			// Start offset: 0x80032E30
			// Variables:
		// 		struct tTournamentManager *this; // $s0

			/* begin block 1.1.1 */
				// Start line: 482
				// Start offset: 0x80032E30
			/* end block 1.1.1 */
			// End offset: 0x80032E30
			// End Line: 482
		/* end block 1.1 */
		// End offset: 0x80032E30
		// End Line: 482

		/* begin block 1.2 */
			// Start line: 482
			// Start offset: 0x80032E30

			/* begin block 1.2.1 */
				// Start line: 482
				// Start offset: 0x80032E30
			/* end block 1.2.1 */
			// End offset: 0x80032E30
			// End Line: 482
		/* end block 1.2 */
		// End offset: 0x80032E30
		// End Line: 482
	/* end block 1 */
	// End offset: 0x80033038
	// End Line: 554

/* WARNING: Control flow encountered bad instruction data */

void UpdateTrackFinishPoints__18tTournamentManager(tTournamentManager *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// short /*$ra*/ AdvanceToNextTrack__18tTournamentManager(struct tTournamentManager *this /*$s1*/)
 // line 569, offset 0x80033048
	/* begin block 1 */
		// Start line: 570
		// Start offset: 0x80033048
		// Variables:
	// 		struct tTourneyInfo *currentTourney; // $s2
	// 		struct tTourneyInfo *tourn; // $v0
	// 		struct tCarInfo *carInfo; // $s3
	// 		struct tTierInfo *currentTier; // $a1
	// 		short i; // $a0

		/* begin block 1.1 */
			// Start line: 570
			// Start offset: 0x80033048
			// Variables:
		// 		struct tTournamentManager *this; // $s1

			/* begin block 1.1.1 */
				// Start line: 570
				// Start offset: 0x80033048
			/* end block 1.1.1 */
			// End offset: 0x80033048
			// End Line: 570
		/* end block 1.1 */
		// End offset: 0x80033048
		// End Line: 570

		/* begin block 1.2 */
			// Start line: 570
			// Start offset: 0x80033048

			/* begin block 1.2.1 */
				// Start line: 578
				// Start offset: 0x800330C4

				/* begin block 1.2.1.1 */
					// Start line: 600
					// Start offset: 0x80033108

					/* begin block 1.2.1.1.1 */
						// Start line: 603
						// Start offset: 0x8003312C

						/* begin block 1.2.1.1.1.1 */
							// Start line: 631
							// Start offset: 0x80033204

							/* begin block 1.2.1.1.1.1.1 */
								// Start line: 632
								// Start offset: 0x80033218

								/* begin block 1.2.1.1.1.1.1.1 */
									// Start line: 655
									// Start offset: 0x800332D0

									/* begin block 1.2.1.1.1.1.1.1.1 */
										// Start line: 659
										// Start offset: 0x800332FC

										/* begin block 1.2.1.1.1.1.1.1.1.1 */
											// Start line: 672
											// Start offset: 0x80033394

											/* begin block 1.2.1.1.1.1.1.1.1.1.1 */
												// Start line: 673
												// Start offset: 0x800333A4
												// Variables:
											// 		int numGarageCars; // $s0
											/* end block 1.2.1.1.1.1.1.1.1.1.1 */
											// End offset: 0x80033468
											// End Line: 693
										/* end block 1.2.1.1.1.1.1.1.1.1 */
										// End offset: 0x80033468
										// End Line: 693
									/* end block 1.2.1.1.1.1.1.1.1 */
									// End offset: 0x80033468
									// End Line: 693
								/* end block 1.2.1.1.1.1.1.1 */
								// End offset: 0x80033468
								// End Line: 693
							/* end block 1.2.1.1.1.1.1 */
							// End offset: 0x80033468
							// End Line: 693
						/* end block 1.2.1.1.1.1 */
						// End offset: 0x80033468
						// End Line: 693
					/* end block 1.2.1.1.1 */
					// End offset: 0x80033468
					// End Line: 693
				/* end block 1.2.1.1 */
				// End offset: 0x80033468
				// End Line: 693
			/* end block 1.2.1 */
			// End offset: 0x8003346C
			// End Line: 699
		/* end block 1.2 */
		// End offset: 0x8003346C
		// End Line: 699
	/* end block 1 */
	// End offset: 0x8003346C
	// End Line: 701

/* WARNING: Control flow encountered bad instruction data */

short AdvanceToNextTrack__18tTournamentManager(tTournamentManager *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// short /*$ra*/ GetLastTrackRaced__18tTournamentManager(struct tTournamentManager *this /*$a0*/)
 // line 706, offset 0x8003348c
	/* begin block 1 */
		// Start line: 707
		// Start offset: 0x8003348C

		/* begin block 1.1 */
			// Start line: 707
			// Start offset: 0x8003348C
			// Variables:
		// 		struct tTournamentManager *this; // $a0

			/* begin block 1.1.1 */
				// Start line: 707
				// Start offset: 0x8003348C
			/* end block 1.1.1 */
			// End offset: 0x8003348C
			// End Line: 707
		/* end block 1.1 */
		// End offset: 0x8003348C
		// End Line: 707
	/* end block 1 */
	// End offset: 0x8003348C
	// End Line: 707

/* WARNING: Control flow encountered bad instruction data */

short GetLastTrackRaced__18tTournamentManager(tTournamentManager *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ SaveTournament__18tTournamentManagerR15tSaveTournament(struct tTournamentManager *this /*$a3*/, struct tSaveTournament *save /*$a1*/)
 // line 744, offset 0x800334fc
	/* begin block 1 */
		// Start line: 745
		// Start offset: 0x800334FC
		// Variables:
	// 		short i; // $a2
	/* end block 1 */
	// End offset: 0x8003353C
	// End Line: 763

/* WARNING: Control flow encountered bad instruction data */

void SaveTournament__18tTournamentManagerR15tSaveTournament
               (tTournamentManager *this,tSaveTournament *save)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ LoadTournament__18tTournamentManagerR15tSaveTournament(struct tTournamentManager *this /*$a3*/, struct tSaveTournament *load /*$a1*/)
 // line 773, offset 0x80033544
	/* begin block 1 */
		// Start line: 774
		// Start offset: 0x80033544
		// Variables:
	// 		short i; // $a2
	/* end block 1 */
	// End offset: 0x80033584
	// End Line: 792

/* WARNING: Control flow encountered bad instruction data */

void LoadTournament__18tTournamentManagerR15tSaveTournament
               (tTournamentManager *this,tSaveTournament *load)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// short /*$ra*/ GetNumCompetitors__18tTournamentManager(struct tTournamentManager *this /*$a0*/)
 // line 803, offset 0x8003358c
	/* begin block 1 */
		// Start line: 804
		// Start offset: 0x8003358C

		/* begin block 1.1 */
			// Start line: 804
			// Start offset: 0x8003358C
			// Variables:
		// 		struct tTournamentManager *this; // $a0

			/* begin block 1.1.1 */
				// Start line: 804
				// Start offset: 0x8003358C
			/* end block 1.1.1 */
			// End offset: 0x8003358C
			// End Line: 804
		/* end block 1.1 */
		// End offset: 0x8003358C
		// End Line: 804
	/* end block 1 */
	// End offset: 0x8003358C
	// End Line: 804

/* WARNING: Control flow encountered bad instruction data */

short GetNumCompetitors__18tTournamentManager(tTournamentManager *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ UpdateCarLineup__18tTournamentManager(struct tTournamentManager *this /*$s0*/)
 // line 812, offset 0x800335d8
	/* begin block 1 */
		// Start line: 813
		// Start offset: 0x800335D8
		// Variables:
	// 		short i; // $a1
	// 		short k; // $a2
	/* end block 1 */
	// End offset: 0x80033678
	// End Line: 835

/* WARNING: Control flow encountered bad instruction data */

void UpdateCarLineup__18tTournamentManager(tTournamentManager *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// long /*$ra*/ GetTrackFinishPrize__18tTournamentManagers(struct tTournamentManager *this /*$s2*/, short position /*$s1*/)
 // line 844, offset 0x80033688
	/* begin block 1 */
		// Start line: 845
		// Start offset: 0x80033688
		// Variables:
	// 		struct tTourneyInfo *currentTourney; // $s3
	// 		long result; // $s0
	// 		struct tCarInfo carInfo; // stack offset -400
	// 		long carPrice; // $a1
	// 		int openClassAdjust[7][6]; // stack offset -192

		/* begin block 1.1 */
			// Start line: 851
			// Start offset: 0x800336E8

			/* begin block 1.1.1 */
				// Start line: 863
				// Start offset: 0x80033708

				/* begin block 1.1.1.1 */
					// Start line: 863
					// Start offset: 0x80033708
					// Variables:
				// 		struct tTournamentManager *this; // $s2

					/* begin block 1.1.1.1.1 */
						// Start line: 863
						// Start offset: 0x80033708
					/* end block 1.1.1.1.1 */
					// End offset: 0x80033708
					// End Line: 863
				/* end block 1.1.1.1 */
				// End offset: 0x80033708
				// End Line: 863
			/* end block 1.1.1 */
			// End offset: 0x80033840
			// End Line: 889
		/* end block 1.1 */
		// End offset: 0x80033840
		// End Line: 889
	/* end block 1 */
	// End offset: 0x80033840
	// End Line: 891

/* WARNING: Control flow encountered bad instruction data */

long GetTrackFinishPrize__18tTournamentManagers(tTournamentManager *this,short position)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// long /*$ra*/ GetTournamentFinishPrize__18tTournamentManagers(struct tTournamentManager *this /*$a2*/, short position /*$a1*/)
 // line 897, offset 0x80033860
	/* begin block 1 */
		// Start line: 898
		// Start offset: 0x80033860

		/* begin block 1.1 */
			// Start line: 898
			// Start offset: 0x80033860

			/* begin block 1.1.1 */
				// Start line: 901
				// Start offset: 0x80033870

				/* begin block 1.1.1.1 */
					// Start line: 901
					// Start offset: 0x80033870
					// Variables:
				// 		struct tTournamentManager *this; // $a2

					/* begin block 1.1.1.1.1 */
						// Start line: 901
						// Start offset: 0x80033870
					/* end block 1.1.1.1.1 */
					// End offset: 0x80033870
					// End Line: 901
				/* end block 1.1.1.1 */
				// End offset: 0x80033870
				// End Line: 901
			/* end block 1.1.1 */
			// End offset: 0x80033878
			// End Line: 906
		/* end block 1.1 */
		// End offset: 0x80033878
		// End Line: 906
	/* end block 1 */
	// End offset: 0x800338CC
	// End Line: 906

/* WARNING: Control flow encountered bad instruction data */

long GetTournamentFinishPrize__18tTournamentManagers(tTournamentManager *this,short position)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ GetAwardInformation__18tTournamentManagerR17tAwardInformation(struct tTournamentManager *this /*$a0*/, struct tAwardInformation *info /*$a1*/)
 // line 913, offset 0x800338d4
	/* begin block 1 */
		// Start line: 914
		// Start offset: 0x800338D4
	/* end block 1 */
	// End offset: 0x80033908
	// End Line: 915

/* WARNING: Control flow encountered bad instruction data */

void GetAwardInformation__18tTournamentManagerR17tAwardInformation
               (tTournamentManager *this,tAwardInformation *info)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ UpdateAwardInformation__18tTournamentManager(struct tTournamentManager *this /*$s1*/)
 // line 920, offset 0x80033914
	/* begin block 1 */
		// Start line: 921
		// Start offset: 0x80033914
		// Variables:
	// 		long bonus; // stack offset -20
	// 		long bill; // stack offset -24
	/* end block 1 */
	// End offset: 0x80033A78
	// End Line: 950

/* WARNING: Control flow encountered bad instruction data */

void UpdateAwardInformation__18tTournamentManager(tTournamentManager *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// short /*$ra*/ TournPointTotal__18tTournamentManagerPs(struct tTournamentManager *this /*$a0*/, short *p /*$a1*/)
 // line 957, offset 0x80033a8c
	/* begin block 1 */
		// Start line: 958
		// Start offset: 0x80033A8C
	/* end block 1 */
	// End offset: 0x80033A8C
	// End Line: 959

/* WARNING: Control flow encountered bad instruction data */

short TournPointTotal__18tTournamentManagerPs(tTournamentManager *this,short *p)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// short /*$ra*/ PlayerRanking__18tTournamentManagers(struct tTournamentManager *this /*$s1*/, short pos /*$a1*/)
 // line 965, offset 0x80033aa8
	/* begin block 1 */
		// Start line: 966
		// Start offset: 0x80033AA8
		// Variables:
	// 		short i; // $a0
	/* end block 1 */
	// End offset: 0x80033B24
	// End Line: 974

/* WARNING: Control flow encountered bad instruction data */

short PlayerRanking__18tTournamentManagers(tTournamentManager *this,short pos)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ CalcTierFinishPrize__18tTournamentManager(struct tTournamentManager *this /*$a0*/)
 // line 979, offset 0x80033b38
	/* begin block 1 */
		// Start line: 980
		// Start offset: 0x80033B38
	/* end block 1 */
	// End offset: 0x80033B38
	// End Line: 981

/* WARNING: Control flow encountered bad instruction data */

void CalcTierFinishPrize__18tTournamentManager(tTournamentManager *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ GetTrophyName__18tTournamentManagerP12tTourneyInfo11tTrophySizePci(struct tTournamentManager *this /*$a0*/, struct tTourneyInfo *tourn /*$a1*/, enum tTrophySize size /*$a2*/, char *buffer /*$a0*/, int place /*stack 16*/)
 // line 1040, offset 0x80033b64
	/* begin block 1 */
		// Start line: 1041
		// Start offset: 0x80033B64
		// Variables:
	// 		int showplace; // $v0
	// 		char trophySizeLetter[3]; // stack offset -24
	// 		char trophyPlacementLetter[4]; // stack offset -16

		/* begin block 1.1 */
			// Start line: 1041
			// Start offset: 0x80033B64

			/* begin block 1.1.1 */
				// Start line: 1041
				// Start offset: 0x80033B64
			/* end block 1.1.1 */
			// End offset: 0x80033B64
			// End Line: 1041
		/* end block 1.1 */
		// End offset: 0x80033B64
		// End Line: 1041
	/* end block 1 */
	// End offset: 0x80033BF0
	// End Line: 1057

/* WARNING: Control flow encountered bad instruction data */

void GetTrophyName__18tTournamentManagerP12tTourneyInfo11tTrophySizePci
               (tTournamentManager *this,tTourneyInfo *tourn,tTrophySize size,char *buffer,int place
               )

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void * /*$ra*/ ValidCar__18tTournamentManagerR8tCarInfo(struct tTournamentManager *this /*$s2*/, struct tCarInfo *carInfo /*$s3*/)
 // line 1063, offset 0x80033c24
	/* begin block 1 */
		// Start line: 1064
		// Start offset: 0x80033C24
		// Variables:
	// 		struct tTourneyInfo *tourney; // $s1
	// 		void * result; // $s0

		/* begin block 1.1 */
			// Start line: 1064
			// Start offset: 0x80033C24
			// Variables:
		// 		struct tTournamentManager *this; // $s2

			/* begin block 1.1.1 */
				// Start line: 1064
				// Start offset: 0x80033C24
			/* end block 1.1.1 */
			// End offset: 0x80033C24
			// End Line: 1064
		/* end block 1.1 */
		// End offset: 0x80033C24
		// End Line: 1064
	/* end block 1 */
	// End offset: 0x80033D7C
	// End Line: 1103

/* WARNING: Control flow encountered bad instruction data */

void * ValidCar__18tTournamentManagerR8tCarInfo(tTournamentManager *this,tCarInfo *carInfo)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// struct tListIteratorTournament * /*$ra*/ __23tListIteratorTournamentPcP18tTournamentManager(struct tListIteratorTournament *this /*$s0*/, char *valPtr /*$v0*/, struct tTournamentManager *tournManager /*$s1*/)
 // line 1109, offset 0x80033d9c
	/* begin block 1 */
		// Start line: 1110
		// Start offset: 0x80033D9C
	/* end block 1 */
	// End offset: 0x80033D9C
	// End Line: 1110

/* WARNING: Control flow encountered bad instruction data */

tListIteratorTournament *
__23tListIteratorTournamentPcP18tTournamentManager
          (tListIteratorTournament *this,char *valPtr,tTournamentManager *tournManager)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ _._23tListIteratorTournament(struct tListIteratorTournament *this /*$a0*/, int __in_chrg /*$a1*/)
 // line 1115, offset 0x80033dec
	/* begin block 1 */
		// Start line: 1116
		// Start offset: 0x80033DEC
	/* end block 1 */
	// End offset: 0x80033DEC
	// End Line: 1116

/* WARNING: Control flow encountered bad instruction data */

void ___23tListIteratorTournament(tListIteratorTournament *this,int __in_chrg)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// char /*$ra*/ Value__23tListIteratorTournament7tPlayer(struct tListIteratorTournament *this /*$a0*/)
 // line 1119, offset 0x80033e14
	/* begin block 1 */
		// Start line: 1120
		// Start offset: 0x80033E14
	/* end block 1 */
	// End offset: 0x80033E14
	// End Line: 1121

/* WARNING: Control flow encountered bad instruction data */

char Value__23tListIteratorTournament7tPlayer(tListIteratorTournament *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// short /*$ra*/ TextValue__23tListIteratorTournament7tPlayer(struct tListIteratorTournament *this /*$a0*/)
 // line 1124, offset 0x80033e28
	/* begin block 1 */
		// Start line: 1125
		// Start offset: 0x80033E28
		// Variables:
	// 		short tournIndex; // $v0
	/* end block 1 */
	// End offset: 0x80033E28
	// End Line: 1129

/* WARNING: Control flow encountered bad instruction data */

short TextValue__23tListIteratorTournament7tPlayer(tListIteratorTournament *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Increment__23tListIteratorTournament7tPlayer(struct tListIteratorTournament *this /*$s0*/)
 // line 1134, offset 0x80033e80
	/* begin block 1 */
		// Start line: 1135
		// Start offset: 0x80033E80
		// Variables:
	// 		struct tTierInfo *tier; // $s1
	/* end block 1 */
	// End offset: 0x80033F0C
	// End Line: 1145

/* WARNING: Control flow encountered bad instruction data */

void Increment__23tListIteratorTournament7tPlayer(tListIteratorTournament *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Decrement__23tListIteratorTournament7tPlayer(struct tListIteratorTournament *this /*$s0*/)
 // line 1148, offset 0x80033f20
	/* begin block 1 */
		// Start line: 1149
		// Start offset: 0x80033F20
		// Variables:
	// 		struct tTierInfo *tier; // $s1
	/* end block 1 */
	// End offset: 0x80033F9C
	// End Line: 1159

/* WARNING: Control flow encountered bad instruction data */

void Decrement__23tListIteratorTournament7tPlayer(tListIteratorTournament *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void * /*$ra*/ ValidTournament__23tListIteratorTournamentc(struct tListIteratorTournament *this /*$a0*/, char tourn /*$a1*/)
 // line 1162, offset 0x80033fb0
	/* begin block 1 */
		// Start line: 1163
		// Start offset: 0x80033FB0
		// Variables:
	// 		struct tTierInfo *currentTier; // $v0
	// 		struct tTourneyInfo *currentTourn; // $a0
	// 		void * result; // $v1
	/* end block 1 */
	// End offset: 0x80034054
	// End Line: 1185

/* WARNING: Control flow encountered bad instruction data */

void * ValidTournament__23tListIteratorTournamentc(tListIteratorTournament *this,char tourn)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}




