#include "NFS4.H"
#include "FRONT.H"

// decompiled code
// original method signature: 
// struct tAllScreens * /*$ra*/ __11tAllScreens(struct tAllScreens *this /*$s1*/)
 // line 226, offset 0x8002baf4
	/* begin block 1 */
		// Start line: 227
		// Start offset: 0x8002BAF4
		// Variables:
	// 		struct tScreenMain *this; // $s1
	/* end block 1 */
	// End offset: 0x8002BAF4
	// End Line: 227

	/* begin block 2 */
		// Start line: 227
		// Start offset: 0x8002BAF4
		// Variables:
	// 		struct tScreenCarSelectDuel *this; // $s0
	/* end block 2 */
	// End offset: 0x8002BAF4
	// End Line: 227

	/* begin block 3 */
		// Start line: 227
		// Start offset: 0x8002BAF4
		// Variables:
	// 		struct tScreenCarSelectTwoPlayer *this; // $s2

		/* begin block 3.1 */
			// Start line: 227
			// Start offset: 0x8002BAF4
			// Variables:
		// 		struct tDialogBackUpOnly *this; // $s0

			/* begin block 3.1.1 */
				// Start line: 227
				// Start offset: 0x8002BAF4
				// Variables:
			// 		struct tDialogMessageString *this; // $s0

				/* begin block 3.1.1.1 */
					// Start line: 227
					// Start offset: 0x8002BAF4
					// Variables:
				// 		struct tDialogBase *this; // $s0

					/* begin block 3.1.1.1.1 */
						// Start line: 227
						// Start offset: 0x8002BAF4
					/* end block 3.1.1.1.1 */
					// End offset: 0x8002BAF4
					// End Line: 227
				/* end block 3.1.1.1 */
				// End offset: 0x8002BAF4
				// End Line: 227

				/* begin block 3.1.1.2 */
					// Start line: 227
					// Start offset: 0x8002BAF4
				/* end block 3.1.1.2 */
				// End offset: 0x8002BAF4
				// End Line: 227
			/* end block 3.1.1 */
			// End offset: 0x8002BAF4
			// End Line: 227
		/* end block 3.1 */
		// End offset: 0x8002BAF4
		// End Line: 227
	/* end block 3 */
	// End offset: 0x8002BAF4
	// End Line: 227

	/* begin block 4 */
		// Start line: 227
		// Start offset: 0x8002BAF4
		// Variables:
	// 		struct tScreenCarSelectTwoPlayer *this; // $s2

		/* begin block 4.1 */
			// Start line: 227
			// Start offset: 0x8002BAF4
			// Variables:
		// 		struct tDialogBackUpOnly *this; // $s0

			/* begin block 4.1.1 */
				// Start line: 227
				// Start offset: 0x8002BAF4
				// Variables:
			// 		struct tDialogMessageString *this; // $s0

				/* begin block 4.1.1.1 */
					// Start line: 227
					// Start offset: 0x8002BAF4
					// Variables:
				// 		struct tDialogBase *this; // $s0

					/* begin block 4.1.1.1.1 */
						// Start line: 227
						// Start offset: 0x8002BAF4
					/* end block 4.1.1.1.1 */
					// End offset: 0x8002BAF4
					// End Line: 227
				/* end block 4.1.1.1 */
				// End offset: 0x8002BAF4
				// End Line: 227

				/* begin block 4.1.1.2 */
					// Start line: 227
					// Start offset: 0x8002BAF4
				/* end block 4.1.1.2 */
				// End offset: 0x8002BAF4
				// End Line: 227
			/* end block 4.1.1 */
			// End offset: 0x8002BAF4
			// End Line: 227
		/* end block 4.1 */
		// End offset: 0x8002BAF4
		// End Line: 227
	/* end block 4 */
	// End offset: 0x8002BAF4
	// End Line: 227

	/* begin block 5 */
		// Start line: 227
		// Start offset: 0x8002BAF4
		// Variables:
	// 		struct tScreenPinkSlipsCarSelect *this; // $s5

		/* begin block 5.1 */
			// Start line: 227
			// Start offset: 0x8002BAF4
			// Variables:
		// 		struct tScreenCarSelectTwoPlayer *this; // $s5

			/* begin block 5.1.1 */
				// Start line: 227
				// Start offset: 0x8002BAF4
				// Variables:
			// 		struct tDialogBackUpOnly *this; // $s0

				/* begin block 5.1.1.1 */
					// Start line: 227
					// Start offset: 0x8002BAF4
					// Variables:
				// 		struct tDialogMessageString *this; // $s0

					/* begin block 5.1.1.1.1 */
						// Start line: 227
						// Start offset: 0x8002BAF4
						// Variables:
					// 		struct tDialogBase *this; // $s0

						/* begin block 5.1.1.1.1.1 */
							// Start line: 227
							// Start offset: 0x8002BAF4
						/* end block 5.1.1.1.1.1 */
						// End offset: 0x8002BAF4
						// End Line: 227
					/* end block 5.1.1.1.1 */
					// End offset: 0x8002BAF4
					// End Line: 227

					/* begin block 5.1.1.1.2 */
						// Start line: 227
						// Start offset: 0x8002BAF4
					/* end block 5.1.1.1.2 */
					// End offset: 0x8002BAF4
					// End Line: 227
				/* end block 5.1.1.1 */
				// End offset: 0x8002BAF4
				// End Line: 227
			/* end block 5.1.1 */
			// End offset: 0x8002BAF4
			// End Line: 227
		/* end block 5.1 */
		// End offset: 0x8002BAF4
		// End Line: 227
	/* end block 5 */
	// End offset: 0x8002BAF4
	// End Line: 227

	/* begin block 6 */
		// Start line: 227
		// Start offset: 0x8002BAF4
		// Variables:
	// 		struct tScreenPinkSlipsCarSelect *this; // $s6

		/* begin block 6.1 */
			// Start line: 227
			// Start offset: 0x8002BAF4
			// Variables:
		// 		struct tScreenCarSelectTwoPlayer *this; // $s6

			/* begin block 6.1.1 */
				// Start line: 227
				// Start offset: 0x8002BAF4
				// Variables:
			// 		struct tDialogBackUpOnly *this; // $s0

				/* begin block 6.1.1.1 */
					// Start line: 227
					// Start offset: 0x8002BAF4
					// Variables:
				// 		struct tDialogMessageString *this; // $s0

					/* begin block 6.1.1.1.1 */
						// Start line: 227
						// Start offset: 0x8002BAF4
						// Variables:
					// 		struct tDialogBase *this; // $s0

						/* begin block 6.1.1.1.1.1 */
							// Start line: 227
							// Start offset: 0x8002BAF4
						/* end block 6.1.1.1.1.1 */
						// End offset: 0x8002BAF4
						// End Line: 227
					/* end block 6.1.1.1.1 */
					// End offset: 0x8002BAF4
					// End Line: 227

					/* begin block 6.1.1.1.2 */
						// Start line: 227
						// Start offset: 0x8002BAF4
					/* end block 6.1.1.1.2 */
					// End offset: 0x8002BAF4
					// End Line: 227
				/* end block 6.1.1.1 */
				// End offset: 0x8002BAF4
				// End Line: 227
			/* end block 6.1.1 */
			// End offset: 0x8002BAF4
			// End Line: 227
		/* end block 6.1 */
		// End offset: 0x8002BAF4
		// End Line: 227
	/* end block 6 */
	// End offset: 0x8002BAF4
	// End Line: 227

	/* begin block 7 */
		// Start line: 227
		// Start offset: 0x8002BAF4
		// Variables:
	// 		struct tScreenTrackRecords *this; // $s5
	/* end block 7 */
	// End offset: 0x8002BAF4
	// End Line: 227

	/* begin block 8 */
		// Start line: 227
		// Start offset: 0x8002BAF4
		// Variables:
	// 		struct tScreenTrackInfo *this; // $s2
	/* end block 8 */
	// End offset: 0x8002BAF4
	// End Line: 227

	/* begin block 9 */
		// Start line: 227
		// Start offset: 0x8002BAF4
		// Variables:
	// 		struct tScreenTrackSelect *this; // $s0
	/* end block 9 */
	// End offset: 0x8002BAF4
	// End Line: 227

	/* begin block 10 */
		// Start line: 227
		// Start offset: 0x8002BAF4
		// Variables:
	// 		struct tScreenTournamentTrophy *this; // $s0

		/* begin block 10.1 */
			// Start line: 227
			// Start offset: 0x8002BAF4
			// Variables:
		// 		struct tScreenCongrats *this; // $s0
		/* end block 10.1 */
		// End offset: 0x8002BAF4
		// End Line: 227
	/* end block 10 */
	// End offset: 0x8002BAF4
	// End Line: 227

	/* begin block 11 */
		// Start line: 227
		// Start offset: 0x8002BAF4
		// Variables:
	// 		struct tScreenTrophyInfo *this; // $s0
	/* end block 11 */
	// End offset: 0x8002BAF4
	// End Line: 227

	/* begin block 12 */
		// Start line: 227
		// Start offset: 0x8002BAF4
		// Variables:
	// 		struct tScreenDisplay *this; // $s0
	/* end block 12 */
	// End offset: 0x8002BAF4
	// End Line: 227

	/* begin block 13 */
		// Start line: 227
		// Start offset: 0x8002BAF4
		// Variables:
	// 		struct tScreenUserName *this; // $s0
	/* end block 13 */
	// End offset: 0x8002BAF4
	// End Line: 227

	/* begin block 14 */
		// Start line: 227
		// Start offset: 0x8002BAF4
		// Variables:
	// 		struct tScreenPinkSlipCongrats *this; // $s2

		/* begin block 14.1 */
			// Start line: 227
			// Start offset: 0x8002BAF4
			// Variables:
		// 		struct tScreenCongrats *this; // $s2
		/* end block 14.1 */
		// End offset: 0x8002BAF4
		// End Line: 227
	/* end block 14 */
	// End offset: 0x8002BAF4
	// End Line: 227

	/* begin block 15 */
		// Start line: 227
		// Start offset: 0x8002BAF4
		// Variables:
	// 		struct tScreenPinkSlipStandings *this; // $s0

		/* begin block 15.1 */
			// Start line: 227
			// Start offset: 0x8002BAF4
			// Variables:
		// 		struct tScreenTournamentStandings3item *this; // $s0
		/* end block 15.1 */
		// End offset: 0x8002BAF4
		// End Line: 227
	/* end block 15 */
	// End offset: 0x8002BAF4
	// End Line: 227

	/* begin block 16 */
		// Start line: 227
		// Start offset: 0x8002BAF4
		// Variables:
	// 		struct tScreenTournamentStandings3item *this; // $s3
	/* end block 16 */
	// End offset: 0x8002BAF4
	// End Line: 227

	/* begin block 17 */
		// Start line: 227
		// Start offset: 0x8002BAF4
		// Variables:
	// 		struct tScreenPinkSlips *this; // $s2
	/* end block 17 */
	// End offset: 0x8002BAF4
	// End Line: 227

	/* begin block 18 */
		// Start line: 227
		// Start offset: 0x8002BAF4
		// Variables:
	// 		struct tScreenBeTheCopCongrats *this; // $s3

		/* begin block 18.1 */
			// Start line: 227
			// Start offset: 0x8002BAF4
			// Variables:
		// 		struct tScreenCongrats *this; // $s3
		/* end block 18.1 */
		// End offset: 0x8002BAF4
		// End Line: 227
	/* end block 18 */
	// End offset: 0x8002BAF4
	// End Line: 227

	/* begin block 19 */
		// Start line: 227
		// Start offset: 0x8002BAF4
		// Variables:
	// 		struct tScreenTournamentCongrats *this; // $s0

		/* begin block 19.1 */
			// Start line: 227
			// Start offset: 0x8002BAF4
			// Variables:
		// 		struct tScreenCongrats *this; // $s0
		/* end block 19.1 */
		// End offset: 0x8002BAF4
		// End Line: 227
	/* end block 19 */
	// End offset: 0x8002BAF4
	// End Line: 227

tAllScreens * __11tAllScreens(tAllScreens *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// autogenerated function stub: 
// void /*$ra*/ _._11tAllScreens(struct tAllScreens *this /*$s2*/, int __in_chrg /*$s1*/)
void _._11tAllScreens _._11tAllScreens(tAllScreens *this /*$s2*/this, int __in_chrg /*$s1*/ __in_chrg)
{ // line 226, offset 0x8002bf0c
	/* begin block 1 */
		// Start line: 227
		// Start offset: 0x8002BF0C

		/* begin block 1.1 */
			// Start line: 227
			// Start offset: 0x8002BF0C
		/* end block 1.1 */
		// End offset: 0x8002BF0C
		// End Line: 227
	/* end block 1 */
	// End offset: 0x8002BF0C
	// End Line: 227

	/* begin block 2 */
		// Start line: 227
		// Start offset: 0x8002BF0C

		/* begin block 2.1 */
			// Start line: 227
			// Start offset: 0x8002BF0C
		/* end block 2.1 */
		// End offset: 0x8002BF0C
		// End Line: 227
	/* end block 2 */
	// End offset: 0x8002BF0C
	// End Line: 227

	/* begin block 3 */
		// Start line: 227
		// Start offset: 0x8002BF0C
	/* end block 3 */
	// End offset: 0x8002BF0C
	// End Line: 227

	/* begin block 4 */
		// Start line: 227
		// Start offset: 0x8002BF0C

		/* begin block 4.1 */
			// Start line: 227
			// Start offset: 0x8002BF0C
		/* end block 4.1 */
		// End offset: 0x8002BF0C
		// End Line: 227
	/* end block 4 */
	// End offset: 0x8002BF0C
	// End Line: 227

	/* begin block 5 */
		// Start line: 227
		// Start offset: 0x8002BF0C

		/* begin block 5.1 */
			// Start line: 227
			// Start offset: 0x8002BF0C

			/* begin block 5.1.1 */
				// Start line: 227
				// Start offset: 0x8002BF0C
			/* end block 5.1.1 */
			// End offset: 0x8002BF0C
			// End Line: 227
		/* end block 5.1 */
		// End offset: 0x8002BF0C
		// End Line: 227
	/* end block 5 */
	// End offset: 0x8002BF0C
	// End Line: 227

	/* begin block 6 */
		// Start line: 227
		// Start offset: 0x8002BF0C

		/* begin block 6.1 */
			// Start line: 227
			// Start offset: 0x8002BF0C
		/* end block 6.1 */
		// End offset: 0x8002BF0C
		// End Line: 227
	/* end block 6 */
	// End offset: 0x8002BF0C
	// End Line: 227

	/* begin block 7 */
		// Start line: 227
		// Start offset: 0x8002BF0C
	/* end block 7 */
	// End offset: 0x8002BF0C
	// End Line: 227

	/* begin block 8 */
		// Start line: 227
		// Start offset: 0x8002BF0C
	/* end block 8 */
	// End offset: 0x8002BF0C
	// End Line: 227

	/* begin block 9 */
		// Start line: 227
		// Start offset: 0x8002BF0C
	/* end block 9 */
	// End offset: 0x8002BF0C
	// End Line: 227

	/* begin block 10 */
		// Start line: 227
		// Start offset: 0x8002BF0C
	/* end block 10 */
	// End offset: 0x8002BF0C
	// End Line: 227

	/* begin block 11 */
		// Start line: 227
		// Start offset: 0x8002BF0C
		// Variables:
			struct tScreenControllerConfig *this; // $s0

		/* begin block 11.1 */
			// Start line: 227
			// Start offset: 0x8002BF0C

			/* begin block 11.1.1 */
				// Start line: 227
				// Start offset: 0x8002BF0C

				/* begin block 11.1.1.1 */
					// Start line: 227
					// Start offset: 0x8002BF0C

					/* begin block 11.1.1.1.1 */
						// Start line: 227
						// Start offset: 0x8002BF0C
					/* end block 11.1.1.1.1 */
					// End offset: 0x8002BF0C
					// End Line: 227
				/* end block 11.1.1.1 */
				// End offset: 0x8002BF0C
				// End Line: 227
			/* end block 11.1.1 */
			// End offset: 0x8002BF0C
			// End Line: 227
		/* end block 11.1 */
		// End offset: 0x8002BF0C
		// End Line: 227
	/* end block 11 */
	// End offset: 0x8002BF0C
	// End Line: 227

	/* begin block 12 */
		// Start line: 227
		// Start offset: 0x8002BF0C
	/* end block 12 */
	// End offset: 0x8002BF0C
	// End Line: 227

	/* begin block 13 */
		// Start line: 227
		// Start offset: 0x8002BF0C

		/* begin block 13.1 */
			// Start line: 227
			// Start offset: 0x8002BF0C
		/* end block 13.1 */
		// End offset: 0x8002BF0C
		// End Line: 227
	/* end block 13 */
	// End offset: 0x8002BF0C
	// End Line: 227

	/* begin block 14 */
		// Start line: 227
		// Start offset: 0x8002BF0C
	/* end block 14 */
	// End offset: 0x8002BF0C
	// End Line: 227

	/* begin block 15 */
		// Start line: 227
		// Start offset: 0x8002BF0C
	/* end block 15 */
	// End offset: 0x8002BF0C
	// End Line: 227

	/* begin block 16 */
		// Start line: 227
		// Start offset: 0x8002BF0C
	/* end block 16 */
	// End offset: 0x8002BF0C
	// End Line: 227

	/* begin block 17 */
		// Start line: 227
		// Start offset: 0x8002BF0C
	/* end block 17 */
	// End offset: 0x8002BF0C
	// End Line: 227

	/* begin block 18 */
		// Start line: 227
		// Start offset: 0x8002BF0C
		// Variables:
			struct tScreenPinkSlipsCarSelect *this; // $s0

		/* begin block 18.1 */
			// Start line: 227
			// Start offset: 0x8002BF0C
			// Variables:
				struct tScreenCarSelectTwoPlayer *this; // $s0

			/* begin block 18.1.1 */
				// Start line: 227
				// Start offset: 0x8002BF0C

				/* begin block 18.1.1.1 */
					// Start line: 227
					// Start offset: 0x8002BF0C

					/* begin block 18.1.1.1.1 */
						// Start line: 227
						// Start offset: 0x8002BF0C
					/* end block 18.1.1.1.1 */
					// End offset: 0x8002BF0C
					// End Line: 227
				/* end block 18.1.1.1 */
				// End offset: 0x8002BF0C
				// End Line: 227
			/* end block 18.1.1 */
			// End offset: 0x8002BF0C
			// End Line: 227
		/* end block 18.1 */
		// End offset: 0x8002BF0C
		// End Line: 227
	/* end block 18 */
	// End offset: 0x8002BF0C
	// End Line: 227

	/* begin block 19 */
		// Start line: 227
		// Start offset: 0x8002BF0C
		// Variables:
			struct tScreenPinkSlipsCarSelect *this; // $s0

		/* begin block 19.1 */
			// Start line: 227
			// Start offset: 0x8002BF0C
			// Variables:
				struct tScreenCarSelectTwoPlayer *this; // $s0

			/* begin block 19.1.1 */
				// Start line: 227
				// Start offset: 0x8002BF0C

				/* begin block 19.1.1.1 */
					// Start line: 227
					// Start offset: 0x8002BF0C

					/* begin block 19.1.1.1.1 */
						// Start line: 227
						// Start offset: 0x8002BF0C
					/* end block 19.1.1.1.1 */
					// End offset: 0x8002BF0C
					// End Line: 227
				/* end block 19.1.1.1 */
				// End offset: 0x8002BF0C
				// End Line: 227
			/* end block 19.1.1 */
			// End offset: 0x8002BF0C
			// End Line: 227
		/* end block 19.1 */
		// End offset: 0x8002BF0C
		// End Line: 227
	/* end block 19 */
	// End offset: 0x8002BF0C
	// End Line: 227

	/* begin block 20 */
		// Start line: 227
		// Start offset: 0x8002BF0C
		// Variables:
			struct tScreenCarSelectTwoPlayer *this; // $s0

		/* begin block 20.1 */
			// Start line: 227
			// Start offset: 0x8002BF0C

			/* begin block 20.1.1 */
				// Start line: 227
				// Start offset: 0x8002BF0C

				/* begin block 20.1.1.1 */
					// Start line: 227
					// Start offset: 0x8002BF0C
				/* end block 20.1.1.1 */
				// End offset: 0x8002BF0C
				// End Line: 227
			/* end block 20.1.1 */
			// End offset: 0x8002BF0C
			// End Line: 227
		/* end block 20.1 */
		// End offset: 0x8002BF0C
		// End Line: 227
	/* end block 20 */
	// End offset: 0x8002BF0C
	// End Line: 227

	/* begin block 21 */
		// Start line: 227
		// Start offset: 0x8002BF0C
		// Variables:
			struct tScreenCarSelectTwoPlayer *this; // $s0

		/* begin block 21.1 */
			// Start line: 227
			// Start offset: 0x8002BF0C

			/* begin block 21.1.1 */
				// Start line: 227
				// Start offset: 0x8002BF0C

				/* begin block 21.1.1.1 */
					// Start line: 227
					// Start offset: 0x8002BF0C
				/* end block 21.1.1.1 */
				// End offset: 0x8002BF0C
				// End Line: 227
			/* end block 21.1.1 */
			// End offset: 0x8002BF0C
			// End Line: 227
		/* end block 21.1 */
		// End offset: 0x8002BF0C
		// End Line: 227
	/* end block 21 */
	// End offset: 0x8002BF0C
	// End Line: 227

	/* begin block 22 */
		// Start line: 227
		// Start offset: 0x8002BF0C
	/* end block 22 */
	// End offset: 0x8002BF0C
	// End Line: 227

	/* begin block 23 */
		// Start line: 227
		// Start offset: 0x8002BF0C
		// Variables:
			struct tScreenMain *this; // $s2
	/* end block 23 */
	// End offset: 0x8002BF0C
	// End Line: 227

}


// decompiled code
// original method signature: 
// void /*$ra*/ Front_ConstructAll__Fv()
 // line 231, offset 0x80026e58
	/* begin block 1 */
		// Start line: 232
		// Start offset: 0x80026E58
	/* end block 1 */
	// End offset: 0x80026E58
	// End Line: 232

void Front_ConstructAll__Fv(void)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ Front_DeleteAll__Fv()
 // line 270, offset 0x80026fe8
	/* begin block 1 */
		// Start line: 271
		// Start offset: 0x80026FE8
	/* end block 1 */
	// End offset: 0x8002703C
	// End Line: 274

void Front_DeleteAll__Fv(void)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ Front_ResetSettingsForCar__Fii(int player /*$a0*/, int car /*$a1*/)
 // line 280, offset 0x8002704c
	/* begin block 1 */
		// Start line: 281
		// Start offset: 0x8002704C
	/* end block 1 */
	// End offset: 0x8002704C
	// End Line: 282

void Front_ResetSettingsForCar__Fii(int player,int car)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ Front_ResetSettingsMenu__Fi(int player /*$s1*/)
 // line 288, offset 0x8002709c
	/* begin block 1 */
		// Start line: 289
		// Start offset: 0x8002709C
		// Variables:
	// 		int i; // $s0
	/* end block 1 */
	// End offset: 0x800270D0
	// End Line: 295

void Front_ResetSettingsMenu__Fi(int player)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ Front_ResetPSXController__Fii(int player /*$s0*/, int config /*$s1*/)
 // line 299, offset 0x800270e4
	/* begin block 1 */
		// Start line: 300
		// Start offset: 0x800270E4
	/* end block 1 */
	// End offset: 0x800270E4
	// End Line: 300

void Front_ResetPSXController__Fii(int player,int config)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ Front_ResetPSXAnalogs__Fi(int player /*$a0*/)
 // line 318, offset 0x80027150
	/* begin block 1 */
		// Start line: 319
		// Start offset: 0x80027150
	/* end block 1 */
	// End offset: 0x80027150
	// End Line: 323

void Front_ResetPSXAnalogs__Fi(int player)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// int /*$ra*/ GetPSXPadValue__Fii(int value /*$s0*/, int player /*$s1*/)
 // line 333, offset 0x80027194
	/* begin block 1 */
		// Start line: 334
		// Start offset: 0x80027194
		// Variables:
	// 		int newControl; // $v0
	// 		int type; // $v1
	/* end block 1 */
	// End offset: 0x800274F8
	// End Line: 466

int GetPSXPadValue__Fii(int value,int player)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ SetPads__Fv()
 // line 474, offset 0x8002750c
	/* begin block 1 */
		// Start line: 475
		// Start offset: 0x8002750C
		// Variables:
	// 		int j; // $s5
	// 		int pad; // $s1

		/* begin block 1.1 */
			// Start line: 475
			// Start offset: 0x8002750C

			/* begin block 1.1.1 */
				// Start line: 477
				// Start offset: 0x80027548
				// Variables:
			// 		int LookingFor; // $s6
			// 		int starttick; // $s0

				/* begin block 1.1.1.1 */
					// Start line: 480
					// Start offset: 0x80027568

					/* begin block 1.1.1.1.1 */
						// Start line: 480
						// Start offset: 0x80027568
					/* end block 1.1.1.1.1 */
					// End offset: 0x8002756C
					// End Line: 480
				/* end block 1.1.1.1 */
				// End offset: 0x8002756C
				// End Line: 480

				/* begin block 1.1.1.2 */
					// Start line: 484
					// Start offset: 0x8002756C

					/* begin block 1.1.1.2.1 */
						// Start line: 484
						// Start offset: 0x8002756C

						/* begin block 1.1.1.2.1.1 */
							// Start line: 484
							// Start offset: 0x8002756C
						/* end block 1.1.1.2.1.1 */
						// End offset: 0x8002756C
						// End Line: 484
					/* end block 1.1.1.2.1 */
					// End offset: 0x8002756C
					// End Line: 484
				/* end block 1.1.1.2 */
				// End offset: 0x8002759C
				// End Line: 484

				/* begin block 1.1.1.3 */
					// Start line: 485
					// Start offset: 0x8002759C

					/* begin block 1.1.1.3.1 */
						// Start line: 486
						// Start offset: 0x800275B0
						// Variables:
					// 		int theanalogoffset; // $s4
					// 		unsigned int gotone; // $s3
					// 		int numoffsets; // $s2

						/* begin block 1.1.1.3.1.1 */
							// Start line: 487
							// Start offset: 0x800275B0
							// Variables:
						// 		int i; // $s0

							/* begin block 1.1.1.3.1.1.1 */
								// Start line: 491
								// Start offset: 0x800275CC
							/* end block 1.1.1.3.1.1.1 */
							// End offset: 0x800275F4
							// End Line: 498
						/* end block 1.1.1.3.1.1 */
						// End offset: 0x800275FC
						// End Line: 500
					/* end block 1.1.1.3.1 */
					// End offset: 0x8002760C
					// End Line: 502
				/* end block 1.1.1.3 */
				// End offset: 0x8002760C
				// End Line: 502
			/* end block 1.1.1 */
			// End offset: 0x8002760C
			// End Line: 502
		/* end block 1.1 */
		// End offset: 0x80027618
		// End Line: 504
	/* end block 1 */
	// End offset: 0x80027618
	// End Line: 504

void SetPads__Fv(void)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ InitFrontEndStructure__Fv()
 // line 507, offset 0x80027648
	/* begin block 1 */
		// Start line: 508
		// Start offset: 0x80027648
		// Variables:
	// 		int i; // $s3
	// 		int j; // $s0
	/* end block 1 */
	// End offset: 0x8002788C
	// End Line: 635

void InitFrontEndStructure__Fv(void)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// int /*$ra*/ LoadConfig__Fv()
 // line 810, offset 0x80027940
	/* begin block 1 */
		// Start line: 811
		// Start offset: 0x80027940
	/* end block 1 */
	// End offset: 0x80027940
	// End Line: 812

int LoadConfig__Fv(void)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ Front_InitialMemCardCheck__Fv()
 // line 819, offset 0x80027948
	/* begin block 1 */
		// Start line: 820
		// Start offset: 0x80027948
	/* end block 1 */
	// End offset: 0x80027948
	// End Line: 820

void Front_InitialMemCardCheck__Fv(void)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ Front_SecondaryMemCardCheck__Fv()
 // line 852, offset 0x80027994
	/* begin block 1 */
		// Start line: 853
		// Start offset: 0x80027994

		/* begin block 1.1 */
			// Start line: 853
			// Start offset: 0x80027994
			// Variables:
		// 		int j; // $s1

			/* begin block 1.1.1 */
				// Start line: 858
				// Start offset: 0x800279C8
				// Variables:
			// 		int i; // $s0
			/* end block 1.1.1 */
			// End offset: 0x80027A18
			// End Line: 866
		/* end block 1.1 */
		// End offset: 0x80027A24
		// End Line: 867
	/* end block 1 */
	// End offset: 0x80027A24
	// End Line: 870

void Front_SecondaryMemCardCheck__Fv(void)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ Front_InitGraphics__Fv()
 // line 880, offset 0x80027a5c
	/* begin block 1 */
		// Start line: 881
		// Start offset: 0x80027A5C
		// Variables:
	// 		char buffer[40]; // stack offset -48
	/* end block 1 */
	// End offset: 0x80027AB4
	// End Line: 913

void Front_InitGraphics__Fv(void)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ Front_InitGraphicsAndDisplayLoading__Fv()
 // line 919, offset 0x80027ad4
	/* begin block 1 */
		// Start line: 920
		// Start offset: 0x80027AD4
	/* end block 1 */
	// End offset: 0x80027AD4
	// End Line: 920

void Front_InitGraphicsAndDisplayLoading__Fv(void)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// int /*$ra*/ Front_Menu__F21tFront_ProcessingType(enum tFront_ProcessingType role /*$s1*/)
 // line 934, offset 0x80027af4
	/* begin block 1 */
		// Start line: 935
		// Start offset: 0x80027AF4
		// Variables:
	// 		int result; // $s3

		/* begin block 1.1 */
			// Start line: 935
			// Start offset: 0x80027AF4

			/* begin block 1.1.1 */
				// Start line: 935
				// Start offset: 0x80027AF4
			/* end block 1.1.1 */
			// End offset: 0x80027AF4
			// End Line: 935
		/* end block 1.1 */
		// End offset: 0x80027AF4
		// End Line: 935

		/* begin block 1.2 */
			// Start line: 935
			// Start offset: 0x80027AF4

			/* begin block 1.2.1 */
				// Start line: 963
				// Start offset: 0x80027B7C

				/* begin block 1.2.1.1 */
					// Start line: 963
					// Start offset: 0x80027B7C
				/* end block 1.2.1.1 */
				// End offset: 0x80027B7C
				// End Line: 963
			/* end block 1.2.1 */
			// End offset: 0x80027B7C
			// End Line: 963

			/* begin block 1.2.2 */
				// Start line: 964
				// Start offset: 0x80027B90

				/* begin block 1.2.2.1 */
					// Start line: 965
					// Start offset: 0x80027B90
					// Variables:
				// 		long extraMoney; // $v0

					/* begin block 1.2.2.1.1 */
						// Start line: 965
						// Start offset: 0x80027B90
					/* end block 1.2.2.1.1 */
					// End offset: 0x80027BB0
					// End Line: 965
				/* end block 1.2.2.1 */
				// End offset: 0x80027BB0
				// End Line: 965
			/* end block 1.2.2 */
			// End offset: 0x80027BB0
			// End Line: 965
		/* end block 1.2 */
		// End offset: 0x80027BB0
		// End Line: 965

		/* begin block 1.3 */
			// Start line: 968
			// Start offset: 0x80027BB0

			/* begin block 1.3.1 */
				// Start line: 969
				// Start offset: 0x80027BE0
				// Variables:
			// 		struct tMenuCommand tempCommand; // stack offset -40

				/* begin block 1.3.1.1 */
					// Start line: 986
					// Start offset: 0x80027C1C

					/* begin block 1.3.1.1.1 */
						// Start line: 996
						// Start offset: 0x80027C60

						/* begin block 1.3.1.1.1.1 */
							// Start line: 996
							// Start offset: 0x80027C60

							/* begin block 1.3.1.1.1.1.1 */
								// Start line: 998
								// Start offset: 0x80027C8C
								// Variables:
							// 		struct Car_tStats *dummyCars; // $v0

								/* begin block 1.3.1.1.1.1.1.1 */
									// Start line: 998
									// Start offset: 0x80027C8C

									/* begin block 1.3.1.1.1.1.1.1.1 */
										// Start line: 998
										// Start offset: 0x80027C8C
									/* end block 1.3.1.1.1.1.1.1.1 */
									// End offset: 0x80027C8C
									// End Line: 998
								/* end block 1.3.1.1.1.1.1.1 */
								// End offset: 0x80027C8C
								// End Line: 998
							/* end block 1.3.1.1.1.1.1 */
							// End offset: 0x80027D14
							// End Line: 1017
						/* end block 1.3.1.1.1.1 */
						// End offset: 0x80027D14
						// End Line: 1017
					/* end block 1.3.1.1.1 */
					// End offset: 0x80027D14
					// End Line: 1017
				/* end block 1.3.1.1 */
				// End offset: 0x80027D14
				// End Line: 1017
			/* end block 1.3.1 */
			// End offset: 0x80027D28
			// End Line: 1021
		/* end block 1.3 */
		// End offset: 0x80027D28
		// End Line: 1021
	/* end block 1 */
	// End offset: 0x80027D28
	// End Line: 1024

int Front_Menu__F21tFront_ProcessingType(tFront_ProcessingType role)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// int * /*$ra*/ OutputDisplaySettings__FPiiiR17tTrackInformation(int *d /*$t0*/, int c /*$t1*/, int player /*$a2*/, struct tTrackInformation *trackInfo /*$a3*/)
 // line 1171, offset 0x80027da8
	/* begin block 1 */
		// Start line: 1172
		// Start offset: 0x80027DA8
		// Variables:
	// 		int valtopass; // $a0
	/* end block 1 */
	// End offset: 0x80027E20
	// End Line: 1191

int * OutputDisplaySettings__FPiiiR17tTrackInformation( (int *d,int c,int player,tTrackInformation *trackInfo)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// int /*$ra*/ Front_GetLapsForType__Fv()
 // line 1210, offset 0x80027fc0
	/* begin block 1 */
		// Start line: 1211
		// Start offset: 0x80027FC0
		// Variables:
	// 		short lapconv[2]; // stack offset -8

		/* begin block 1.1 */
			// Start line: 1211
			// Start offset: 0x80027FC0

			/* begin block 1.1.1 */
				// Start line: 1215
				// Start offset: 0x80027FEC

				/* begin block 1.1.1.1 */
					// Start line: 1215
					// Start offset: 0x80027FEC

					/* begin block 1.1.1.1.1 */
						// Start line: 1215
						// Start offset: 0x80027FEC
					/* end block 1.1.1.1.1 */
					// End offset: 0x80027FEC
					// End Line: 1215
				/* end block 1.1.1.1 */
				// End offset: 0x80027FEC
				// End Line: 1215
			/* end block 1.1.1 */
			// End offset: 0x80028060
			// End Line: 1224
		/* end block 1.1 */
		// End offset: 0x80028060
		// End Line: 1224
	/* end block 1 */
	// End offset: 0x80028060
	// End Line: 1224

int Front_GetLapsForType__Fv(void)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ Front_InitStream__FR9tFEStream(struct tFEStream *streamData /*$a0*/)
 // line 1231, offset 0x80028068
	/* begin block 1 */
		// Start line: 1232
		// Start offset: 0x80028068
	/* end block 1 */
	// End offset: 0x80028068
	// End Line: 1232

void Front_InitStream__FR9tFEStream(tFEStream *streamData)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ Front_InitPlayerCars__FR9tFEStream(struct tFEStream *streamData /*$s1*/)
 // line 1241, offset 0x80028098
	/* begin block 1 */
		// Start line: 1242
		// Start offset: 0x80028098
		// Variables:
	// 		short i; // $s2
	// 		struct tCarInfo *carInfo; // $a1

		/* begin block 1.1 */
			// Start line: 1299
			// Start offset: 0x80028354

			/* begin block 1.1.1 */
				// Start line: 1299
				// Start offset: 0x8002835C
				// Variables:
			// 		enum tCarModels carModel; // stack offset -32
			// 		char carColor; // stack offset -28
			/* end block 1.1.1 */
			// End offset: 0x800283CC
			// End Line: 1317
		/* end block 1.1 */
		// End offset: 0x80028440
		// End Line: 1325
	/* end block 1 */
	// End offset: 0x80028440
	// End Line: 1325

void Front_InitPlayerCars__FR9tFEStream(tFEStream *streamData)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ Front_InitTourneyTraffic__FR9tFEStream(struct tFEStream *streamData /*$s0*/)
 // line 1329, offset 0x8002845c
	/* begin block 1 */
		// Start line: 1330
		// Start offset: 0x8002845C
		// Variables:
	// 		enum tCarModels carModel; // stack offset -40
	// 		char carColor; // stack offset -36
	// 		short i; // $s1

		/* begin block 1.1 */
			// Start line: 1330
			// Start offset: 0x8002845C

			/* begin block 1.1.1 */
				// Start line: 1330
				// Start offset: 0x8002845C
			/* end block 1.1.1 */
			// End offset: 0x8002845C
			// End Line: 1330
		/* end block 1.1 */
		// End offset: 0x8002845C
		// End Line: 1330
	/* end block 1 */
	// End offset: 0x800285AC
	// End Line: 1359

void Front_InitTourneyTraffic__FR9tFEStream(tFEStream *streamData)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ Front_InitOpponentCars__FR9tFEStream(struct tFEStream *streamData /*$s2*/)
 // line 1366, offset 0x800285d0
	/* begin block 1 */
		// Start line: 1367
		// Start offset: 0x800285D0
		// Variables:
	// 		short i; // $s1
	// 		struct tCarLineup *carLineup; // $s0
	// 		short numOpponents; // $s7

		/* begin block 1.1 */
			// Start line: 1367
			// Start offset: 0x800285D0

			/* begin block 1.1.1 */
				// Start line: 1377
				// Start offset: 0x80028634
				// Variables:
			// 		struct tCarInfo *carInfo; // $s0
			// 		enum tCarModels carModel; // stack offset -64
			// 		char carColor; // stack offset -60
			// 		enum tCarClassType opponentClass; // $v1
			// 		unsigned int usePlayerUpgrades; // stack offset -48
			// 		struct tTourneyInfo *tourn; // $s3

				/* begin block 1.1.1.1 */
					// Start line: 1382
					// Start offset: 0x80028634

					/* begin block 1.1.1.1.1 */
						// Start line: 1389
						// Start offset: 0x8002863C

						/* begin block 1.1.1.1.1.1 */
							// Start line: 1389
							// Start offset: 0x8002863C

							/* begin block 1.1.1.1.1.1.1 */
								// Start line: 1389
								// Start offset: 0x8002863C
							/* end block 1.1.1.1.1.1.1 */
							// End offset: 0x8002863C
							// End Line: 1389
						/* end block 1.1.1.1.1.1 */
						// End offset: 0x8002863C
						// End Line: 1389
					/* end block 1.1.1.1.1 */
					// End offset: 0x8002863C
					// End Line: 1389
				/* end block 1.1.1.1 */
				// End offset: 0x80028694
				// End Line: 1390

				/* begin block 1.1.1.2 */
					// Start line: 1392
					// Start offset: 0x80028694

					/* begin block 1.1.1.2.1 */
						// Start line: 1393
						// Start offset: 0x800286A0

						/* begin block 1.1.1.2.1.1 */
							// Start line: 1393
							// Start offset: 0x800286A0

							/* begin block 1.1.1.2.1.1.1 */
								// Start line: 1393
								// Start offset: 0x800286A0
							/* end block 1.1.1.2.1.1.1 */
							// End offset: 0x800286A0
							// End Line: 1393
						/* end block 1.1.1.2.1.1 */
						// End offset: 0x800286A0
						// End Line: 1393
					/* end block 1.1.1.2.1 */
					// End offset: 0x800286A0
					// End Line: 1393

					/* begin block 1.1.1.2.2 */
						// Start line: 1398
						// Start offset: 0x800286DC

						/* begin block 1.1.1.2.2.1 */
							// Start line: 1398
							// Start offset: 0x800286DC

							/* begin block 1.1.1.2.2.1.1 */
								// Start line: 1398
								// Start offset: 0x800286DC
							/* end block 1.1.1.2.2.1.1 */
							// End offset: 0x80028724
							// End Line: 1398
						/* end block 1.1.1.2.2.1 */
						// End offset: 0x80028724
						// End Line: 1398
					/* end block 1.1.1.2.2 */
					// End offset: 0x80028724
					// End Line: 1398
				/* end block 1.1.1.2 */
				// End offset: 0x80028724
				// End Line: 1398

				/* begin block 1.1.1.3 */
					// Start line: 1401
					// Start offset: 0x80028724

					/* begin block 1.1.1.3.1 */
						// Start line: 1402
						// Start offset: 0x80028738

						/* begin block 1.1.1.3.1.1 */
							// Start line: 1402
							// Start offset: 0x80028738

							/* begin block 1.1.1.3.1.1.1 */
								// Start line: 1402
								// Start offset: 0x80028738
							/* end block 1.1.1.3.1.1.1 */
							// End offset: 0x80028738
							// End Line: 1402
						/* end block 1.1.1.3.1.1 */
						// End offset: 0x80028738
						// End Line: 1402
					/* end block 1.1.1.3.1 */
					// End offset: 0x80028738
					// End Line: 1402
				/* end block 1.1.1.3 */
				// End offset: 0x80028748
				// End Line: 1403

				/* begin block 1.1.1.4 */
					// Start line: 1454
					// Start offset: 0x80028908

					/* begin block 1.1.1.4.1 */
						// Start line: 1455
						// Start offset: 0x8002891C

						/* begin block 1.1.1.4.1.1 */
							// Start line: 1455
							// Start offset: 0x8002891C

							/* begin block 1.1.1.4.1.1.1 */
								// Start line: 1455
								// Start offset: 0x8002891C
							/* end block 1.1.1.4.1.1.1 */
							// End offset: 0x8002891C
							// End Line: 1455
						/* end block 1.1.1.4.1.1 */
						// End offset: 0x8002891C
						// End Line: 1455

						/* begin block 1.1.1.4.1.2 */
							// Start line: 1455
							// Start offset: 0x8002891C

							/* begin block 1.1.1.4.1.2.1 */
								// Start line: 1455
								// Start offset: 0x8002891C
							/* end block 1.1.1.4.1.2.1 */
							// End offset: 0x8002891C
							// End Line: 1455
						/* end block 1.1.1.4.1.2 */
						// End offset: 0x8002891C
						// End Line: 1455
					/* end block 1.1.1.4.1 */
					// End offset: 0x8002899C
					// End Line: 1463
				/* end block 1.1.1.4 */
				// End offset: 0x800289E4
				// End Line: 1473
			/* end block 1.1.1 */
			// End offset: 0x800289E4
			// End Line: 1473

			/* begin block 1.1.2 */
				// Start line: 1476
				// Start offset: 0x800289F0

				/* begin block 1.1.2.1 */
					// Start line: 1476
					// Start offset: 0x800289F0

					/* begin block 1.1.2.1.1 */
						// Start line: 1479
						// Start offset: 0x80028A1C
						// Variables:
					// 		struct tCarInfo carInfo; // stack offset -288
					// 		enum tCarModels carModel; // stack offset -56
					// 		char carColor; // stack offset -52
					// 		enum tCarModels modelList[3]; // stack offset -80
					/* end block 1.1.2.1.1 */
					// End offset: 0x80028ABC
					// End Line: 1511
				/* end block 1.1.2.1 */
				// End offset: 0x80028B34
				// End Line: 1530
			/* end block 1.1.2 */
			// End offset: 0x80028B34
			// End Line: 1530
		/* end block 1.1 */
		// End offset: 0x80028B34
		// End Line: 1530
	/* end block 1 */
	// End offset: 0x80028B34
	// End Line: 1530

void Front_InitOpponentCars__FR9tFEStream(tFEStream *streamData)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ Front_InitMissions__FR9tFEStream(struct tFEStream *streamData /*$s4*/)
 // line 1536, offset 0x80028b64
	/* begin block 1 */
		// Start line: 1537
		// Start offset: 0x80028B64
		// Variables:
	// 		short i; // $a0
	// 		enum tCarModels fBestCar; // $a2

		/* begin block 1.1 */
			// Start line: 1537
			// Start offset: 0x80028B64

			/* begin block 1.1.1 */
				// Start line: 1553
				// Start offset: 0x80028BA0
				// Variables:
			// 		char oldTier; // $s2
			// 		char oldMission; // $s3
			/* end block 1.1.1 */
			// End offset: 0x80028C74
			// End Line: 1578
		/* end block 1.1 */
		// End offset: 0x80028C74
		// End Line: 1578
	/* end block 1 */
	// End offset: 0x80028C74
	// End Line: 1578

void Front_InitMissions__FR9tFEStream(tFEStream *streamData)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ Front_InitCopCars__FR9tFEStream(struct tFEStream *streamData /*$s2*/)
 // line 1606, offset 0x80028c94
	/* begin block 1 */
		// Start line: 1607
		// Start offset: 0x80028C94
		// Variables:
	// 		enum tCarModels fBestModel; // $a1
	// 		enum tCarClassType fBestClass; // $a2
	// 		enum tCarModels copModel; // stack offset -48
	// 		char copColor; // stack offset -44
	// 		short i; // $s3
	/* end block 1 */
	// End offset: 0x80029028
	// End Line: 1695

void Front_InitCopCars__FR9tFEStream(tFEStream *streamData)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ Front_InitPerps__FR9tFEStream(struct tFEStream *streamData /*$s0*/)
 // line 1702, offset 0x80029054
	/* begin block 1 */
		// Start line: 1703
		// Start offset: 0x80029054
		// Variables:
	// 		short i; // $s1
	// 		short j; // $v1
	// 		struct tCarInfo *carInfo; // $a1

		/* begin block 1.1 */
			// Start line: 1703
			// Start offset: 0x80029054

			/* begin block 1.1.1 */
				// Start line: 1713
				// Start offset: 0x80029088

				/* begin block 1.1.1.1 */
					// Start line: 1714
					// Start offset: 0x80029088

					/* begin block 1.1.1.1.1 */
						// Start line: 1714
						// Start offset: 0x8002909C
						// Variables:
					// 		enum tCarModels carModel; // stack offset -40
					// 		char carColor; // stack offset -36
					/* end block 1.1.1.1.1 */
					// End offset: 0x800291E4
					// End Line: 1747
				/* end block 1.1.1.1 */
				// End offset: 0x800291F8
				// End Line: 1748
			/* end block 1.1.1 */
			// End offset: 0x800291F8
			// End Line: 1748
		/* end block 1.1 */
		// End offset: 0x800291F8
		// End Line: 1748
	/* end block 1 */
	// End offset: 0x800291F8
	// End Line: 1748

void Front_InitPerps__FR9tFEStream(tFEStream *streamData)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ Front_InitTrack__FR9tFEStream(struct tFEStream *streamData /*$s1*/)
 // line 1754, offset 0x8002921c
	/* begin block 1 */
		// Start line: 1755
		// Start offset: 0x8002921C
		// Variables:
	// 		struct tTrackInfo *tournTrack; // $v1
	/* end block 1 */
	// End offset: 0x800293CC
	// End Line: 1802

void Front_InitTrack__FR9tFEStream(tFEStream *streamData)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ Front_InitTraffic__FR9tFEStream(struct tFEStream *streamData /*$s3*/)
 // line 1809, offset 0x800293e0
	/* begin block 1 */
		// Start line: 1810
		// Start offset: 0x800293E0
		// Variables:
	// 		enum tCarModels carModel; // stack offset -40
	// 		char carColor; // stack offset -36
	// 		short i; // $s0
	// 		unsigned int bTraffic; // $a0
	// 		short maxTraffic; // $a2
	/* end block 1 */
	// End offset: 0x800295F4
	// End Line: 1880

void Front_InitTraffic__FR9tFEStream(tFEStream *streamData)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// int * /*$ra*/ Front_AppendPlayerCarData__FPiR9tFEStream(int *stream /*$a3*/, struct tFEStream *streamData /*$s0*/)
 // line 1889, offset 0x80029618
	/* begin block 1 */
		// Start line: 1890
		// Start offset: 0x80029618
		// Variables:
	// 		short i; // $s1
	// 		struct tCarInfo *carInfo; // $a1
	// 		struct tCarLineup *carLineup; // $a2
	/* end block 1 */
	// End offset: 0x80029AA0
	// End Line: 1960

int * Front_AppendPlayerCarData__FPiR9tFEStream(int *stream,tFEStream *streamData)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// int * /*$ra*/ Front_AppendOpponentData__FPiR9tFEStream(int *stream /*$s1*/, struct tFEStream *streamData /*$s2*/)
 // line 1968, offset 0x80029afc
	/* begin block 1 */
		// Start line: 1969
		// Start offset: 0x80029AFC
		// Variables:
	// 		short i; // $s3
	// 		struct tCarInfo *carInfo; // $v0
	// 		struct tCarLineup *carLineup; // $s0
	/* end block 1 */
	// End offset: 0x80029E10
	// End Line: 1999

int * Front_AppendOpponentData__FPiR9tFEStream(int *stream,tFEStream *streamData)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// int * /*$ra*/ Front_AppendCopData__FPiR9tFEStream(int *stream /*$s0*/, struct tFEStream *streamData /*$s1*/)
 // line 2003, offset 0x80029e30
	/* begin block 1 */
		// Start line: 2004
		// Start offset: 0x80029E30
		// Variables:
	// 		short i; // $s3

		/* begin block 1.1 */
			// Start line: 2017
			// Start offset: 0x80029E7C

			/* begin block 1.1.1 */
				// Start line: 2017
				// Start offset: 0x80029E80
			/* end block 1.1.1 */
			// End offset: 0x80029F34
			// End Line: 2023
		/* end block 1.1 */
		// End offset: 0x8002A064
		// End Line: 2034
	/* end block 1 */
	// End offset: 0x8002A064
	// End Line: 2036

int * Front_AppendCopData__FPiR9tFEStream(int *stream,tFEStream *streamData)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// int * /*$ra*/ Front_AppendPerpData__FPiR9tFEStream(int *stream /*$s1*/, struct tFEStream *streamData /*$s2*/)
 // line 2040, offset 0x8002a084
	/* begin block 1 */
		// Start line: 2041
		// Start offset: 0x8002A084
		// Variables:
	// 		short i; // $s3
	/* end block 1 */
	// End offset: 0x8002A2E4
	// End Line: 2075

int * Front_AppendPerpData__FPiR9tFEStream(int *stream,tFEStream *streamData)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// int * /*$ra*/ Front_AppendTrafficData__FPiR9tFEStream(int *stream /*$s0*/, struct tFEStream *streamData /*$s1*/)
 // line 2081, offset 0x8002a31c
	/* begin block 1 */
		// Start line: 2082
		// Start offset: 0x8002A31C
		// Variables:
	// 		short i; // $s2
	// 		int density; // $a0
	/* end block 1 */
	// End offset: 0x8002A53C
	// End Line: 2108

int * Front_AppendTrafficData__FPiR9tFEStream(int *stream,tFEStream *streamData)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// int * /*$ra*/ Front_AppendTrackData__FPiR9tFEStream(int *stream /*$s1*/, struct tFEStream *streamData /*$s2*/)
 // line 2114, offset 0x8002a56c
	/* begin block 1 */
		// Start line: 2115
		// Start offset: 0x8002A56C
		// Variables:
	// 		struct tTrackInformation trackInfo; // stack offset -64
	// 		int valtopass; // $a0
	/* end block 1 */
	// End offset: 0x8002A5F0
	// End Line: 2135

int * Front_AppendTrackData__FPiR9tFEStream(int *stream,tFEStream *streamData)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// unsigned int /*$ra*/ Front_EnableLocalSpeech__Fv()
 // line 2269, offset 0x8002a6ac
	/* begin block 1 */
		// Start line: 2270
		// Start offset: 0x8002A6AC
		// Variables:
	// 		unsigned int result; // $s1
	// 		struct tTrackInformation trackInfo; // stack offset -64
	/* end block 1 */
	// End offset: 0x8002A720
	// End Line: 2291

uint Front_EnableLocalSpeech__Fv(void)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// int * /*$ra*/ Front_BuildStream__FPi(int *stream /*$s3*/)
 // line 2299, offset 0x8002a738
	/* begin block 1 */
		// Start line: 2300
		// Start offset: 0x8002A738
		// Variables:
	// 		int *d; // $s0
	// 		int j; // $v1
	// 		struct tFEStream streamData; // stack offset -768
	// 		int colourLoop; // $v1
	// 		int numplaylistsongs; // $a1
	// 		int type; // $s2
	// 		int config; // $s4
	// 		int gameLang; // $s2
	// 		int trackLang; // $s1

		/* begin block 1.1 */
			// Start line: 2300
			// Start offset: 0x8002A738

			/* begin block 1.1.1 */
				// Start line: 2300
				// Start offset: 0x8002A738
			/* end block 1.1.1 */
			// End offset: 0x8002A738
			// End Line: 2300
		/* end block 1.1 */
		// End offset: 0x8002A738
		// End Line: 2300
	/* end block 1 */
	// End offset: 0x8002B6A0
	// End Line: 2720

int * Front_BuildStream__FPi(int *stream)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ Front_GetInGameVars__Fv()
 // line 2728, offset 0x8002b6d8
	/* begin block 1 */
		// Start line: 2729
		// Start offset: 0x8002B6D8
		// Variables:
	// 		int i; // $t1
	/* end block 1 */
	// End offset: 0x8002B7BC
	// End Line: 2753

void Front_GetInGameVars__Fv(void)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ SetLicensePlate__Fv()
 // line 2762, offset 0x8002b7cc
	/* begin block 1 */
		// Start line: 2763
		// Start offset: 0x8002B7CC

		/* begin block 1.1 */
			// Start line: 2763
			// Start offset: 0x8002B7CC
			// Variables:
		// 		short i; // $s2
		/* end block 1.1 */
		// End offset: 0x8002B858
		// End Line: 2772
	/* end block 1 */
	// End offset: 0x8002B858
	// End Line: 2772

void SetLicensePlate__Fv(void)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ SetPlayList__Fi(int ivealreadygotone /*$s0*/)
 // line 2777, offset 0x8002b874
	/* begin block 1 */
		// Start line: 2778
		// Start offset: 0x8002B874
		// Variables:
	// 		int i; // $v1
	// 		struct AudioMus_tSongList *songlist; // $a0
	/* end block 1 */
	// End offset: 0x8002B920
	// End Line: 2807

void SetPlayList__Fi(int ivealreadygotone)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// short /*$ra*/ Front_GetTrackRaced__Fv()
 // line 2815, offset 0x8002b960
	/* begin block 1 */
		// Start line: 2816
		// Start offset: 0x8002B960
		// Variables:
	// 		short trackraced; // $v0
	// 		struct tTrackInformation trackInfo; // stack offset -56
	/* end block 1 */
	// End offset: 0x8002B9BC
	// End Line: 2831

short Front_GetTrackRaced__Fv(void)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// unsigned int /*$ra*/ PlayerNameExist__Fi(int player /*$a0*/)
 // line 2834, offset 0x8002b9d0
	/* begin block 1 */
		// Start line: 2835
		// Start offset: 0x8002B9D0
	/* end block 1 */
	// End offset: 0x8002B9D0
	// End Line: 2835

uint PlayerNameExist__Fi(int player)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// char * /*$ra*/ PlayerName__Fi(int player /*$s2*/)
 // line 2841, offset 0x8002b9fc
	/* begin block 1 */
		// Start line: 2842
		// Start offset: 0x8002B9FC
	/* end block 1 */
	// End offset: 0x8002BA70
	// End Line: 2851

char * PlayerName__Fi(int player)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// char * /*$ra*/ PlayerNameMixedCase__Fi(int player /*$s2*/)
 // line 2859, offset 0x8002ba88
	/* begin block 1 */
		// Start line: 2860
		// Start offset: 0x8002BA88
	/* end block 1 */
	// End offset: 0x8002BADC
	// End Line: 2867

char * PlayerNameMixedCase__Fi(int player)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}





