#ifndef SCREENMEMCARD_H
#define SCREENMEMCARD_H

extern void _._14tScreenMemcard(struct tScreenMemcard *this, int __in_chrg); // 0x80047E3C


// decompiled code
// original method signature: 
// void /*$ra*/ _._14tScreenMemcard(struct tScreenMemcard *this /*$a0*/, int __in_chrg /*$a1*/)
 // line 99, offset 0x80047e3c
/* WARNING: Control flow encountered bad instruction data */

void ___14tScreenMemcard(tScreenMemcard *this,int __in_chrg)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}




#endif
