#include "NFS4.H"
#include "SCREENTRACKS.H"

// decompiled code
// original method signature: 
// void /*$ra*/ DrawBackground__18tScreenTrackSelect(struct tScreenTrackSelect *this /*$s7*/)
 // line 83, offset 0x80041600
	/* begin block 1 */
		// Start line: 84
		// Start offset: 0x80041600
		// Variables:
	// 		struct RECT r; // stack offset -192
	// 		struct tTrackInformation trackInfo; // stack offset -184
	// 		short shapeY; // $s6
	// 		struct POLY_FT4 *prim; // $fp
	// 		enum VIDEOSTATE state; // $v1

		/* begin block 1.1 */
			// Start line: 84
			// Start offset: 0x80041600

			/* begin block 1.1.1 */
				// Start line: 106
				// Start offset: 0x800416C8
				// Variables:
			// 		struct tVideoWall *this; // $s0

				/* begin block 1.1.1.1 */
					// Start line: 106
					// Start offset: 0x800416C8
				/* end block 1.1.1.1 */
				// End offset: 0x800416C8
				// End Line: 106
			/* end block 1.1.1 */
			// End offset: 0x800416C8
			// End Line: 106
		/* end block 1.1 */
		// End offset: 0x800416F8
		// End Line: 109

		/* begin block 1.2 */
			// Start line: 116
			// Start offset: 0x800416F8

			/* begin block 1.2.1 */
				// Start line: 122
				// Start offset: 0x80041724
				// Variables:
			// 		struct RECT r; // stack offset -136

				/* begin block 1.2.1.1 */
					// Start line: 125
					// Start offset: 0x80041724

					/* begin block 1.2.1.1.1 */
						// Start line: 125
						// Start offset: 0x80041724
					/* end block 1.2.1.1.1 */
					// End offset: 0x80041724
					// End Line: 125
				/* end block 1.2.1.1 */
				// End offset: 0x80041724
				// End Line: 125
			/* end block 1.2.1 */
			// End offset: 0x80041724
			// End Line: 125

			/* begin block 1.2.2 */
				// Start line: 135
				// Start offset: 0x80041774

				/* begin block 1.2.2.1 */
					// Start line: 135
					// Start offset: 0x80041774

					/* begin block 1.2.2.1.1 */
						// Start line: 143
						// Start offset: 0x800417B4

						/* begin block 1.2.2.1.1.1 */
							// Start line: 143
							// Start offset: 0x800417B4

							/* begin block 1.2.2.1.1.1.1 */
								// Start line: 143
								// Start offset: 0x800417DC

								/* begin block 1.2.2.1.1.1.1.1 */
									// Start line: 143
									// Start offset: 0x800417DC
								/* end block 1.2.2.1.1.1.1.1 */
								// End offset: 0x800417DC
								// End Line: 143
							/* end block 1.2.2.1.1.1.1 */
							// End offset: 0x800417DC
							// End Line: 143

							/* begin block 1.2.2.1.1.1.2 */
								// Start line: 144
								// Start offset: 0x800417F8
								// Variables:
							// 		char moviename[80]; // stack offset -128
							/* end block 1.2.2.1.1.1.2 */
							// End offset: 0x80041864
							// End Line: 151
						/* end block 1.2.2.1.1.1 */
						// End offset: 0x80041864
						// End Line: 151
					/* end block 1.2.2.1.1 */
					// End offset: 0x80041864
					// End Line: 151
				/* end block 1.2.2.1 */
				// End offset: 0x80041864
				// End Line: 151
			/* end block 1.2.2 */
			// End offset: 0x80041864
			// End Line: 151
		/* end block 1.2 */
		// End offset: 0x80041864
		// End Line: 151
	/* end block 1 */
	// End offset: 0x80041A74
	// End Line: 178

/* WARNING: Control flow encountered bad instruction data */

void DrawBackground__18tScreenTrackSelect(tScreenTrackSelect *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ GetShapeInfo__18tScreenTrackSelectRsT1PPcT3(struct tScreenTrackSelect *this /*$s5*/, short *numPermShapes /*$s2*/, short *numSwapShapes /*$s3*/, char **permFileName /*$s4*/, char **swapFileName /*stack 16*/)
 // line 183, offset 0x80041aac
	/* begin block 1 */
		// Start line: 184
		// Start offset: 0x80041AAC
		// Variables:
	// 		struct tTrackInformation trackInfo; // stack offset -80
	/* end block 1 */
	// End offset: 0x80041AAC
	// End Line: 184

/* WARNING: Control flow encountered bad instruction data */

void GetShapeInfo__18tScreenTrackSelectRsT1PPcT3
               (tScreenTrackSelect *this,short *numPermShapes,short *numSwapShapes,
               char **permFileName,char **swapFileName)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Initialize__18tScreenTrackSelect(struct tScreenTrackSelect *this /*$s2*/)
 // line 200, offset 0x80041b6c
	/* begin block 1 */
		// Start line: 201
		// Start offset: 0x80041B6C
		// Variables:
	// 		struct tTrackInformation trackInfo; // stack offset -152
	// 		struct RECT r; // stack offset -104
	// 		char moviename[80]; // stack offset -96

		/* begin block 1.1 */
			// Start line: 201
			// Start offset: 0x80041B6C

			/* begin block 1.1.1 */
				// Start line: 201
				// Start offset: 0x80041B6C
			/* end block 1.1.1 */
			// End offset: 0x80041B6C
			// End Line: 201
		/* end block 1.1 */
		// End offset: 0x80041B6C
		// End Line: 201
	/* end block 1 */
	// End offset: 0x80041B6C
	// End Line: 201

/* WARNING: Control flow encountered bad instruction data */

void Initialize__18tScreenTrackSelect(tScreenTrackSelect *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Cleanup__18tScreenTrackSelect(struct tScreenTrackSelect *this /*$s0*/)
 // line 251, offset 0x80041d28
	/* begin block 1 */
		// Start line: 252
		// Start offset: 0x80041D28
	/* end block 1 */
	// End offset: 0x80041D28
	// End Line: 252

/* WARNING: Control flow encountered bad instruction data */

void Cleanup__18tScreenTrackSelect(tScreenTrackSelect *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ SetBrightness__18tScreenTrackSelects(struct tScreenTrackSelect *this /*$a0*/, short bright /*$a1*/)
 // line 261, offset 0x80041d68
	/* begin block 1 */
		// Start line: 262
		// Start offset: 0x80041D68

		/* begin block 1.1 */
			// Start line: 263
			// Start offset: 0x80041D68

			/* begin block 1.1.1 */
				// Start line: 264
				// Start offset: 0x80041D7C

				/* begin block 1.1.1.1 */
					// Start line: 265
					// Start offset: 0x80041D7C

					/* begin block 1.1.1.1.1 */
						// Start line: 265
						// Start offset: 0x80041D7C
					/* end block 1.1.1.1.1 */
					// End offset: 0x80041D7C
					// End Line: 265
				/* end block 1.1.1.1 */
				// End offset: 0x80041D7C
				// End Line: 265
			/* end block 1.1.1 */
			// End offset: 0x80041D90
			// End Line: 267
		/* end block 1.1 */
		// End offset: 0x80041D90
		// End Line: 267
	/* end block 1 */
	// End offset: 0x80041D90
	// End Line: 267

/* WARNING: Control flow encountered bad instruction data */

void SetBrightness__18tScreenTrackSelects(tScreenTrackSelect *this,short bright)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ UpdateBrightness__18tScreenTrackSelectR17tTrackInformation(struct tScreenTrackSelect *this /*$s0*/, struct tTrackInformation *trackInfo /*$s1*/)
 // line 272, offset 0x80041d98
	/* begin block 1 */
		// Start line: 273
		// Start offset: 0x80041D98
		// Variables:
	// 		long elapsed; // $v1

		/* begin block 1.1 */
			// Start line: 273
			// Start offset: 0x80041D98

			/* begin block 1.1.1 */
				// Start line: 273
				// Start offset: 0x80041D98
			/* end block 1.1.1 */
			// End offset: 0x80041D98
			// End Line: 273
		/* end block 1.1 */
		// End offset: 0x80041D98
		// End Line: 273

		/* begin block 1.2 */
			// Start line: 291
			// Start offset: 0x80041E24

			/* begin block 1.2.1 */
				// Start line: 292
				// Start offset: 0x80041E34

				/* begin block 1.2.1.1 */
					// Start line: 293
					// Start offset: 0x80041E34

					/* begin block 1.2.1.1.1 */
						// Start line: 295
						// Start offset: 0x80041E50

						/* begin block 1.2.1.1.1.1 */
							// Start line: 296
							// Start offset: 0x80041E50

							/* begin block 1.2.1.1.1.1.1 */
								// Start line: 296
								// Start offset: 0x80041E50
							/* end block 1.2.1.1.1.1.1 */
							// End offset: 0x80041E50
							// End Line: 296
						/* end block 1.2.1.1.1.1 */
						// End offset: 0x80041E50
						// End Line: 296
					/* end block 1.2.1.1.1 */
					// End offset: 0x80041E74
					// End Line: 298
				/* end block 1.2.1.1 */
				// End offset: 0x80041E74
				// End Line: 298
			/* end block 1.2.1 */
			// End offset: 0x80041E74
			// End Line: 298
		/* end block 1.2 */
		// End offset: 0x80041E74
		// End Line: 298
	/* end block 1 */
	// End offset: 0x80041E74
	// End Line: 298

/* WARNING: Control flow encountered bad instruction data */

void UpdateBrightness__18tScreenTrackSelectR17tTrackInformation
               (tScreenTrackSelect *this,tTrackInformation *trackInfo)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ UpdateVideoWall__18tScreenTrackSelectR17tTrackInformation(struct tScreenTrackSelect *this /*$s0*/, struct tTrackInformation *trackInfo /*$s1*/)
 // line 305, offset 0x80041e88
	/* begin block 1 */
		// Start line: 306
		// Start offset: 0x80041E88
	/* end block 1 */
	// End offset: 0x80041EE8
	// End Line: 315

/* WARNING: Control flow encountered bad instruction data */

void UpdateVideoWall__18tScreenTrackSelectR17tTrackInformation
               (tScreenTrackSelect *this,tTrackInformation *trackInfo)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ DrawVideoWall__18tScreenTrackSelect(struct tScreenTrackSelect *this /*$s1*/)
 // line 319, offset 0x80041efc
	/* begin block 1 */
		// Start line: 320
		// Start offset: 0x80041EFC
		// Variables:
	// 		struct tTrackInformation trackInfo; // stack offset -64
	/* end block 1 */
	// End offset: 0x80041FE0
	// End Line: 341

/* WARNING: Control flow encountered bad instruction data */

void DrawVideoWall__18tScreenTrackSelect(tScreenTrackSelect *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ ProcessInput__18tScreenTrackSelect7tPlayerR13tInputKeyTypeR12tMenuCommand(struct tScreenTrackSelect *this /*$s0*/, enum tInputKeyType *keyval /*$a2*/)
 // line 345, offset 0x8004200c
	/* begin block 1 */
		// Start line: 346
		// Start offset: 0x8004200C
		// Variables:
	// 		struct tTrackInformation trackInfo; // stack offset -56

		/* begin block 1.1 */
			// Start line: 346
			// Start offset: 0x8004200C

			/* begin block 1.1.1 */
				// Start line: 350
				// Start offset: 0x80042028

				/* begin block 1.1.1.1 */
					// Start line: 351
					// Start offset: 0x80042028

					/* begin block 1.1.1.1.1 */
						// Start line: 351
						// Start offset: 0x80042028
					/* end block 1.1.1.1.1 */
					// End offset: 0x80042028
					// End Line: 351
				/* end block 1.1.1.1 */
				// End offset: 0x80042028
				// End Line: 351

				/* begin block 1.1.1.2 */
					// Start line: 351
					// Start offset: 0x80042028

					/* begin block 1.1.1.2.1 */
						// Start line: 357
						// Start offset: 0x80042088

						/* begin block 1.1.1.2.1.1 */
							// Start line: 357
							// Start offset: 0x80042088

							/* begin block 1.1.1.2.1.1.1 */
								// Start line: 357
								// Start offset: 0x80042088
							/* end block 1.1.1.2.1.1.1 */
							// End offset: 0x8004208C
							// End Line: 357
						/* end block 1.1.1.2.1.1 */
						// End offset: 0x8004208C
						// End Line: 357
					/* end block 1.1.1.2.1 */
					// End offset: 0x8004208C
					// End Line: 357
				/* end block 1.1.1.2 */
				// End offset: 0x8004208C
				// End Line: 357

				/* begin block 1.1.1.3 */
					// Start line: 358
					// Start offset: 0x8004208C

					/* begin block 1.1.1.3.1 */
						// Start line: 359
						// Start offset: 0x800420A0

						/* begin block 1.1.1.3.1.1 */
							// Start line: 359
							// Start offset: 0x800420A0

							/* begin block 1.1.1.3.1.1.1 */
								// Start line: 359
								// Start offset: 0x800420A0
							/* end block 1.1.1.3.1.1.1 */
							// End offset: 0x800420B8
							// End Line: 359
						/* end block 1.1.1.3.1.1 */
						// End offset: 0x800420B8
						// End Line: 359
					/* end block 1.1.1.3.1 */
					// End offset: 0x800420B8
					// End Line: 359
				/* end block 1.1.1.3 */
				// End offset: 0x800420B8
				// End Line: 359

				/* begin block 1.1.1.4 */
					// Start line: 360
					// Start offset: 0x800420B8

					/* begin block 1.1.1.4.1 */
						// Start line: 361
						// Start offset: 0x800420C8

						/* begin block 1.1.1.4.1.1 */
							// Start line: 361
							// Start offset: 0x800420C8

							/* begin block 1.1.1.4.1.1.1 */
								// Start line: 361
								// Start offset: 0x800420C8
							/* end block 1.1.1.4.1.1.1 */
							// End offset: 0x800420E0
							// End Line: 361
						/* end block 1.1.1.4.1.1 */
						// End offset: 0x800420E0
						// End Line: 361
					/* end block 1.1.1.4.1 */
					// End offset: 0x800420E0
					// End Line: 361
				/* end block 1.1.1.4 */
				// End offset: 0x800420E0
				// End Line: 361

				/* begin block 1.1.1.5 */
					// Start line: 362
					// Start offset: 0x800420E0

					/* begin block 1.1.1.5.1 */
						// Start line: 363
						// Start offset: 0x80042108

						/* begin block 1.1.1.5.1.1 */
							// Start line: 363
							// Start offset: 0x80042108

							/* begin block 1.1.1.5.1.1.1 */
								// Start line: 363
								// Start offset: 0x80042108
							/* end block 1.1.1.5.1.1.1 */
							// End offset: 0x80042120
							// End Line: 363
						/* end block 1.1.1.5.1.1 */
						// End offset: 0x80042120
						// End Line: 363
					/* end block 1.1.1.5.1 */
					// End offset: 0x80042120
					// End Line: 363
				/* end block 1.1.1.5 */
				// End offset: 0x80042120
				// End Line: 363

				/* begin block 1.1.1.6 */
					// Start line: 364
					// Start offset: 0x80042120

					/* begin block 1.1.1.6.1 */
						// Start line: 365
						// Start offset: 0x80042140

						/* begin block 1.1.1.6.1.1 */
							// Start line: 365
							// Start offset: 0x80042140

							/* begin block 1.1.1.6.1.1.1 */
								// Start line: 365
								// Start offset: 0x80042140
							/* end block 1.1.1.6.1.1.1 */
							// End offset: 0x80042140
							// End Line: 365
						/* end block 1.1.1.6.1.1 */
						// End offset: 0x80042140
						// End Line: 365
					/* end block 1.1.1.6.1 */
					// End offset: 0x80042140
					// End Line: 365

					/* begin block 1.1.1.6.2 */
						// Start line: 366
						// Start offset: 0x8004215C

						/* begin block 1.1.1.6.2.1 */
							// Start line: 366
							// Start offset: 0x8004215C

							/* begin block 1.1.1.6.2.1.1 */
								// Start line: 366
								// Start offset: 0x8004215C
							/* end block 1.1.1.6.2.1.1 */
							// End offset: 0x8004215C
							// End Line: 366
						/* end block 1.1.1.6.2.1 */
						// End offset: 0x8004215C
						// End Line: 366
					/* end block 1.1.1.6.2 */
					// End offset: 0x8004215C
					// End Line: 366
				/* end block 1.1.1.6 */
				// End offset: 0x8004215C
				// End Line: 366
			/* end block 1.1.1 */
			// End offset: 0x8004215C
			// End Line: 366

			/* begin block 1.1.2 */
				// Start line: 368
				// Start offset: 0x80042178

				/* begin block 1.1.2.1 */
					// Start line: 368
					// Start offset: 0x80042178

					/* begin block 1.1.2.1.1 */
						// Start line: 369
						// Start offset: 0x80042184

						/* begin block 1.1.2.1.1.1 */
							// Start line: 370
							// Start offset: 0x80042184

							/* begin block 1.1.2.1.1.1.1 */
								// Start line: 370
								// Start offset: 0x80042184
								// Variables:
							// 		struct tFEApplication *this; // $v0

								/* begin block 1.1.2.1.1.1.1.1 */
									// Start line: 370
									// Start offset: 0x80042184
								/* end block 1.1.2.1.1.1.1.1 */
								// End offset: 0x80042184
								// End Line: 370
							/* end block 1.1.2.1.1.1.1 */
							// End offset: 0x80042184
							// End Line: 370
						/* end block 1.1.2.1.1.1 */
						// End offset: 0x800421C4
						// End Line: 371
					/* end block 1.1.2.1.1 */
					// End offset: 0x800421C4
					// End Line: 371
				/* end block 1.1.2.1 */
				// End offset: 0x800421C4
				// End Line: 371
			/* end block 1.1.2 */
			// End offset: 0x800421C4
			// End Line: 371
		/* end block 1.1 */
		// End offset: 0x800421C4
		// End Line: 371
	/* end block 1 */
	// End offset: 0x800421C4
	// End Line: 371

/* WARNING: Control flow encountered bad instruction data */

void ProcessInput__18tScreenTrackSelect7tPlayerR13tInputKeyTypeR12tMenuCommand
               (tScreenTrackSelect *this,tInputKeyType *keyval)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}




