#ifndef SCREENTRACKRECORDS_H
#define SCREENTRACKRECORDS_H

extern void _._19tScreenTrackRecords(struct tScreenTrackRecords *this, int __in_chrg); // 0x800430F8


// decompiled code
// original method signature: 
// void /*$ra*/ _._19tScreenTrackRecords(struct tScreenTrackRecords *this /*$a0*/, int __in_chrg /*$a1*/)
 // line 55, offset 0x800430f8
/* WARNING: Control flow encountered bad instruction data */

void ___19tScreenTrackRecords(tScreenTrackRecords *this,int __in_chrg)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}




#endif
