#include "NFS4.H"
#include "SCREENMAIN.H"

// decompiled code
// original method signature: 
// void /*$ra*/ SwapBackground__11tScreenMaini(struct tScreenMain *this /*$s0*/, int num /*$s1*/)
 // line 218, offset 0x80036f20
	/* begin block 1 */
		// Start line: 219
		// Start offset: 0x80036F20
		// Variables:
	// 		char buffer[8]; // stack offset -24
	// 		enum tScreenMainState oldState; // $a0
	/* end block 1 */
	// End offset: 0x800370C4
	// End Line: 266

/* WARNING: Control flow encountered bad instruction data */

void SwapBackground__11tScreenMaini(tScreenMain *this,int num)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void * /*$ra*/ DoneLoadingBackground__11tScreenMain(struct tScreenMain *this /*$a0*/)
 // line 270, offset 0x800370dc
	/* begin block 1 */
		// Start line: 271
		// Start offset: 0x800370DC
	/* end block 1 */
	// End offset: 0x80037150
	// End Line: 277

/* WARNING: Control flow encountered bad instruction data */

void * DoneLoadingBackground__11tScreenMain(tScreenMain *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ SetState__11tScreenMain16tScreenMainState(struct tScreenMain *this /*$s2*/, enum tScreenMainState state /*$s0*/)
 // line 280, offset 0x80037158
	/* begin block 1 */
		// Start line: 281
		// Start offset: 0x80037158
		// Variables:
	// 		short i; // $s1
	// 		struct tTexture_ShapeInfo *shape; // $a2

		/* begin block 1.1 */
			// Start line: 281
			// Start offset: 0x80037158

			/* begin block 1.1.1 */
				// Start line: 286
				// Start offset: 0x80037180

				/* begin block 1.1.1.1 */
					// Start line: 288
					// Start offset: 0x80037180

					/* begin block 1.1.1.1.1 */
						// Start line: 288
						// Start offset: 0x80037180
					/* end block 1.1.1.1.1 */
					// End offset: 0x80037180
					// End Line: 288
				/* end block 1.1.1.1 */
				// End offset: 0x80037180
				// End Line: 288

				/* begin block 1.1.1.2 */
					// Start line: 288
					// Start offset: 0x80037180

					/* begin block 1.1.1.2.1 */
						// Start line: 292
						// Start offset: 0x800371AC

						/* begin block 1.1.1.2.1.1 */
							// Start line: 292
							// Start offset: 0x800371AC
						/* end block 1.1.1.2.1.1 */
						// End offset: 0x800371AC
						// End Line: 292
					/* end block 1.1.1.2.1 */
					// End offset: 0x800371AC
					// End Line: 292
				/* end block 1.1.1.2 */
				// End offset: 0x800371C8
				// End Line: 294

				/* begin block 1.1.1.3 */
					// Start line: 297
					// Start offset: 0x800371C8

					/* begin block 1.1.1.3.1 */
						// Start line: 297
						// Start offset: 0x800371C8
					/* end block 1.1.1.3.1 */
					// End offset: 0x800371C8
					// End Line: 297
				/* end block 1.1.1.3 */
				// End offset: 0x800371C8
				// End Line: 297
			/* end block 1.1.1 */
			// End offset: 0x80037414
			// End Line: 343
		/* end block 1.1 */
		// End offset: 0x80037414
		// End Line: 343
	/* end block 1 */
	// End offset: 0x80037414
	// End Line: 343

/* WARNING: Control flow encountered bad instruction data */

void SetState__11tScreenMain16tScreenMainState(tScreenMain *this,tScreenMainState state)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ InitDynamicImages__11tScreenMain(struct tScreenMain *this /*$t0*/)
 // line 348, offset 0x8003742c
	/* begin block 1 */
		// Start line: 349
		// Start offset: 0x8003742C
		// Variables:
	// 		struct tVideo *video; // $s1
	// 		int videoWallConfig; // $fp
	// 		int startX; // $t1
	// 		int startY; // $t3
	// 		int x; // $s2
	// 		int y; // $s3
	// 		int xOffset; // $v1
	// 		int yOffset; // $v0
	// 		int i; // $t2
	// 		int j; // $s6
	// 		int k; // $s4
	// 		int index; // $v0
	/* end block 1 */
	// End offset: 0x80037768
	// End Line: 403

/* WARNING: Control flow encountered bad instruction data */

void InitDynamicImages__11tScreenMain(tScreenMain *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ ProcessInput__11tScreenMain7tPlayerR13tInputKeyTypeR12tMenuCommand(struct tScreenMain *this /*$a0*/, enum tInputKeyType *keyval /*$a2*/)
 // line 406, offset 0x80037798
	/* begin block 1 */
		// Start line: 407
		// Start offset: 0x80037798

		/* begin block 1.1 */
			// Start line: 407
			// Start offset: 0x80037798

			/* begin block 1.1.1 */
				// Start line: 408
				// Start offset: 0x800377B4
				// Variables:
			// 		struct tFEApplication *this; // $v0

				/* begin block 1.1.1.1 */
					// Start line: 408
					// Start offset: 0x800377B4
				/* end block 1.1.1.1 */
				// End offset: 0x800377B4
				// End Line: 408
			/* end block 1.1.1 */
			// End offset: 0x800377B4
			// End Line: 408

			/* begin block 1.1.2 */
				// Start line: 409
				// Start offset: 0x800377CC

				/* begin block 1.1.2.1 */
					// Start line: 410
					// Start offset: 0x800377CC

					/* begin block 1.1.2.1.1 */
						// Start line: 410
						// Start offset: 0x800377CC
						// Variables:
					// 		struct tFEApplication *this; // $v1

						/* begin block 1.1.2.1.1.1 */
							// Start line: 410
							// Start offset: 0x800377CC
						/* end block 1.1.2.1.1.1 */
						// End offset: 0x800377CC
						// End Line: 410
					/* end block 1.1.2.1.1 */
					// End offset: 0x800377CC
					// End Line: 410
				/* end block 1.1.2.1 */
				// End offset: 0x800377F4
				// End Line: 413
			/* end block 1.1.2 */
			// End offset: 0x800377F4
			// End Line: 413
		/* end block 1.1 */
		// End offset: 0x800377F4
		// End Line: 413
	/* end block 1 */
	// End offset: 0x800377F4
	// End Line: 413

/* WARNING: Control flow encountered bad instruction data */

void ProcessInput__11tScreenMain7tPlayerR13tInputKeyTypeR12tMenuCommand
               (tScreenMain *this,tInputKeyType *keyval)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ DrawDropShadow__11tScreenMain(struct tScreenMain *this /*$a0*/)
 // line 417, offset 0x80037804
	/* begin block 1 */
		// Start line: 418
		// Start offset: 0x80037804
		// Variables:
	// 		int i; // $t0
	// 		struct POLY_G4 *prim; // $a0
	/* end block 1 */
	// End offset: 0x80037900
	// End Line: 438

/* WARNING: Control flow encountered bad instruction data */

void DrawDropShadow__11tScreenMain(tScreenMain *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ DrawVideoLines__11tScreenMain(struct tScreenMain *this /*$a0*/)
 // line 441, offset 0x80037918
	/* begin block 1 */
		// Start line: 442
		// Start offset: 0x80037918
		// Variables:
	// 		int i; // $s0
	/* end block 1 */
	// End offset: 0x800379A0
	// End Line: 453

/* WARNING: Control flow encountered bad instruction data */

void DrawVideoLines__11tScreenMain(tScreenMain *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ DrawBackground__11tScreenMain(struct tScreenMain *this /*$s6*/)
 // line 456, offset 0x800379c0
	/* begin block 1 */
		// Start line: 457
		// Start offset: 0x800379C0
		// Variables:
	// 		short i; // $s2
	// 		short j; // $s0
	// 		struct tDrawShapeExtended drawFlags; // stack offset -184
	// 		unsigned long deltaTicks; // $s1
	// 		short animFade; // $s7
	// 		short x; // $s1
	// 		short y; // $s3
	// 		char buffer[32]; // stack offset -160
	// 		int shapeX; // $v0
	// 		int shapeY; // $s0

		/* begin block 1.1 */
			// Start line: 457
			// Start offset: 0x800379C0

			/* begin block 1.1.1 */
				// Start line: 469
				// Start offset: 0x800379FC

				/* begin block 1.1.1.1 */
					// Start line: 471
					// Start offset: 0x80037A10

					/* begin block 1.1.1.1.1 */
						// Start line: 473
						// Start offset: 0x80037A3C
						// Variables:
					// 		void * bAllTVsOn; // $a2
					/* end block 1.1.1.1.1 */
					// End offset: 0x80037B08
					// End Line: 486
				/* end block 1.1.1.1 */
				// End offset: 0x80037B08
				// End Line: 486
			/* end block 1.1.1 */
			// End offset: 0x80037B08
			// End Line: 486
		/* end block 1.1 */
		// End offset: 0x80037B10
		// End Line: 489

		/* begin block 1.2 */
			// Start line: 490
			// Start offset: 0x80037B10

			/* begin block 1.2.1 */
				// Start line: 490
				// Start offset: 0x80037B20
				// Variables:
			// 		struct tFEApplication *this; // $a0

				/* begin block 1.2.1.1 */
					// Start line: 490
					// Start offset: 0x80037B20
				/* end block 1.2.1.1 */
				// End offset: 0x80037B20
				// End Line: 490
			/* end block 1.2.1 */
			// End offset: 0x80037B20
			// End Line: 490

			/* begin block 1.2.2 */
				// Start line: 494
				// Start offset: 0x80037B44

				/* begin block 1.2.2.1 */
					// Start line: 494
					// Start offset: 0x80037B44

					/* begin block 1.2.2.1.1 */
						// Start line: 494
						// Start offset: 0x80037B44
						// Variables:
					// 		struct tFEApplication *this; // $a0

						/* begin block 1.2.2.1.1.1 */
							// Start line: 494
							// Start offset: 0x80037B44
						/* end block 1.2.2.1.1.1 */
						// End offset: 0x80037B44
						// End Line: 494
					/* end block 1.2.2.1.1 */
					// End offset: 0x80037B44
					// End Line: 494
				/* end block 1.2.2.1 */
				// End offset: 0x80037B74
				// End Line: 496
			/* end block 1.2.2 */
			// End offset: 0x80037B74
			// End Line: 496
		/* end block 1.2 */
		// End offset: 0x80037B74
		// End Line: 496

		/* begin block 1.3 */
			// Start line: 499
			// Start offset: 0x80037B74

			/* begin block 1.3.1 */
				// Start line: 502
				// Start offset: 0x80037B9C

				/* begin block 1.3.1.1 */
					// Start line: 503
					// Start offset: 0x80037B9C

					/* begin block 1.3.1.1.1 */
						// Start line: 504
						// Start offset: 0x80037BAC
						// Variables:
					// 		struct tFEApplication *this; // $v0

						/* begin block 1.3.1.1.1.1 */
							// Start line: 504
							// Start offset: 0x80037BAC
						/* end block 1.3.1.1.1.1 */
						// End offset: 0x80037BAC
						// End Line: 504
					/* end block 1.3.1.1.1 */
					// End offset: 0x80037BAC
					// End Line: 504

					/* begin block 1.3.1.1.2 */
						// Start line: 504
						// Start offset: 0x80037BAC

						/* begin block 1.3.1.1.2.1 */
							// Start line: 504
							// Start offset: 0x80037BAC
						/* end block 1.3.1.1.2.1 */
						// End offset: 0x80037BAC
						// End Line: 504
					/* end block 1.3.1.1.2 */
					// End offset: 0x80037BAC
					// End Line: 504
				/* end block 1.3.1.1 */
				// End offset: 0x80037BE4
				// End Line: 505
			/* end block 1.3.1 */
			// End offset: 0x80037BE4
			// End Line: 505

			/* begin block 1.3.2 */
				// Start line: 507
				// Start offset: 0x80037BEC

				/* begin block 1.3.2.1 */
					// Start line: 507
					// Start offset: 0x80037BEC

					/* begin block 1.3.2.1.1 */
						// Start line: 508
						// Start offset: 0x80037BFC
						// Variables:
					// 		struct tFEApplication *this; // $v0

						/* begin block 1.3.2.1.1.1 */
							// Start line: 508
							// Start offset: 0x80037BFC
						/* end block 1.3.2.1.1.1 */
						// End offset: 0x80037BFC
						// End Line: 508
					/* end block 1.3.2.1.1 */
					// End offset: 0x80037BFC
					// End Line: 508

					/* begin block 1.3.2.1.2 */
						// Start line: 508
						// Start offset: 0x80037BFC

						/* begin block 1.3.2.1.2.1 */
							// Start line: 508
							// Start offset: 0x80037BFC
						/* end block 1.3.2.1.2.1 */
						// End offset: 0x80037BFC
						// End Line: 508
					/* end block 1.3.2.1.2 */
					// End offset: 0x80037BFC
					// End Line: 508
				/* end block 1.3.2.1 */
				// End offset: 0x80037C44
				// End Line: 509
			/* end block 1.3.2 */
			// End offset: 0x80037C44
			// End Line: 509
		/* end block 1.3 */
		// End offset: 0x80037C44
		// End Line: 509

		/* begin block 1.4 */
			// Start line: 512
			// Start offset: 0x80037C44

			/* begin block 1.4.1 */
				// Start line: 513
				// Start offset: 0x80037C64
				// Variables:
			// 		int fade; // $v0
			// 		int TextCol; // $s0
			// 		struct RECT r; // stack offset -128
			/* end block 1.4.1 */
			// End offset: 0x80037F24
			// End Line: 557
		/* end block 1.4 */
		// End offset: 0x80037F24
		// End Line: 557

		/* begin block 1.5 */
			// Start line: 566
			// Start offset: 0x80037F3C

			/* begin block 1.5.1 */
				// Start line: 567
				// Start offset: 0x80037F54

				/* begin block 1.5.1.1 */
					// Start line: 567
					// Start offset: 0x80037F54

					/* begin block 1.5.1.1.1 */
						// Start line: 567
						// Start offset: 0x80037F54
					/* end block 1.5.1.1.1 */
					// End offset: 0x80037F54
					// End Line: 567
				/* end block 1.5.1.1 */
				// End offset: 0x80037F54
				// End Line: 567
			/* end block 1.5.1 */
			// End offset: 0x80037F84
			// End Line: 573

			/* begin block 1.5.2 */
				// Start line: 576
				// Start offset: 0x80037F8C

				/* begin block 1.5.2.1 */
					// Start line: 576
					// Start offset: 0x80037F8C

					/* begin block 1.5.2.1.1 */
						// Start line: 578
						// Start offset: 0x80037FA4

						/* begin block 1.5.2.1.1.1 */
							// Start line: 578
							// Start offset: 0x80037FA4
						/* end block 1.5.2.1.1.1 */
						// End offset: 0x80037FA4
						// End Line: 578
					/* end block 1.5.2.1.1 */
					// End offset: 0x80037FA4
					// End Line: 578

					/* begin block 1.5.2.1.2 */
						// Start line: 579
						// Start offset: 0x80037FD4
						// Variables:
					// 		char moviename[80]; // stack offset -120
					// 		struct RECT r; // stack offset -128
					/* end block 1.5.2.1.2 */
					// End offset: 0x80038098
					// End Line: 604
				/* end block 1.5.2.1 */
				// End offset: 0x80038098
				// End Line: 604
			/* end block 1.5.2 */
			// End offset: 0x80038098
			// End Line: 604
		/* end block 1.5 */
		// End offset: 0x80038098
		// End Line: 604

		/* begin block 1.6 */
			// Start line: 615
			// Start offset: 0x800380C8

			/* begin block 1.6.1 */
				// Start line: 615
				// Start offset: 0x800380C8
			/* end block 1.6.1 */
			// End offset: 0x800380C8
			// End Line: 615
		/* end block 1.6 */
		// End offset: 0x800380C8
		// End Line: 615

		/* begin block 1.7 */
			// Start line: 644
			// Start offset: 0x8003819C

			/* begin block 1.7.1 */
				// Start line: 646
				// Start offset: 0x800381B8

				/* begin block 1.7.1.1 */
					// Start line: 647
					// Start offset: 0x800381B8

					/* begin block 1.7.1.1.1 */
						// Start line: 647
						// Start offset: 0x800381B8
					/* end block 1.7.1.1.1 */
					// End offset: 0x800381B8
					// End Line: 647
				/* end block 1.7.1.1 */
				// End offset: 0x800381B8
				// End Line: 647
			/* end block 1.7.1 */
			// End offset: 0x800381EC
			// End Line: 652
		/* end block 1.7 */
		// End offset: 0x800381EC
		// End Line: 652

		/* begin block 1.8 */
			// Start line: 662
			// Start offset: 0x80038218

			/* begin block 1.8.1 */
				// Start line: 663
				// Start offset: 0x80038234
				// Variables:
			// 		int drawAnimFade; // $t1

				/* begin block 1.8.1.1 */
					// Start line: 665
					// Start offset: 0x80038234

					/* begin block 1.8.1.1.1 */
						// Start line: 665
						// Start offset: 0x80038234

						/* begin block 1.8.1.1.1.1 */
							// Start line: 665
							// Start offset: 0x80038234
						/* end block 1.8.1.1.1.1 */
						// End offset: 0x80038234
						// End Line: 665
					/* end block 1.8.1.1.1 */
					// End offset: 0x80038234
					// End Line: 665
				/* end block 1.8.1.1 */
				// End offset: 0x8003828C
				// End Line: 669
			/* end block 1.8.1 */
			// End offset: 0x800382FC
			// End Line: 674
		/* end block 1.8 */
		// End offset: 0x800382FC
		// End Line: 674

		/* begin block 1.9 */
			// Start line: 678
			// Start offset: 0x800382FC

			/* begin block 1.9.1 */
				// Start line: 679
				// Start offset: 0x8003830C

				/* begin block 1.9.1.1 */
					// Start line: 681
					// Start offset: 0x80038330

					/* begin block 1.9.1.1.1 */
						// Start line: 682
						// Start offset: 0x80038338

						/* begin block 1.9.1.1.1.1 */
							// Start line: 682
							// Start offset: 0x80038348

							/* begin block 1.9.1.1.1.1.1 */
								// Start line: 682
								// Start offset: 0x80038348
							/* end block 1.9.1.1.1.1.1 */
							// End offset: 0x80038348
							// End Line: 682
						/* end block 1.9.1.1.1.1 */
						// End offset: 0x80038348
						// End Line: 682
					/* end block 1.9.1.1.1 */
					// End offset: 0x80038348
					// End Line: 682
				/* end block 1.9.1.1 */
				// End offset: 0x800383E8
				// End Line: 686
			/* end block 1.9.1 */
			// End offset: 0x800383E8
			// End Line: 687
		/* end block 1.9 */
		// End offset: 0x800383F4
		// End Line: 688

		/* begin block 1.10 */
			// Start line: 688
			// Start offset: 0x800383F4

			/* begin block 1.10.1 */
				// Start line: 688
				// Start offset: 0x800383F4
			/* end block 1.10.1 */
			// End offset: 0x800383F4
			// End Line: 688
		/* end block 1.10 */
		// End offset: 0x800383F4
		// End Line: 688
	/* end block 1 */
	// End offset: 0x8003866C
	// End Line: 738

/* WARNING: Control flow encountered bad instruction data */

void DrawBackground__11tScreenMain(tScreenMain *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ GetShapeInfo__11tScreenMainRsT1PPcT3(struct tScreenMain *this /*$a0*/, short *numPermShapes /*$a1*/, short *numSwapShapes /*$a2*/, char **permFileName /*$a3*/, char **swapFileName /*stack 16*/)
 // line 747, offset 0x80038698
	/* begin block 1 */
		// Start line: 748
		// Start offset: 0x80038698
	/* end block 1 */
	// End offset: 0x80038698
	// End Line: 748

/* WARNING: Control flow encountered bad instruction data */

void GetShapeInfo__11tScreenMainRsT1PPcT3
               (tScreenMain *this,short *numPermShapes,short *numSwapShapes,char **permFileName,
               char **swapFileName)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ PreLoad__11tScreenMain(struct tScreenMain *this /*$s3*/)
 // line 758, offset 0x800386c8
	/* begin block 1 */
		// Start line: 759
		// Start offset: 0x800386C8
		// Variables:
	// 		char buffer[32]; // stack offset -56
	// 		short i; // $s2
	/* end block 1 */
	// End offset: 0x800388B4
	// End Line: 785

/* WARNING: Control flow encountered bad instruction data */

void PreLoad__11tScreenMain(tScreenMain *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Initialize__11tScreenMain(struct tScreenMain *this /*$s1*/)
 // line 788, offset 0x800388d4
	/* begin block 1 */
		// Start line: 789
		// Start offset: 0x800388D4
		// Variables:
	// 		short i; // $s0
	// 		void * shapesLoaded; // $s0

		/* begin block 1.1 */
			// Start line: 809
			// Start offset: 0x80038988

			/* begin block 1.1.1 */
				// Start line: 809
				// Start offset: 0x80038988
			/* end block 1.1.1 */
			// End offset: 0x80038988
			// End Line: 809
		/* end block 1.1 */
		// End offset: 0x80038988
		// End Line: 809

		/* begin block 1.2 */
			// Start line: 809
			// Start offset: 0x80038988

			/* begin block 1.2.1 */
				// Start line: 809
				// Start offset: 0x80038988
			/* end block 1.2.1 */
			// End offset: 0x80038988
			// End Line: 809
		/* end block 1.2 */
		// End offset: 0x80038988
		// End Line: 809
	/* end block 1 */
	// End offset: 0x80038ABC
	// End Line: 838

/* WARNING: Control flow encountered bad instruction data */

void Initialize__11tScreenMain(tScreenMain *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Cleanup__11tScreenMain(struct tScreenMain *this /*$s2*/)
 // line 841, offset 0x80038ad8
	/* begin block 1 */
		// Start line: 842
		// Start offset: 0x80038AD8
		// Variables:
	// 		int i; // $s1
	/* end block 1 */
	// End offset: 0x80038B24
	// End Line: 852

/* WARNING: Control flow encountered bad instruction data */

void Cleanup__11tScreenMain(tScreenMain *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}




