#ifndef SCREENCONTROLLER_H
#define SCREENCONTROLLER_H

extern void _._23tScreenControllerConfig(struct tScreenControllerConfig *this, int __in_chrg); // 0x8004590C


// decompiled code
// original method signature: 
// void /*$ra*/ _._23tScreenControllerConfig(struct tScreenControllerConfig *this /*$s0*/, int __in_chrg /*$s1*/)
 // line 177, offset 0x8004590c
	/* begin block 1 */
		// Start line: 178
		// Start offset: 0x8004590C

		/* begin block 1.1 */
			// Start line: 178
			// Start offset: 0x8004590C

			/* begin block 1.1.1 */
				// Start line: 178
				// Start offset: 0x8004590C

				/* begin block 1.1.1.1 */
					// Start line: 178
					// Start offset: 0x8004590C
				/* end block 1.1.1.1 */
				// End offset: 0x8004590C
				// End Line: 178
			/* end block 1.1.1 */
			// End offset: 0x8004590C
			// End Line: 178
		/* end block 1.1 */
		// End offset: 0x8004590C
		// End Line: 178
	/* end block 1 */
	// End offset: 0x8004590C
	// End Line: 178

/* WARNING: Control flow encountered bad instruction data */

void ___23tScreenControllerConfig(tScreenControllerConfig *this,int __in_chrg)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}




#endif
