#ifndef SCREENTROPHYINFO_H
#define SCREENTROPHYINFO_H

extern void _._17tScreenTrophyInfo(struct tScreenTrophyInfo *this, int __in_chrg); // 0x800415E0


// decompiled code
// original method signature: 
// void /*$ra*/ _._17tScreenTrophyInfo(struct tScreenTrophyInfo *this /*$a0*/, int __in_chrg /*$a1*/)
 // line 30, offset 0x800415e0
/* WARNING: Control flow encountered bad instruction data */

void ___17tScreenTrophyInfo(tScreenTrophyInfo *this,int __in_chrg)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}




#endif
