#include "NFS4.H"
#include "SCREENCONGRATS.H"

// decompiled code
// original method signature: 
// void /*$ra*/ Cleanup__15tScreenCongrats(struct tScreenCongrats *this /*$s0*/)
 // line 53, offset 0x80047e60
	/* begin block 1 */
		// Start line: 54
		// Start offset: 0x80047E60
	/* end block 1 */
	// End offset: 0x80047E60
	// End Line: 54

void Cleanup__15tScreenCongrats(tScreenCongrats *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ GetShapeInfo__15tScreenCongratsRsT1PPcT3(struct tScreenCongrats *this /*$s3*/, short *numPermShapes /*$t0*/, short *numSwapShapes /*$s7*/, char **permFileName /*$s0*/, char **swapFileName /*stack 16*/)
 // line 64, offset 0x80047e8c
	/* begin block 1 */
		// Start line: 65
		// Start offset: 0x80047E8C
		// Variables:
	// 		struct tTourneyInfo *tourneyInfo; // $s4

		/* begin block 1.1 */
			// Start line: 65
			// Start offset: 0x80047E8C

			/* begin block 1.1.1 */
				// Start line: 65
				// Start offset: 0x80047E8C
			/* end block 1.1.1 */
			// End offset: 0x80047E8C
			// End Line: 65
		/* end block 1.1 */
		// End offset: 0x80047E8C
		// End Line: 65

		/* begin block 1.2 */
			// Start line: 78
			// Start offset: 0x80047F5C

			/* begin block 1.2.1 */
				// Start line: 83
				// Start offset: 0x80047F90
				// Variables:
			// 		int j; // $s2

				/* begin block 1.2.1.1 */
					// Start line: 83
					// Start offset: 0x80047F90

					/* begin block 1.2.1.1.1 */
						// Start line: 83
						// Start offset: 0x80047F90
					/* end block 1.2.1.1.1 */
					// End offset: 0x80047F90
					// End Line: 83
				/* end block 1.2.1.1 */
				// End offset: 0x80047F90
				// End Line: 83

				/* begin block 1.2.1.2 */
					// Start line: 83
					// Start offset: 0x80047F90
					// Variables:
				// 		int i; // $s0
				/* end block 1.2.1.2 */
				// End offset: 0x80047FF4
				// End Line: 89
			/* end block 1.2.1 */
			// End offset: 0x80047FF4
			// End Line: 89
		/* end block 1.2 */
		// End offset: 0x800480B8
		// End Line: 109
	/* end block 1 */
	// End offset: 0x800480B8
	// End Line: 117

void GetShapeInfo__15tScreenCongratsRsT1PPcT3( (tScreenCongrats *this,short *numPermShapes,short *numSwapShapes,char **permFileName, char **swapFileName)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// unsigned int /*$ra*/ GetCar__15tScreenCongratsR8tCarInfo(struct tScreenCongrats *this /*$a0*/, struct tCarInfo *carInfo /*$s0*/)
 // line 121, offset 0x800480e4
	/* begin block 1 */
		// Start line: 122
		// Start offset: 0x800480E4
	/* end block 1 */
	// End offset: 0x800480E4
	// End Line: 122

uint GetCar__15tScreenCongratsR8tCarInfo(tScreenCongrats *this,tCarInfo *carInfo)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ DrawBackground__15tScreenCongrats(struct tScreenCongrats *this /*$s3*/)
 // line 128, offset 0x8004813c
	/* begin block 1 */
		// Start line: 129
		// Start offset: 0x8004813C
		// Variables:
	// 		int fJustFadeOff; // $s4
	// 		static unsigned long carRotate; // offset 0x0
	// 		struct tDrawShapeExtended drawFlags; // stack offset -96
	// 		struct tDrawShapeExtended drawFlags2; // stack offset -72
	// 		int StripeRGB; // $a0
	// 		int bannerframe; // $s1
	// 		struct tDrawShapeExtended drawFlags3; // stack offset -48

		/* begin block 1.1 */
			// Start line: 135
			// Start offset: 0x80048170

			/* begin block 1.1.1 */
				// Start line: 146
				// Start offset: 0x800481FC

				/* begin block 1.1.1.1 */
					// Start line: 146
					// Start offset: 0x800481FC
				/* end block 1.1.1.1 */
				// End offset: 0x800481FC
				// End Line: 146
			/* end block 1.1.1 */
			// End offset: 0x800481FC
			// End Line: 146

			/* begin block 1.1.2 */
				// Start line: 147
				// Start offset: 0x80048218

				/* begin block 1.1.2.1 */
					// Start line: 147
					// Start offset: 0x80048218

					/* begin block 1.1.2.1.1 */
						// Start line: 147
						// Start offset: 0x80048218
					/* end block 1.1.2.1.1 */
					// End offset: 0x80048218
					// End Line: 147
				/* end block 1.1.2.1 */
				// End offset: 0x80048218
				// End Line: 147
			/* end block 1.1.2 */
			// End offset: 0x80048218
			// End Line: 147

			/* begin block 1.1.3 */
				// Start line: 151
				// Start offset: 0x80048224
				// Variables:
			// 		unsigned int scale; // $s0

				/* begin block 1.1.3.1 */
					// Start line: 152
					// Start offset: 0x80048224

					/* begin block 1.1.3.1.1 */
						// Start line: 152
						// Start offset: 0x80048234

						/* begin block 1.1.3.1.1.1 */
							// Start line: 152
							// Start offset: 0x80048234

							/* begin block 1.1.3.1.1.1.1 */
								// Start line: 152
								// Start offset: 0x80048234
							/* end block 1.1.3.1.1.1.1 */
							// End offset: 0x80048234
							// End Line: 152
						/* end block 1.1.3.1.1.1 */
						// End offset: 0x80048234
						// End Line: 152
					/* end block 1.1.3.1.1 */
					// End offset: 0x80048240
					// End Line: 152
				/* end block 1.1.3.1 */
				// End offset: 0x80048240
				// End Line: 152

				/* begin block 1.1.3.2 */
					// Start line: 154
					// Start offset: 0x80048240

					/* begin block 1.1.3.2.1 */
						// Start line: 155
						// Start offset: 0x80048250
						// Variables:
					// 		int colf; // $s2
					// 		int colb; // $s1

						/* begin block 1.1.3.2.1.1 */
							// Start line: 156
							// Start offset: 0x80048250

							/* begin block 1.1.3.2.1.1.1 */
								// Start line: 156
								// Start offset: 0x80048250

								/* begin block 1.1.3.2.1.1.1.1 */
									// Start line: 156
									// Start offset: 0x80048250
								/* end block 1.1.3.2.1.1.1.1 */
								// End offset: 0x80048250
								// End Line: 156
							/* end block 1.1.3.2.1.1.1 */
							// End offset: 0x80048250
							// End Line: 156
						/* end block 1.1.3.2.1.1 */
						// End offset: 0x800482B0
						// End Line: 165

						/* begin block 1.1.3.2.1.2 */
							// Start line: 165
							// Start offset: 0x800482B0

							/* begin block 1.1.3.2.1.2.1 */
								// Start line: 165
								// Start offset: 0x800482B0
							/* end block 1.1.3.2.1.2.1 */
							// End offset: 0x800482B0
							// End Line: 165
						/* end block 1.1.3.2.1.2 */
						// End offset: 0x800482B0
						// End Line: 165
					/* end block 1.1.3.2.1 */
					// End offset: 0x80048380
					// End Line: 180
				/* end block 1.1.3.2 */
				// End offset: 0x80048380
				// End Line: 180

				/* begin block 1.1.3.3 */
					// Start line: 184
					// Start offset: 0x80048380

					/* begin block 1.1.3.3.1 */
						// Start line: 184
						// Start offset: 0x80048390

						/* begin block 1.1.3.3.1.1 */
							// Start line: 184
							// Start offset: 0x80048390
						/* end block 1.1.3.3.1.1 */
						// End offset: 0x80048390
						// End Line: 184
					/* end block 1.1.3.3.1 */
					// End offset: 0x80048390
					// End Line: 184
				/* end block 1.1.3.3 */
				// End offset: 0x800483B8
				// End Line: 187

				/* begin block 1.1.3.4 */
					// Start line: 194
					// Start offset: 0x800483B8

					/* begin block 1.1.3.4.1 */
						// Start line: 196
						// Start offset: 0x800483C8

						/* begin block 1.1.3.4.1.1 */
							// Start line: 197
							// Start offset: 0x800483C8

							/* begin block 1.1.3.4.1.1.1 */
								// Start line: 200
								// Start offset: 0x800483FC

								/* begin block 1.1.3.4.1.1.1.1 */
									// Start line: 200
									// Start offset: 0x800483FC

									/* begin block 1.1.3.4.1.1.1.1.1 */
										// Start line: 200
										// Start offset: 0x800483FC
									/* end block 1.1.3.4.1.1.1.1.1 */
									// End offset: 0x800483FC
									// End Line: 200
								/* end block 1.1.3.4.1.1.1.1 */
								// End offset: 0x800483FC
								// End Line: 200
							/* end block 1.1.3.4.1.1.1 */
							// End offset: 0x8004843C
							// End Line: 218

							/* begin block 1.1.3.4.1.1.2 */
								// Start line: 221
								// Start offset: 0x80048444

								/* begin block 1.1.3.4.1.1.2.1 */
									// Start line: 221
									// Start offset: 0x80048444

									/* begin block 1.1.3.4.1.1.2.1.1 */
										// Start line: 221
										// Start offset: 0x80048444
									/* end block 1.1.3.4.1.1.2.1.1 */
									// End offset: 0x80048444
									// End Line: 221
								/* end block 1.1.3.4.1.1.2.1 */
								// End offset: 0x80048444
								// End Line: 221

								/* begin block 1.1.3.4.1.1.2.2 */
									// Start line: 221
									// Start offset: 0x80048444

									/* begin block 1.1.3.4.1.1.2.2.1 */
										// Start line: 233
										// Start offset: 0x80048474

										/* begin block 1.1.3.4.1.1.2.2.1.1 */
											// Start line: 234
											// Start offset: 0x80048474

											/* begin block 1.1.3.4.1.1.2.2.1.1.1 */
												// Start line: 234
												// Start offset: 0x80048474

												/* begin block 1.1.3.4.1.1.2.2.1.1.1.1 */
													// Start line: 234
													// Start offset: 0x80048474
												/* end block 1.1.3.4.1.1.2.2.1.1.1.1 */
												// End offset: 0x80048474
												// End Line: 234
											/* end block 1.1.3.4.1.1.2.2.1.1.1 */
											// End offset: 0x80048474
											// End Line: 234

											/* begin block 1.1.3.4.1.1.2.2.1.1.2 */
												// Start line: 238
												// Start offset: 0x800484E0

												/* begin block 1.1.3.4.1.1.2.2.1.1.2.1 */
													// Start line: 239
													// Start offset: 0x800484E0

													/* begin block 1.1.3.4.1.1.2.2.1.1.2.1.1 */
														// Start line: 239
														// Start offset: 0x800484E0
													/* end block 1.1.3.4.1.1.2.2.1.1.2.1.1 */
													// End offset: 0x800484E0
													// End Line: 239
												/* end block 1.1.3.4.1.1.2.2.1.1.2.1 */
												// End offset: 0x800484E0
												// End Line: 239
											/* end block 1.1.3.4.1.1.2.2.1.1.2 */
											// End offset: 0x800484E0
											// End Line: 239
										/* end block 1.1.3.4.1.1.2.2.1.1 */
										// End offset: 0x800484E0
										// End Line: 239
									/* end block 1.1.3.4.1.1.2.2.1 */
									// End offset: 0x800484E0
									// End Line: 239
								/* end block 1.1.3.4.1.1.2.2 */
								// End offset: 0x800484E0
								// End Line: 239
							/* end block 1.1.3.4.1.1.2 */
							// End offset: 0x800484E0
							// End Line: 239
						/* end block 1.1.3.4.1.1 */
						// End offset: 0x800484E0
						// End Line: 239
					/* end block 1.1.3.4.1 */
					// End offset: 0x800484E0
					// End Line: 239

					/* begin block 1.1.3.4.2 */
						// Start line: 246
						// Start offset: 0x800484F0

						/* begin block 1.1.3.4.2.1 */
							// Start line: 248
							// Start offset: 0x800484F0

							/* begin block 1.1.3.4.2.1.1 */
								// Start line: 248
								// Start offset: 0x800484F0
							/* end block 1.1.3.4.2.1.1 */
							// End offset: 0x800484F0
							// End Line: 248
						/* end block 1.1.3.4.2.1 */
						// End offset: 0x800484F0
						// End Line: 248
					/* end block 1.1.3.4.2 */
					// End offset: 0x80048550
					// End Line: 251
				/* end block 1.1.3.4 */
				// End offset: 0x80048550
				// End Line: 251

				/* begin block 1.1.3.5 */
					// Start line: 261
					// Start offset: 0x800485C8

					/* begin block 1.1.3.5.1 */
						// Start line: 262
						// Start offset: 0x800485E0

						/* begin block 1.1.3.5.1.1 */
							// Start line: 262
							// Start offset: 0x800485E0

							/* begin block 1.1.3.5.1.1.1 */
								// Start line: 262
								// Start offset: 0x800485E0
							/* end block 1.1.3.5.1.1.1 */
							// End offset: 0x800485E0
							// End Line: 262
						/* end block 1.1.3.5.1.1 */
						// End offset: 0x800485E0
						// End Line: 262
					/* end block 1.1.3.5.1 */
					// End offset: 0x80048638
					// End Line: 264
				/* end block 1.1.3.5 */
				// End offset: 0x80048638
				// End Line: 264

				/* begin block 1.1.3.6 */
					// Start line: 270
					// Start offset: 0x80048638

					/* begin block 1.1.3.6.1 */
						// Start line: 271
						// Start offset: 0x8004864C

						/* begin block 1.1.3.6.1.1 */
							// Start line: 272
							// Start offset: 0x8004864C

							/* begin block 1.1.3.6.1.1.1 */
								// Start line: 273
								// Start offset: 0x8004866C

								/* begin block 1.1.3.6.1.1.1.1 */
									// Start line: 273
									// Start offset: 0x8004866C

									/* begin block 1.1.3.6.1.1.1.1.1 */
										// Start line: 273
										// Start offset: 0x8004866C
									/* end block 1.1.3.6.1.1.1.1.1 */
									// End offset: 0x8004866C
									// End Line: 273
								/* end block 1.1.3.6.1.1.1.1 */
								// End offset: 0x8004866C
								// End Line: 273

								/* begin block 1.1.3.6.1.1.1.2 */
									// Start line: 279
									// Start offset: 0x800486D0

									/* begin block 1.1.3.6.1.1.1.2.1 */
										// Start line: 279
										// Start offset: 0x800486D0
									/* end block 1.1.3.6.1.1.1.2.1 */
									// End offset: 0x800486D0
									// End Line: 279
								/* end block 1.1.3.6.1.1.1.2 */
								// End offset: 0x800486D0
								// End Line: 279
							/* end block 1.1.3.6.1.1.1 */
							// End offset: 0x8004874C
							// End Line: 284
						/* end block 1.1.3.6.1.1 */
						// End offset: 0x8004874C
						// End Line: 284
					/* end block 1.1.3.6.1 */
					// End offset: 0x8004874C
					// End Line: 284
				/* end block 1.1.3.6 */
				// End offset: 0x8004874C
				// End Line: 284
			/* end block 1.1.3 */
			// End offset: 0x8004874C
			// End Line: 284
		/* end block 1.1 */
		// End offset: 0x8004874C
		// End Line: 284

		/* begin block 1.2 */
			// Start line: 314
			// Start offset: 0x800487C8

			/* begin block 1.2.1 */
				// Start line: 321
				// Start offset: 0x800487F8

				/* begin block 1.2.1.1 */
					// Start line: 322
					// Start offset: 0x800487F8
					// Variables:
				// 		int i; // $s0
				/* end block 1.2.1.1 */
				// End offset: 0x80048858
				// End Line: 329

				/* begin block 1.2.1.2 */
					// Start line: 330
					// Start offset: 0x80048858
					// Variables:
				// 		int i; // $s0
				/* end block 1.2.1.2 */
				// End offset: 0x800488BC
				// End Line: 337
			/* end block 1.2.1 */
			// End offset: 0x800488BC
			// End Line: 337

			/* begin block 1.2.2 */
				// Start line: 340
				// Start offset: 0x800488C4

				/* begin block 1.2.2.1 */
					// Start line: 341
					// Start offset: 0x800488C4
					// Variables:
				// 		int i; // $s0
				/* end block 1.2.2.1 */
				// End offset: 0x80048928
				// End Line: 348
			/* end block 1.2.2 */
			// End offset: 0x80048928
			// End Line: 348
		/* end block 1.2 */
		// End offset: 0x80048928
		// End Line: 348
	/* end block 1 */
	// End offset: 0x80048990
	// End Line: 353

void DrawBackground__15tScreenCongrats(tScreenCongrats *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ DrawForeground__15tScreenCongrats(struct tScreenCongrats *this /*$a0*/)
 // line 360, offset 0x800489b0
	/* begin block 1 */
		// Start line: 361
		// Start offset: 0x800489B0
	/* end block 1 */
	// End offset: 0x800489B0
	// End Line: 361

void DrawForeground__15tScreenCongrats(tScreenCongrats *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ CalculatePrizes__15tScreenCongrats(struct tScreenCongrats *this /*$a0*/)
 // line 365, offset 0x800489b8
	/* begin block 1 */
		// Start line: 366
		// Start offset: 0x800489B8
	/* end block 1 */
	// End offset: 0x80048A24
	// End Line: 381

void CalculatePrizes__15tScreenCongrats(tScreenCongrats *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ Initialize__15tScreenCongrats(struct tScreenCongrats *this /*$s0*/)
 // line 385, offset 0x80048a2c
	/* begin block 1 */
		// Start line: 386
		// Start offset: 0x80048A2C

		/* begin block 1.1 */
			// Start line: 386
			// Start offset: 0x80048A2C

			/* begin block 1.1.1 */
				// Start line: 386
				// Start offset: 0x80048A2C
			/* end block 1.1.1 */
			// End offset: 0x80048A2C
			// End Line: 386
		/* end block 1.1 */
		// End offset: 0x80048A2C
		// End Line: 386
	/* end block 1 */
	// End offset: 0x80048AD8
	// End Line: 416

void Initialize__15tScreenCongrats(tScreenCongrats *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ ProcessInput__15tScreenCongrats7tPlayerR13tInputKeyTypeR12tMenuCommand(struct tScreenCongrats *this /*$a0*/, enum tPlayer p /*$a1*/, enum tInputKeyType *keyval /*$a2*/, struct tMenuCommand *c /*$a3*/)
 // line 423, offset 0x80048af0
	/* begin block 1 */
		// Start line: 424
		// Start offset: 0x80048AF0

		/* begin block 1.1 */
			// Start line: 425
			// Start offset: 0x80048AF0

			/* begin block 1.1.1 */
				// Start line: 426
				// Start offset: 0x80048B00

				/* begin block 1.1.1.1 */
					// Start line: 427
					// Start offset: 0x80048B00

					/* begin block 1.1.1.1.1 */
						// Start line: 427
						// Start offset: 0x80048B00

						/* begin block 1.1.1.1.1.1 */
							// Start line: 427
							// Start offset: 0x80048B00
						/* end block 1.1.1.1.1.1 */
						// End offset: 0x80048B00
						// End Line: 427
					/* end block 1.1.1.1.1 */
					// End offset: 0x80048B00
					// End Line: 427

					/* begin block 1.1.1.1.2 */
						// Start line: 427
						// Start offset: 0x80048B10

						/* begin block 1.1.1.1.2.1 */
							// Start line: 427
							// Start offset: 0x80048B10
						/* end block 1.1.1.1.2.1 */
						// End offset: 0x80048B10
						// End Line: 427
					/* end block 1.1.1.1.2 */
					// End offset: 0x80048B10
					// End Line: 427
				/* end block 1.1.1.1 */
				// End offset: 0x80048B40
				// End Line: 428
			/* end block 1.1.1 */
			// End offset: 0x80048B40
			// End Line: 428
		/* end block 1.1 */
		// End offset: 0x80048B40
		// End Line: 428
	/* end block 1 */
	// End offset: 0x80048B40
	// End Line: 428

void ProcessInput__15tScreenCongrats7tPlayerR13tInputKeyTypeR12tMenuCommand( (tScreenCongrats *this,tPlayer p,tInputKeyType *keyval,tMenuCommand *c)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ DrawCongratsMessage__23tScreenPinkSlipCongrats(struct tScreenPinkSlipCongrats *this /*$s3*/)
 // line 432, offset 0x80048b48
	/* begin block 1 */
		// Start line: 433
		// Start offset: 0x80048B48
		// Variables:
	// 		struct RECT r; // stack offset -288
	// 		char buffer[250]; // stack offset -280
	/* end block 1 */
	// End offset: 0x80048C34
	// End Line: 453

void DrawCongratsMessage__23tScreenPinkSlipCongrats(tScreenPinkSlipCongrats *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// unsigned int /*$ra*/ GetCar__23tScreenPinkSlipCongratsR8tCarInfo(struct tScreenPinkSlipCongrats *this /*$a0*/, struct tCarInfo *carInfo /*$s0*/)
 // line 456, offset 0x80048c64
	/* begin block 1 */
		// Start line: 457
		// Start offset: 0x80048C64
	/* end block 1 */
	// End offset: 0x80048C64
	// End Line: 457

uint GetCar__23tScreenPinkSlipCongratsR8tCarInfo(tScreenPinkSlipCongrats *this,tCarInfo *carInfo)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ CalculatePrizes__23tScreenPinkSlipCongrats(struct tScreenPinkSlipCongrats *this /*$s3*/)
 // line 463, offset 0x80048cdc
	/* begin block 1 */
		// Start line: 464
		// Start offset: 0x80048CDC
		// Variables:
	// 		struct tCarInfo carinfo; // stack offset -232

		/* begin block 1.1 */
			// Start line: 464
			// Start offset: 0x80048CDC

			/* begin block 1.1.1 */
				// Start line: 464
				// Start offset: 0x80048CDC
			/* end block 1.1.1 */
			// End offset: 0x80048CDC
			// End Line: 464
		/* end block 1.1 */
		// End offset: 0x80048CDC
		// End Line: 464
	/* end block 1 */
	// End offset: 0x80048DAC
	// End Line: 486

void CalculatePrizes__23tScreenPinkSlipCongrats(tScreenPinkSlipCongrats *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ Initialize__23tScreenPinkSlipCongrats(struct tScreenPinkSlipCongrats *this /*$a0*/)
 // line 491, offset 0x80048dec
	/* begin block 1 */
		// Start line: 492
		// Start offset: 0x80048DEC
	/* end block 1 */
	// End offset: 0x80048E2C
	// End Line: 501

void Initialize__23tScreenPinkSlipCongrats(tScreenPinkSlipCongrats *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ Cleanup__23tScreenPinkSlipCongrats(struct tScreenPinkSlipCongrats *this /*$s0*/)
 // line 505, offset 0x80048e44
	/* begin block 1 */
		// Start line: 506
		// Start offset: 0x80048E44
	/* end block 1 */
	// End offset: 0x80048E44
	// End Line: 506

void Cleanup__23tScreenPinkSlipCongrats(tScreenPinkSlipCongrats *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ ProcessInput__23tScreenTournamentTrophy7tPlayerR13tInputKeyTypeR12tMenuCommand(struct tScreenTournamentTrophy *this /*$a0*/, enum tPlayer p /*$a1*/, enum tInputKeyType *keyval /*$a2*/, struct tMenuCommand *c /*$a3*/)
 // line 518, offset 0x80048e70
	/* begin block 1 */
		// Start line: 519
		// Start offset: 0x80048E70
	/* end block 1 */
	// End offset: 0x80048EA0
	// End Line: 528

void ProcessInput__23tScreenTournamentTrophy7tPlayerR13tInputKeyTypeR12tMenuCommand( (tScreenTournamentTrophy *this,tPlayer p,tInputKeyType *keyval,tMenuCommand *c)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// unsigned int /*$ra*/ GetCar__23tScreenTournamentTrophyR8tCarInfo(struct tScreenTournamentTrophy *this /*$a0*/, struct tCarInfo *carInfo /*$s0*/)
 // line 531, offset 0x80048eb8
	/* begin block 1 */
		// Start line: 532
		// Start offset: 0x80048EB8

		/* begin block 1.1 */
			// Start line: 532
			// Start offset: 0x80048EB8

			/* begin block 1.1.1 */
				// Start line: 534
				// Start offset: 0x80048ED4
				// Variables:
			// 		struct tAwardInformation tInfo; // stack offset -80
			/* end block 1.1.1 */
			// End offset: 0x80048ED4
			// End Line: 536
		/* end block 1.1 */
		// End offset: 0x80048F50
		// End Line: 549
	/* end block 1 */
	// End offset: 0x80048F50
	// End Line: 551

uint GetCar__23tScreenTournamentTrophyR8tCarInfo(tScreenTournamentTrophy *this,tCarInfo *carInfo)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ DrawCongratsMessage__23tScreenTournamentTrophy(struct tScreenTournamentTrophy *this /*$s4*/)
 // line 555, offset 0x80048f64
	/* begin block 1 */
		// Start line: 556
		// Start offset: 0x80048F64
		// Variables:
	// 		struct RECT r; // stack offset -1432
	// 		struct tAwardInformation tInfo; // stack offset -1424
	// 		char buffer1[500]; // stack offset -1352
	// 		char buffer2[500]; // stack offset -848

		/* begin block 1.1 */
			// Start line: 556
			// Start offset: 0x80048F64

			/* begin block 1.1.1 */
				// Start line: 568
				// Start offset: 0x80048FB4
				// Variables:
			// 		int firstmessage; // $s2
			// 		int secondmessage; // $s3
			// 		struct tTourneyInfo *tourneyInfo; // $s1

				/* begin block 1.1.1.1 */
					// Start line: 569
					// Start offset: 0x80048FB4

					/* begin block 1.1.1.1.1 */
						// Start line: 569
						// Start offset: 0x80048FB4
					/* end block 1.1.1.1.1 */
					// End offset: 0x80048FB4
					// End Line: 569
				/* end block 1.1.1.1 */
				// End offset: 0x80048FB4
				// End Line: 569

				/* begin block 1.1.1.2 */
					// Start line: 569
					// Start offset: 0x80048FB4

					/* begin block 1.1.1.2.1 */
						// Start line: 569
						// Start offset: 0x80048FB4

						/* begin block 1.1.1.2.1.1 */
							// Start line: 569
							// Start offset: 0x80048FB4
						/* end block 1.1.1.2.1.1 */
						// End offset: 0x80048FB4
						// End Line: 569
					/* end block 1.1.1.2.1 */
					// End offset: 0x80048FB4
					// End Line: 569

					/* begin block 1.1.1.2.2 */
						// Start line: 576
						// Start offset: 0x80049010
						// Variables:
					// 		int placeoffset; // $s0
					/* end block 1.1.1.2.2 */
					// End offset: 0x80049084
					// End Line: 593
				/* end block 1.1.1.2 */
				// End offset: 0x80049084
				// End Line: 593

				/* begin block 1.1.1.3 */
					// Start line: 596
					// Start offset: 0x80049084

					/* begin block 1.1.1.3.1 */
						// Start line: 598
						// Start offset: 0x80049094

						/* begin block 1.1.1.3.1.1 */
							// Start line: 598
							// Start offset: 0x80049094
						/* end block 1.1.1.3.1.1 */
						// End offset: 0x80049094
						// End Line: 598
					/* end block 1.1.1.3.1 */
					// End offset: 0x80049094
					// End Line: 598
				/* end block 1.1.1.3 */
				// End offset: 0x800490F4
				// End Line: 608

				/* begin block 1.1.1.4 */
					// Start line: 625
					// Start offset: 0x80049154

					/* begin block 1.1.1.4.1 */
						// Start line: 627
						// Start offset: 0x80049174
						// Variables:
					// 		char buffer[256]; // stack offset -344
					// 		char money[64]; // stack offset -88
					/* end block 1.1.1.4.1 */
					// End offset: 0x80049174
					// End Line: 631
				/* end block 1.1.1.4 */
				// End offset: 0x80049174
				// End Line: 631
			/* end block 1.1.1 */
			// End offset: 0x80049174
			// End Line: 631

			/* begin block 1.1.2 */
				// Start line: 640
				// Start offset: 0x800491DC
				// Variables:
			// 		int yyy; // $s0
			/* end block 1.1.2 */
			// End offset: 0x8004921C
			// End Line: 648
		/* end block 1.1 */
		// End offset: 0x8004921C
		// End Line: 648
	/* end block 1 */
	// End offset: 0x8004921C
	// End Line: 648

void DrawCongratsMessage__23tScreenTournamentTrophy(tScreenTournamentTrophy *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ CalculatePrizes__23tScreenTournamentTrophy(struct tScreenTournamentTrophy *this /*$s2*/)
 // line 654, offset 0x8004923c
	/* begin block 1 */
		// Start line: 655
		// Start offset: 0x8004923C
		// Variables:
	// 		int i; // $s1
	// 		int j; // $s3
	// 		struct tAwardInformation tInfo; // stack offset -104
	// 		struct tTourneyInfo *tourneyInfo; // $s5

		/* begin block 1.1 */
			// Start line: 655
			// Start offset: 0x8004923C

			/* begin block 1.1.1 */
				// Start line: 655
				// Start offset: 0x8004923C
			/* end block 1.1.1 */
			// End offset: 0x8004923C
			// End Line: 655
		/* end block 1.1 */
		// End offset: 0x8004923C
		// End Line: 655

		/* begin block 1.2 */
			// Start line: 655
			// Start offset: 0x8004923C

			/* begin block 1.2.1 */
				// Start line: 655
				// Start offset: 0x8004923C
			/* end block 1.2.1 */
			// End offset: 0x8004923C
			// End Line: 655
		/* end block 1.2 */
		// End offset: 0x8004923C
		// End Line: 655

		/* begin block 1.3 */
			// Start line: 713
			// Start offset: 0x800493C0

			/* begin block 1.3.1 */
				// Start line: 713
				// Start offset: 0x800493C0
			/* end block 1.3.1 */
			// End offset: 0x800493C0
			// End Line: 713
		/* end block 1.3 */
		// End offset: 0x800493C0
		// End Line: 713
	/* end block 1 */
	// End offset: 0x80049458
	// End Line: 732

void CalculatePrizes__23tScreenTournamentTrophy(tScreenTournamentTrophy *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// unsigned int /*$ra*/ GetCar__23tScreenBeTheCopCongratsR8tCarInfo(struct tScreenBeTheCopCongrats *this /*$a0*/, struct tCarInfo *carInfo /*$s1*/)
 // line 746, offset 0x8004947c
	/* begin block 1 */
		// Start line: 747
		// Start offset: 0x8004947C
	/* end block 1 */
	// End offset: 0x8004947C
	// End Line: 747

uint GetCar__23tScreenBeTheCopCongratsR8tCarInfo(tScreenBeTheCopCongrats *this,tCarInfo *carInfo)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ CalculatePrizes__23tScreenBeTheCopCongrats(struct tScreenBeTheCopCongrats *this /*$s0*/)
 // line 756, offset 0x800494dc
	/* begin block 1 */
		// Start line: 757
		// Start offset: 0x800494DC
	/* end block 1 */
	// End offset: 0x800494DC
	// End Line: 757

void CalculatePrizes__23tScreenBeTheCopCongrats(tScreenBeTheCopCongrats *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ DrawCongratsMessage__23tScreenBeTheCopCongrats(struct tScreenBeTheCopCongrats *this /*$s1*/)
 // line 766, offset 0x8004952c
	/* begin block 1 */
		// Start line: 767
		// Start offset: 0x8004952C
		// Variables:
	// 		short congrats; // $s0
	// 		struct RECT r; // stack offset -280
	// 		char buffer[250]; // stack offset -272
	/* end block 1 */
	// End offset: 0x80049594
	// End Line: 783

void DrawCongratsMessage__23tScreenBeTheCopCongrats(tScreenBeTheCopCongrats *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// unsigned int /*$ra*/ GetCar__25tScreenTournamentCongratsR8tCarInfo(struct tScreenTournamentCongrats *this /*$a0*/, struct tCarInfo *carInfo /*$s0*/)
 // line 796, offset 0x800495e8
	/* begin block 1 */
		// Start line: 797
		// Start offset: 0x800495E8
		// Variables:
	// 		struct tAwardInformation tInfo; // stack offset -80
	/* end block 1 */
	// End offset: 0x800495E8
	// End Line: 797

uint GetCar__25tScreenTournamentCongratsR8tCarInfo( (tScreenTournamentCongrats *this,tCarInfo *carInfo)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ CalculatePrizes__25tScreenTournamentCongrats(struct tScreenTournamentCongrats *this /*$s1*/)
 // line 807, offset 0x8004963c
	/* begin block 1 */
		// Start line: 808
		// Start offset: 0x8004963C
		// Variables:
	// 		struct tAwardInformation tInfo; // stack offset -88

		/* begin block 1.1 */
			// Start line: 808
			// Start offset: 0x8004963C

			/* begin block 1.1.1 */
				// Start line: 808
				// Start offset: 0x8004963C
			/* end block 1.1.1 */
			// End offset: 0x8004963C
			// End Line: 808
		/* end block 1.1 */
		// End offset: 0x8004963C
		// End Line: 808
	/* end block 1 */
	// End offset: 0x80049694
	// End Line: 818

void CalculatePrizes__25tScreenTournamentCongrats(tScreenTournamentCongrats *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ DrawCongratsMessage__25tScreenTournamentCongrats(struct tScreenTournamentCongrats *this /*$a0*/)
 // line 825, offset 0x800496d4
	/* begin block 1 */
		// Start line: 826
		// Start offset: 0x800496D4
		// Variables:
	// 		struct RECT r; // stack offset -408
	// 		struct tAwardInformation tInfo; // stack offset -400

		/* begin block 1.1 */
			// Start line: 826
			// Start offset: 0x800496D4

			/* begin block 1.1.1 */
				// Start line: 839
				// Start offset: 0x80049740
				// Variables:
			// 		char buffer[256]; // stack offset -328
			// 		char money[64]; // stack offset -72
			/* end block 1.1.1 */
			// End offset: 0x80049790
			// End Line: 847
		/* end block 1.1 */
		// End offset: 0x80049790
		// End Line: 847
	/* end block 1 */
	// End offset: 0x80049790
	// End Line: 847

void DrawCongratsMessage__25tScreenTournamentCongrats(tScreenTournamentCongrats *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}





