#include "NFS4.H"
#include "SCREENTROPHYROOM.H"

// decompiled code
// original method signature: 
// struct tScreenTrophyRoom * /*$ra*/ __17tScreenTrophyRoom(struct tScreenTrophyRoom *this /*$s0*/)
 // line 40, offset 0x80040570
	/* begin block 1 */
		// Start line: 41
		// Start offset: 0x80040570
	/* end block 1 */
	// End offset: 0x80040570
	// End Line: 41

/* WARNING: Control flow encountered bad instruction data */

tScreenTrophyRoom * __17tScreenTrophyRoom(tScreenTrophyRoom *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ _._17tScreenTrophyRoom(struct tScreenTrophyRoom *this /*$a0*/, int __in_chrg /*$a1*/)
 // line 48, offset 0x800405b0
	/* begin block 1 */
		// Start line: 49
		// Start offset: 0x800405B0
	/* end block 1 */
	// End offset: 0x800405B0
	// End Line: 49

/* WARNING: Control flow encountered bad instruction data */

void ___17tScreenTrophyRoom(tScreenTrophyRoom *this,int __in_chrg)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ GetShapeInfo__17tScreenTrophyRoomRsT1PPcT3(struct tScreenTrophyRoom *this /*$a0*/, short *numPermShapes /*$a1*/, short *numSwapShapes /*$a2*/, char **permFileName /*$s1*/, char **swapFileName /*stack 16*/)
 // line 54, offset 0x800405d8
	/* begin block 1 */
		// Start line: 55
		// Start offset: 0x800405D8

		/* begin block 1.1 */
			// Start line: 55
			// Start offset: 0x800405D8

			/* begin block 1.1.1 */
				// Start line: 55
				// Start offset: 0x800405D8
			/* end block 1.1.1 */
			// End offset: 0x800405D8
			// End Line: 55
		/* end block 1.1 */
		// End offset: 0x800405D8
		// End Line: 55
	/* end block 1 */
	// End offset: 0x800405D8
	// End Line: 55

/* WARNING: Control flow encountered bad instruction data */

void GetShapeInfo__17tScreenTrophyRoomRsT1PPcT3
               (tScreenTrophyRoom *this,short *numPermShapes,short *numSwapShapes,
               char **permFileName,char **swapFileName)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ ProcessInput__17tScreenTrophyRoom7tPlayerR13tInputKeyTypeR12tMenuCommand(struct tScreenTrophyRoom *this /*$s0*/, enum tPlayer fromPlayer /*$s3*/, enum tInputKeyType *keyval /*$s1*/, struct tMenuCommand *command /*$s2*/)
 // line 67, offset 0x80040698
	/* begin block 1 */
		// Start line: 68
		// Start offset: 0x80040698
	/* end block 1 */
	// End offset: 0x80040878
	// End Line: 100

/* WARNING: Control flow encountered bad instruction data */

void ProcessInput__17tScreenTrophyRoom7tPlayerR13tInputKeyTypeR12tMenuCommand
               (tScreenTrophyRoom *this,tPlayer fromPlayer,tInputKeyType *keyval,
               tMenuCommand *command)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ PreLoad__17tScreenTrophyRoom(struct tScreenTrophyRoom *this /*$s0*/)
 // line 103, offset 0x800408a8
	/* begin block 1 */
		// Start line: 104
		// Start offset: 0x800408A8
	/* end block 1 */
	// End offset: 0x800408F4
	// End Line: 112

/* WARNING: Control flow encountered bad instruction data */

void PreLoad__17tScreenTrophyRoom(tScreenTrophyRoom *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Initialize__17tScreenTrophyRoom(struct tScreenTrophyRoom *this /*$s0*/)
 // line 115, offset 0x80040910
	/* begin block 1 */
		// Start line: 116
		// Start offset: 0x80040910
		// Variables:
	// 		short i; // $s1

		/* begin block 1.1 */
			// Start line: 128
			// Start offset: 0x80040974

			/* begin block 1.1.1 */
				// Start line: 131
				// Start offset: 0x80040990

				/* begin block 1.1.1.1 */
					// Start line: 133
					// Start offset: 0x800409A8

					/* begin block 1.1.1.1.1 */
						// Start line: 133
						// Start offset: 0x800409A8
					/* end block 1.1.1.1.1 */
					// End offset: 0x800409A8
					// End Line: 133
				/* end block 1.1.1.1 */
				// End offset: 0x800409A8
				// End Line: 133

				/* begin block 1.1.1.2 */
					// Start line: 133
					// Start offset: 0x800409A8

					/* begin block 1.1.1.2.1 */
						// Start line: 133
						// Start offset: 0x800409A8
					/* end block 1.1.1.2.1 */
					// End offset: 0x800409A8
					// End Line: 133
				/* end block 1.1.1.2 */
				// End offset: 0x800409A8
				// End Line: 133
			/* end block 1.1.1 */
			// End offset: 0x80040A18
			// End Line: 141
		/* end block 1.1 */
		// End offset: 0x80040A50
		// End Line: 142

		/* begin block 1.2 */
			// Start line: 150
			// Start offset: 0x80040A9C

			/* begin block 1.2.1 */
				// Start line: 150
				// Start offset: 0x80040A9C
			/* end block 1.2.1 */
			// End offset: 0x80040A9C
			// End Line: 150
		/* end block 1.2 */
		// End offset: 0x80040A9C
		// End Line: 150
	/* end block 1 */
	// End offset: 0x80040A9C
	// End Line: 150

/* WARNING: Control flow encountered bad instruction data */

void Initialize__17tScreenTrophyRoom(tScreenTrophyRoom *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Cleanup__17tScreenTrophyRoom(struct tScreenTrophyRoom *this /*$s0*/)
 // line 157, offset 0x80040ae8
	/* begin block 1 */
		// Start line: 158
		// Start offset: 0x80040AE8
	/* end block 1 */
	// End offset: 0x80040AE8
	// End Line: 158

/* WARNING: Control flow encountered bad instruction data */

void Cleanup__17tScreenTrophyRoom(tScreenTrophyRoom *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ DrawBackground__17tScreenTrophyRoom(struct tScreenTrophyRoom *this /*$s2*/)
 // line 171, offset 0x80040b18
	/* begin block 1 */
		// Start line: 172
		// Start offset: 0x80040B18
		// Variables:
	// 		struct tDrawShapeExtended drawFlags3; // stack offset -80
	// 		int fModNumber; // $s3
	// 		int TROPHY_LEFTOFFSET; // $s5
	// 		struct tDrawShapeExtended drawFlags; // stack offset -56
	// 		short i; // $s1
	// 		short x; // $a2
	// 		short y; // $a3
	// 		int texttoshow; // $a0

		/* begin block 1.1 */
			// Start line: 172
			// Start offset: 0x80040B18

			/* begin block 1.1.1 */
				// Start line: 172
				// Start offset: 0x80040B18
			/* end block 1.1.1 */
			// End offset: 0x80040B18
			// End Line: 172
		/* end block 1.1 */
		// End offset: 0x80040B18
		// End Line: 172

		/* begin block 1.2 */
			// Start line: 179
			// Start offset: 0x80040BC0

			/* begin block 1.2.1 */
				// Start line: 193
				// Start offset: 0x80040C54

				/* begin block 1.2.1.1 */
					// Start line: 194
					// Start offset: 0x80040C54

					/* begin block 1.2.1.1.1 */
						// Start line: 194
						// Start offset: 0x80040C54
					/* end block 1.2.1.1.1 */
					// End offset: 0x80040C54
					// End Line: 194
				/* end block 1.2.1.1 */
				// End offset: 0x80040C54
				// End Line: 194
			/* end block 1.2.1 */
			// End offset: 0x80040C6C
			// End Line: 195
		/* end block 1.2 */
		// End offset: 0x80040C6C
		// End Line: 195

		/* begin block 1.3 */
			// Start line: 198
			// Start offset: 0x80040C6C

			/* begin block 1.3.1 */
				// Start line: 198
				// Start offset: 0x80040C6C
			/* end block 1.3.1 */
			// End offset: 0x80040C6C
			// End Line: 198
		/* end block 1.3 */
		// End offset: 0x80040C6C
		// End Line: 198

		/* begin block 1.4 */
			// Start line: 213
			// Start offset: 0x80040D88

			/* begin block 1.4.1 */
				// Start line: 216
				// Start offset: 0x80040DC8

				/* begin block 1.4.1.1 */
					// Start line: 218
					// Start offset: 0x80040DE0

					/* begin block 1.4.1.1.1 */
						// Start line: 221
						// Start offset: 0x80040E6C

						/* begin block 1.4.1.1.1.1 */
							// Start line: 222
							// Start offset: 0x80040E6C

							/* begin block 1.4.1.1.1.1.1 */
								// Start line: 222
								// Start offset: 0x80040E6C
							/* end block 1.4.1.1.1.1.1 */
							// End offset: 0x80040E6C
							// End Line: 222
						/* end block 1.4.1.1.1.1 */
						// End offset: 0x80040E6C
						// End Line: 222
					/* end block 1.4.1.1.1 */
					// End offset: 0x80040EAC
					// End Line: 225
				/* end block 1.4.1.1 */
				// End offset: 0x80040F00
				// End Line: 231
			/* end block 1.4.1 */
			// End offset: 0x80040F00
			// End Line: 231
		/* end block 1.4 */
		// End offset: 0x80040F08
		// End Line: 235
	/* end block 1 */
	// End offset: 0x80040F08
	// End Line: 235

/* WARNING: Control flow encountered bad instruction data */

void DrawBackground__17tScreenTrophyRoom(tScreenTrophyRoom *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ LoadTrophy__17tScreenTrophyRoom(struct tScreenTrophyRoom *this /*$s1*/)
 // line 240, offset 0x80040f2c
	/* begin block 1 */
		// Start line: 241
		// Start offset: 0x80040F2C

		/* begin block 1.1 */
			// Start line: 241
			// Start offset: 0x80040F2C

			/* begin block 1.1.1 */
				// Start line: 245
				// Start offset: 0x80040F64

				/* begin block 1.1.1.1 */
					// Start line: 246
					// Start offset: 0x80040F64

					/* begin block 1.1.1.1.1 */
						// Start line: 246
						// Start offset: 0x80040F64
					/* end block 1.1.1.1.1 */
					// End offset: 0x80040F64
					// End Line: 246
				/* end block 1.1.1.1 */
				// End offset: 0x80040F64
				// End Line: 246
			/* end block 1.1.1 */
			// End offset: 0x80040FF0
			// End Line: 249
		/* end block 1.1 */
		// End offset: 0x80040FF0
		// End Line: 249
	/* end block 1 */
	// End offset: 0x80040FF0
	// End Line: 249

/* WARNING: Control flow encountered bad instruction data */

void LoadTrophy__17tScreenTrophyRoom(tScreenTrophyRoom *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}




