#include "NFS4.H"
#include "SCREENTRACKRECORDS.H"

// decompiled code
// original method signature: 
// void /*$ra*/ GetShapeInfo__19tScreenTrackRecordsRsT1PPcT3(struct tScreenTrackRecords *this /*$a0*/, short *numPermShapes /*$a1*/, short *numSwapShapes /*$a2*/, char **permFileName /*$a3*/, char **swapFileName /*stack 16*/)
 // line 67, offset 0x80042648
	/* begin block 1 */
		// Start line: 68
		// Start offset: 0x80042648
	/* end block 1 */
	// End offset: 0x80042648
	// End Line: 68

void GetShapeInfo__19tScreenTrackRecordsRsT1PPcT3( (tScreenTrackRecords *this,short *numPermShapes,short *numSwapShapes, char **permFileName,char **swapFileName)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ Initialize__19tScreenTrackRecords(struct tScreenTrackRecords *this /*$s0*/)
 // line 78, offset 0x8004266c
	/* begin block 1 */
		// Start line: 79
		// Start offset: 0x8004266C
	/* end block 1 */
	// End offset: 0x8004266C
	// End Line: 79

void Initialize__19tScreenTrackRecords(tScreenTrackRecords *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ Cleanup__19tScreenTrackRecords(struct tScreenTrackRecords *this /*$s0*/)
 // line 97, offset 0x800426c4
	/* begin block 1 */
		// Start line: 98
		// Start offset: 0x800426C4
	/* end block 1 */
	// End offset: 0x800426C4
	// End Line: 98

void Cleanup__19tScreenTrackRecords(tScreenTrackRecords *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ DrawOneRecord__19tScreenTrackRecordsibi(struct tScreenTrackRecords *this /*$s4*/, int index /*$s2*/, unsigned int newrecord /*$s6*/, int y /*$s5*/)
 // line 113, offset 0x80042700
	/* begin block 1 */
		// Start line: 114
		// Start offset: 0x80042700
		// Variables:
	// 		char sBuildOutput[80]; // stack offset -112
	// 		enum tMenuTextState textState; // $s3
	/* end block 1 */
	// End offset: 0x80042940
	// End Line: 156

void DrawOneRecord__19tScreenTrackRecordsibi( (tScreenTrackRecords *this,int index,uint newrecord,int y)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ DrawRecords__19tScreenTrackRecordss(struct tScreenTrackRecords *this /*$s4*/, short maxitem /*$fp*/)
 // line 161, offset 0x80042968
	/* begin block 1 */
		// Start line: 162
		// Start offset: 0x80042968
		// Variables:
	// 		short nLapIndicator; // $a0
	// 		short k; // $s2
	/* end block 1 */
	// End offset: 0x80042B18
	// End Line: 200

void DrawRecords__19tScreenTrackRecordss(tScreenTrackRecords *this,short maxitem)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}




// decompiled code
// original method signature: 
// void /*$ra*/ DrawBackground__19tScreenTrackRecords(struct tScreenTrackRecords *this /*stack 0*/)
 // line 210, offset 0x80042b48
	/* begin block 1 */
		// Start line: 211
		// Start offset: 0x80042B48
		// Variables:
	// 		char string[50]; // stack offset -232
	// 		char string2[50]; // stack offset -176
	// 		int fade; // $v1
	// 		short linefadeval; // stack offset -96
	// 		short maxitem; // stack offset -88
	// 		short boxx; // stack offset -80
	// 		short boxy; // stack offset -72
	// 		short boxw; // stack offset -64
	// 		short midy; // stack offset -56
	// 		short j; // $s1
	// 		int Col; // $s6
	// 		int ColTextSel; // $fp
	// 		int ColTextBright; // $s2
	// 		struct tTexture_ShapeInfo *shape; // $a0
	// 		int lbx; // $s3
	// 		int tt; // $s2
	// 		struct tDrawShapeExtended drawflags; // stack offset -120

		/* begin block 1.1 */
			// Start line: 220
			// Start offset: 0x80042C24

			/* begin block 1.1.1 */
				// Start line: 220
				// Start offset: 0x80042C24
			/* end block 1.1.1 */
			// End offset: 0x80042C24
			// End Line: 220
		/* end block 1.1 */
		// End offset: 0x80042C24
		// End Line: 220

		/* begin block 1.2 */
			// Start line: 220
			// Start offset: 0x80042C24

			/* begin block 1.2.1 */
				// Start line: 220
				// Start offset: 0x80042C24
			/* end block 1.2.1 */
			// End offset: 0x80042C24
			// End Line: 220
		/* end block 1.2 */
		// End offset: 0x80042C24
		// End Line: 220

		/* begin block 1.3 */
			// Start line: 220
			// Start offset: 0x80042C24

			/* begin block 1.3.1 */
				// Start line: 220
				// Start offset: 0x80042C24
			/* end block 1.3.1 */
			// End offset: 0x80042C24
			// End Line: 220
		/* end block 1.3 */
		// End offset: 0x80042C24
		// End Line: 220

		/* begin block 1.4 */
			// Start line: 259
			// Start offset: 0x80042E38

			/* begin block 1.4.1 */
				// Start line: 268
				// Start offset: 0x80042EFC
				// Variables:
			// 		int xx; // $s0
			/* end block 1.4.1 */
			// End offset: 0x80042F7C
			// End Line: 275
		/* end block 1.4 */
		// End offset: 0x80042F84
		// End Line: 276
	/* end block 1 */
	// End offset: 0x800430AC
	// End Line: 291

void DrawBackground__19tScreenTrackRecords(tScreenTrackRecords *this)
{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    
  halt_baddata();


}





