#ifndef SCREENUSERNAME_H
#define SCREENUSERNAME_H

extern void _._15tScreenUserName(struct tScreenUserName *this, int __in_chrg); // 0x8004B7D4


// decompiled code
// original method signature: 
// void /*$ra*/ _._15tScreenUserName(struct tScreenUserName *this /*$a0*/, int __in_chrg /*$a1*/)
 // line 97, offset 0x8004b7d4
/* WARNING: Control flow encountered bad instruction data */

void ___15tScreenUserName(tScreenUserName *this,int __in_chrg)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}




#endif
