#include "NFS4.H"
#include "SCREENTOURNSELECT.H"

// decompiled code
// original method signature: 
// struct tScreenTournSelect * /*$ra*/ __18tScreenTournSelect(struct tScreenTournSelect *this /*$s0*/)
 // line 64, offset 0x8003f778
	/* begin block 1 */
		// Start line: 65
		// Start offset: 0x8003F778
	/* end block 1 */
	// End offset: 0x8003F778
	// End Line: 65

/* WARNING: Control flow encountered bad instruction data */

tScreenTournSelect * __18tScreenTournSelect(tScreenTournSelect *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ _._18tScreenTournSelect(struct tScreenTournSelect *this /*$a0*/, int __in_chrg /*$a1*/)
 // line 68, offset 0x8003f7ac
	/* begin block 1 */
		// Start line: 69
		// Start offset: 0x8003F7AC
	/* end block 1 */
	// End offset: 0x8003F7AC
	// End Line: 69

/* WARNING: Control flow encountered bad instruction data */

void ___18tScreenTournSelect(tScreenTournSelect *this,int __in_chrg)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ GetShapeInfo__18tScreenTournSelectRsT1PPcT3(struct tScreenTournSelect *this /*$a0*/, short *numPermShapes /*$a1*/, short *numSwapShapes /*$t1*/, char **permFileName /*$a3*/, char **swapFileName /*stack 16*/)
 // line 78, offset 0x8003f7d4
	/* begin block 1 */
		// Start line: 79
		// Start offset: 0x8003F7D4

		/* begin block 1.1 */
			// Start line: 80
			// Start offset: 0x8003F808

			/* begin block 1.1.1 */
				// Start line: 80
				// Start offset: 0x8003F808
			/* end block 1.1.1 */
			// End offset: 0x8003F808
			// End Line: 80
		/* end block 1.1 */
		// End offset: 0x8003F808
		// End Line: 80
	/* end block 1 */
	// End offset: 0x8003F808
	// End Line: 80

/* WARNING: Control flow encountered bad instruction data */

void GetShapeInfo__18tScreenTournSelectRsT1PPcT3
               (tScreenTournSelect *this,short *numPermShapes,short *numSwapShapes,
               char **permFileName,char **swapFileName)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Initialize__18tScreenTournSelect(struct tScreenTournSelect *this /*$s3*/)
 // line 91, offset 0x8003f8a0
	/* begin block 1 */
		// Start line: 92
		// Start offset: 0x8003F8A0
		// Variables:
	// 		short i; // $s5
	// 		short j; // $s2
	// 		struct RECT r; // stack offset -120
	// 		char moviename[80]; // stack offset -112

		/* begin block 1.1 */
			// Start line: 137
			// Start offset: 0x8003FA64

			/* begin block 1.1.1 */
				// Start line: 137
				// Start offset: 0x8003FA64
			/* end block 1.1.1 */
			// End offset: 0x8003FA64
			// End Line: 137
		/* end block 1.1 */
		// End offset: 0x8003FA64
		// End Line: 137

		/* begin block 1.2 */
			// Start line: 137
			// Start offset: 0x8003FA64

			/* begin block 1.2.1 */
				// Start line: 137
				// Start offset: 0x8003FA64
			/* end block 1.2.1 */
			// End offset: 0x8003FA64
			// End Line: 137
		/* end block 1.2 */
		// End offset: 0x8003FA64
		// End Line: 137
	/* end block 1 */
	// End offset: 0x8003FA64
	// End Line: 137

/* WARNING: Control flow encountered bad instruction data */

void Initialize__18tScreenTournSelect(tScreenTournSelect *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Cleanup__18tScreenTournSelect(struct tScreenTournSelect *this /*$s0*/)
 // line 143, offset 0x8003fae8
	/* begin block 1 */
		// Start line: 144
		// Start offset: 0x8003FAE8
	/* end block 1 */
	// End offset: 0x8003FAE8
	// End Line: 144

/* WARNING: Control flow encountered bad instruction data */

void Cleanup__18tScreenTournSelect(tScreenTournSelect *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ UpdateVideoWall__18tScreenTournSelectP12tTourneyInfo(struct tScreenTournSelect *this /*$s1*/, struct tTourneyInfo *tourn /*$s2*/)
 // line 156, offset 0x8003fb28
	/* begin block 1 */
		// Start line: 157
		// Start offset: 0x8003FB28

		/* begin block 1.1 */
			// Start line: 157
			// Start offset: 0x8003FB28

			/* begin block 1.1.1 */
				// Start line: 159
				// Start offset: 0x8003FB5C

				/* begin block 1.1.1.1 */
					// Start line: 160
					// Start offset: 0x8003FB5C

					/* begin block 1.1.1.1.1 */
						// Start line: 166
						// Start offset: 0x8003FBA0

						/* begin block 1.1.1.1.1.1 */
							// Start line: 166
							// Start offset: 0x8003FBA0

							/* begin block 1.1.1.1.1.1.1 */
								// Start line: 166
								// Start offset: 0x8003FBA0
							/* end block 1.1.1.1.1.1.1 */
							// End offset: 0x8003FBA0
							// End Line: 166
						/* end block 1.1.1.1.1.1 */
						// End offset: 0x8003FBA0
						// End Line: 166
					/* end block 1.1.1.1.1 */
					// End offset: 0x8003FBB0
					// End Line: 168
				/* end block 1.1.1.1 */
				// End offset: 0x8003FBB0
				// End Line: 168
			/* end block 1.1.1 */
			// End offset: 0x8003FBB0
			// End Line: 168
		/* end block 1.1 */
		// End offset: 0x8003FBB0
		// End Line: 168
	/* end block 1 */
	// End offset: 0x8003FBB0
	// End Line: 168

/* WARNING: Control flow encountered bad instruction data */

void UpdateVideoWall__18tScreenTournSelectP12tTourneyInfo
               (tScreenTournSelect *this,tTourneyInfo *tourn)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ DrawVideoWall__18tScreenTournSelect(struct tScreenTournSelect *this /*$s2*/)
 // line 173, offset 0x8003fbcc
	/* begin block 1 */
		// Start line: 174
		// Start offset: 0x8003FBCC
		// Variables:
	// 		long i; // $s1
	// 		long j; // $s0
	// 		struct tDrawShapeExtended drawFlags; // stack offset -48

		/* begin block 1.1 */
			// Start line: 190
			// Start offset: 0x8003FC7C

			/* begin block 1.1.1 */
				// Start line: 190
				// Start offset: 0x8003FC7C
			/* end block 1.1.1 */
			// End offset: 0x8003FC7C
			// End Line: 190
		/* end block 1.1 */
		// End offset: 0x8003FC7C
		// End Line: 190

		/* begin block 1.2 */
			// Start line: 225
			// Start offset: 0x8003FDF4

			/* begin block 1.2.1 */
				// Start line: 225
				// Start offset: 0x8003FDF4
			/* end block 1.2.1 */
			// End offset: 0x8003FDF4
			// End Line: 225
		/* end block 1.2 */
		// End offset: 0x8003FDF4
		// End Line: 225
	/* end block 1 */
	// End offset: 0x8003FE10
	// End Line: 230

/* WARNING: Control flow encountered bad instruction data */

void DrawVideoWall__18tScreenTournSelect(tScreenTournSelect *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ DrawBackground__18tScreenTournSelect(struct tScreenTournSelect *this /*$s4*/)
 // line 239, offset 0x8003fe5c
	/* begin block 1 */
		// Start line: 240
		// Start offset: 0x8003FE5C
		// Variables:
	// 		short y; // $s3
	// 		char buffer[64]; // stack offset -208
	// 		short i; // $s2
	// 		short j; // $s1
	// 		struct RECT r; // stack offset -144
	// 		struct tTourneyInfo *tourn; // $s7
	// 		int YellowCol; // $s6
	// 		int DarkGreyCol; // $s5
	// 		int GreyCol; // $fp
	// 		short shapeY; // $t0
	// 		unsigned long movieRGB; // stack offset -56

		/* begin block 1.1 */
			// Start line: 248
			// Start offset: 0x8003FEB0

			/* begin block 1.1.1 */
				// Start line: 248
				// Start offset: 0x8003FEB0
			/* end block 1.1.1 */
			// End offset: 0x8003FEB0
			// End Line: 248
		/* end block 1.1 */
		// End offset: 0x8003FEB0
		// End Line: 248

		/* begin block 1.2 */
			// Start line: 248
			// Start offset: 0x8003FEB0

			/* begin block 1.2.1 */
				// Start line: 248
				// Start offset: 0x8003FEB0
			/* end block 1.2.1 */
			// End offset: 0x8003FEB0
			// End Line: 248
		/* end block 1.2 */
		// End offset: 0x8003FEB0
		// End Line: 248

		/* begin block 1.3 */
			// Start line: 277
			// Start offset: 0x8004006C

			/* begin block 1.3.1 */
				// Start line: 280
				// Start offset: 0x800400A4

				/* begin block 1.3.1.1 */
					// Start line: 281
					// Start offset: 0x800400A4

					/* begin block 1.3.1.1.1 */
						// Start line: 281
						// Start offset: 0x800400A4
					/* end block 1.3.1.1.1 */
					// End offset: 0x800400A4
					// End Line: 281
				/* end block 1.3.1.1 */
				// End offset: 0x800400A4
				// End Line: 281
			/* end block 1.3.1 */
			// End offset: 0x800400C0
			// End Line: 283
		/* end block 1.3 */
		// End offset: 0x800400C0
		// End Line: 283

		/* begin block 1.4 */
			// Start line: 323
			// Start offset: 0x80040214

			/* begin block 1.4.1 */
				// Start line: 332
				// Start offset: 0x80040254
				// Variables:
			// 		char moviename[80]; // stack offset -136
			/* end block 1.4.1 */
			// End offset: 0x80040288
			// End Line: 337
		/* end block 1.4 */
		// End offset: 0x80040288
		// End Line: 337
	/* end block 1 */
	// End offset: 0x800404A8
	// End Line: 381

/* WARNING: Control flow encountered bad instruction data */

void DrawBackground__18tScreenTournSelect(tScreenTournSelect *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ DrawForeground__18tScreenTournSelect(struct tScreenTournSelect *this /*$s2*/)
 // line 387, offset 0x800404d8
	/* begin block 1 */
		// Start line: 388
		// Start offset: 0x800404D8
	/* end block 1 */
	// End offset: 0x800404D8
	// End Line: 388

/* WARNING: Control flow encountered bad instruction data */

void DrawForeground__18tScreenTournSelect(tScreenTournSelect *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}




