#include "NFS4.H"
#include "SCREENAUDIO.H"

// decompiled code
// original method signature: 
// void /*$ra*/ PlaySound__12tScreenAudio(struct tScreenAudio *this /*$s1*/)
 // line 39, offset 0x80045a28
	/* begin block 1 */
		// Start line: 40
		// Start offset: 0x80045A28

		/* begin block 1.1 */
			// Start line: 40
			// Start offset: 0x80045A28

			/* begin block 1.1.1 */
				// Start line: 40
				// Start offset: 0x80045A28

				/* begin block 1.1.1.1 */
					// Start line: 40
					// Start offset: 0x80045A28
				/* end block 1.1.1.1 */
				// End offset: 0x80045A28
				// End Line: 40
			/* end block 1.1.1 */
			// End offset: 0x80045A28
			// End Line: 40
		/* end block 1.1 */
		// End offset: 0x80045AA0
		// End Line: 51

		/* begin block 1.2 */
			// Start line: 63
			// Start offset: 0x80045AA0

			/* begin block 1.2.1 */
				// Start line: 69
				// Start offset: 0x80045AE8
				// Variables:
			// 		struct SNDSYSOPTS opts; // stack offset -88
			/* end block 1.2.1 */
			// End offset: 0x80045B64
			// End Line: 100
		/* end block 1.2 */
		// End offset: 0x80045B64
		// End Line: 100

		/* begin block 1.3 */
			// Start line: 105
			// Start offset: 0x80045B64

			/* begin block 1.3.1 */
				// Start line: 105
				// Start offset: 0x80045B64

				/* begin block 1.3.1.1 */
					// Start line: 105
					// Start offset: 0x80045B64
				/* end block 1.3.1.1 */
				// End offset: 0x80045B64
				// End Line: 105
			/* end block 1.3.1 */
			// End offset: 0x80045B64
			// End Line: 105

			/* begin block 1.3.2 */
				// Start line: 105
				// Start offset: 0x80045B80

				/* begin block 1.3.2.1 */
					// Start line: 105
					// Start offset: 0x80045B80
				/* end block 1.3.2.1 */
				// End offset: 0x80045B80
				// End Line: 105
			/* end block 1.3.2 */
			// End offset: 0x80045B80
			// End Line: 105

			/* begin block 1.3.3 */
				// Start line: 106
				// Start offset: 0x80045B8C
				// Variables:
			// 		int sndover; // $s3
			// 		int vol; // $s2
			// 		int RepresentativeSound; // $s0

				/* begin block 1.3.3.1 */
					// Start line: 107
					// Start offset: 0x80045B8C

					/* begin block 1.3.3.1.1 */
						// Start line: 132
						// Start offset: 0x80045C3C

						/* begin block 1.3.3.1.1.1 */
							// Start line: 132
							// Start offset: 0x80045C3C
						/* end block 1.3.3.1.1.1 */
						// End offset: 0x80045C3C
						// End Line: 132
					/* end block 1.3.3.1.1 */
					// End offset: 0x80045C3C
					// End Line: 132
				/* end block 1.3.3.1 */
				// End offset: 0x80045C3C
				// End Line: 132

				/* begin block 1.3.3.2 */
					// Start line: 142
					// Start offset: 0x80045C7C

					/* begin block 1.3.3.2.1 */
						// Start line: 142
						// Start offset: 0x80045C84

						/* begin block 1.3.3.2.1.1 */
							// Start line: 142
							// Start offset: 0x80045C84
						/* end block 1.3.3.2.1.1 */
						// End offset: 0x80045C84
						// End Line: 142
					/* end block 1.3.3.2.1 */
					// End offset: 0x80045C84
					// End Line: 142

					/* begin block 1.3.3.2.2 */
						// Start line: 143
						// Start offset: 0x80045C9C
						// Variables:
					// 		int azimuth; // $a2
					/* end block 1.3.3.2.2 */
					// End offset: 0x80045D6C
					// End Line: 178
				/* end block 1.3.3.2 */
				// End offset: 0x80045D6C
				// End Line: 178
			/* end block 1.3.3 */
			// End offset: 0x80045D6C
			// End Line: 184
		/* end block 1.3 */
		// End offset: 0x80045DA8
		// End Line: 192
	/* end block 1 */
	// End offset: 0x80045DA8
	// End Line: 192

/* WARNING: Control flow encountered bad instruction data */

void PlaySound__12tScreenAudio(tScreenAudio *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ DrawForeground__12tScreenAudio(struct tScreenAudio *this /*$a0*/)
 // line 195, offset 0x80045dc8
	/* begin block 1 */
		// Start line: 196
		// Start offset: 0x80045DC8
		// Variables:
	// 		short fade; // $s2

		/* begin block 1.1 */
			// Start line: 196
			// Start offset: 0x80045DC8

			/* begin block 1.1.1 */
				// Start line: 196
				// Start offset: 0x80045DC8
			/* end block 1.1.1 */
			// End offset: 0x80045DC8
			// End Line: 196
		/* end block 1.1 */
		// End offset: 0x80045DC8
		// End Line: 196

		/* begin block 1.2 */
			// Start line: 198
			// Start offset: 0x80045E20
			// Variables:
		// 		int i; // $s0
		/* end block 1.2 */
		// End offset: 0x80045E5C
		// End Line: 203
	/* end block 1 */
	// End offset: 0x80045EC0
	// End Line: 213

/* WARNING: Control flow encountered bad instruction data */

void DrawForeground__12tScreenAudio(tScreenAudio *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ DrawBackground__12tScreenAudio(struct tScreenAudio *this /*$a0*/)
 // line 220, offset 0x80045ed8
	/* begin block 1 */
		// Start line: 221
		// Start offset: 0x80045ED8
		// Variables:
	// 		static int lastpercentage; // offset 0x0
	// 		static int perfade; // offset 0x4
	// 		short fade; // $s3
	// 		int percent; // $s0

		/* begin block 1.1 */
			// Start line: 221
			// Start offset: 0x80045ED8
			// Variables:
		// 		struct tOptionsMenu *this; // $v1

			/* begin block 1.1.1 */
				// Start line: 221
				// Start offset: 0x80045ED8
			/* end block 1.1.1 */
			// End offset: 0x80045ED8
			// End Line: 221
		/* end block 1.1 */
		// End offset: 0x80045ED8
		// End Line: 221

		/* begin block 1.2 */
			// Start line: 234
			// Start offset: 0x80045F2C

			/* begin block 1.2.1 */
				// Start line: 252
				// Start offset: 0x80045FBC

				/* begin block 1.2.1.1 */
					// Start line: 252
					// Start offset: 0x80045FBC
				/* end block 1.2.1.1 */
				// End offset: 0x80045FBC
				// End Line: 252
			/* end block 1.2.1 */
			// End offset: 0x80045FBC
			// End Line: 252
		/* end block 1.2 */
		// End offset: 0x80045FBC
		// End Line: 252

		/* begin block 1.3 */
			// Start line: 256
			// Start offset: 0x80045FC4

			/* begin block 1.3.1 */
				// Start line: 259
				// Start offset: 0x80045FDC
				// Variables:
			// 		int ColText; // $s2
			// 		char sBuildOutput[255]; // stack offset -280

				/* begin block 1.3.1.1 */
					// Start line: 264
					// Start offset: 0x80046048

					/* begin block 1.3.1.1.1 */
						// Start line: 264
						// Start offset: 0x80046048
					/* end block 1.3.1.1.1 */
					// End offset: 0x80046048
					// End Line: 264
				/* end block 1.3.1.1 */
				// End offset: 0x80046048
				// End Line: 264
			/* end block 1.3.1 */
			// End offset: 0x800460E8
			// End Line: 275
		/* end block 1.3 */
		// End offset: 0x800460E8
		// End Line: 275

		/* begin block 1.4 */
			// Start line: 279
			// Start offset: 0x800460E8
			// Variables:
		// 		int i; // $s0
		/* end block 1.4 */
		// End offset: 0x80046124
		// End Line: 282
	/* end block 1 */
	// End offset: 0x80046124
	// End Line: 282

/* WARNING: Control flow encountered bad instruction data */

void DrawBackground__12tScreenAudio(tScreenAudio *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ GetShapeInfo__12tScreenAudioRsT1PPcT3(struct tScreenAudio *this /*$a0*/, short *numPermShapes /*$a1*/, short *numSwapShapes /*$a2*/, char **permFileName /*$a3*/, char **swapFileName /*stack 16*/)
 // line 288, offset 0x80046140
	/* begin block 1 */
		// Start line: 289
		// Start offset: 0x80046140
	/* end block 1 */
	// End offset: 0x80046140
	// End Line: 289

/* WARNING: Control flow encountered bad instruction data */

void GetShapeInfo__12tScreenAudioRsT1PPcT3
               (tScreenAudio *this,short *numPermShapes,short *numSwapShapes,char **permFileName,
               char **swapFileName)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// struct tScreenAudio * /*$ra*/ __12tScreenAudio(struct tScreenAudio *this /*$s0*/)
 // line 297, offset 0x80046164
	/* begin block 1 */
		// Start line: 298
		// Start offset: 0x80046164
	/* end block 1 */
	// End offset: 0x80046164
	// End Line: 298

/* WARNING: Control flow encountered bad instruction data */

tScreenAudio * __12tScreenAudio(tScreenAudio *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Initialize__12tScreenAudio(struct tScreenAudio *this /*$s0*/)
 // line 305, offset 0x800461a4
	/* begin block 1 */
		// Start line: 306
		// Start offset: 0x800461A4
	/* end block 1 */
	// End offset: 0x800461A4
	// End Line: 306

/* WARNING: Control flow encountered bad instruction data */

void Initialize__12tScreenAudio(tScreenAudio *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Cleanup__12tScreenAudio(struct tScreenAudio *this /*$s1*/)
 // line 318, offset 0x80046204
	/* begin block 1 */
		// Start line: 319
		// Start offset: 0x80046204

		/* begin block 1.1 */
			// Start line: 340
			// Start offset: 0x800462C8

			/* begin block 1.1.1 */
				// Start line: 340
				// Start offset: 0x800462C8

				/* begin block 1.1.1.1 */
					// Start line: 340
					// Start offset: 0x800462C8
				/* end block 1.1.1.1 */
				// End offset: 0x800462C8
				// End Line: 340
			/* end block 1.1.1 */
			// End offset: 0x800462C8
			// End Line: 340
		/* end block 1.1 */
		// End offset: 0x800462D8
		// End Line: 340
	/* end block 1 */
	// End offset: 0x800462E8
	// End Line: 340

/* WARNING: Control flow encountered bad instruction data */

void Cleanup__12tScreenAudio(tScreenAudio *this)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}




