#ifndef SCREENPOST_H
#define SCREENPOST_H

extern void _._26tScreenTournamentStandings(struct tScreenTournamentStandings *this, int __in_chrg); // 0x8003A8CC

extern void _._31tScreenTournamentStandings3item(struct tScreenTournamentStandings3item *this, int __in_chrg); // 0x8003A8AC

extern void ProcessInput__24tScreenPinkSlipStandings7tPlayerR13tInputKeyTypeR12tMenuCommand(struct tScreenPinkSlipStandings *this, enum tPlayer fromPlayer, enum tInputKeyType *keyval, struct tMenuCommand *command); // 0x8003A86C

extern void _._24tScreenPinkSlipStandings(struct tScreenPinkSlipStandings *this, int __in_chrg); // 0x8003A88C


// decompiled code
// original method signature: 
// void /*$ra*/ _._26tScreenTournamentStandings(struct tScreenTournamentStandings *this /*$a0*/, int __in_chrg /*$a1*/)
 // line 64, offset 0x8003a8cc
/* WARNING: Control flow encountered bad instruction data */

void ___26tScreenTournamentStandings(tScreenTournamentStandings *this,int __in_chrg)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ _._31tScreenTournamentStandings3item(struct tScreenTournamentStandings3item *this /*$a0*/, int __in_chrg /*$a1*/)
 // line 72, offset 0x8003a8ac
	/* begin block 1 */
		// Start line: 73
		// Start offset: 0x8003A8AC
	/* end block 1 */
	// End offset: 0x8003A8AC
	// End Line: 73

/* WARNING: Control flow encountered bad instruction data */

void ___31tScreenTournamentStandings3item(tScreenTournamentStandings3item *this,int __in_chrg)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ ProcessInput__24tScreenPinkSlipStandings7tPlayerR13tInputKeyTypeR12tMenuCommand(struct tScreenPinkSlipStandings *this /*$a0*/, enum tPlayer fromPlayer /*$a1*/, enum tInputKeyType *keyval /*$a2*/, struct tMenuCommand *command /*$a3*/)
 // line 80, offset 0x8003a86c
	/* begin block 1 */
		// Start line: 81
		// Start offset: 0x8003A86C
	/* end block 1 */
	// End offset: 0x8003A86C
	// End Line: 81

/* WARNING: Control flow encountered bad instruction data */

void ProcessInput__24tScreenPinkSlipStandings7tPlayerR13tInputKeyTypeR12tMenuCommand
               (tScreenPinkSlipStandings *this,tPlayer fromPlayer,tInputKeyType *keyval,
               tMenuCommand *command)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ _._24tScreenPinkSlipStandings(struct tScreenPinkSlipStandings *this /*$a0*/, int __in_chrg /*$a1*/)
 // line 82, offset 0x8003a88c
	/* begin block 1 */
		// Start line: 83
		// Start offset: 0x8003A88C

		/* begin block 1.1 */
			// Start line: 83
			// Start offset: 0x8003A88C
		/* end block 1.1 */
		// End offset: 0x8003A88C
		// End Line: 83
	/* end block 1 */
	// End offset: 0x8003A88C
	// End Line: 83

/* WARNING: Control flow encountered bad instruction data */

void ___24tScreenPinkSlipStandings(tScreenPinkSlipStandings *this,int __in_chrg)

{
  undefined4 in_v1;
  undefined4 in_t5;
  
  special2(in_v1,in_t5,5,0x13);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}




#endif
